import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import type { FieldDto } from "@shared/fields";
import type { PlantationDto } from "@shared/crop-lifecycle";
import type { CultureCatalogEntry } from "@shared/crops";
import { emptyNutrients, planNutrientKeys, type FertilizationPlanDto, type NutrientAmounts } from "@shared/fertilization-plans";
import { useI18n } from "../../i18n";
import { operationCopies } from "../operations/operation-locales.generated";
import { pluralWorkspaceMessage } from "../workspace-locales";
import { planCopies, type PlanCopy } from "./plan-locales.generated";
import "./plans.css";

type Data = { plans: FertilizationPlanDto[]; fields: FieldDto[]; plantations: PlantationDto[]; cultures: readonly CultureCatalogEntry[] };
type SourceForm = { name: string; nutrients: Record<(typeof planNutrientKeys)[number], string> };
type FieldForm = { selected: boolean; targetType: FertilizationPlanDto["fields"][number]["targetType"]; plantationId: string; areaHa: string; objectives: Record<(typeof planNutrientKeys)[number], string>; sources: SourceForm[]; irrigationSector: string; nitrateDate: string; nitrateValue: string; irrigationForecast: string; includeCoverCrop: boolean; coverCrop: Record<(typeof planNutrientKeys)[number], string> };
const blankNutrients = () => Object.fromEntries(planNutrientKeys.map((key) => [key, ""])) as Record<(typeof planNutrientKeys)[number], string>;
const blankField = (areaHa = ""): FieldForm => ({ selected: false, targetType: "current_plantation", plantationId: "", areaHa, objectives: blankNutrients(), sources: [], irrigationSector: "", nitrateDate: "", nitrateValue: "", irrigationForecast: "", includeCoverCrop: false, coverCrop: blankNutrients() });
const nutrientLabels: Record<(typeof planNutrientKeys)[number], string> = { nTotal: "N", p2o5: "P₂O₅", k2o: "K₂O", cao: "CaO", mgo: "MgO", so3: "SO₃" };

export default function PlansModule() {
  const { locale } = useI18n();
  const t = planCopies[locale];
  const operationCopy = operationCopies[locale];
  const [data, setData] = useState<Data>({ plans: [], fields: [], plantations: [], cultures: [] });
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);
  const [adding, setAdding] = useState(false);
  const [selectedPlanId, setSelectedPlanId] = useState<string>();
  const load = useCallback(async () => {
    setLoading(true); setFailed(false);
    try {
      const responses = await Promise.all(["/api/farm/fertilization-plans", "/api/farm/fields", "/api/farm/crop-lifecycle", "/api/farm/crop-catalog"].map((url) => fetch(url, { credentials: "include" })));
      if (responses.some((response) => !response.ok)) throw new Error();
      const [plans, fields, lifecycle, cultures] = await Promise.all(responses.map((response) => response.json()));
      setData({ plans: plans.data, fields: fields.data, plantations: lifecycle.data.plantations, cultures: cultures.data });
    } catch { setFailed(true); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);
  const selected = data.plans.find((plan) => plan.id === selectedPlanId);
  const active = data.plans.filter((plan) => plan.status === "in_force").length;
  const drafts = data.plans.filter((plan) => plan.status === "draft").length;
  const warningCount = data.plans.filter((plan) => plan.status !== "superseded").flatMap((plan) => plan.fields).reduce((sum, field) => sum + field.warnings.length, 0);
  const cultures = useMemo(() => new Map<string, string>(data.cultures.map((culture) => [culture.id, culture.sourceName])), [data.cultures]);
  const fields = useMemo(() => new Map(data.fields.map((field) => [field.id, field.name])), [data.fields]);
  const fieldPlanCount = (count: number) => pluralWorkspaceMessage(locale, count, { one:t.fieldOne,two:t.fieldTwo,few:t.fieldFew,many:t.fieldMany,zero:t.fieldZero,other:t.fieldOther });
  return <>
    <section className="page-heading"><div><p>{t.kicker}</p><h1>{t.title}</h1><span>{t.description}</span></div><button className="primary-action" disabled={!data.fields.length} onClick={() => setAdding(true)}>＋ {t.addPlan}</button></section>
    <aside className="plan-integrity-notice">{t.operationNotice}</aside>
    <section className="plan-metrics"><Metric label={t.activePlans} value={active} /><Metric label={t.drafts} value={drafts} /><Metric label={t.warnings} value={warningCount} warning={warningCount > 0} /></section>
    <section className="panel plan-panel">
      {loading ? <div className="module-state"><span className="spinner" /></div> : failed ? <div className="module-state error-state"><p>{t.loadError}</p><button onClick={() => void load()}>{t.addPlan}</button></div> : data.plans.length ? <div className="plan-list">{[...data.plans].reverse().map((plan) => <article key={plan.id} className={plan.status}><div><span>{cultures.get(plan.cultureId)}</span><h2>{plan.name}</h2><p>{plan.startsOn} — {plan.endsOn} · {plan.fields.length.toLocaleString(locale)} {fieldPlanCount(plan.fields.length)}</p></div><div className="plan-status"><em>{statusLabel(t, plan.status)}</em><b>{t.version} {plan.version}</b></div><button className="subtle-button" onClick={() => setSelectedPlanId(plan.id)}>{t.details} →</button></article>)}</div> : <div className="module-state"><p>{t.empty}</p></div>}
    </section>
    {adding && <PlanDialog data={data} t={t} operationCopy={operationCopy} onClose={() => setAdding(false)} onSaved={async () => { setAdding(false); await load(); }} />}
    {selected && <PlanDetail plan={selected} t={t} locale={locale} fields={fields} culture={cultures.get(selected.cultureId) || selected.cultureId} onClose={() => setSelectedPlanId(undefined)} onActivated={load} />}
  </>;
}

function Metric({ label, value, warning = false }: { label: string; value: number; warning?: boolean }) { return <article className={warning ? "warning" : ""}><span>{label}</span><b>{value}</b></article>; }
const statusLabel = (t: PlanCopy, status: FertilizationPlanDto["status"]) => ({ draft: t.draft, in_force: t.inForce, superseded: t.superseded })[status];
const values = (form: Record<(typeof planNutrientKeys)[number], string>): NutrientAmounts => Object.fromEntries(planNutrientKeys.map((key) => [key, Number(form[key] || 0)])) as NutrientAmounts;

function PlanDialog({ data, t, operationCopy, onClose, onSaved }: { data: Data; t: PlanCopy; operationCopy: typeof operationCopies[keyof typeof operationCopies]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(""); const [cultureId, setCultureId] = useState<string>(data.cultures[0]?.id || ""); const [startsOn, setStartsOn] = useState(new Date().toISOString().slice(0, 10)); const [endsOn, setEndsOn] = useState(`${new Date().getUTCFullYear()}-12-31`); const [notes, setNotes] = useState("");
  const [rows, setRows] = useState<Record<string, FieldForm>>(Object.fromEntries(data.fields.map((field) => [field.id, blankField(String(field.usableAreaHa))]))); const [saving, setSaving] = useState(false); const [failed, setFailed] = useState(false);
  const update = (fieldId: string, change: Partial<FieldForm>) => setRows((current) => ({ ...current, [fieldId]: { ...current[fieldId], ...change } }));
  const updateNutrient = (fieldId: string, group: "objectives" | "coverCrop", key: (typeof planNutrientKeys)[number], value: string) => update(fieldId, { [group]: { ...rows[fieldId][group], [key]: value } });
  const updateSource = (fieldId: string, index: number, change: Partial<SourceForm>) => update(fieldId, { sources: rows[fieldId].sources.map((source, sourceIndex) => sourceIndex === index ? { ...source, ...change } : source) });
  const setSourceNutrient = (fieldId: string, index: number, key: (typeof planNutrientKeys)[number], value: string) => updateSource(fieldId, index, { nutrients: { ...rows[fieldId].sources[index].nutrients, [key]: value } });
  useEffect(() => { setRows((current) => Object.fromEntries(Object.entries(current).map(([fieldId, row]) => { const plantation = data.plantations.find((item) => item.fieldId === fieldId && item.cultureId === cultureId && item.status === "active"); return [fieldId, { ...row, plantationId: plantation?.id || "", targetType: plantation ? (plantation.kind === "permanent" ? "current_campaign" : "current_plantation") : "next_planting" }]; }))); }, [cultureId, data.plantations]);
  async function submit(event: FormEvent) {
    event.preventDefault(); setSaving(true); setFailed(false);
    const selected = data.fields.filter((field) => rows[field.id].selected);
    if (!selected.length) { setFailed(true); setSaving(false); return; }
    const payload = { name, cultureId, startsOn, endsOn, ...(notes ? { notes } : {}), fields: selected.map((field) => { const row = rows[field.id]; const plantation = data.plantations.find((item) => item.id === row.plantationId); return { fieldId: field.id, ...(row.plantationId ? { plantationId: row.plantationId } : {}), targetType: row.targetType, targetLabel: plantation?.name || field.name, areaHa: Number(row.areaHa), objectivesKgHa: values(row.objectives), plannedSources: row.sources.filter((source) => source.name.trim()).map((source) => ({ name: source.name, nutrientsKgHa: values(source.nutrients) })), ...(row.irrigationSector ? { irrigationSectorSnapshot: row.irrigationSector } : {}), ...(row.nitrateDate && row.nitrateValue ? { nitrateAnalysisSnapshot: { sampledOn: row.nitrateDate, nitrateMgL: Number(row.nitrateValue) } } : {}), ...(row.irrigationForecast ? { irrigationForecastM3Ha: Number(row.irrigationForecast) } : {}), includeCoverCrop: row.includeCoverCrop, ...(row.includeCoverCrop ? { coverCropContributionKgHa: values(row.coverCrop) } : {}) }; }) };
    try { const response = await fetch("/api/farm/fertilization-plans", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(); await onSaved(); } catch { setFailed(true); setSaving(false); }
  }
  return <div className="modal-backdrop"><section className="holding-dialog plan-dialog"><header><h2>{t.addPlan}</h2><button onClick={onClose} aria-label={t.close}>×</button></header><form onSubmit={(event) => void submit(event)}>
    <div className="plan-general-grid"><Input label={t.name} value={name} onChange={setName} /><label><span>{t.culture}</span><select value={cultureId} onChange={(event) => setCultureId(event.target.value)}>{data.cultures.map((culture) => <option key={culture.id} value={culture.id}>{culture.sourceName}</option>)}</select></label><Input label={t.startsOn} type="date" value={startsOn} onChange={setStartsOn} /><Input label={t.endsOn} type="date" value={endsOn} onChange={setEndsOn} /></div>
    <p className="snapshot-notice">{t.optionalSnapshotNotice}</p><fieldset className="field-plan-editor"><legend>{t.fieldPlans}</legend>{data.fields.map((field) => { const row = rows[field.id]; const compatible = data.plantations.filter((item) => item.fieldId === field.id && item.cultureId === cultureId && item.status === "active"); return <article key={field.id} className={row.selected ? "selected" : ""}><label className="field-toggle"><input type="checkbox" checked={row.selected} onChange={(event) => update(field.id, { selected: event.target.checked })} /><b>{field.name}</b><span>{field.usableAreaHa} ha</span></label>{row.selected && <div className="individual-plan-fields"><label><span>{t.target}</span><select value={row.targetType} onChange={(event) => update(field.id, { targetType: event.target.value as FieldForm["targetType"] })}><option value="current_plantation">{t.currentPlantation}</option><option value="next_planting">{t.nextPlanting}</option><option value="current_campaign">{t.currentCampaign}</option><option value="next_campaign">{t.nextCampaign}</option></select></label><label><span>{operationCopy.plantation}</span><select value={row.plantationId} onChange={(event) => update(field.id, { plantationId: event.target.value })}><option value="">—</option>{compatible.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Input label={`${operationCopy.area} (ha)`} type="number" value={row.areaHa} onChange={(value) => update(field.id, { areaHa: value })} />
      <NutrientInputs title={t.objectives} values={row.objectives} onChange={(key, value) => updateNutrient(field.id, "objectives", key, value)} t={t} />
      <fieldset className="source-editor"><legend>{t.plannedSources}</legend>{row.sources.map((source, index) => <div key={index} className="source-row"><Input label={t.sourceName} value={source.name} onChange={(value) => updateSource(field.id, index, { name: value })} /><NutrientInputs values={source.nutrients} onChange={(key, value) => setSourceNutrient(field.id, index, key, value)} t={t} /><button type="button" className="danger-link" onClick={() => update(field.id, { sources: row.sources.filter((_, sourceIndex) => sourceIndex !== index) })}>×</button></div>)}<button type="button" className="subtle-button" onClick={() => update(field.id, { sources: [...row.sources, { name: "", nutrients: blankNutrients() }] })}>＋ {t.addSource}</button></fieldset>
      <Input label={t.irrigationSector} required={false} value={row.irrigationSector} onChange={(value) => update(field.id, { irrigationSector: value })} /><Input label={t.irrigationForecast} type="number" required={false} value={row.irrigationForecast} onChange={(value) => update(field.id, { irrigationForecast: value })} /><Input label={t.nitrateDate} type="date" required={false} value={row.nitrateDate} onChange={(value) => update(field.id, { nitrateDate: value })} /><Input label={t.nitrateValue} type="number" required={false} value={row.nitrateValue} onChange={(value) => update(field.id, { nitrateValue: value })} /><label className="cover-toggle"><input type="checkbox" checked={row.includeCoverCrop} onChange={(event) => update(field.id, { includeCoverCrop: event.target.checked })} /><span>{t.includeCoverCrop}</span></label>{row.includeCoverCrop && <NutrientInputs title={t.coverCropContribution} values={row.coverCrop} onChange={(key, value) => updateNutrient(field.id, "coverCrop", key, value)} t={t} />}</div>}</article>; })}</fieldset>
    <label><span>{operationCopy.notes}</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{failed && <p className="form-error">{data.fields.some((field) => rows[field.id].selected) ? t.saveError : t.fieldsRequired}</p>}<footer><button type="button" onClick={onClose}>{t.close}</button><button className="primary-action" disabled={saving}>{saving ? "…" : t.saveDraft}</button></footer>
  </form></section></div>;
}

function NutrientInputs({ title, values: row, onChange, t }: { title?: string; values: Record<(typeof planNutrientKeys)[number], string>; onChange: (key: (typeof planNutrientKeys)[number], value: string) => void; t: PlanCopy }) { return <fieldset className="nutrient-objectives">{title && <legend>{title}</legend>}{planNutrientKeys.map((key) => <Input key={key} label={`${nutrientLabels[key]} (${t.kgHa})`} type="number" required={false} value={row[key]} onChange={(value) => onChange(key, value)} />)}</fieldset>; }

function PlanDetail({ plan, t, locale, fields, culture, onClose, onActivated }: { plan: FertilizationPlanDto; t: PlanCopy; locale: string; fields: Map<string, string>; culture: string; onClose: () => void; onActivated: () => Promise<void> }) {
  const [activating, setActivating] = useState(false); const [failed, setFailed] = useState(false); const [elemental, setElemental] = useState(false);
  async function activate() { setActivating(true); setFailed(false); try { const response = await fetch(`/api/farm/fertilization-plans/${plan.id}/activate`, { method: "POST", credentials: "include" }); if (!response.ok) throw new Error(); await onActivated(); onClose(); } catch { setFailed(true); setActivating(false); } }
  return <div className="modal-backdrop"><section className="holding-dialog plan-detail"><header><div><span>{culture} · {t.version} {plan.version}</span><h2>{plan.name}</h2></div><button onClick={onClose} aria-label={t.close}>×</button></header><div className="detail-period"><em>{statusLabel(t, plan.status)}</em><span>{plan.startsOn} — {plan.endsOn}</span></div><div className="nutrient-form-toggle" aria-label={t.objectives}><button className={!elemental?"active":""} onClick={()=>setElemental(false)}>P₂O₅ · K₂O · CaO · MgO · SO₃</button><button className={elemental?"active":""} onClick={()=>setElemental(true)}>P · K · Ca · Mg · S</button></div>{plan.fields.map((field) => <article key={field.id}><header><div><span>{fields.get(field.fieldId)}</span><h3>{field.targetLabel}</h3></div><b>{field.areaHa.toLocaleString(locale)} ha</b></header>{field.warnings.length > 0 && <div className="plan-warnings">{field.warnings.map((warning) => <span key={warning}>! {warningLabel(t, warning)}</span>)}</div>}<div className="balance-table"><div className="balance-head"><b>{t.objectives}</b><b>{t.plannedSources}</b><b>{t.delivered}</b><b>{t.remaining}</b></div>{planNutrientKeys.map((key) => <div key={key}><strong>{displayNutrient(key,elemental)}</strong><span>{format(convertNutrient(field.objectivesKgHa[key],key,elemental), locale)} {t.kgHa}</span><span>{format(convertNutrient(field.plannedKgHa[key],key,elemental), locale)} {t.kgHa}</span><span>{format(convertNutrient(field.deliveredKgHa[key],key,elemental), locale)} {t.kgHa}</span><span className={field.balanceKgHa[key] < 0 ? "negative" : ""}>{format(convertNutrient(field.balanceKgHa[key],key,elemental), locale)} {t.kgHa}</span></div>)}</div><div className="field-snapshots"><span>{t.irrigationSector}: <b>{field.irrigationSectorSnapshot || "—"}</b></span><span>{t.irrigationForecast}: <b>{field.irrigationForecastM3Ha === undefined ? "—" : field.irrigationForecastM3Ha.toLocaleString(locale)}</b></span><span>{t.nitrateAnalysis}: <b>{field.nitrateAnalysisSnapshot ? `${field.nitrateAnalysisSnapshot.nitrateMgL.toLocaleString(locale)} mg/L · ${field.nitrateAnalysisSnapshot.sampledOn}` : "—"}</b></span></div></article>)}{failed && <p className="form-error">{t.saveError}</p>}<footer><button onClick={onClose}>{t.close}</button>{plan.status === "draft" && <button className="primary-action" disabled={activating} onClick={() => void activate()}>{activating ? "…" : t.activate}</button>}</footer></section></div>;
}
const format = (value: number, locale: string) => value.toLocaleString(locale, { maximumFractionDigits: 3 });
const elementalFactors:Partial<Record<(typeof planNutrientKeys)[number],number>>={p2o5:0.4364,k2o:0.8301,cao:0.7147,mgo:0.603,so3:0.4005};
const displayNutrient=(key:(typeof planNutrientKeys)[number],elemental:boolean)=>elemental?({p2o5:"P",k2o:"K",cao:"Ca",mgo:"Mg",so3:"S"}as Record<string,string>)[key]||nutrientLabels[key]:nutrientLabels[key];
const convertNutrient=(value:number,key:(typeof planNutrientKeys)[number],elemental:boolean)=>elemental?value*(elementalFactors[key]||1):value;
const warningLabel = (t: PlanCopy, warning: FertilizationPlanDto["fields"][number]["warnings"][number]) => ({ missing_irrigation_sector: t.missingIrrigationSector, missing_nitrate_analysis: t.missingNitrateAnalysis, stale_nitrate_analysis: t.staleNitrateAnalysis, unknown_composition: t.unknownComposition, objective_exceeded: t.objectiveExceeded })[warning];
function Input({ label, value, onChange, type = "text", required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label><span>{label}</span><input required={required} type={type} step={type === "number" ? "0.001" : undefined} min={type === "number" ? "0" : undefined} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
