export const planEnglishCopy = {
  kicker: "Agronomic decision",
  title: "Fertilization plans",
  description: "Plan crop nutrient needs and compare them with planned sources and nutrients actually applied.",
  addPlan: "Create plan",
  activePlans: "Plans in force",
  drafts: "Drafts",
  warnings: "Warnings",
  history: "History",
  empty: "No fertilization plans have been created yet.",
  loadError: "Fertilization plans could not be loaded.",
  saveError: "The fertilization plan could not be saved.",
  name: "Plan name",
  culture: "Crop",
  period: "Plan period",
  startsOn: "Start date",
  endsOn: "End date",
  status: "Status",
  draft: "Draft",
  inForce: "In force",
  superseded: "Superseded",
  version: "Version",
  objectives: "Nutrient requirements",
  plannedSources: "Planned nutrient sources",
  delivered: "Actually applied",
  remaining: "Remaining to target",
  plannedBalance: "Difference after planned sources",
  fieldPlans: "Individual field plans",
  fieldOne: "{count} field plan",
  fieldTwo: "{count} field plans",
  fieldFew: "{count} field plans",
  fieldMany: "{count} field plans",
  fieldZero: "{count} field plans",
  fieldOther: "{count} field plans",
  target: "Agronomic target",
  currentPlantation: "Current plantation",
  nextPlanting: "Next planting",
  currentCampaign: "Current campaign",
  nextCampaign: "Next campaign",
  sourceName: "Source name",
  addSource: "Add source",
  noSources: "No nutrient source has been planned.",
  irrigationForecast: "Irrigation forecast (m³/ha)",
  irrigationSector: "Irrigation sector snapshot",
  nitrateAnalysis: "Nitrate analysis snapshot",
  nitrateDate: "Sampling date",
  nitrateValue: "Nitrate (mg/L)",
  includeCoverCrop: "Include cover crop contribution",
  coverCropContribution: "Cover crop contribution",
  activate: "Put into force",
  saveDraft: "Save draft",
  close: "Close",
  details: "View balance",
  operationNotice: "Actual values come directly from completed physical operations; products, resources, costs and nutrients are never duplicated in the plan.",
  optionalSnapshotNotice: "Irrigation sectors and nitrate analyses are optional frozen snapshots until their source modules are available.",
  missingIrrigationSector: "No irrigation sector snapshot",
  missingNitrateAnalysis: "No nitrate analysis snapshot",
  staleNitrateAnalysis: "Nitrate analysis is more than one year old",
  unknownComposition: "At least one applied product has unknown composition",
  objectiveExceeded: "At least one nutrient target has been exceeded",
  fieldsRequired: "Select at least one field.",
  kgHa: "kg/ha",
} as const;

export type PlanCopy = Record<keyof typeof planEnglishCopy, string>;
