import type { SupportedLocale } from "../../home-copy";

export type EntitlementCopy = { plan:string;usage:string;unlimited:string;readOnly:string;limitReached:string;limitMessage:string;options:string;managePlan:string;subscribe:string;perMonth:string;perYear:string;noOptions:string;close:string;checkoutError:string;activeAreaHectares:string;activePlots:string;activePlantations:string;virtualStations:string;applicationUsers:string;addons:string };
const c=(plan:string,usage:string,unlimited:string,readOnly:string,limitReached:string,limitMessage:string,options:string,managePlan:string,subscribe:string,perMonth:string,perYear:string,noOptions:string,close:string,checkoutError:string,labels:[string,string,string,string,string],addons:string):EntitlementCopy=>({plan,usage,unlimited,readOnly,limitReached,limitMessage,options,managePlan,subscribe,perMonth,perYear,noOptions,close,checkoutError,applicationUsers:labels[0],activeAreaHectares:labels[1],activePlots:labels[2],activePlantations:labels[3],virtualStations:labels[4],addons});
export const entitlementCopies:Record<SupportedLocale,EntitlementCopy>={
"pt-PT":c("Plano","Utilização","Sem limite","Apenas consulta e exportação","Limite atingido","A utilização é {usage} de {limit}. Esta ação aumentaria para {requested}.","Opções disponíveis","Gerir plano no Gero Core","Subscrever add-on","/mês","/ano","Não existem opções elegíveis neste momento.","Fechar","Não foi possível iniciar a subscrição.",["Utilizadores","Área ativa (ha)","Talhões ativos","Plantações ativas","Estações virtuais"],"Add-ons ativos"),
"pt-BR":c("Plano","Uso","Ilimitado","Somente consulta e exportação","Limite atingido","O uso é {usage} de {limit}. Esta ação aumentaria para {requested}.","Opções disponíveis","Gerenciar plano no Gero Core","Assinar add-on","/mês","/ano","Não há opções elegíveis no momento.","Fechar","Não foi possível iniciar a assinatura.",["Usuários","Área ativa (ha)","Talhões ativos","Plantações ativas","Estações virtuais"],"Add-ons ativos"),
en:c("Plan","Usage","Unlimited","Read and export only","Limit reached","Usage is {usage} of {limit}. This action would increase it to {requested}.","Available options","Manage plan in Gero Core","Subscribe to add-on","/month","/year","No eligible options are currently available.","Close","Subscription could not be started.",["Users","Active area (ha)","Active plots","Active plantations","Virtual stations"],"Active add-ons"),
fr:c("Forfait","Utilisation","Illimité","Consultation et export uniquement","Limite atteinte","L’utilisation est de {usage} sur {limit}. Cette action la porterait à {requested}.","Options disponibles","Gérer le forfait dans Gero Core","Souscrire l’extension","/mois","/an","Aucune option éligible actuellement.","Fermer","Impossible de démarrer la souscription.",["Utilisateurs","Surface active (ha)","Parcelles actives","Plantations actives","Stations virtuelles"],"Extensions actives"),
es:c("Plan","Uso","Sin límite","Solo consulta y exportación","Límite alcanzado","El uso es {usage} de {limit}. Esta acción lo aumentaría a {requested}.","Opciones disponibles","Gestionar plan en Gero Core","Suscribir complemento","/mes","/año","No hay opciones elegibles en este momento.","Cerrar","No se pudo iniciar la suscripción.",["Usuarios","Área activa (ha)","Parcelas activas","Plantaciones activas","Estaciones virtuales"],"Complementos activos"),
nl:c("Abonnement","Gebruik","Onbeperkt","Alleen lezen en exporteren","Limiet bereikt","Gebruik is {usage} van {limit}. Deze actie verhoogt dit tot {requested}.","Beschikbare opties","Abonnement beheren in Gero Core","Add-on nemen","/maand","/jaar","Momenteel zijn er geen geschikte opties.","Sluiten","Abonnement kon niet worden gestart.",["Gebruikers","Actief areaal (ha)","Actieve percelen","Actieve teelten","Virtuele stations"],"Actieve add-ons"),
de:c("Tarif","Nutzung","Unbegrenzt","Nur Lesen und Export","Limit erreicht","Die Nutzung beträgt {usage} von {limit}. Diese Aktion würde sie auf {requested} erhöhen.","Verfügbare Optionen","Tarif in Gero Core verwalten","Add-on abonnieren","/Monat","/Jahr","Derzeit sind keine passenden Optionen verfügbar.","Schließen","Abonnement konnte nicht gestartet werden.",["Benutzer","Aktive Fläche (ha)","Aktive Schläge","Aktive Pflanzungen","Virtuelle Stationen"],"Aktive Add-ons"),
ja:c("プラン","使用量","無制限","閲覧・エクスポートのみ","上限に達しました","使用量は {limit} 中 {usage} です。この操作で {requested} になります。","利用可能な選択肢","Gero Core でプランを管理","アドオンを契約","/月","/年","現在利用可能な選択肢はありません。","閉じる","契約を開始できませんでした。",["ユーザー","有効面積 (ha)","有効な圃場","有効な作付け","仮想観測所"],"有効なアドオン"),
he:c("תוכנית","שימוש","ללא הגבלה","קריאה וייצוא בלבד","הגעת למגבלה","השימוש הוא {usage} מתוך {limit}. הפעולה תגדיל אותו ל-{requested}.","אפשרויות זמינות","ניהול תוכנית ב-Gero Core","רכישת תוסף","/חודש","/שנה","אין כעת אפשרויות מתאימות.","סגירה","לא ניתן להתחיל את הרכישה.",["משתמשים","שטח פעיל (הקטר)","חלקות פעילות","נטיעות פעילות","תחנות וירטואליות"],"תוספים פעילים"),
tr:c("Plan","Kullanım","Sınırsız","Yalnızca görüntüleme ve dışa aktarma","Sınıra ulaşıldı","Kullanım {limit} üzerinden {usage}. Bu işlem {requested} değerine çıkarır.","Mevcut seçenekler","Planı Gero Core’da yönet","Eklentiye abone ol","/ay","/yıl","Şu anda uygun seçenek yok.","Kapat","Abonelik başlatılamadı.",["Kullanıcılar","Aktif alan (ha)","Aktif parseller","Aktif dikimler","Sanal istasyonlar"],"Aktif eklentiler"),
ar:c("الخطة","الاستخدام","غير محدود","عرض وتصدير فقط","تم بلوغ الحد","الاستخدام {usage} من {limit}. سيزيده هذا الإجراء إلى {requested}.","الخيارات المتاحة","إدارة الخطة في Gero Core","الاشتراك في إضافة","/شهر","/سنة","لا توجد خيارات مؤهلة حاليًا.","إغلاق","تعذر بدء الاشتراك.",["المستخدمون","المساحة النشطة (هكتار)","القطع النشطة","المزروعات النشطة","المحطات الافتراضية"],"الإضافات النشطة"),
pl:c("Plan","Użycie","Bez limitu","Tylko odczyt i eksport","Osiągnięto limit","Użycie wynosi {usage} z {limit}. Ta czynność zwiększyłaby je do {requested}.","Dostępne opcje","Zarządzaj planem w Gero Core","Subskrybuj dodatek","/miesiąc","/rok","Brak obecnie dostępnych opcji.","Zamknij","Nie udało się rozpocząć subskrypcji.",["Użytkownicy","Aktywny obszar (ha)","Aktywne działki","Aktywne uprawy","Stacje wirtualne"],"Aktywne dodatki"),
hr:c("Plan","Korištenje","Neograničeno","Samo pregled i izvoz","Dosegnuto ograničenje","Korištenje je {usage} od {limit}. Ova radnja povećala bi ga na {requested}.","Dostupne mogućnosti","Upravljaj planom u Gero Core","Pretplati se na dodatak","/mjesec","/godina","Trenutačno nema dostupnih mogućnosti.","Zatvori","Pretplatu nije moguće pokrenuti.",["Korisnici","Aktivna površina (ha)","Aktivne parcele","Aktivni nasadi","Virtualne stanice"],"Aktivni dodaci"),
el:c("Πλάνο","Χρήση","Χωρίς όριο","Μόνο προβολή και εξαγωγή","Το όριο καλύφθηκε","Η χρήση είναι {usage} από {limit}. Η ενέργεια θα την αυξήσει σε {requested}.","Διαθέσιμες επιλογές","Διαχείριση πλάνου στο Gero Core","Εγγραφή σε πρόσθετο","/μήνα","/έτος","Δεν υπάρχουν διαθέσιμες επιλογές τώρα.","Κλείσιμο","Η εγγραφή δεν μπόρεσε να ξεκινήσει.",["Χρήστες","Ενεργή έκταση (ha)","Ενεργά αγροτεμάχια","Ενεργές φυτεύσεις","Εικονικοί σταθμοί"],"Ενεργά πρόσθετα"),
sv:c("Plan","Användning","Obegränsat","Endast läsning och export","Gränsen har nåtts","Användningen är {usage} av {limit}. Åtgärden skulle öka den till {requested}.","Tillgängliga alternativ","Hantera plan i Gero Core","Prenumerera på tillägg","/månad","/år","Inga berättigade alternativ finns just nu.","Stäng","Prenumerationen kunde inte startas.",["Användare","Aktiv areal (ha)","Aktiva skiften","Aktiva planteringar","Virtuella stationer"],"Aktiva tillägg"),
no:c("Plan","Bruk","Ubegrenset","Bare lesing og eksport","Grensen er nådd","Bruken er {usage} av {limit}. Handlingen vil øke den til {requested}.","Tilgjengelige valg","Administrer plan i Gero Core","Abonner på tillegg","/måned","/år","Ingen kvalifiserte valg er tilgjengelige nå.","Lukk","Abonnementet kunne ikke startes.",["Brukere","Aktivt areal (ha)","Aktive skifter","Aktive beplantninger","Virtuelle stasjoner"],"Aktive tillegg"),
da:c("Plan","Brug","Ubegrænset","Kun læsning og eksport","Grænsen er nået","Brugen er {usage} af {limit}. Handlingen vil øge den til {requested}.","Tilgængelige muligheder","Administrer plan i Gero Core","Abonner på tilføjelse","/måned","/år","Ingen kvalificerede muligheder er tilgængelige nu.","Luk","Abonnementet kunne ikke startes.",["Brugere","Aktivt areal (ha)","Aktive marker","Aktive plantninger","Virtuelle stationer"],"Aktive tilføjelser"),
it:c("Piano","Utilizzo","Illimitato","Solo consultazione ed esportazione","Limite raggiunto","L’utilizzo è {usage} su {limit}. Questa azione lo porterebbe a {requested}.","Opzioni disponibili","Gestisci piano in Gero Core","Abbonati al componente","/mese","/anno","Non ci sono opzioni idonee al momento.","Chiudi","Impossibile avviare l’abbonamento.",["Utenti","Area attiva (ha)","Appezzamenti attivi","Coltivazioni attive","Stazioni virtuali"],"Componenti attivi"),
uk:c("План","Використання","Без обмежень","Лише перегляд та експорт","Досягнуто ліміту","Використано {usage} із {limit}. Дія збільшить значення до {requested}.","Доступні варіанти","Керувати планом у Gero Core","Підписатися на додаток","/місяць","/рік","Наразі немає доступних варіантів.","Закрити","Не вдалося розпочати підписку.",["Користувачі","Активна площа (га)","Активні ділянки","Активні насадження","Віртуальні станції"],"Активні додатки"),
ro:c("Plan","Utilizare","Nelimitat","Doar consultare și export","Limită atinsă","Utilizarea este {usage} din {limit}. Acțiunea ar crește-o la {requested}.","Opțiuni disponibile","Gestionează planul în Gero Core","Abonează-te la extensie","/lună","/an","Nu există opțiuni eligibile momentan.","Închide","Abonamentul nu a putut fi inițiat.",["Utilizatori","Suprafață activă (ha)","Parcelele active","Plantații active","Stații virtuale"],"Extensii active"),
fi:c("Tilaus","Käyttö","Rajoittamaton","Vain luku ja vienti","Raja saavutettu","Käyttö on {usage}/{limit}. Toiminto nostaisi sen arvoon {requested}.","Saatavilla olevat vaihtoehdot","Hallitse tilausta Gero Coressa","Tilaa lisäosa","/kuukausi","/vuosi","Sopivia vaihtoehtoja ei ole nyt saatavilla.","Sulje","Tilausta ei voitu aloittaa.",["Käyttäjät","Aktiivinen pinta-ala (ha)","Aktiiviset lohkot","Aktiiviset istutukset","Virtuaaliasemat"],"Aktiiviset lisäosat"),
bg:c("План","Използване","Без ограничение","Само преглед и експорт","Лимитът е достигнат","Използването е {usage} от {limit}. Действието ще го увеличи до {requested}.","Налични възможности","Управление на плана в Gero Core","Абониране за добавка","/месец","/година","В момента няма подходящи възможности.","Затвори","Абонаментът не можа да започне.",["Потребители","Активна площ (ха)","Активни парцели","Активни насаждения","Виртуални станции"],"Активни добавки"),
hu:c("Csomag","Használat","Korlátlan","Csak megtekintés és export","Korlát elérve","A használat {usage}/{limit}. A művelet {requested} értékre növelné.","Elérhető lehetőségek","Csomag kezelése a Gero Core-ban","Kiegészítő előfizetése","/hó","/év","Jelenleg nincs megfelelő lehetőség.","Bezárás","Az előfizetés nem indítható el.",["Felhasználók","Aktív terület (ha)","Aktív táblák","Aktív ültetvények","Virtuális állomások"],"Aktív kiegészítők"),
is:c("Áskrift","Notkun","Ótakmarkað","Aðeins lestur og útflutningur","Hámarki náð","Notkun er {usage} af {limit}. Aðgerðin myndi hækka hana í {requested}.","Tiltækir kostir","Stjórna áskrift í Gero Core","Gerast áskrifandi að viðbót","/mánuð","/ár","Engir gjaldgengir kostir eru tiltækir núna.","Loka","Ekki tókst að hefja áskrift.",["Notendur","Virkt svæði (ha)","Virkir reitir","Virkar ræktanir","Sýndarstöðvar"],"Virkar viðbætur"),
sk:c("Plán","Využitie","Bez obmedzenia","Len čítanie a export","Limit dosiahnutý","Využitie je {usage} z {limit}. Akcia ho zvýši na {requested}.","Dostupné možnosti","Spravovať plán v Gero Core","Predplatiť doplnok","/mesiac","/rok","Momentálne nie sú dostupné vhodné možnosti.","Zavrieť","Predplatné sa nepodarilo spustiť.",["Používatelia","Aktívna plocha (ha)","Aktívne parcely","Aktívne výsadby","Virtuálne stanice"],"Aktívne doplnky"),
lt:c("Planas","Naudojimas","Neribota","Tik peržiūra ir eksportas","Pasiekta riba","Naudojama {usage} iš {limit}. Veiksmas padidintų iki {requested}.","Galimos parinktys","Valdyti planą Gero Core","Prenumeruoti priedą","/mėn.","/metus","Šiuo metu tinkamų parinkčių nėra.","Uždaryti","Nepavyko pradėti prenumeratos.",["Naudotojai","Aktyvus plotas (ha)","Aktyvūs laukai","Aktyvūs sodiniai","Virtualios stotys"],"Aktyvūs priedai"),
sl:c("Paket","Uporaba","Neomejeno","Samo ogled in izvoz","Omejitev dosežena","Uporaba je {usage} od {limit}. Dejanje bi jo povečalo na {requested}.","Razpoložljive možnosti","Upravljaj paket v Gero Core","Naroči dodatek","/mesec","/leto","Trenutno ni ustreznih možnosti.","Zapri","Naročnine ni bilo mogoče začeti.",["Uporabniki","Aktivna površina (ha)","Aktivne parcele","Aktivni nasadi","Navidezne postaje"],"Aktivni dodatki"),
lv:c("Plāns","Izmantojums","Neierobežots","Tikai skatīšana un eksports","Limits sasniegts","Izmantojums ir {usage} no {limit}. Darbība to palielinātu līdz {requested}.","Pieejamās iespējas","Pārvaldīt plānu Gero Core","Abonēt papildinājumu","/mēnesī","/gadā","Pašlaik nav piemērotu iespēju.","Aizvērt","Abonementu neizdevās sākt.",["Lietotāji","Aktīvā platība (ha)","Aktīvie lauki","Aktīvie stādījumi","Virtuālās stacijas"],"Aktīvie papildinājumi")};

export function entitlementMessage(template:string,values:Record<string,string|number>){return template.replace(/\{(\w+)\}/g,(_,key)=>String(values[key]??""))}
