import { useEffect, useMemo, useState } from "react";
import { capacityOptions, type BillingCatalog, type CapacityErrorDetails, type EntitlementSummary, type FarmLimitKey } from "@shared/entitlements";
import { useI18n } from "../../i18n";
import type { CoreConfig } from "../../auth";
import { entitlementCopies, entitlementMessage } from "./entitlement-locales";
import "./entitlements.css";

const resources:FarmLimitKey[]=["applicationUsers","activeAreaHectares","activePlots","activePlantations","virtualStations"];
export default function EntitlementCenter({config}:{config:CoreConfig|null}){const{locale}=useI18n(),t=entitlementCopies[locale],[summary,setSummary]=useState<EntitlementSummary|null>(null),[blocked,setBlocked]=useState<CapacityErrorDetails|null>(null),[catalog,setCatalog]=useState<BillingCatalog|null>(null),[checkoutError,setCheckoutError]=useState(false);
useEffect(()=>{void fetch("/api/farm/entitlements",{credentials:"include"}).then(async r=>{if(r.ok)setSummary(((await r.json())as{data:EntitlementSummary}).data)}).catch(()=>undefined)},[]);
useEffect(()=>{const original=window.fetch.bind(window);window.fetch=async(...args)=>{const response=await original(...args);if(response.status===409){void response.clone().json().then((body:{code?:string;details?:CapacityErrorDetails})=>{if(body.code==="ENTITLEMENT_LIMIT_REACHED"&&body.details)setBlocked(body.details)}).catch(()=>undefined)}return response};return()=>{window.fetch=original}},[]);
useEffect(()=>{if(blocked&&!catalog)void fetch("/api/billing/catalog",{credentials:"include"}).then(async r=>{if(r.ok)setCatalog(((await r.json())as{data:BillingCatalog}).data)}).catch(()=>undefined)},[blocked,catalog]);
const options=useMemo(()=>blocked&&summary&&catalog?capacityOptions(catalog,summary,blocked.resource,blocked.requested):null,[blocked,summary,catalog]);
async function checkout(code:string,billingPeriod:"monthly"|"yearly",quantity=1){setCheckoutError(false);const returnUrl=window.location.href;const response=await fetch("/api/billing/checkout",{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"addon",code,billingPeriod,quantity,successUrl:returnUrl,cancelUrl:returnUrl})});const body=await response.json().catch(()=>null)as{data?:{url?:string}}|null;if(!response.ok||!body?.data?.url){setCheckoutError(true);return}window.location.assign(body.data.url)}
if(!summary)return null;return <><section className="entitlement-strip"><div><span>{t.plan}</span><b>{summary.plan?.name||"—"}</b>{summary.access.mode==="read_only"&&<em>{t.readOnly}</em>}</div>{resources.map(resource=>summary.usage[resource]===null?null:<div key={resource}><span>{t[resource]}</span><b>{new Intl.NumberFormat(locale,{maximumFractionDigits:4}).format(summary.usage[resource]!)} / {summary.limits[resource]===null?t.unlimited:new Intl.NumberFormat(locale,{maximumFractionDigits:4}).format(summary.limits[resource]!)}</b></div>)}{summary.addons.length>0&&<div><span>{t.addons}</span><b>{summary.addons.map(item=>`${item.code} ×${item.quantity}`).join(", ")}</b></div>}</section>{blocked&&<div className="entitlement-backdrop" role="presentation"><section className="entitlement-dialog" role="dialog" aria-modal="true" aria-labelledby="limit-title"><header><div><span>{t.usage}</span><h2 id="limit-title">{t.limitReached}</h2></div><button onClick={()=>setBlocked(null)} aria-label={t.close}>×</button></header><p>{entitlementMessage(t.limitMessage,blocked)}</p><h3>{t.options}</h3><div className="entitlement-options">{options?.addons.map(item=><article key={item.code}><b>{item.name}</b><p>{item.description}</p><Prices prices={item.prices} locale={locale} month={t.perMonth} year={t.perYear}/><button className="primary-action" onClick={()=>void checkout(item.code,item.prices[0].billingPeriod,item.requiredQuantity)}>{t.subscribe}{item.requiredQuantity>1?` ×${item.requiredQuantity}`:""}</button></article>)}{options?.plans.map(item=><article key={item.code}><b>{item.name}</b><p>{item.description}</p><Prices prices={item.prices} locale={locale} month={t.perMonth} year={t.perYear}/>{config&&<a className="primary-action" href={config.accountUrl}>{t.managePlan}</a>}</article>)}{options&&options.addons.length===0&&options.plans.length===0&&<p>{t.noOptions}</p>}</div>{checkoutError&&<p className="form-error">{t.checkoutError}</p>}</section></div>}</>}
function Prices({prices,locale,month,year}:{prices:Array<{billingPeriod:"monthly"|"yearly";priceCents:number;currency:string}>;locale:string;month:string;year:string}){return <div className="entitlement-prices">{prices.map(price=><span key={price.billingPeriod}>{new Intl.NumberFormat(locale,{style:"currency",currency:price.currency}).format(price.priceCents/100)} {price.billingPeriod==="monthly"?month:year}</span>)}</div>}
