import { useState, type ReactNode } from "react";
import { useI18n } from "./i18n";
import { openCookiePreferences } from "./cookie-consent";
import { cookieMessage } from "./cookie-messages";

const icons = ["map", "crop", "spray", "water", "fertilize", "harvest", "team", "book"] as const;

function Icon({ name }: { name: typeof icons[number] | "weather" | "inventory" | "costs" | "privacy" | "check" | "arrow" }) {
  const paths: Record<string, ReactNode> = {
    map: <><path d="m4 6 5-2 6 2 5-2v14l-5 2-6-2-5 2Z"/><path d="M9 4v14m6-12v14"/></>,
    crop: <><path d="M12 21V9"/><path d="M12 13c-5 0-7-3-7-7 4 0 7 2 7 7Zm0-3c1-4 4-6 8-5 0 4-3 7-8 7Z"/></>,
    spray: <><path d="M7 9h9l2 3v8H6V11Z"/><path d="M9 9V5h5v4m4 0 3-2m-1 5h2"/></>,
    water: <><path d="M12 3s6 7 6 12a6 6 0 0 1-12 0c0-5 6-12 6-12Z"/><path d="M9 16c.5 1.5 1.5 2 3 2"/></>,
    fertilize: <><path d="M8 3h8v5l3 5-2 8H7l-2-8 3-5Z"/><path d="M8 8h8m-6 7h4"/></>,
    harvest: <><path d="M4 18h16l-2 3H6Z"/><path d="M8 18V8m4 10V5m4 13V9"/><path d="M8 9 5 7m7 0 3-3m1 7 3-2"/></>,
    team: <><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7m0-6c4 0 6 2 6 6"/></>,
    book: <><path d="M4 5c3-1 6 0 8 2v14c-2-2-5-3-8-2Zm16 0c-3-1-6 0-8 2v14c2-2 5-3 8-2Z"/></>,
    weather: <><circle cx="9" cy="9" r="4"/><path d="M9 2v2m0 10v2M2 9h2m10 0h2M4 4l1.5 1.5m7 7L14 14"/><path d="M8 20h10a4 4 0 0 0 0-8 6 6 0 0 0-10 4"/></>,
    inventory: <><path d="m4 7 8-4 8 4-8 4Z"/><path d="M4 7v10l8 4 8-4V7m-8 4v10"/></>,
    costs: <><circle cx="12" cy="12" r="9"/><path d="M15 8.5c-.7-.8-1.7-1.2-3-1.2-1.7 0-3 1-3 2.3 0 3.4 6 1.7 6 5 0 1.4-1.3 2.4-3.2 2.4-1.3 0-2.5-.5-3.3-1.4M12 5v14"/></>,
    privacy: <><path d="M12 3 20 7v5c0 5-3.4 8.2-8 9-4.6-.8-8-4-8-9V7Z"/><path d="m8.5 12 2.3 2.3 4.7-5"/></>,
    check: <path d="m5 12 4 4L19 6"/>, arrow: <><path d="M5 12h14"/><path d="m14 7 5 5-5 5"/></>,
  };
  return <svg aria-hidden="true" className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

function Brand() { return <a href="#top" className="brand" aria-label="GeroFarm"><img src="/brand/gerofarm-mark.svg" alt="GeroFarm" /></a>; }
function SectionTitle({ kicker, title, description }: { kicker: string; title: string; description: string }) { return <div className="section-title"><p className="kicker">{kicker}</p><h2>{title}</h2><p>{description}</p></div>; }
function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

export default function MarketingHome() {
  const { locale, copy, setLocale, options } = useI18n();
  const [annual, setAnnual] = useState(false); const [menu, setMenu] = useState(false);

  return <div className="marketing" id="top">
    <header className="site-header"><div className="shell header-inner"><Brand /><nav className={menu ? "main-nav open" : "main-nav"} aria-label={copy.nav.menu}>{[["platform", copy.nav.platform], ["weather", copy.nav.weather], ["privacy", copy.nav.privacy], ["plans", copy.nav.plans], ["faq", copy.nav.faq]].map(([id, label]) => <button key={id} onClick={() => { scrollTo(id); setMenu(false); }}>{label}</button>)}</nav><div className="header-actions"><label className="language"><span className="sr-only">{copy.nav.language}</span><select aria-label={copy.nav.language} value={locale} onChange={(event) => setLocale(event.target.value as typeof locale)}>{options.map((option) => <option key={option.code} value={option.code}>{option.label}</option>)}</select></label><a className="login-link" href="/login">{copy.nav.login}</a><a className="button small" href="/register">{copy.nav.start}</a><button className="menu-button" aria-expanded={menu} aria-label={copy.nav.menu} onClick={() => setMenu((value) => !value)}><span/><span/><span/></button></div></div></header>
    <main>
      <section className="hero-section"><div className="shell hero-grid"><div className="hero-copy"><p className="pill">{copy.hero.eyebrow}</p><h1>{copy.hero.title} <em>{copy.hero.accent}</em></h1><p className="hero-description">{copy.hero.description}</p><div className="cta-row"><a className="button" href="/register">{copy.hero.primary}<Icon name="arrow" /></a><button className="button ghost" onClick={() => scrollTo("plans")}>{copy.hero.secondary}</button></div><p className="hero-note"><Icon name="check" />{copy.hero.note}</p></div><div className="hero-visual"><img src="/images/gerofarm-field-intelligence-hero.webp" alt={copy.hero.imageAlt} width="1536" height="1024" fetchPriority="high"/><div className="hero-stats"><div><span>{copy.hero.mapLabel}</span><b>28</b></div><div><span>{copy.hero.cropLabel}</span><b>14</b></div><div><span>{copy.hero.operationLabel}</span><b>186</b></div></div></div></div></section>
      <section className="proof-strip"><div className="shell proof-grid">{copy.proof.map((item) => <p key={item}><Icon name="check" />{item}</p>)}</div></section>
      <section className="section shell" id="platform"><SectionTitle kicker={copy.flow.kicker} title={copy.flow.title} description={copy.flow.description}/><ol className="flow">{copy.flow.stages.map((stage, index) => <li key={stage}><span>{String(index + 1).padStart(2, "0")}</span><b>{stage}</b></li>)}</ol></section>
      <section className="section platform-section"><div className="shell"><SectionTitle kicker={copy.platform.kicker} title={copy.platform.title} description={copy.platform.description}/><div className="feature-grid">{copy.platform.cards.map((card, index) => <article className="feature-card" key={card.title}><div className="feature-icon"><Icon name={icons[index]} /></div><div><span className="status-dot">{card.status}</span><h3>{card.title}</h3><p>{card.description}</p></div></article>)}</div></div></section>
      <section className="section weather-section" id="weather"><div className="shell weather-grid"><div><p className="kicker light">{copy.weather.kicker}</p><h2>{copy.weather.title}</h2><p className="weather-description">{copy.weather.description}</p></div><div className="weather-panel"><div className="weather-head"><span>ET₀</span><b>3,8 mm</b><small>+0,4</small></div><div className="weather-chart" aria-hidden="true"><span/><span/><span/><span/><span/><span/><span/></div><ul>{copy.weather.metrics.map((metric) => <li key={metric}><Icon name="check" />{metric}</li>)}</ul></div></div></section>
      <section className="section shell"><SectionTitle kicker={copy.modules.kicker} title={copy.modules.title} description={copy.modules.description}/><div className="module-grid"><article><span className="module-icon"><Icon name="inventory" /></span><h3>{copy.modules.inventory}</h3><p>{copy.modules.inventoryDesc}</p></article><article><span className="module-icon"><Icon name="costs" /></span><h3>{copy.modules.costs}</h3><p>{copy.modules.costsDesc}</p></article></div></section>
      <section className="section privacy-section" id="privacy"><div className="shell privacy-grid"><div className="privacy-intro"><span className="privacy-icon"><Icon name="privacy" /></span><p className="kicker light">{copy.privacy.kicker}</p><h2>{copy.privacy.title}</h2><p>{copy.privacy.description}</p><strong>{copy.privacy.badge}</strong></div><ul className="privacy-list">{copy.privacy.items.map((item) => <li key={item}><Icon name="check" /><span>{item}</span></li>)}</ul></div></section>
      <section className="section pricing-section" id="plans"><div className="shell"><SectionTitle kicker={copy.pricing.kicker} title={copy.pricing.title} description={copy.pricing.description}/><div className="billing-toggle" role="group" aria-label={copy.pricing.annualNote}><button className={!annual ? "active" : ""} onClick={() => setAnnual(false)}>{copy.pricing.monthly}</button><button className={annual ? "active" : ""} onClick={() => setAnnual(true)}>{copy.pricing.annual}</button><span>{copy.pricing.annualNote}</span></div><div className="pricing-grid">{copy.pricing.plans.map((plan, index) => <article className={index === 2 ? "price-card recommended" : "price-card"} key={plan.name}>{index === 2 && <span className="popular">{copy.pricing.recommended}</span>}<h3>{plan.name}</h3><p className="plan-desc">{plan.description}</p><p className="price"><b>{annual ? plan.annual : plan.monthly}</b>{!plan.monthly.toLowerCase().includes("request") && !plan.monthly.toLowerCase().includes("consulta") && <span>{annual ? copy.pricing.year : copy.pricing.month}</span>}</p><ul>{plan.features.map((feature) => <li key={feature}><Icon name="check" />{feature}</li>)}</ul><a className={index === 2 ? "button" : "button outline"} href={index === 3 ? "mailto:comercial@gero.pt?subject=GeroFarm%20Custom" : "/register"}>{index === 3 ? copy.pricing.contact : copy.pricing.choose}</a></article>)}</div><p className="vat-note">{copy.pricing.vat}</p><div className="addons"><div><h3>{copy.pricing.addonsTitle}</h3><ul>{copy.pricing.addons.map((addon) => <li key={addon}><Icon name="check" />{addon}</li>)}</ul></div><div className="paid-notes"><p>{copy.pricing.paidNote}</p></div></div></div></section>
      <section className="section shell faq-section" id="faq"><SectionTitle kicker={copy.faq.kicker} title={copy.faq.title} description=""/><div className="faq-list">{copy.faq.items.map((item) => <details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section>
      <section className="closing"><div className="shell closing-inner"><div><h2>{copy.closing.title}</h2><p>{copy.closing.description}</p></div><div className="cta-row"><a className="button light-button" href="/register">{copy.closing.primary}<Icon name="arrow" /></a><a className="button transparent" href="/login">{copy.closing.secondary}</a></div></div></section>
    </main>
    <footer><div className="shell footer-grid"><div><Brand/><p>{copy.footer.tagline}</p></div><div><b>{copy.footer.product}</b><a href="#platform">{copy.nav.platform}</a><a href="#weather">{copy.nav.weather}</a><a href="#privacy">{copy.nav.privacy}</a><a href="#plans">{copy.nav.plans}</a></div><div><b>{copy.footer.account}</b><a href="/register">{copy.nav.start}</a><a href="/login">{copy.nav.login}</a></div><div><b>{copy.footer.legal}</b><a href={`/privacy-policy?lang=${locale}`}>{copy.footer.privacy}</a><a href={`/terms?lang=${locale}`}>{copy.footer.terms}</a><a href={`/cookie-policy?lang=${locale}`}>{copy.footer.cookies}</a><button className="footer-cookie-button" onClick={openCookiePreferences}>{cookieMessage(locale, "cookies.manage")}</button></div></div><div className="shell footer-bottom"><p>{copy.footer.future}</p><p>© {new Date().getFullYear()} Gero · {copy.footer.rights}</p></div></footer>
  </div>;
}
