CREATE TABLE "farm"."irrigation_sectors"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"holding_id" uuid NOT NULL REFERENCES "farm"."farm_holdings"("id"),"code" varchar(20) NOT NULL,"name" varchar(160) NOT NULL,"system" varchar(24) NOT NULL,"custom_system" varchar(120),"efficiency_percent" numeric(6,2),"status" varchar(16) DEFAULT 'active' NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,"updated_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "irrigation_sectors_system_valid" CHECK("system" in ('drip','sprinkler','gravity','flood','other')),CONSTRAINT "irrigation_sectors_custom_system_valid" CHECK(("system"='other' and "custom_system" is not null) or ("system"<>'other' and "custom_system" is null)),CONSTRAINT "irrigation_sectors_efficiency_valid" CHECK("efficiency_percent" is null or ("efficiency_percent">0 and "efficiency_percent"<=100)),CONSTRAINT "irrigation_sectors_status_valid" CHECK("status" in ('active','inactive')));
--> statement-breakpoint
CREATE UNIQUE INDEX "irrigation_sectors_org_code_unique" ON "farm"."irrigation_sectors"("organization_id","code"); CREATE INDEX "irrigation_sectors_holding_status_idx" ON "farm"."irrigation_sectors"("organization_id","holding_id","status");
--> statement-breakpoint
CREATE TABLE "farm"."irrigation_sector_fields"("sector_id" uuid NOT NULL REFERENCES "farm"."irrigation_sectors"("id"),"field_id" uuid NOT NULL REFERENCES "farm"."fields"("id"),"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"assigned_at" timestamptz DEFAULT now() NOT NULL); CREATE UNIQUE INDEX "irrigation_sector_fields_sector_field_unique" ON "farm"."irrigation_sector_fields"("sector_id","field_id"); CREATE UNIQUE INDEX "irrigation_sector_fields_active_field_unique" ON "farm"."irrigation_sector_fields"("organization_id","field_id");
--> statement-breakpoint
CREATE TABLE "farm"."water_meters"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"holding_id" uuid NOT NULL REFERENCES "farm"."farm_holdings"("id"),"code" varchar(20) NOT NULL,"name" varchar(160) NOT NULL,"serial_number" varchar(120) NOT NULL,"unit" varchar(8) DEFAULT 'm3' NOT NULL,"status" varchar(16) DEFAULT 'active' NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "water_meters_unit_valid" CHECK("unit"='m3'),CONSTRAINT "water_meters_status_valid" CHECK("status" in ('active','inactive','replaced'))); CREATE UNIQUE INDEX "water_meters_org_code_unique" ON "farm"."water_meters"("organization_id","code"); CREATE INDEX "water_meters_holding_status_idx" ON "farm"."water_meters"("organization_id","holding_id","status");
--> statement-breakpoint
CREATE TABLE "farm"."water_meter_sectors"("meter_id" uuid NOT NULL REFERENCES "farm"."water_meters"("id"),"sector_id" uuid NOT NULL REFERENCES "farm"."irrigation_sectors"("id"),"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id")); CREATE UNIQUE INDEX "water_meter_sectors_unique" ON "farm"."water_meter_sectors"("meter_id","sector_id");
--> statement-breakpoint
CREATE TABLE "farm"."water_meter_readings"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"meter_id" uuid NOT NULL REFERENCES "farm"."water_meters"("id"),"read_at" timestamptz NOT NULL,"value_m3" numeric(18,3) NOT NULL,"origin" varchar(16) NOT NULL,"event" varchar(16) DEFAULT 'normal' NOT NULL,"photo_url" varchar(1000),"notes" varchar(1000),"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "water_meter_readings_value_valid" CHECK("value_m3">=0),CONSTRAINT "water_meter_readings_origin_valid" CHECK("origin" in ('manual','integrated')),CONSTRAINT "water_meter_readings_event_valid" CHECK("event" in ('normal','replacement','reset','rollover'))); CREATE INDEX "water_meter_readings_meter_date_idx" ON "farm"."water_meter_readings"("organization_id","meter_id","read_at");
--> statement-breakpoint
CREATE TABLE "farm"."irrigation_water_analyses"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"sampled_on" date NOT NULL,"nitrate_mg_l" numeric(12,4) NOT NULL,"source" varchar(180),"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "irrigation_water_analyses_nitrate_valid" CHECK("nitrate_mg_l">=0)); CREATE INDEX "irrigation_water_analyses_org_date_idx" ON "farm"."irrigation_water_analyses"("organization_id","sampled_on");
--> statement-breakpoint
CREATE TABLE "farm"."irrigation_water_analysis_sectors"("analysis_id" uuid NOT NULL REFERENCES "farm"."irrigation_water_analyses"("id"),"sector_id" uuid NOT NULL REFERENCES "farm"."irrigation_sectors"("id"),"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id")); CREATE UNIQUE INDEX "irrigation_water_analysis_sectors_unique" ON "farm"."irrigation_water_analysis_sectors"("analysis_id","sector_id");
--> statement-breakpoint
CREATE TABLE "farm"."irrigation_records"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"operation_id" uuid REFERENCES "farm"."operations"("id"),"status" varchar(32) NOT NULL,"input_mode" varchar(24) NOT NULL,"scheduled_week_end" date,"performed_at" timestamptz,"area_ha" numeric(14,4) NOT NULL,"volume_m3" numeric(16,3) NOT NULL,"dose_m3_ha" numeric(16,3) NOT NULL,"depth_mm" numeric(16,3) NOT NULL,"flow_m3_h" numeric(16,3),"duration_minutes" numeric(12,2),"applications" jsonb NOT NULL,"meter_allocations" jsonb DEFAULT '[]'::jsonb NOT NULL,"water_analysis_id" uuid REFERENCES "farm"."irrigation_water_analyses"("id"),"nitrate_analysis_snapshot" jsonb,"fertigation_snapshot" jsonb,"resource_snapshot" jsonb NOT NULL,"notes" varchar(2000),"reversed_at" timestamptz,"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "irrigation_records_status_valid" CHECK("status" in ('scheduled','performed','performed_by_schedule','reversed')),CONSTRAINT "irrigation_records_input_valid" CHECK("input_mode" in ('volume_total','dose_m3_ha','depth_mm','flow_duration','meter_difference')),CONSTRAINT "irrigation_records_values_valid" CHECK("area_ha">0 and "volume_m3">0 and "dose_m3_ha">0 and "depth_mm">0),CONSTRAINT "irrigation_records_schedule_valid" CHECK(("status"='scheduled' and "operation_id" is null and "scheduled_week_end" is not null and "performed_at" is null) or ("status"<>'scheduled' and "operation_id" is not null and "performed_at" is not null))); CREATE UNIQUE INDEX "irrigation_records_operation_unique" ON "farm"."irrigation_records"("operation_id"); CREATE INDEX "irrigation_records_org_status_week_idx" ON "farm"."irrigation_records"("organization_id","status","scheduled_week_end");
--> statement-breakpoint
ALTER TABLE "farm"."irrigation_sectors" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_sectors" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_sector_fields" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_sector_fields" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."water_meters" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."water_meters" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."water_meter_sectors" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."water_meter_sectors" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."water_meter_readings" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."water_meter_readings" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_water_analyses" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_water_analyses" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_water_analysis_sectors" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_water_analysis_sectors" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_records" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."irrigation_records" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "irrigation_sectors_tenant_isolation" ON "farm"."irrigation_sectors" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "irrigation_sector_fields_tenant_isolation" ON "farm"."irrigation_sector_fields" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "water_meters_tenant_isolation" ON "farm"."water_meters" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "water_meter_sectors_tenant_isolation" ON "farm"."water_meter_sectors" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "water_meter_readings_tenant_isolation" ON "farm"."water_meter_readings" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "irrigation_water_analyses_tenant_isolation" ON "farm"."irrigation_water_analyses" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "irrigation_water_analysis_sectors_tenant_isolation" ON "farm"."irrigation_water_analysis_sectors" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "irrigation_records_tenant_isolation" ON "farm"."irrigation_records" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid);
--> statement-breakpoint
CREATE FUNCTION "farm"."protect_irrigation_physical_history"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status in ('performed','performed_by_schedule','reversed') AND NEW.status <> 'reversed' THEN RAISE EXCEPTION 'performed irrigation history is immutable'; END IF; IF OLD.status='reversed' THEN RAISE EXCEPTION 'reversed irrigation history is immutable'; END IF; RETURN NEW; END $$; CREATE TRIGGER "irrigation_records_history_guard" BEFORE UPDATE ON "farm"."irrigation_records" FOR EACH ROW EXECUTE FUNCTION "farm"."protect_irrigation_physical_history"(); REVOKE DELETE ON TABLE "farm"."irrigation_records", "farm"."water_meter_readings" FROM "gero_farm_app";
--> statement-breakpoint
ALTER TABLE "farm"."irrigation_records" DROP CONSTRAINT "irrigation_records_schedule_valid"; CREATE OR REPLACE FUNCTION "farm"."protect_irrigation_physical_history"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status='reversed' THEN RAISE EXCEPTION 'reversed irrigation history is immutable'; END IF; IF OLD.status in ('performed','performed_by_schedule') AND NOT (OLD.operation_id is null AND NEW.operation_id is not null AND NEW.status=OLD.status) AND NEW.status <> 'reversed' THEN RAISE EXCEPTION 'performed irrigation history is immutable'; END IF; RETURN NEW; END $$;
