CREATE TABLE "farm"."agronomic_monitorings"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"observed_at" timestamptz NOT NULL,"technician_worker_id" uuid REFERENCES "farm"."workers"("id"),"field_ids" jsonb NOT NULL,"plantation_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"crop_period_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"geometry" jsonb,"automatic_weather" jsonb NOT NULL,"corrected_weather" jsonb,"correction_reason" varchar(500),"findings" jsonb NOT NULL,"linked_operation_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"attachments" jsonb DEFAULT '[]'::jsonb NOT NULL,"notes" varchar(2000),"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "agronomic_monitorings_findings_valid" CHECK(jsonb_array_length("findings")>0));
CREATE INDEX "agronomic_monitorings_org_date_idx" ON "farm"."agronomic_monitorings"("organization_id","observed_at");
--> statement-breakpoint
CREATE TABLE "farm"."laboratory_samples"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"sampled_on" date NOT NULL,"responsible_worker_id" uuid REFERENCES "farm"."workers"("id"),"type" varchar(16) NOT NULL,"method" varchar(180) NOT NULL,"field_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"irrigation_sector_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"plantation_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"crop_period_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,"notes" varchar(2000),"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "laboratory_samples_type_valid" CHECK("type" in ('soil','water','leaf','other')));
CREATE INDEX "laboratory_samples_org_date_idx" ON "farm"."laboratory_samples"("organization_id","sampled_on");
--> statement-breakpoint
CREATE TABLE "farm"."laboratory_results"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"sample_id" uuid NOT NULL REFERENCES "farm"."laboratory_samples"("id"),"resulted_on" date NOT NULL,"laboratory" varchar(180) NOT NULL,"bulletin_number" varchar(120) NOT NULL,"bulletin_url" varchar(1000),"valid_until" date,"results" jsonb NOT NULL,"created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "laboratory_results_sample_unique" ON "farm"."laboratory_results"("sample_id"); CREATE INDEX "laboratory_results_org_validity_idx" ON "farm"."laboratory_results"("organization_id","valid_until");
--> statement-breakpoint
CREATE TABLE "farm"."harvest_sequences"("organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"year" numeric(4,0) NOT NULL,"next_value" numeric(12,0) DEFAULT 1 NOT NULL); CREATE UNIQUE INDEX "harvest_sequences_org_year_unique" ON "farm"."harvest_sequences"("organization_id","year");
--> statement-breakpoint
CREATE TABLE "farm"."harvests"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"operation_id" uuid NOT NULL REFERENCES "farm"."operations"("id"),"lot_code" varchar(40) NOT NULL,"culture_id" varchar(32) NOT NULL,"started_at" timestamptz NOT NULL,"ended_at" timestamptz,"total_net_kg" numeric(18,3) NOT NULL,"origins" jsonb NOT NULL,"categories" jsonb NOT NULL,"lots" jsonb NOT NULL,"destinations" jsonb NOT NULL,"quality" jsonb NOT NULL,"commercial_snapshot" jsonb,"loss_reason" varchar(1000),"safety_warnings" jsonb DEFAULT '[]'::jsonb NOT NULL,"notes" varchar(2000),"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "harvests_weight_valid" CHECK("total_net_kg">0)); CREATE UNIQUE INDEX "harvests_operation_unique" ON "farm"."harvests"("operation_id"); CREATE UNIQUE INDEX "harvests_org_lot_unique" ON "farm"."harvests"("organization_id","lot_code"); CREATE INDEX "harvests_org_date_idx" ON "farm"."harvests"("organization_id","started_at");
--> statement-breakpoint
CREATE TABLE "farm"."notebook_sequences"("organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"holding_id" uuid NOT NULL REFERENCES "farm"."farm_holdings"("id"),"year" numeric(4,0) NOT NULL,"next_value" numeric(12,0) DEFAULT 1 NOT NULL); CREATE UNIQUE INDEX "notebook_sequences_holding_year_unique" ON "farm"."notebook_sequences"("holding_id","year");
--> statement-breakpoint
CREATE TABLE "farm"."field_notebooks"("id" uuid PRIMARY KEY,"organization_id" uuid NOT NULL REFERENCES "farm"."organizations"("organization_id"),"holding_id" uuid NOT NULL REFERENCES "farm"."farm_holdings"("id"),"number" varchar(40) NOT NULL,"version" numeric(6,0) NOT NULL,"scope" jsonb NOT NULL,"snapshot" jsonb NOT NULL,"language" varchar(16) NOT NULL,"timezone" varchar(64) NOT NULL,"issuer_user_id" uuid NOT NULL,"integrity_id" varchar(64) NOT NULL,"pdf_base64" text,"issued_at" timestamptz DEFAULT now() NOT NULL,"deleted_at" timestamptz,"deleted_by" uuid,"created_at" timestamptz DEFAULT now() NOT NULL,CONSTRAINT "field_notebooks_version_valid" CHECK("version">0)); CREATE UNIQUE INDEX "field_notebooks_org_number_version_unique" ON "farm"."field_notebooks"("organization_id","number","version"); CREATE UNIQUE INDEX "field_notebooks_integrity_unique" ON "farm"."field_notebooks"("integrity_id"); CREATE INDEX "field_notebooks_org_issued_idx" ON "farm"."field_notebooks"("organization_id","issued_at");
--> statement-breakpoint
ALTER TABLE "farm"."agronomic_monitorings" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."agronomic_monitorings" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."laboratory_samples" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."laboratory_samples" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."laboratory_results" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."laboratory_results" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."harvest_sequences" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."harvest_sequences" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."harvests" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."harvests" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."notebook_sequences" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."notebook_sequences" FORCE ROW LEVEL SECURITY; ALTER TABLE "farm"."field_notebooks" ENABLE ROW LEVEL SECURITY; ALTER TABLE "farm"."field_notebooks" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "agronomic_monitorings_tenant_isolation" ON "farm"."agronomic_monitorings" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "laboratory_samples_tenant_isolation" ON "farm"."laboratory_samples" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "laboratory_results_tenant_isolation" ON "farm"."laboratory_results" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "harvest_sequences_tenant_isolation" ON "farm"."harvest_sequences" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "harvests_tenant_isolation" ON "farm"."harvests" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "notebook_sequences_tenant_isolation" ON "farm"."notebook_sequences" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid); CREATE POLICY "field_notebooks_tenant_isolation" ON "farm"."field_notebooks" AS RESTRICTIVE FOR ALL TO public USING("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid) WITH CHECK("organization_id"=nullif(current_setting('app.organization_id',true),'')::uuid);
--> statement-breakpoint
CREATE FUNCTION "farm"."protect_harvest_lot_code"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.lot_code<>OLD.lot_code OR NEW.operation_id<>OLD.operation_id OR NEW.culture_id<>OLD.culture_id THEN RAISE EXCEPTION 'harvest identity is immutable'; END IF; RETURN NEW; END $$; CREATE TRIGGER "harvest_identity_guard" BEFORE UPDATE ON "farm"."harvests" FOR EACH ROW EXECUTE FUNCTION "farm"."protect_harvest_lot_code"();
--> statement-breakpoint
CREATE FUNCTION "farm"."protect_notebook_version"() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.deleted_at is null AND NEW.deleted_at is not null AND NEW.pdf_base64 is null AND NEW.number=OLD.number AND NEW.version=OLD.version AND NEW.snapshot=OLD.snapshot AND NEW.integrity_id=OLD.integrity_id THEN RETURN NEW; END IF; RAISE EXCEPTION 'issued field notebook is immutable'; END $$; CREATE TRIGGER "field_notebook_version_guard" BEFORE UPDATE ON "farm"."field_notebooks" FOR EACH ROW EXECUTE FUNCTION "farm"."protect_notebook_version"(); REVOKE DELETE ON TABLE "farm"."field_notebooks", "farm"."harvests", "farm"."laboratory_results" FROM "gero_farm_app";
