import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { PrivacyRequestDto } from "@shared/privacy";
import { useAuth } from "../../auth";
import { useI18n } from "../../i18n";
import { privacyCopies } from "./privacy-locales.generated";
import "./privacy.css";

type Overview = { requests: PrivacyRequestDto[]; policies: Array<{ category: string; years: number; trigger: string; action: string; legallyControlled: boolean }> };
export default function PrivacyModule() {
  const { locale } = useI18n(); const { session } = useAuth(); const t = privacyCopies[locale]; const owner = session?.access.membership.role === "owner";
  const [overview, setOverview] = useState<Overview | null>(null); const [managed, setManaged] = useState<PrivacyRequestDto[]>([]); const [failed, setFailed] = useState(false); const [form, setForm] = useState<{ type: "access" | "rectification" | "erasure"; details: string }>({ type: "access", details: "" }); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setFailed(false); try { const responses = await Promise.all([fetch("/api/farm/privacy", { credentials: "include" }), ...(owner ? [fetch("/api/farm/privacy/manage", { credentials: "include" })] : [])]); if (responses.some((response) => !response.ok)) throw new Error(); const payloads = await Promise.all(responses.map((response) => response.json())); setOverview(payloads[0].data); if (owner) setManaged(payloads[1].data); } catch { setFailed(true); } }, [owner]);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); const response = await fetch("/api/farm/privacy/requests", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); if (response.ok) { setForm({ type: "access", details: "" }); await load(); } else setFailed(true); setSaving(false); }
  if (!overview) return <div className={`module-state ${failed ? "error-state" : ""}`}>{failed ? <p>{t["privacy.noRequests"]}</p> : <span className="spinner" />}</div>;
  const requestLabels = { access: t["profile.privacy.requestData"], rectification: t["profile.privacy.requestRectification"], erasure: t["profile.privacy.requestErasure"] };
  return <><section className="page-heading"><div><p>Privacy by Design</p><h1>{t["privacy.title"]}</h1><span>{t["privacy.description"]}</span></div><a className="primary-action" href="/api/farm/privacy/export">{t["privacy.exportPersonalData"]}</a></section><section className="privacy-dashboard"><div><span>{t["privacy.dashboard.pending"]}</span><b>{overview.requests.filter((request) => request.status === "submitted" || request.status === "in_review").length}</b></div><div><span>{t["privacy.dashboard.completed"]}</span><b>{overview.requests.filter((request) => request.status === "completed").length}</b></div><div><span>{t["privacy.dashboard.retentionPolicy"]}</span><b>{overview.policies.length}</b></div></section><div className="privacy-columns"><section className="panel privacy-panel"><h2>{t["privacy.requestsTitle"]}</h2><p>{t["privacy.requestsDescription"]}</p><form onSubmit={(event) => void submit(event)}><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as typeof form.type })}>{Object.entries(requestLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea required minLength={10} maxLength={4000} value={form.details} aria-label={t["privacy.requestsDescription"]} onChange={(event) => setForm({ ...form, details: event.target.value })} /><button className="primary-action" disabled={saving}>{requestLabels[form.type]}</button></form><RequestList requests={overview.requests} t={t} labels={requestLabels} /></section><section className="panel privacy-panel"><h2>{t["privacy.retentionPoliciesTitle"]}</h2><p>{t["privacy.retentionPoliciesDescription"]}</p><div className="retention-list">{overview.policies.map((policy) => <article key={policy.category}><b>{t[`retention.category.${policy.category}` as keyof typeof t]}</b><span>{policy.years} {t["retention.unit.years"]}</span><em>{t[`retention.action.${policy.action}` as keyof typeof t]}</em>{policy.legallyControlled && <small>{t["privacy.policyLegallyControlled"]}</small>}</article>)}</div></section></div>{owner && <section className="panel privacy-panel privacy-manage"><h2>{t["privacy.managerTitle"]}</h2><p>{t["privacy.ownerRecovery"]}</p><RequestList requests={managed} t={t} labels={requestLabels} manage onReviewed={load} /></section>}</>;
}
function RequestList({ requests, t, labels, manage, onReviewed }: { requests: PrivacyRequestDto[]; t: Record<string, string>; labels: Record<string, string>; manage?: boolean; onReviewed?: () => Promise<void> }) { if (!requests.length) return <p className="privacy-empty">{t["privacy.noRequests"]}</p>; return <div className="privacy-requests">{requests.map((request) => <article key={request.id}><div><b>{labels[request.type] || t["privacy.requestType"]}</b><span>{new Date(request.submittedAt).toLocaleDateString()} · {statusLabel(t, request.status)}</span><p>{request.details}</p>{request.response && <blockquote>{request.response}</blockquote>}</div>{manage && (request.status === "submitted" || request.status === "in_review") && <Review request={request} t={t} onReviewed={onReviewed!} />}</article>)}</div>; }
function Review({ request, t, onReviewed }: { request: PrivacyRequestDto; t: Record<string, string>; onReviewed: () => Promise<void> }) { const [response, setResponse] = useState(""); async function review(status: "in_review" | "completed" | "rejected") { const result = await fetch(`/api/farm/privacy/requests/${request.id}`, { method: "PATCH", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ status, response }) }); if (result.ok) await onReviewed(); } return <div className="privacy-review"><textarea value={response} minLength={2} maxLength={4000} aria-label={t["privacy.responseToUser"]} onChange={(event) => setResponse(event.target.value)} /><button disabled={response.length < 2} onClick={() => void review("in_review")}>{t["privacy.acceptRequest"]}</button><button disabled={response.length < 2} onClick={() => void review("completed")}>{t["privacy.completeRequest"]}</button><button disabled={response.length < 2} onClick={() => void review("rejected")}>{t["privacy.rejectRequest"]}</button></div>; }
function statusLabel(t: Record<string, string>, status: string) { return status === "submitted" ? t["privacy.action.privacy_request.submitted"] : status === "in_review" ? t["privacy.acceptRequest"] : status === "completed" ? t["privacy.requestCompleted"] : status === "archived" ? t["privacy.archived"] : t["privacy.rejectRequest"]; }
