import type { SupportedLocale } from "../home-copy";

export type DashboardCopy = { attention: string; readyTitle: string; readyDescription: string; missingTitle: string; errorTitle: string; actionsTitle: string; contextTitle: string };
const c = (...values: string[]): DashboardCopy => { const [attention, readyTitle, readyDescription, missingTitle, errorTitle, actionsTitle, contextTitle] = values; return { attention, readyTitle, readyDescription, missingTitle, errorTitle, actionsTitle, contextTitle }; };

export const dashboardCopies: Record<SupportedLocale, DashboardCopy> = {
  "pt-PT": c("O que precisa da sua atenção?", "A exploração está pronta", "Pode começar a registar e acompanhar o trabalho de campo.", "Conclua a configuração da exploração", "Não foi possível verificar a exploração", "O que quer fazer agora?", "Contexto atual"),
  "pt-BR": c("O que precisa da sua atenção?", "A fazenda está pronta", "Você pode começar a registrar e acompanhar o trabalho de campo.", "Conclua a configuração da fazenda", "Não foi possível verificar a fazenda", "O que você quer fazer agora?", "Contexto atual"),
  en: c("What needs your attention?", "The holding is ready", "You can start recording and following field work.", "Complete the holding setup", "The holding could not be checked", "What would you like to do now?", "Current context"),
  fr: c("Qu’est-ce qui requiert votre attention ?", "L’exploitation est prête", "Vous pouvez commencer à enregistrer et suivre les travaux.", "Terminez la configuration de l’exploitation", "Impossible de vérifier l’exploitation", "Que souhaitez-vous faire maintenant ?", "Contexte actuel"),
  es: c("¿Qué requiere su atención?", "La explotación está lista", "Puede empezar a registrar y seguir el trabajo de campo.", "Complete la configuración de la explotación", "No se pudo verificar la explotación", "¿Qué quiere hacer ahora?", "Contexto actual"),
  nl: c("Wat vraagt uw aandacht?", "Het bedrijf is klaar", "U kunt veldwerk registreren en opvolgen.", "Voltooi de bedrijfsconfiguratie", "Het bedrijf kon niet worden gecontroleerd", "Wat wilt u nu doen?", "Huidige context"),
  de: c("Was erfordert Ihre Aufmerksamkeit?", "Der Betrieb ist bereit", "Sie können Feldarbeiten erfassen und verfolgen.", "Betriebseinrichtung abschließen", "Der Betrieb konnte nicht geprüft werden", "Was möchten Sie jetzt tun?", "Aktueller Kontext"),
  ja: c("確認が必要なことは何ですか？", "農場の準備ができました", "圃場作業の記録と確認を開始できます。", "農場の設定を完了してください", "農場を確認できませんでした", "次に何をしますか？", "現在のコンテキスト"),
  he: c("מה דורש את תשומת לבך?", "המשק מוכן", "אפשר להתחיל לתעד ולעקוב אחר עבודת השטח.", "השלמת הגדרת המשק", "לא ניתן לבדוק את המשק", "מה ברצונך לעשות כעת?", "ההקשר הנוכחי"),
  tr: c("Neye dikkat etmeniz gerekiyor?", "İşletme hazır", "Saha çalışmalarını kaydetmeye ve izlemeye başlayabilirsiniz.", "İşletme kurulumunu tamamlayın", "İşletme denetlenemedi", "Şimdi ne yapmak istersiniz?", "Geçerli bağlam"),
  ar: c("ما الذي يحتاج إلى انتباهك؟", "المزرعة جاهزة", "يمكنك البدء في تسجيل العمل الميداني ومتابعته.", "أكمل إعداد المزرعة", "تعذر التحقق من المزرعة", "ماذا تريد أن تفعل الآن؟", "السياق الحالي"),
  pl: c("Co wymaga uwagi?", "Gospodarstwo jest gotowe", "Można rozpocząć rejestrowanie i śledzenie prac polowych.", "Dokończ konfigurację gospodarstwa", "Nie udało się sprawdzić gospodarstwa", "Co chcesz teraz zrobić?", "Bieżący kontekst"),
  hr: c("Što zahtijeva vašu pozornost?", "Gospodarstvo je spremno", "Možete početi bilježiti i pratiti radove u polju.", "Dovršite postavljanje gospodarstva", "Gospodarstvo nije moguće provjeriti", "Što sada želite učiniti?", "Trenutačni kontekst"),
  el: c("Τι χρειάζεται την προσοχή σας;", "Η εκμετάλλευση είναι έτοιμη", "Μπορείτε να αρχίσετε να καταγράφετε και να παρακολουθείτε τις εργασίες.", "Ολοκληρώστε τη ρύθμιση της εκμετάλλευσης", "Δεν ήταν δυνατός ο έλεγχος της εκμετάλλευσης", "Τι θέλετε να κάνετε τώρα;", "Τρέχον πλαίσιο"),
  sv: c("Vad behöver din uppmärksamhet?", "Gården är redo", "Du kan börja registrera och följa fältarbetet.", "Slutför gårdsinställningen", "Gården kunde inte kontrolleras", "Vad vill du göra nu?", "Aktuellt sammanhang"),
  no: c("Hva trenger oppmerksomheten din?", "Gården er klar", "Du kan begynne å registrere og følge feltarbeidet.", "Fullfør gårdsoppsettet", "Gården kunne ikke kontrolleres", "Hva vil du gjøre nå?", "Gjeldende kontekst"),
  da: c("Hvad kræver din opmærksomhed?", "Bedriften er klar", "Du kan begynde at registrere og følge markarbejdet.", "Færdiggør opsætningen af bedriften", "Bedriften kunne ikke kontrolleres", "Hvad vil du gøre nu?", "Aktuel kontekst"),
  it: c("Cosa richiede la tua attenzione?", "L’azienda è pronta", "Puoi iniziare a registrare e seguire il lavoro in campo.", "Completa la configurazione dell’azienda", "Non è stato possibile verificare l’azienda", "Cosa vuoi fare ora?", "Contesto attuale"),
  uk: c("Що потребує вашої уваги?", "Господарство готове", "Можна почати реєструвати та відстежувати польові роботи.", "Завершіть налаштування господарства", "Не вдалося перевірити господарство", "Що ви хочете зробити зараз?", "Поточний контекст"),
  ro: c("Ce necesită atenția dvs.?", "Exploatația este pregătită", "Puteți începe să înregistrați și să urmăriți lucrările de teren.", "Finalizați configurarea exploatației", "Exploatația nu a putut fi verificată", "Ce doriți să faceți acum?", "Context actual"),
  fi: c("Mikä vaatii huomiotasi?", "Tila on valmis", "Voit aloittaa peltotöiden kirjaamisen ja seurannan.", "Viimeistele tilan määritys", "Tilaa ei voitu tarkistaa", "Mitä haluat tehdä nyt?", "Nykyinen konteksti"),
  bg: c("Какво изисква вниманието ви?", "Стопанството е готово", "Можете да започнете да регистрирате и следите полската работа.", "Завършете настройката на стопанството", "Стопанството не можа да бъде проверено", "Какво искате да направите сега?", "Текущ контекст"),
  hu: c("Mi igényel figyelmet?", "A gazdaság készen áll", "Megkezdheti a szántóföldi munkák rögzítését és követését.", "Fejezze be a gazdaság beállítását", "A gazdaság nem ellenőrizhető", "Mit szeretne most tenni?", "Jelenlegi környezet"),
  is: c("Hvað þarfnast athygli þinnar?", "Býlið er tilbúið", "Þú getur byrjað að skrá og fylgjast með vinnu á akri.", "Ljúktu við uppsetningu býlisins", "Ekki tókst að athuga býlið", "Hvað viltu gera núna?", "Núverandi samhengi"),
  sk: c("Čo si vyžaduje vašu pozornosť?", "Hospodárstvo je pripravené", "Môžete začať zaznamenávať a sledovať práce na poli.", "Dokončite nastavenie hospodárstva", "Hospodárstvo sa nepodarilo skontrolovať", "Čo chcete teraz urobiť?", "Aktuálny kontext"),
  lt: c("Kam reikia jūsų dėmesio?", "Ūkis parengtas", "Galite pradėti registruoti ir stebėti lauko darbus.", "Užbaikite ūkio nustatymą", "Ūkio patikrinti nepavyko", "Ką norite daryti dabar?", "Dabartinis kontekstas"),
  sl: c("Kaj zahteva vašo pozornost?", "Kmetija je pripravljena", "Začnete lahko beležiti in spremljati delo na polju.", "Dokončajte nastavitev kmetije", "Kmetije ni bilo mogoče preveriti", "Kaj želite storiti zdaj?", "Trenutni kontekst"),
  lv: c("Kam nepieciešama jūsu uzmanība?", "Saimniecība ir gatava", "Varat sākt reģistrēt un pārraudzīt lauka darbus.", "Pabeidziet saimniecības iestatīšanu", "Saimniecību neizdevās pārbaudīt", "Ko vēlaties darīt tagad?", "Pašreizējais konteksts"),
};
