import type { SupportedLocale } from "../home-copy";

export type WorkspaceCopy = {
  overview: string;
  settings: string;
  currentOrganization: string;
  navigation: string;
  openNavigation: string;
  closeNavigation: string;
  search: string;
  notifications: string;
  registerOperation: string;
  language: string;
  signOut: string;
  accountRole: string;
  workspace: string;
  greeting: string;
  ready: string;
  account: string;
  organization: string;
  access: string;
  authenticated: string;
  selected: string;
  authorized: string;
  implementation: string;
  pending: string;
  pendingDescription: string;
  homepage: string;
  mockup: string;
};

export const workspaceCopies: Record<SupportedLocale, WorkspaceCopy> = {
  "pt-PT": { overview: "Início", settings: "Configurações", currentOrganization: "Organização atual", navigation: "Navegação da aplicação", openNavigation: "Abrir navegação", closeNavigation: "Fechar navegação", search: "Pesquisar", notifications: "Avisos", registerOperation: "Registar operação", language: "Idioma", signOut: "Sair", accountRole: "Conta Gero", workspace: "Área de trabalho", greeting: "Olá, {name}.", ready: "A organização {organization} está selecionada e pronta para trabalhar.", account: "Conta", organization: "Organização", access: "Acesso", authenticated: "Autenticada", selected: "Selecionada", authorized: "Autorizado", implementation: "Implementação por módulos", pending: "Módulo em preparação", pendingDescription: "Este módulo está previsto na sequência aprovada e será disponibilizado depois de concluir o seu modelo de dados, regras, interface e revisão nas 28 línguas.", homepage: "Ver homepage", mockup: "Ver mockup" },
  "pt-BR": { overview: "Início", settings: "Configurações", currentOrganization: "Organização atual", navigation: "Navegação do aplicativo", openNavigation: "Abrir navegação", closeNavigation: "Fechar navegação", search: "Pesquisar", notifications: "Avisos", registerOperation: "Registrar operação", language: "Idioma", signOut: "Sair", accountRole: "Conta Gero", workspace: "Área de trabalho", greeting: "Olá, {name}.", ready: "A organização {organization} está selecionada e pronta para trabalhar.", account: "Conta", organization: "Organização", access: "Acesso", authenticated: "Autenticada", selected: "Selecionada", authorized: "Autorizado", implementation: "Implementação por módulos", pending: "Módulo em preparação", pendingDescription: "Este módulo está previsto na sequência aprovada e será disponibilizado depois que seu modelo de dados, regras, interface e revisão nos 28 idiomas forem concluídos.", homepage: "Ver página inicial", mockup: "Ver mockup" },
  en: { overview: "Overview", settings: "Settings", currentOrganization: "Current organisation", navigation: "Application navigation", openNavigation: "Open navigation", closeNavigation: "Close navigation", search: "Search", notifications: "Alerts", registerOperation: "Record operation", language: "Language", signOut: "Sign out", accountRole: "Gero account", workspace: "Workspace", greeting: "Hello, {name}.", ready: "The organisation {organization} is selected and ready for work.", account: "Account", organization: "Organisation", access: "Access", authenticated: "Authenticated", selected: "Selected", authorized: "Authorised", implementation: "Module implementation", pending: "Module being prepared", pendingDescription: "This module is in the approved sequence and will become available after its data model, rules, interface and review in all 28 languages are complete.", homepage: "View homepage", mockup: "View mockup" },
  fr: { overview: "Accueil", settings: "Paramètres", currentOrganization: "Organisation actuelle", navigation: "Navigation de l’application", openNavigation: "Ouvrir la navigation", closeNavigation: "Fermer la navigation", search: "Rechercher", notifications: "Alertes", registerOperation: "Enregistrer une opération", language: "Langue", signOut: "Se déconnecter", accountRole: "Compte Gero", workspace: "Espace de travail", greeting: "Bonjour, {name}.", ready: "L’organisation {organization} est sélectionnée et prête à travailler.", account: "Compte", organization: "Organisation", access: "Accès", authenticated: "Authentifié", selected: "Sélectionnée", authorized: "Autorisé", implementation: "Mise en œuvre par modules", pending: "Module en préparation", pendingDescription: "Ce module figure dans la séquence approuvée et sera disponible après finalisation de son modèle de données, de ses règles, de son interface et de sa révision dans les 28 langues.", homepage: "Voir la page d’accueil", mockup: "Voir la maquette" },
  es: { overview: "Inicio", settings: "Configuración", currentOrganization: "Organización actual", navigation: "Navegación de la aplicación", openNavigation: "Abrir navegación", closeNavigation: "Cerrar navegación", search: "Buscar", notifications: "Avisos", registerOperation: "Registrar operación", language: "Idioma", signOut: "Salir", accountRole: "Cuenta Gero", workspace: "Área de trabajo", greeting: "Hola, {name}.", ready: "La organización {organization} está seleccionada y lista para trabajar.", account: "Cuenta", organization: "Organización", access: "Acceso", authenticated: "Autenticada", selected: "Seleccionada", authorized: "Autorizado", implementation: "Implementación por módulos", pending: "Módulo en preparación", pendingDescription: "Este módulo forma parte de la secuencia aprobada y estará disponible cuando se completen su modelo de datos, reglas, interfaz y revisión en los 28 idiomas.", homepage: "Ver página de inicio", mockup: "Ver maqueta" },
  nl: { overview: "Overzicht", settings: "Instellingen", currentOrganization: "Huidige organisatie", navigation: "Applicatienavigatie", openNavigation: "Navigatie openen", closeNavigation: "Navigatie sluiten", search: "Zoeken", notifications: "Meldingen", registerOperation: "Bewerking registreren", language: "Taal", signOut: "Afmelden", accountRole: "Gero-account", workspace: "Werkruimte", greeting: "Hallo, {name}.", ready: "De organisatie {organization} is geselecteerd en klaar om mee te werken.", account: "Account", organization: "Organisatie", access: "Toegang", authenticated: "Geverifieerd", selected: "Geselecteerd", authorized: "Geautoriseerd", implementation: "Implementatie per module", pending: "Module in voorbereiding", pendingDescription: "Deze module staat in de goedgekeurde volgorde en wordt beschikbaar nadat het gegevensmodel, de regels, de interface en de beoordeling in alle 28 talen zijn voltooid.", homepage: "Homepage bekijken", mockup: "Mock-up bekijken" },
  de: { overview: "Übersicht", settings: "Einstellungen", currentOrganization: "Aktuelle Organisation", navigation: "Anwendungsnavigation", openNavigation: "Navigation öffnen", closeNavigation: "Navigation schließen", search: "Suchen", notifications: "Hinweise", registerOperation: "Arbeitsgang erfassen", language: "Sprache", signOut: "Abmelden", accountRole: "Gero-Konto", workspace: "Arbeitsbereich", greeting: "Hallo, {name}.", ready: "Die Organisation {organization} ist ausgewählt und arbeitsbereit.", account: "Konto", organization: "Organisation", access: "Zugriff", authenticated: "Authentifiziert", selected: "Ausgewählt", authorized: "Autorisiert", implementation: "Modulweise Umsetzung", pending: "Modul in Vorbereitung", pendingDescription: "Dieses Modul ist Teil der genehmigten Reihenfolge und wird verfügbar, sobald Datenmodell, Regeln, Oberfläche und Prüfung in allen 28 Sprachen abgeschlossen sind.", homepage: "Startseite ansehen", mockup: "Mock-up ansehen" },
  ja: { overview: "概要", settings: "設定", currentOrganization: "現在の組織", navigation: "アプリケーションのナビゲーション", openNavigation: "ナビゲーションを開く", closeNavigation: "ナビゲーションを閉じる", search: "検索", notifications: "通知", registerOperation: "作業を記録", language: "言語", signOut: "ログアウト", accountRole: "Geroアカウント", workspace: "ワークスペース", greeting: "こんにちは、{name}さん。", ready: "組織「{organization}」が選択され、作業の準備ができています。", account: "アカウント", organization: "組織", access: "アクセス", authenticated: "認証済み", selected: "選択済み", authorized: "許可済み", implementation: "モジュール別の実装", pending: "準備中のモジュール", pendingDescription: "このモジュールは承認済みの実装順序に含まれており、データモデル、規則、画面、および28言語すべての確認が完了した後に利用可能になります。", homepage: "ホームページを見る", mockup: "モックアップを見る" },
  he: { overview: "סקירה", settings: "הגדרות", currentOrganization: "הארגון הנוכחי", navigation: "ניווט ביישום", openNavigation: "פתיחת הניווט", closeNavigation: "סגירת הניווט", search: "חיפוש", notifications: "התראות", registerOperation: "רישום פעולה", language: "שפה", signOut: "יציאה", accountRole: "חשבון Gero", workspace: "סביבת עבודה", greeting: "שלום, {name}.", ready: "הארגון {organization} נבחר ומוכן לעבודה.", account: "חשבון", organization: "ארגון", access: "גישה", authenticated: "מאומת", selected: "נבחר", authorized: "מורשה", implementation: "יישום לפי מודולים", pending: "המודול בהכנה", pendingDescription: "מודול זה נכלל בסדר שאושר ויהיה זמין לאחר השלמת מודל הנתונים, הכללים, הממשק והבדיקה בכל 28 השפות.", homepage: "הצגת דף הבית", mockup: "הצגת הדגם" },
  tr: { overview: "Genel bakış", settings: "Ayarlar", currentOrganization: "Geçerli kuruluş", navigation: "Uygulama gezintisi", openNavigation: "Gezintiyi aç", closeNavigation: "Gezintiyi kapat", search: "Ara", notifications: "Uyarılar", registerOperation: "İşlem kaydet", language: "Dil", signOut: "Çıkış yap", accountRole: "Gero hesabı", workspace: "Çalışma alanı", greeting: "Merhaba, {name}.", ready: "{organization} kuruluşu seçildi ve çalışmaya hazır.", account: "Hesap", organization: "Kuruluş", access: "Erişim", authenticated: "Kimliği doğrulandı", selected: "Seçildi", authorized: "Yetkili", implementation: "Modül bazında uygulama", pending: "Modül hazırlanıyor", pendingDescription: "Bu modül onaylanan sırada yer alır ve veri modeli, kuralları, arayüzü ve 28 dildeki incelemesi tamamlandıktan sonra kullanıma açılacaktır.", homepage: "Ana sayfayı görüntüle", mockup: "Modeli görüntüle" },
  ar: { overview: "نظرة عامة", settings: "الإعدادات", currentOrganization: "المنظمة الحالية", navigation: "التنقل في التطبيق", openNavigation: "فتح التنقل", closeNavigation: "إغلاق التنقل", search: "بحث", notifications: "التنبيهات", registerOperation: "تسجيل عملية", language: "اللغة", signOut: "تسجيل الخروج", accountRole: "حساب Gero", workspace: "مساحة العمل", greeting: "مرحبًا، {name}.", ready: "تم اختيار المنظمة {organization} وهي جاهزة للعمل.", account: "الحساب", organization: "المنظمة", access: "الوصول", authenticated: "تمت المصادقة", selected: "محددة", authorized: "مصرّح به", implementation: "التنفيذ حسب الوحدات", pending: "الوحدة قيد الإعداد", pendingDescription: "هذه الوحدة مدرجة في التسلسل المعتمد وستتاح بعد اكتمال نموذج البيانات والقواعد والواجهة والمراجعة بجميع اللغات الـ28.", homepage: "عرض الصفحة الرئيسية", mockup: "عرض النموذج" },
  pl: { overview: "Przegląd", settings: "Ustawienia", currentOrganization: "Bieżąca organizacja", navigation: "Nawigacja aplikacji", openNavigation: "Otwórz nawigację", closeNavigation: "Zamknij nawigację", search: "Szukaj", notifications: "Alerty", registerOperation: "Zarejestruj zabieg", language: "Język", signOut: "Wyloguj się", accountRole: "Konto Gero", workspace: "Obszar roboczy", greeting: "Witaj, {name}.", ready: "Organizacja {organization} jest wybrana i gotowa do pracy.", account: "Konto", organization: "Organizacja", access: "Dostęp", authenticated: "Uwierzytelniono", selected: "Wybrana", authorized: "Upoważniony", implementation: "Wdrażanie modułami", pending: "Moduł w przygotowaniu", pendingDescription: "Ten moduł znajduje się w zatwierdzonej kolejności i zostanie udostępniony po ukończeniu modelu danych, reguł, interfejsu oraz przeglądu we wszystkich 28 językach.", homepage: "Zobacz stronę główną", mockup: "Zobacz makietę" },
  hr: { overview: "Pregled", settings: "Postavke", currentOrganization: "Trenutačna organizacija", navigation: "Navigacija aplikacije", openNavigation: "Otvori navigaciju", closeNavigation: "Zatvori navigaciju", search: "Pretraži", notifications: "Upozorenja", registerOperation: "Evidentiraj postupak", language: "Jezik", signOut: "Odjava", accountRole: "Gero račun", workspace: "Radni prostor", greeting: "Pozdrav, {name}.", ready: "Organizacija {organization} odabrana je i spremna za rad.", account: "Račun", organization: "Organizacija", access: "Pristup", authenticated: "Potvrđen identitet", selected: "Odabrana", authorized: "Odobren", implementation: "Implementacija po modulima", pending: "Modul u pripremi", pendingDescription: "Ovaj je modul u odobrenom redoslijedu i bit će dostupan nakon dovršetka podatkovnog modela, pravila, sučelja i pregleda na svih 28 jezika.", homepage: "Prikaži početnu stranicu", mockup: "Prikaži maketu" },
  el: { overview: "Επισκόπηση", settings: "Ρυθμίσεις", currentOrganization: "Τρέχων οργανισμός", navigation: "Πλοήγηση εφαρμογής", openNavigation: "Άνοιγμα πλοήγησης", closeNavigation: "Κλείσιμο πλοήγησης", search: "Αναζήτηση", notifications: "Ειδοποιήσεις", registerOperation: "Καταχώριση εργασίας", language: "Γλώσσα", signOut: "Αποσύνδεση", accountRole: "Λογαριασμός Gero", workspace: "Χώρος εργασίας", greeting: "Γεια σας, {name}.", ready: "Ο οργανισμός {organization} έχει επιλεγεί και είναι έτοιμος για εργασία.", account: "Λογαριασμός", organization: "Οργανισμός", access: "Πρόσβαση", authenticated: "Πιστοποιημένος", selected: "Επιλεγμένος", authorized: "Εξουσιοδοτημένος", implementation: "Υλοποίηση ανά ενότητα", pending: "Η ενότητα προετοιμάζεται", pendingDescription: "Αυτή η ενότητα περιλαμβάνεται στην εγκεκριμένη σειρά και θα είναι διαθέσιμη αφού ολοκληρωθούν το μοντέλο δεδομένων, οι κανόνες, η διεπαφή και ο έλεγχος και στις 28 γλώσσες.", homepage: "Προβολή αρχικής σελίδας", mockup: "Προβολή μακέτας" },
  sv: { overview: "Översikt", settings: "Inställningar", currentOrganization: "Aktuell organisation", navigation: "Programnavigering", openNavigation: "Öppna navigering", closeNavigation: "Stäng navigering", search: "Sök", notifications: "Aviseringar", registerOperation: "Registrera åtgärd", language: "Språk", signOut: "Logga ut", accountRole: "Gero-konto", workspace: "Arbetsyta", greeting: "Hej, {name}.", ready: "Organisationen {organization} är vald och klar att arbeta med.", account: "Konto", organization: "Organisation", access: "Åtkomst", authenticated: "Autentiserad", selected: "Vald", authorized: "Behörig", implementation: "Modulvis implementering", pending: "Modulen förbereds", pendingDescription: "Den här modulen ingår i den godkända ordningen och blir tillgänglig när datamodell, regler, gränssnitt och granskning på samtliga 28 språk är klara.", homepage: "Visa startsidan", mockup: "Visa modell" },
  no: { overview: "Oversikt", settings: "Innstillinger", currentOrganization: "Gjeldende organisasjon", navigation: "Programnavigasjon", openNavigation: "Åpne navigasjon", closeNavigation: "Lukk navigasjon", search: "Søk", notifications: "Varsler", registerOperation: "Registrer tiltak", language: "Språk", signOut: "Logg ut", accountRole: "Gero-konto", workspace: "Arbeidsområde", greeting: "Hei, {name}.", ready: "Organisasjonen {organization} er valgt og klar til bruk.", account: "Konto", organization: "Organisasjon", access: "Tilgang", authenticated: "Autentisert", selected: "Valgt", authorized: "Autorisert", implementation: "Modulvis implementering", pending: "Modulen forberedes", pendingDescription: "Denne modulen er med i den godkjente rekkefølgen og blir tilgjengelig når datamodellen, reglene, grensesnittet og gjennomgangen på alle 28 språk er ferdige.", homepage: "Vis startsiden", mockup: "Vis modell" },
  da: { overview: "Overblik", settings: "Indstillinger", currentOrganization: "Aktuel organisation", navigation: "Programnavigation", openNavigation: "Åbn navigation", closeNavigation: "Luk navigation", search: "Søg", notifications: "Advarsler", registerOperation: "Registrer arbejdsgang", language: "Sprog", signOut: "Log ud", accountRole: "Gero-konto", workspace: "Arbejdsområde", greeting: "Hej, {name}.", ready: "Organisationen {organization} er valgt og klar til arbejde.", account: "Konto", organization: "Organisation", access: "Adgang", authenticated: "Godkendt", selected: "Valgt", authorized: "Autoriseret", implementation: "Modulvis implementering", pending: "Modulet forberedes", pendingDescription: "Dette modul indgår i den godkendte rækkefølge og bliver tilgængeligt, når datamodel, regler, grænseflade og gennemgang på alle 28 sprog er færdige.", homepage: "Se forsiden", mockup: "Se mockup" },
  it: { overview: "Panoramica", settings: "Impostazioni", currentOrganization: "Organizzazione attuale", navigation: "Navigazione dell’applicazione", openNavigation: "Apri navigazione", closeNavigation: "Chiudi navigazione", search: "Cerca", notifications: "Avvisi", registerOperation: "Registra operazione", language: "Lingua", signOut: "Esci", accountRole: "Account Gero", workspace: "Area di lavoro", greeting: "Ciao, {name}.", ready: "L’organizzazione {organization} è selezionata e pronta per lavorare.", account: "Account", organization: "Organizzazione", access: "Accesso", authenticated: "Autenticato", selected: "Selezionata", authorized: "Autorizzato", implementation: "Implementazione per moduli", pending: "Modulo in preparazione", pendingDescription: "Questo modulo rientra nella sequenza approvata e sarà disponibile dopo il completamento del modello dati, delle regole, dell’interfaccia e della revisione in tutte le 28 lingue.", homepage: "Visualizza pagina iniziale", mockup: "Visualizza modello" },
  uk: { overview: "Огляд", settings: "Налаштування", currentOrganization: "Поточна організація", navigation: "Навігація застосунку", openNavigation: "Відкрити навігацію", closeNavigation: "Закрити навігацію", search: "Пошук", notifications: "Сповіщення", registerOperation: "Зареєструвати операцію", language: "Мова", signOut: "Вийти", accountRole: "Обліковий запис Gero", workspace: "Робочий простір", greeting: "Вітаємо, {name}.", ready: "Організацію {organization} вибрано, і вона готова до роботи.", account: "Обліковий запис", organization: "Організація", access: "Доступ", authenticated: "Автентифіковано", selected: "Вибрано", authorized: "Авторизовано", implementation: "Реалізація за модулями", pending: "Модуль готується", pendingDescription: "Цей модуль входить до затвердженої послідовності та стане доступним після завершення моделі даних, правил, інтерфейсу й перевірки всіма 28 мовами.", homepage: "Переглянути головну сторінку", mockup: "Переглянути макет" },
  ro: { overview: "Prezentare generală", settings: "Setări", currentOrganization: "Organizația curentă", navigation: "Navigarea în aplicație", openNavigation: "Deschide navigarea", closeNavigation: "Închide navigarea", search: "Caută", notifications: "Alerte", registerOperation: "Înregistrează lucrarea", language: "Limbă", signOut: "Deconectare", accountRole: "Cont Gero", workspace: "Spațiu de lucru", greeting: "Bună, {name}.", ready: "Organizația {organization} este selectată și pregătită pentru lucru.", account: "Cont", organization: "Organizație", access: "Acces", authenticated: "Autentificat", selected: "Selectată", authorized: "Autorizat", implementation: "Implementare pe module", pending: "Modul în pregătire", pendingDescription: "Acest modul face parte din ordinea aprobată și va fi disponibil după finalizarea modelului de date, a regulilor, a interfeței și a verificării în toate cele 28 de limbi.", homepage: "Vezi pagina principală", mockup: "Vezi macheta" },
  fi: { overview: "Yleiskatsaus", settings: "Asetukset", currentOrganization: "Nykyinen organisaatio", navigation: "Sovelluksen navigointi", openNavigation: "Avaa navigointi", closeNavigation: "Sulje navigointi", search: "Hae", notifications: "Ilmoitukset", registerOperation: "Kirjaa toimenpide", language: "Kieli", signOut: "Kirjaudu ulos", accountRole: "Gero-tili", workspace: "Työtila", greeting: "Hei, {name}.", ready: "Organisaatio {organization} on valittu ja valmis työskentelyyn.", account: "Tili", organization: "Organisaatio", access: "Käyttöoikeus", authenticated: "Tunnistettu", selected: "Valittu", authorized: "Valtuutettu", implementation: "Moduulikohtainen toteutus", pending: "Moduulia valmistellaan", pendingDescription: "Tämä moduuli kuuluu hyväksyttyyn järjestykseen ja tulee käyttöön, kun sen tietomalli, säännöt, käyttöliittymä ja tarkistus kaikilla 28 kielellä ovat valmiit.", homepage: "Näytä etusivu", mockup: "Näytä mallikuva" },
  bg: { overview: "Общ преглед", settings: "Настройки", currentOrganization: "Текуща организация", navigation: "Навигация в приложението", openNavigation: "Отваряне на навигацията", closeNavigation: "Затваряне на навигацията", search: "Търсене", notifications: "Известия", registerOperation: "Регистриране на операция", language: "Език", signOut: "Изход", accountRole: "Акаунт в Gero", workspace: "Работно пространство", greeting: "Здравейте, {name}.", ready: "Организацията {organization} е избрана и готова за работа.", account: "Акаунт", organization: "Организация", access: "Достъп", authenticated: "Удостоверен", selected: "Избрана", authorized: "Упълномощен", implementation: "Изпълнение по модули", pending: "Модулът се подготвя", pendingDescription: "Този модул е част от одобрената последователност и ще бъде достъпен след завършване на модела на данните, правилата, интерфейса и прегледа на всички 28 езика.", homepage: "Преглед на началната страница", mockup: "Преглед на макета" },
  hu: { overview: "Áttekintés", settings: "Beállítások", currentOrganization: "Jelenlegi szervezet", navigation: "Alkalmazásnavigáció", openNavigation: "Navigáció megnyitása", closeNavigation: "Navigáció bezárása", search: "Keresés", notifications: "Értesítések", registerOperation: "Művelet rögzítése", language: "Nyelv", signOut: "Kijelentkezés", accountRole: "Gero-fiók", workspace: "Munkaterület", greeting: "Üdvözöljük, {name}.", ready: "A(z) {organization} szervezet ki van választva, és készen áll a munkára.", account: "Fiók", organization: "Szervezet", access: "Hozzáférés", authenticated: "Hitelesítve", selected: "Kiválasztva", authorized: "Engedélyezve", implementation: "Modulonkénti megvalósítás", pending: "A modul előkészítés alatt áll", pendingDescription: "Ez a modul szerepel a jóváhagyott sorrendben, és az adatmodell, a szabályok, a felület és a mind a 28 nyelvre kiterjedő ellenőrzés befejezése után válik elérhetővé.", homepage: "Kezdőlap megtekintése", mockup: "Makett megtekintése" },
  is: { overview: "Yfirlit", settings: "Stillingar", currentOrganization: "Núverandi stofnun", navigation: "Leiðsögn forrits", openNavigation: "Opna leiðsögn", closeNavigation: "Loka leiðsögn", search: "Leita", notifications: "Tilkynningar", registerOperation: "Skrá aðgerð", language: "Tungumál", signOut: "Skrá út", accountRole: "Gero-reikningur", workspace: "Vinnusvæði", greeting: "Halló, {name}.", ready: "Stofnunin {organization} er valin og tilbúin til vinnu.", account: "Reikningur", organization: "Stofnun", access: "Aðgangur", authenticated: "Auðkenndur", selected: "Valin", authorized: "Heimilaður", implementation: "Innleiðing eftir einingum", pending: "Eining í undirbúningi", pendingDescription: "Þessi eining er í samþykktri röð og verður tiltæk þegar gagnalíkan, reglur, viðmót og yfirferð á öllum 28 tungumálum eru fullgerð.", homepage: "Skoða heimasíðu", mockup: "Skoða frumgerð" },
  sk: { overview: "Prehľad", settings: "Nastavenia", currentOrganization: "Aktuálna organizácia", navigation: "Navigácia aplikácie", openNavigation: "Otvoriť navigáciu", closeNavigation: "Zavrieť navigáciu", search: "Hľadať", notifications: "Upozornenia", registerOperation: "Zaznamenať úkon", language: "Jazyk", signOut: "Odhlásiť sa", accountRole: "Účet Gero", workspace: "Pracovný priestor", greeting: "Dobrý deň, {name}.", ready: "Organizácia {organization} je vybraná a pripravená na prácu.", account: "Účet", organization: "Organizácia", access: "Prístup", authenticated: "Overené", selected: "Vybraná", authorized: "Oprávnený", implementation: "Implementácia po moduloch", pending: "Modul sa pripravuje", pendingDescription: "Tento modul je súčasťou schváleného poradia a bude dostupný po dokončení dátového modelu, pravidiel, rozhrania a kontroly vo všetkých 28 jazykoch.", homepage: "Zobraziť domovskú stránku", mockup: "Zobraziť maketu" },
  lt: { overview: "Apžvalga", settings: "Nustatymai", currentOrganization: "Dabartinė organizacija", navigation: "Programos naršymas", openNavigation: "Atverti naršymą", closeNavigation: "Užverti naršymą", search: "Ieškoti", notifications: "Įspėjimai", registerOperation: "Registruoti darbą", language: "Kalba", signOut: "Atsijungti", accountRole: "Gero paskyra", workspace: "Darbo sritis", greeting: "Sveiki, {name}.", ready: "Organizacija {organization} pasirinkta ir parengta darbui.", account: "Paskyra", organization: "Organizacija", access: "Prieiga", authenticated: "Tapatybė patvirtinta", selected: "Pasirinkta", authorized: "Įgaliotas", implementation: "Diegimas moduliais", pending: "Modulis ruošiamas", pendingDescription: "Šis modulis įtrauktas į patvirtintą seką ir bus pasiekiamas užbaigus jo duomenų modelį, taisykles, sąsają ir patikrą visomis 28 kalbomis.", homepage: "Rodyti pradžios puslapį", mockup: "Rodyti maketą" },
  sl: { overview: "Pregled", settings: "Nastavitve", currentOrganization: "Trenutna organizacija", navigation: "Krmarjenje po aplikaciji", openNavigation: "Odpri krmarjenje", closeNavigation: "Zapri krmarjenje", search: "Išči", notifications: "Opozorila", registerOperation: "Zabeleži opravilo", language: "Jezik", signOut: "Odjava", accountRole: "Račun Gero", workspace: "Delovni prostor", greeting: "Pozdravljeni, {name}.", ready: "Organizacija {organization} je izbrana in pripravljena za delo.", account: "Račun", organization: "Organizacija", access: "Dostop", authenticated: "Overjeno", selected: "Izbrana", authorized: "Pooblaščen", implementation: "Izvedba po modulih", pending: "Modul je v pripravi", pendingDescription: "Ta modul je v odobrenem zaporedju in bo na voljo, ko bodo dokončani podatkovni model, pravila, vmesnik ter pregled v vseh 28 jezikih.", homepage: "Prikaži domačo stran", mockup: "Prikaži maketo" },
  lv: { overview: "Pārskats", settings: "Iestatījumi", currentOrganization: "Pašreizējā organizācija", navigation: "Lietotnes navigācija", openNavigation: "Atvērt navigāciju", closeNavigation: "Aizvērt navigāciju", search: "Meklēt", notifications: "Brīdinājumi", registerOperation: "Reģistrēt darbu", language: "Valoda", signOut: "Izrakstīties", accountRole: "Gero konts", workspace: "Darbvieta", greeting: "Sveiki, {name}.", ready: "Organizācija {organization} ir atlasīta un gatava darbam.", account: "Konts", organization: "Organizācija", access: "Piekļuve", authenticated: "Autentificēts", selected: "Atlasīta", authorized: "Pilnvarots", implementation: "Ieviešana pa moduļiem", pending: "Modulis tiek sagatavots", pendingDescription: "Šis modulis ir iekļauts apstiprinātajā secībā un būs pieejams pēc datu modeļa, noteikumu, saskarnes un pārbaudes visās 28 valodās pabeigšanas.", homepage: "Skatīt sākumlapu", mockup: "Skatīt maketu" },
};

export const workspaceStateCopies: Record<SupportedLocale, { loading: string; unavailable: string; retry: string; denied: string }> = {
  "pt-PT": { loading: "A carregar", unavailable: "Não foi possível abrir o GeroFarm.", retry: "Tente novamente dentro de instantes.", denied: "Esta organização ainda não tem acesso ao GeroFarm." },
  "pt-BR": { loading: "Carregando", unavailable: "Não foi possível abrir o GeroFarm.", retry: "Tente novamente em instantes.", denied: "Esta organização ainda não tem acesso ao GeroFarm." },
  en: { loading: "Loading", unavailable: "GeroFarm could not be opened.", retry: "Please try again in a moment.", denied: "This organisation does not yet have access to GeroFarm." },
  fr: { loading: "Chargement", unavailable: "Impossible d’ouvrir GeroFarm.", retry: "Veuillez réessayer dans quelques instants.", denied: "Cette organisation n’a pas encore accès à GeroFarm." },
  es: { loading: "Cargando", unavailable: "No se pudo abrir GeroFarm.", retry: "Vuelva a intentarlo en unos instantes.", denied: "Esta organización aún no tiene acceso a GeroFarm." },
  nl: { loading: "Laden", unavailable: "GeroFarm kon niet worden geopend.", retry: "Probeer het zo opnieuw.", denied: "Deze organisatie heeft nog geen toegang tot GeroFarm." },
  de: { loading: "Wird geladen", unavailable: "GeroFarm konnte nicht geöffnet werden.", retry: "Versuchen Sie es in Kürze erneut.", denied: "Diese Organisation hat noch keinen Zugriff auf GeroFarm." },
  ja: { loading: "読み込み中", unavailable: "GeroFarmを開けませんでした。", retry: "しばらくしてからもう一度お試しください。", denied: "この組織はまだGeroFarmを利用できません。" },
  he: { loading: "בטעינה", unavailable: "לא ניתן לפתוח את GeroFarm.", retry: "נסו שוב בעוד מספר רגעים.", denied: "לארגון זה עדיין אין גישה ל-GeroFarm." },
  tr: { loading: "Yükleniyor", unavailable: "GeroFarm açılamadı.", retry: "Lütfen birazdan tekrar deneyin.", denied: "Bu kuruluşun henüz GeroFarm erişimi yok." },
  ar: { loading: "جارٍ التحميل", unavailable: "تعذر فتح GeroFarm.", retry: "يرجى المحاولة مرة أخرى بعد لحظات.", denied: "لا تملك هذه المنظمة صلاحية الوصول إلى GeroFarm بعد." },
  pl: { loading: "Ładowanie", unavailable: "Nie udało się otworzyć GeroFarm.", retry: "Spróbuj ponownie za chwilę.", denied: "Ta organizacja nie ma jeszcze dostępu do GeroFarm." },
  hr: { loading: "Učitavanje", unavailable: "GeroFarm nije moguće otvoriti.", retry: "Pokušajte ponovno za nekoliko trenutaka.", denied: "Ova organizacija još nema pristup GeroFarmu." },
  el: { loading: "Φόρτωση", unavailable: "Δεν ήταν δυνατό το άνοιγμα του GeroFarm.", retry: "Δοκιμάστε ξανά σε λίγο.", denied: "Αυτός ο οργανισμός δεν έχει ακόμη πρόσβαση στο GeroFarm." },
  sv: { loading: "Läser in", unavailable: "GeroFarm kunde inte öppnas.", retry: "Försök igen om en liten stund.", denied: "Den här organisationen har ännu inte åtkomst till GeroFarm." },
  no: { loading: "Laster", unavailable: "GeroFarm kunne ikke åpnes.", retry: "Prøv igjen om litt.", denied: "Denne organisasjonen har ennå ikke tilgang til GeroFarm." },
  da: { loading: "Indlæser", unavailable: "GeroFarm kunne ikke åbnes.", retry: "Prøv igen om et øjeblik.", denied: "Denne organisation har endnu ikke adgang til GeroFarm." },
  it: { loading: "Caricamento", unavailable: "Non è stato possibile aprire GeroFarm.", retry: "Riprova tra qualche istante.", denied: "Questa organizzazione non ha ancora accesso a GeroFarm." },
  uk: { loading: "Завантаження", unavailable: "Не вдалося відкрити GeroFarm.", retry: "Спробуйте ще раз за кілька секунд.", denied: "Ця організація ще не має доступу до GeroFarm." },
  ro: { loading: "Se încarcă", unavailable: "GeroFarm nu a putut fi deschis.", retry: "Încercați din nou peste câteva momente.", denied: "Această organizație nu are încă acces la GeroFarm." },
  fi: { loading: "Ladataan", unavailable: "GeroFarmia ei voitu avata.", retry: "Yritä hetken kuluttua uudelleen.", denied: "Tällä organisaatiolla ei vielä ole GeroFarmin käyttöoikeutta." },
  bg: { loading: "Зареждане", unavailable: "GeroFarm не можа да бъде отворен.", retry: "Опитайте отново след малко.", denied: "Тази организация все още няма достъп до GeroFarm." },
  hu: { loading: "Betöltés", unavailable: "A GeroFarm nem nyitható meg.", retry: "Próbálja újra néhány pillanat múlva.", denied: "Ez a szervezet még nem fér hozzá a GeroFarmhoz." },
  is: { loading: "Hleður", unavailable: "Ekki tókst að opna GeroFarm.", retry: "Reyndu aftur eftir augnablik.", denied: "Þessi stofnun hefur ekki enn aðgang að GeroFarm." },
  sk: { loading: "Načítava sa", unavailable: "GeroFarm sa nepodarilo otvoriť.", retry: "Skúste to znova o chvíľu.", denied: "Táto organizácia zatiaľ nemá prístup ku GeroFarmu." },
  lt: { loading: "Įkeliama", unavailable: "Nepavyko atverti GeroFarm.", retry: "Po kelių akimirkų bandykite dar kartą.", denied: "Ši organizacija dar neturi prieigos prie GeroFarm." },
  sl: { loading: "Nalaganje", unavailable: "Aplikacije GeroFarm ni bilo mogoče odpreti.", retry: "Poskusite znova čez nekaj trenutkov.", denied: "Ta organizacija še nima dostopa do aplikacije GeroFarm." },
  lv: { loading: "Notiek ielāde", unavailable: "Neizdevās atvērt GeroFarm.", retry: "Pēc brīža mēģiniet vēlreiz.", denied: "Šai organizācijai vēl nav piekļuves GeroFarm." },
};

export function formatWorkspaceMessage(message: string, values: Record<string, string>) {
  return message.replace(/\{(\w+)\}/g, (_match, key: string) => values[key] ?? `{${key}}`);
}

export type PluralForms = { other: string } & Partial<Record<Intl.LDMLPluralRule, string>>;

export function pluralWorkspaceMessage(locale: SupportedLocale, count: number, forms: PluralForms) {
  const category = new Intl.PluralRules(locale).select(count);
  return formatWorkspaceMessage(forms[category] || forms.other, { count: new Intl.NumberFormat(locale).format(count) });
}
