import { createHash, randomUUID } from "node:crypto";
import { and, asc, eq, gte, inArray, lte, sql } from "drizzle-orm";
import { allocateHarvest, canonicalJson, harvestLotSegments, type AutomaticMonitoringWeather, type CreateHarvestInput, type CreateLaboratoryResultInput, type CreateLaboratorySampleInput, type CreateMonitoringInput, type MonitoringWeatherSubject, type NotebookScope } from "@shared/agronomy";
import { agronomicMonitorings, cropPeriods, farmAuditEvents, farmFields, farmHoldings, farmOperations, fieldNotebooks, harvestSequences, harvests, laboratoryResults, laboratorySamples, notebookSequences, operationDestinations, plantations } from "@shared/schema";
import type { FarmRequestContext } from "./farm-context";
import type { FarmDatabase } from "./database";
import { withOrganizationTransaction } from "./database";
import type { OperationRepository } from "./operations";
import { strToU8, zipSync } from "fflate";

export type AgronomyOverview={monitorings:unknown[];samples:unknown[];laboratoryResults:unknown[];harvests:unknown[];notebooks:unknown[]};
export type MonitoringWeatherCapture=(subject:MonitoringWeatherSubject|null,requestedAt:string)=>Promise<AutomaticMonitoringWeather>;
export interface AgronomyRepository{overview(context:FarmRequestContext):Promise<AgronomyOverview>;createMonitoring(context:FarmRequestContext,input:CreateMonitoringInput,captureWeather:MonitoringWeatherCapture):Promise<unknown>;createSample(context:FarmRequestContext,input:CreateLaboratorySampleInput):Promise<unknown>;createResult(context:FarmRequestContext,input:CreateLaboratoryResultInput):Promise<unknown>;createHarvest(context:FarmRequestContext,input:CreateHarvestInput):Promise<unknown>;currentNotebook(context:FarmRequestContext,scope:NotebookScope):Promise<Record<string,unknown>>;xlsx(context:FarmRequestContext,scope:NotebookScope):Promise<{filename:string;data:Buffer}>;issueNotebook(context:FarmRequestContext,scope:NotebookScope):Promise<unknown>;deleteNotebook(context:FarmRequestContext,id:string):Promise<boolean>;pdf(context:FarmRequestContext,id:string):Promise<{filename:string;data:Buffer}|null>}
const audit=(tx:Parameters<Parameters<FarmDatabase["transaction"]>[0]>[0],context:FarmRequestContext,action:string,entityType:string,entityId:string,metadata:Record<string,string|number|boolean|null>={})=>tx.insert(farmAuditEvents).values({id:randomUUID(),organizationId:context.organization.id,actorUserId:context.user.id,action,entityType,entityId,metadata});
const dateOnly=(value:Date|string)=>typeof value==="string"?value.slice(0,10):value.toISOString().slice(0,10);
function pdfEscape(value:string){return value.replace(/[^\x20-\x7e]/g,"?").replace(/[\\()]/g,"\\$&")}
export function createNotebookPdf(lines:string[]):Buffer{const content=["BT","/F1 11 Tf","48 790 Td",...lines.slice(0,45).flatMap((line,index)=>index?["0 -16 Td",`(${pdfEscape(line)}) Tj`]:[`(${pdfEscape(line)}) Tj`]),"ET"].join("\n");const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];let pdf="%PDF-1.4\n",offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>String(offset).padStart(10,"0")+" 00000 n \n").join("")}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf)}
export function notebookProjection(snapshot:Record<string,unknown>):Record<string,unknown>{const clone=structuredClone(snapshot) as Record<string,unknown>,sections=clone.sections as {operations?:Array<Record<string,unknown>>;harvests?:Array<Record<string,unknown>>}|undefined;if(sections?.operations)sections.operations=sections.operations.filter(operation=>operation.type!=="harvest");if(sections?.harvests)sections.harvests=sections.harvests.map(({commercialSnapshot:_commercialSnapshot,revenue:_revenue,price:_price,cost:_cost,margin:_margin,...agronomic})=>agronomic);return clone;}
const xml=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function cell(value:unknown){const text=typeof value==="object"&&value!==null?JSON.stringify(value):String(value??"");return `<c t="inlineStr"><is><t xml:space="preserve">${xml(text)}</t></is></c>`}
export function createNotebookXlsx(snapshot:Record<string,unknown>):Buffer{const safe=notebookProjection(snapshot),sections=(safe.sections||{})as Record<string,unknown>,names=["operations","monitorings","laboratorySamples","harvests"],worksheets:Record<string,Uint8Array>={};for(const[name,index]of names.map((name,index)=>[name,index]as const)){const rows=Array.isArray(sections[name])?sections[name]as Array<Record<string,unknown>>:[],keys=[...new Set(rows.flatMap(row=>Object.keys(row)))];const body=[keys,...rows.map(row=>keys.map(key=>row[key]))].map((row,rowIndex)=>`<row r="${rowIndex+1}">${row.map(cell).join("")}</row>`).join("");worksheets[`xl/worksheets/sheet${index+1}.xml`]=strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${body}</sheetData></worksheet>`)}const workbookSheets=names.map((name,index)=>`<sheet name="${name}" sheetId="${index+1}" r:id="rId${index+1}"/>`).join(""),relationships=names.map((_name,index)=>`<Relationship Id="rId${index+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${index+1}.xml"/>`).join(""),overrides=names.map((_name,index)=>`<Override PartName="/xl/worksheets/sheet${index+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("");return Buffer.from(zipSync({"[Content_Types].xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${overrides}</Types>`),"_rels/.rels":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),"xl/workbook.xml":strToU8(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${workbookSheets}</sheets></workbook>`),"xl/_rels/workbook.xml.rels":strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${relationships}</Relationships>`),...worksheets}))}

export function createPostgresAgronomyRepository(db:FarmDatabase,operations:OperationRepository):AgronomyRepository{
  async function current(context:FarmRequestContext,scope:NotebookScope){const operationProjections=await operations.list(context);return withOrganizationTransaction(db,context.organization.id,async tx=>{const from=new Date(`${scope.from}T00:00:00.000Z`),to=new Date(`${scope.to}T23:59:59.999Z`);const [holding,monitoring,samples,results,harvestRows]=await Promise.all([tx.select().from(farmHoldings).where(eq(farmHoldings.id,scope.holdingId)),tx.select().from(agronomicMonitorings).where(and(gte(agronomicMonitorings.observedAt,from),lte(agronomicMonitorings.observedAt,to))).orderBy(asc(agronomicMonitorings.observedAt)),tx.select().from(laboratorySamples).where(and(gte(laboratorySamples.sampledOn,scope.from),lte(laboratorySamples.sampledOn,scope.to))).orderBy(asc(laboratorySamples.sampledOn)),tx.select().from(laboratoryResults),tx.select().from(harvests).where(and(gte(harvests.startedAt,from),lte(harvests.startedAt,to))).orderBy(asc(harvests.startedAt))]);if(!holding[0])throw Object.assign(new Error("Holding not found"),{status:404,code:"HOLDING_NOT_FOUND"});const selected=(fieldId:string,plantationId?:string|null)=>scope.wholeHolding||scope.fieldIds.includes(fieldId)||!!plantationId&&scope.plantationIds.includes(plantationId);const physicalOperations=operationProjections.flatMap(operation=>{if(dateOnly(operation.performedAt)<scope.from||dateOnly(operation.performedAt)>scope.to)return[];if(operation.status==="voided"&&!scope.includeVoidedAudit)return[];const allocations=operation.destinations.filter(d=>selected(d.fieldId,d.plantationId));if(!allocations.length)return[];return[{...operation,destinations:allocations}];});const selectedMonitoring=monitoring.filter(row=>scope.wholeHolding||row.fieldIds.some(id=>scope.fieldIds.includes(id))||row.plantationIds.some(id=>scope.plantationIds.includes(id)));const selectedSamples=samples.filter(row=>scope.wholeHolding||row.fieldIds.some(id=>scope.fieldIds.includes(id))||row.plantationIds.some(id=>scope.plantationIds.includes(id))||row.cropPeriodIds.some(id=>scope.cropPeriodIds.includes(id)));return{generatedAt:new Date().toISOString(),organization:{id:context.organization.id,name:context.organization.name},holding:holding[0],scope,sections:{operations:physicalOperations,monitorings:selectedMonitoring,laboratorySamples:selectedSamples.map(sample=>({...sample,result:results.find(result=>result.sampleId===sample.id)})),harvests:harvestRows.filter(row=>{const origins=row.origins as Array<{fieldId:string;plantationId:string}>;return scope.wholeHolding||origins.some(x=>selected(x.fieldId,x.plantationId))})},warnings:scope.acceptedWarnings};});}
  return{
    async overview(context){return withOrganizationTransaction(db,context.organization.id,async tx=>{const [monitorings,samples,results,harvestRows,notebooks]=await Promise.all([tx.select().from(agronomicMonitorings).orderBy(asc(agronomicMonitorings.observedAt)),tx.select().from(laboratorySamples).orderBy(asc(laboratorySamples.sampledOn)),tx.select().from(laboratoryResults),tx.select().from(harvests).orderBy(asc(harvests.startedAt)),tx.select({id:fieldNotebooks.id,number:fieldNotebooks.number,version:fieldNotebooks.version,language:fieldNotebooks.language,integrityId:fieldNotebooks.integrityId,issuedAt:fieldNotebooks.issuedAt,deletedAt:fieldNotebooks.deletedAt}).from(fieldNotebooks).orderBy(asc(fieldNotebooks.issuedAt))]);return{monitorings,samples,laboratoryResults:results,harvests:harvestRows,notebooks}});},
    async createMonitoring(context,input,captureWeather){
      const resolveSubject=async(tx:Parameters<Parameters<FarmDatabase["transaction"]>[0]>[0])=>{const {weatherSubject,observedAt}=input;if(!weatherSubject)return{subject:null as MonitoringWeatherSubject|null,plantationIds:[] as string[],cropPeriodIds:[] as string[]};const [plantation]=await tx.select({id:plantations.id,fieldId:plantations.fieldId}).from(plantations).where(eq(plantations.id,weatherSubject.plantationId));if(!plantation||!input.fieldIds.includes(plantation.fieldId))throw Object.assign(new Error("Monitoring weather subject is not compatible with the selected fields"),{status:400,code:"MONITORING_WEATHER_SUBJECT_INVALID"});if(!weatherSubject.cropPeriodId)return{subject:{subjectType:"plantation",subjectId:plantation.id,plantationId:plantation.id,cropPeriodId:null}as MonitoringWeatherSubject,plantationIds:[plantation.id],cropPeriodIds:[]};const [period]=await tx.select({id:cropPeriods.id,plantationId:cropPeriods.plantationId,startedOn:cropPeriods.startedOn,endedOn:cropPeriods.endedOn}).from(cropPeriods).where(eq(cropPeriods.id,weatherSubject.cropPeriodId)),day=observedAt.slice(0,10);if(!period||period.plantationId!==plantation.id||day<period.startedOn||!!period.endedOn&&day>period.endedOn)throw Object.assign(new Error("Monitoring weather period is not compatible with the selected plantation and instant"),{status:400,code:"MONITORING_WEATHER_SUBJECT_INVALID"});return{subject:{subjectType:"plantation",subjectId:plantation.id,plantationId:plantation.id,cropPeriodId:period.id}as MonitoringWeatherSubject,plantationIds:[plantation.id],cropPeriodIds:[period.id]};};
      const canonical=await withOrganizationTransaction(db,context.organization.id,resolveSubject),automaticWeather=await captureWeather(canonical.subject,input.observedAt);
      return withOrganizationTransaction(db,context.organization.id,async tx=>{const revalidated=await resolveSubject(tx);if(canonical.subject?.subjectId!==revalidated.subject?.subjectId)throw Object.assign(new Error("Monitoring weather subject changed before persistence"),{status:409,code:"MONITORING_WEATHER_SUBJECT_CHANGED"});const {observedAt,weatherSubject:_weatherSubject,...details}=input,id=randomUUID(),[row]=await tx.insert(agronomicMonitorings).values({id,organizationId:context.organization.id,observedAt:new Date(observedAt),...details,plantationIds:revalidated.plantationIds,cropPeriodIds:revalidated.cropPeriodIds,automaticWeather}).returning();await audit(tx,context,"monitoring.created","monitoring",id,{findingCount:input.findings.length,weatherCorrected:!!input.correctedWeather,automaticWeatherAvailable:automaticWeather.status==="available"});return row;});
    },
    async createSample(context,input){return withOrganizationTransaction(db,context.organization.id,async tx=>{const id=randomUUID(),[row]=await tx.insert(laboratorySamples).values({id,organizationId:context.organization.id,...input}).returning();await audit(tx,context,"laboratory_sample.created","laboratory_sample",id,{type:input.type});return row;});},
    async createResult(context,input){return withOrganizationTransaction(db,context.organization.id,async tx=>{const [sample]=await tx.select({id:laboratorySamples.id}).from(laboratorySamples).where(eq(laboratorySamples.id,input.sampleId));if(!sample)throw Object.assign(new Error("Sample not found"),{status:404,code:"SAMPLE_NOT_FOUND"});const id=randomUUID(),[row]=await tx.insert(laboratoryResults).values({id,organizationId:context.organization.id,...input}).returning();await audit(tx,context,"laboratory_result.created","laboratory_result",id,{parameterCount:input.results.length});return row;});},
    async createHarvest(context,input){const allocations=allocateHarvest(input),area=allocations.reduce((sum,x)=>sum+x.areaHa,0);const operation=await operations.create(context,{type:"harvest",performedAt:input.startedAt,notes:input.notes,destinations:allocations.map(x=>({fieldId:x.fieldId,plantationId:x.plantationId,areaHa:x.areaHa,percentage:x.areaHa/area*100})),workerIds:input.workerIds,equipmentIds:input.equipmentIds,contractorIds:input.contractorIds});return withOrganizationTransaction(db,context.organization.id,async tx=>{const year=new Date(input.startedAt).getUTCFullYear(),seq=await tx.execute(sql`insert into ${harvestSequences} (organization_id,year,next_value) values (${context.organization.id},${year},2) on conflict (organization_id,year) do update set next_value=${harvestSequences.nextValue}+1 returning next_value-1 as value`),value=Number((seq.rows[0] as {value:string}).value),segments=harvestLotSegments(input),date=input.startedAt.slice(2,10).replaceAll("-",""),culture=input.cultureId.replace(/[^A-Za-z]/g,"").slice(0,2).toUpperCase().padEnd(2,"X"),lotCode=`${culture}${segments.variety}${segments.field}${date}${String(value).padStart(3,"0")}`;const lots=[{code:lotCode,category:"main",quantityKg:input.categories.filter(x=>!x.separateLot).reduce((s,x)=>s+x.quantityKg,0)},...input.categories.filter(x=>x.separateLot).map((x,index)=>({code:`${lotCode}-${index+2}`,category:x.name,quantityKg:x.quantityKg}))];const id=randomUUID(),[row]=await tx.insert(harvests).values({id,organizationId:context.organization.id,operationId:operation.id,lotCode,cultureId:input.cultureId,startedAt:new Date(input.startedAt),endedAt:input.endedAt?new Date(input.endedAt):null,totalNetKg:String(input.totalNetKg),origins:allocations,categories:input.categories,lots,destinations:input.destinations,quality:input.quality,commercialSnapshot:input.revenue,lossReason:input.lossReason,safetyWarnings:input.safetyWarnings,notes:input.notes}).returning();await audit(tx,context,"harvest.created","harvest",id,{lotCode,operationId:operation.id,totalNetKg:input.totalNetKg,originCount:allocations.length});return row;});},
    async currentNotebook(context,scope){return notebookProjection(await current(context,scope));},
    async xlsx(context,scope){const snapshot=await current(context,scope);return{filename:`gerofarm-${scope.from}-${scope.to}.xlsx`,data:createNotebookXlsx(snapshot)};},
    async issueNotebook(context,scope){const snapshot=await current(context,scope);return withOrganizationTransaction(db,context.organization.id,async tx=>{let number:string,version=1;if(scope.previousNotebookId){const [previous]=await tx.select().from(fieldNotebooks).where(eq(fieldNotebooks.id,scope.previousNotebookId));if(!previous)throw Object.assign(new Error("Notebook not found"),{status:404,code:"NOTEBOOK_NOT_FOUND"});number=previous.number;version=Number(previous.version)+1;}else{const year=Number(scope.to.slice(0,4)),[holding]=await tx.select({code:farmHoldings.code}).from(farmHoldings).where(eq(farmHoldings.id,scope.holdingId));if(!holding)throw Object.assign(new Error("Holding not found"),{status:404,code:"HOLDING_NOT_FOUND"});const seq=await tx.execute(sql`insert into ${notebookSequences} (organization_id,holding_id,year,next_value) values (${context.organization.id},${scope.holdingId},${year},2) on conflict (holding_id,year) do update set next_value=${notebookSequences.nextValue}+1 returning next_value-1 as value`);number=`${holding.code}-${year}-${String(Number((seq.rows[0]as{value:string}).value)).padStart(4,"0")}`;}const integrityId=createHash("sha256").update(canonicalJson({number,version,snapshot})).digest("hex"),pdf=createNotebookPdf(["GeroFarm",`${number}-V${version}`,`Language: ${scope.language}`,`Timezone: ${context.organization.timezone||"Europe/Lisbon"}`,`Integrity: ${integrityId}`]);const id=randomUUID(),[row]=await tx.insert(fieldNotebooks).values({id,organizationId:context.organization.id,holdingId:scope.holdingId,number,version:String(version),scope,snapshot,language:scope.language,timezone:context.organization.timezone||"Europe/Lisbon",issuerUserId:context.user.id,integrityId,pdfBase64:pdf.toString("base64")}).returning();await audit(tx,context,"field_notebook.issued","field_notebook",id,{number,version,integrityId});return{...row,pdfBase64:undefined};});},
    async deleteNotebook(context,id){return withOrganizationTransaction(db,context.organization.id,async tx=>{const [row]=await tx.update(fieldNotebooks).set({deletedAt:new Date(),deletedBy:context.user.id,pdfBase64:null}).where(and(eq(fieldNotebooks.id,id),sql`${fieldNotebooks.deletedAt} is null`)).returning({id:fieldNotebooks.id,number:fieldNotebooks.number,version:fieldNotebooks.version});if(!row)return false;await audit(tx,context,"field_notebook.deleted","field_notebook",id,{number:row.number,version:Number(row.version)});return true;});},
    async pdf(context,id){return withOrganizationTransaction(db,context.organization.id,async tx=>{const [row]=await tx.select({number:fieldNotebooks.number,version:fieldNotebooks.version,pdfBase64:fieldNotebooks.pdfBase64,deletedAt:fieldNotebooks.deletedAt}).from(fieldNotebooks).where(eq(fieldNotebooks.id,id));if(!row||row.deletedAt||!row.pdfBase64)return null;return{filename:`${row.number}-V${row.version}.pdf`,data:Buffer.from(row.pdfBase64,"base64")};});}
  };
}
