import { randomUUID } from "node:crypto";
import { and, asc, eq } from "drizzle-orm";
import { cropPeriods, cropVarieties, farmAuditEvents, farmFields, fieldFallows, plantations, plantationUprootings, type CropPeriod, type FieldFallow, type Plantation } from "@shared/schema";
import { OccupancyError, type CreateCropPeriodInput, type CreateFallowInput, type CreatePlantationInput, type CropPeriodDto, type FallowDto, type PlantationDto, type RotationEntry } from "@shared/crop-lifecycle";
import type { FarmDatabase, FarmTransaction } from "./database";
import { withOrganizationTransaction } from "./database";
import type { FarmRequestContext } from "./farm-context";
import { assertPlantationCapacity } from "./entitlements";

export interface CropLifecycleRepository { list(context: FarmRequestContext): Promise<{ plantations: PlantationDto[]; periods: CropPeriodDto[]; fallows: FallowDto[]; rotation: RotationEntry[] }>; createPlantation(context: FarmRequestContext, input: CreatePlantationInput): Promise<PlantationDto>; createPeriod(context: FarmRequestContext, input: CreateCropPeriodInput): Promise<CropPeriodDto>; closePeriod(context: FarmRequestContext, id: string, endedOn: string): Promise<CropPeriodDto | null>; uproot(context: FarmRequestContext, id: string, input: { uprootedOn: string; reason: string }): Promise<PlantationDto | null>; createFallow(context: FarmRequestContext, input: CreateFallowInput): Promise<FallowDto>; closeFallow(context: FarmRequestContext, id: string, endedOn: string): Promise<FallowDto | null>; }
const plantationDto = (row: Plantation): PlantationDto => ({ ...row, varietyId: row.varietyId || undefined, areaHa: Number(row.areaHa), kind: row.kind as PlantationDto["kind"], status: row.status as PlantationDto["status"], createdAt: row.createdAt.toISOString() });
const periodDto = (row: CropPeriod): CropPeriodDto => ({ ...row, kind: row.kind as CropPeriodDto["kind"], status: row.status as CropPeriodDto["status"] });
const fallowDto = (row: FieldFallow): FallowDto => ({ ...row, areaHa: Number(row.areaHa), status: row.status as FallowDto["status"] });
async function assertCapacity(tx: FarmTransaction, fieldId: string, requestedAreaHa: number, requestedKind?: "permanent" | "temporary") { const [field] = await tx.select({ usableAreaHa: farmFields.usableAreaHa }).from(farmFields).where(and(eq(farmFields.id, fieldId),eq(farmFields.status,"active"))).for("update"); if (!field) throw Object.assign(new Error("Field not found"), { code: "FIELD_NOT_FOUND", status: 404 }); const [activePlantations, activeFallows] = await Promise.all([tx.select({ areaHa: plantations.areaHa, kind: plantations.kind }).from(plantations).where(and(eq(plantations.fieldId, fieldId), eq(plantations.status, "active"))), tx.select({ areaHa: fieldFallows.areaHa }).from(fieldFallows).where(and(eq(fieldFallows.fieldId, fieldId), eq(fieldFallows.status, "active")))]); if (requestedKind && activePlantations.some((row) => row.kind !== requestedKind)) throw Object.assign(new Error("Permanent and temporary main plantations cannot coexist in one field"), { code: "INCOMPATIBLE_FIELD_PLANTATION_KIND", status: 409 }); const occupied = [...activePlantations, ...activeFallows].reduce((sum, row) => sum + Number(row.areaHa), 0); const available = Math.max(0, Number(field.usableAreaHa) - occupied); if (requestedAreaHa > available + 0.00005) throw new OccupancyError(available); }
async function audit(tx: FarmTransaction, context: FarmRequestContext, action: string, entityType: string, entityId: string, metadata: Record<string, string | number | boolean | null> = {}) { await tx.insert(farmAuditEvents).values({ id: randomUUID(), organizationId: context.organization.id, actorUserId: context.user.id, action, entityType, entityId, metadata }); }

export function createPostgresCropLifecycleRepository(db: FarmDatabase): CropLifecycleRepository { return {
  async list(context) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [p, periods, fallows] = await Promise.all([tx.select().from(plantations).orderBy(asc(plantations.startedOn)), tx.select().from(cropPeriods).orderBy(asc(cropPeriods.startedOn)), tx.select().from(fieldFallows).orderBy(asc(fieldFallows.startedOn))]); const pDtos = p.map(plantationDto); const fDtos = fallows.map(fallowDto); const rotation: RotationEntry[] = [...pDtos.filter((row) => row.status !== "voided").map((row) => ({ id: row.id, fieldId: row.fieldId, type: "plantation" as const, label: row.name, startedOn: row.startedOn, endedOn: row.endedOn, areaHa: row.areaHa, cultureId: row.cultureId, kind: row.kind })), ...fDtos.map((row) => ({ id: row.id, fieldId: row.fieldId, type: "fallow" as const, label: row.name, startedOn: row.startedOn, endedOn: row.endedOn, areaHa: row.areaHa }))].sort((a, b) => b.startedOn.localeCompare(a.startedOn)); return { plantations: pDtos, periods: periods.map(periodDto), fallows: fDtos, rotation }; }); },
  async createPlantation(context, input) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { await assertPlantationCapacity(tx, context); await assertCapacity(tx, input.fieldId, input.areaHa, input.kind); if (input.varietyId) { const [variety] = await tx.select({ cultureId: cropVarieties.cultureId }).from(cropVarieties).where(eq(cropVarieties.id, input.varietyId)); if (!variety || variety.cultureId !== input.cultureId) throw Object.assign(new Error("Variety does not belong to the selected crop"), { code: "CROP_VARIETY_INVALID", status: 400 }); } const id = randomUUID(); const [created] = await tx.insert(plantations).values({ id, organizationId: context.organization.id, ...input, areaHa: String(input.areaHa) }).returning(); if (input.kind === "temporary") await tx.insert(cropPeriods).values({ id: randomUUID(), organizationId: context.organization.id, plantationId: id, kind: "cycle", name: input.name, startedOn: input.startedOn, status: "active" }); await audit(tx, context, "plantation.created", "plantation", id, { kind: input.kind, cultureId: input.cultureId, areaHa: input.areaHa, initialCycleCreated: input.kind === "temporary" }); return plantationDto(created); }); },
  async createPeriod(context, input) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [plantation] = await tx.select().from(plantations).where(eq(plantations.id, input.plantationId)).for("update"); if (!plantation || plantation.status !== "active") throw Object.assign(new Error("Active plantation not found"), { code: "PLANTATION_NOT_FOUND", status: 404 }); if (input.startedOn < plantation.startedOn || input.endedOn && input.endedOn > (plantation.endedOn || input.endedOn)) throw Object.assign(new Error("Cultural period is outside the plantation lifecycle"), { code: "CROP_PERIOD_DATE_INVALID", status: 400 }); const existing = await tx.select().from(cropPeriods).where(eq(cropPeriods.plantationId, plantation.id)).orderBy(asc(cropPeriods.startedOn)); if (existing.some((row) => row.status === "active")) throw Object.assign(new Error("An active period already exists"), { code: "ACTIVE_CROP_PERIOD_EXISTS", status: 409 }); const previous = existing.at(-1); if (previous?.endedOn && input.startedOn <= previous.endedOn) throw Object.assign(new Error("A new cultural period can only start after the previous period ends"), { code: "CROP_PERIOD_OVERLAP", status: 409 }); const id = randomUUID(); const [created] = await tx.insert(cropPeriods).values({ id, organizationId: context.organization.id, ...input, kind: plantation.kind === "permanent" ? "campaign" : "cycle", endedOn: input.endedOn || null, status: input.endedOn ? "closed" : "active" }).returning(); await audit(tx, context, "crop_period.created", "crop_period", id, { kind: created.kind, plantationId: plantation.id }); return periodDto(created); }); },
  async closePeriod(context, id, endedOn) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [period] = await tx.select().from(cropPeriods).where(and(eq(cropPeriods.id, id), eq(cropPeriods.status, "active"))).for("update"); if (!period) return null; if (endedOn < period.startedOn) throw Object.assign(new Error("Cultural period end precedes its start"), { code: "CROP_PERIOD_DATE_INVALID", status: 400 }); const [updated] = await tx.update(cropPeriods).set({ endedOn, status: "closed" }).where(eq(cropPeriods.id, id)).returning(); if (updated.kind === "cycle") await tx.update(plantations).set({ endedOn, status: "ended" }).where(and(eq(plantations.id, updated.plantationId), eq(plantations.status, "active"))); await audit(tx, context, "crop_period.closed", "crop_period", id, { endedOn, plantationClosed: updated.kind === "cycle" }); return periodDto(updated); }); },
  async uproot(context, id, input) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [plantation] = await tx.select().from(plantations).where(eq(plantations.id, id)).for("update"); if (!plantation || plantation.kind !== "permanent" || plantation.status !== "active") return null; const activePeriods = await tx.select({ startedOn: cropPeriods.startedOn }).from(cropPeriods).where(and(eq(cropPeriods.plantationId, id), eq(cropPeriods.status, "active"))); if (input.uprootedOn < plantation.startedOn || activePeriods.some((row) => input.uprootedOn < row.startedOn)) throw Object.assign(new Error("Uprooting date precedes the plantation or active campaign"), { code: "UPROOTING_DATE_INVALID", status: 400 }); await tx.update(cropPeriods).set({ endedOn: input.uprootedOn, status: "closed" }).where(and(eq(cropPeriods.plantationId, id), eq(cropPeriods.status, "active"))); await tx.insert(plantationUprootings).values({ id: randomUUID(), organizationId: context.organization.id, plantationId: id, ...input }); const [updated] = await tx.update(plantations).set({ status: "uprooted", endedOn: input.uprootedOn }).where(eq(plantations.id, id)).returning(); await audit(tx, context, "plantation.uprooted", "plantation", id, { uprootedOn: input.uprootedOn, definitive: true }); return plantationDto(updated); }); },
  async createFallow(context, input) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { await assertCapacity(tx, input.fieldId, input.areaHa); const id = randomUUID(); const [created] = await tx.insert(fieldFallows).values({ id, organizationId: context.organization.id, ...input, areaHa: String(input.areaHa), endedOn: input.endedOn || null, status: input.endedOn ? "closed" : "active" }).returning(); await audit(tx, context, "field_fallow.created", "field_fallow", id, { fieldId: input.fieldId, areaHa: input.areaHa }); return fallowDto(created); }); },
  async closeFallow(context, id, endedOn) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [fallow] = await tx.select().from(fieldFallows).where(and(eq(fieldFallows.id, id), eq(fieldFallows.status, "active"))).for("update"); if (!fallow) return null; if (endedOn < fallow.startedOn) throw Object.assign(new Error("Fallow end precedes its start"), { code: "FALLOW_DATE_INVALID", status: 400 }); const [updated] = await tx.update(fieldFallows).set({ endedOn, status: "closed" }).where(eq(fieldFallows.id, id)).returning(); await audit(tx, context, "field_fallow.closed", "field_fallow", id, { endedOn }); return fallowDto(updated); }); },
}; }
