import assert from "node:assert/strict";
import test from "node:test";
import type { AddressInfo } from "node:net";
import { createApp } from "./app";
import type { CoreAccess } from "./gero-core-client";
import type { FarmRequestContext } from "./farm-context";

const organization={id:"11111111-1111-4111-8111-111111111111",name:"Farm",slug:"farm",status:"active"},membership={role:"owner",status:"active"};
function access(overrides:Partial<CoreAccess["access"]>={},features:Record<string,boolean|string|null>={inventory:false,costs:true}):CoreAccess{return{organization,membership,applicationMembership:{profile:"owner",status:"active",expiresAt:null,temporary:false,permissions:["*"],permissionOverrides:{allow:[],deny:[]}},application:{id:"33333333-3333-4333-8333-333333333333",code:"farm",name:"GeroFarm",slug:"gerofarm",status:"active",url:null},access:{allowed:true,reason:null,evaluatedAt:new Date().toISOString(),mode:"full",writeAllowed:true,exportAllowed:true,graceEndsAt:null,...overrides},subscription:{id:"44444444-4444-4444-8444-444444444444",status:"active",startsAt:"2026-01-01",trialEndsAt:null,renewsAt:null,endsAt:null,canceledAt:null,autoRenew:true,plan:{code:"grow",name:"Grow",status:"active"}},entitlements:{features,limits:{},addons:[]},onboarding:null}}
function context(core=access()):FarmRequestContext{return{organization,membership,user:{id:"22222222-2222-4222-8222-222222222222",name:"Ana",email:"ana@example.test",preferredLocale:"pt-PT",preferences:{},status:"active",emailVerifiedAt:null,platformRoles:[]},access:core}}
const holdings={list:async()=>[],create:async()=>{throw new Error("must not write")},update:async()=>null};
async function call(core:CoreAccess,method:string,path:string,body?:unknown){const fields={list:async()=>[],create:async()=>({} as never),update:async(_context:unknown,id:string,input:{status?:"active"|"inactive"})=>({id,holdingId:"55555555-5555-4555-8555-555555555555",code:"0001",name:"Norte",geometry:{type:"Polygon" as const,coordinates:[[[-8,39],[-8,39.1],[-8.1,39.1],[-8,39]]]},totalAreaHa:1,usableAreaHa:1,occupiedAreaHa:0,freeAreaHa:input.status==="inactive"?0:1,manuallyClosed:false,status:input.status||"active",codeLocked:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})};const economics={overview:async()=>({products:[{id:"p"}],lots:[{id:"l"}],consumptions:[{id:"c"}],costs:[{id:"cost"}],operations:[]}),createProduct:async()=>({} as never),receive:async()=>({} as never),consume:async()=>({} as never),regularize:async()=>null,createCost:async()=>({} as never)} as never;const app=createApp({farmHoldingRepository:holdings,fieldRepository:fields as never,economicsRepository:economics,farmContextResolver:async()=>context(core)}),server=app.listen(0);const port=(server.address()as AddressInfo).port;try{const response=await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:{"content-type":"application/json",origin:`http://127.0.0.1:${port}`},body:body?JSON.stringify(body):undefined});return{status:response.status,body:await response.json().catch(()=>null)}}finally{server.close()}}
test("direct inventory API calls are gated by the effective feature",async()=>{const result=await call(access(),"GET","/api/farm/economics?view=inventory");assert.equal(result.status,403);assert.equal((result.body as{code:string}).code,"FEATURE_NOT_ENTITLED")});
test("economics projection never exposes inventory through the costs view",async()=>{const result=await call(access(),"GET","/api/farm/economics?view=costs");assert.equal(result.status,200);assert.deepEqual((result.body as{data:{products:unknown[];lots:unknown[];consumptions:unknown[]}}).data.products,[]);assert.deepEqual((result.body as{data:{lots:unknown[]}}).data.lots,[])});
test("read-only access blocks creation but preserves capacity release",async()=>{const readOnly=access({mode:"read_only",writeAllowed:false});assert.equal((await call(readOnly,"POST","/api/farm/holdings",{name:"Farm",code:"F1",timezone:"Europe/Lisbon"})).status,403);assert.equal((await call(readOnly,"PATCH","/api/farm/fields/66666666-6666-4666-8666-666666666666",{status:"inactive"})).status,200)});
