import assert from "node:assert/strict";
import test from "node:test";
import type { Request } from "express";
import type { WeatherDataPoint, WeatherReport } from "@shared/weather";
import { captureMonitoringWeather } from "./monitoring-weather";

const subject={subjectType:"plantation" as const,subjectId:"plantation-1",plantationId:"plantation-1",cropPeriodId:"campaign-2026"};
const req={headers:{cookie:"gero_session=session"}} as Request;
const point:WeatherDataPoint={at:"2026-08-24T09:00:00.000Z",summary:"Provider text",icon:null,temperatureC:22,apparentTemperatureC:23,precipitationProbability:.1,precipitationIntensityMmPerHour:0,humidityPercent:65,windSpeedKph:12,windGustKph:18,windBearingDegrees:270,pressureHpa:1015,cloudCoverPercent:20,uvIndex:4,dewPointC:15,elevationM:100,solarRadiationWm2:450,precipitationAccumulationMm:0,precipitationType:"none",temporalStatus:"observed",valueSource:"estimated"};
const report:WeatherReport={latitude:38,longitude:-9,timezone:"Europe/Lisbon",units:"metric",current:point,hourly:{summary:null,data:[point]},daily:{summary:null,data:[]},station:{requestedFor:"2026-08-24T09:00:00.000Z",station:{id:"11111111-1111-4111-8111-111111111111",organizationId:"org",name:"Monte",latitude:38,longitude:-9,elevationM:100,timezone:"Europe/Lisbon",archivedAt:null,createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z"},assignment:{id:"22222222-2222-4222-8222-222222222222",stationId:"11111111-1111-4111-8111-111111111111",subjectType:"plantation",subjectId:"plantation-1",effectiveFrom:"2026-01-01T00:00:00Z",effectiveTo:null}},meta:{provider:"must-not-persist",fetchedAt:"2026-08-24T09:01:00Z",cached:true,stale:false,cache:{status:"fresh",freshUntil:"2026-08-24T09:10:00Z",staleUntil:"2026-08-24T10:00:00Z"},contractVersion:"2"}};

test("monitoring weather persists only provider-independent values and canonical plantation provenance",async()=>{const original=globalThis.fetch;let called="";globalThis.fetch=async input=>{called=String(input);return new Response(JSON.stringify({data:report}),{status:200,headers:{"content-type":"application/json"}})};try{const snapshot=await captureMonitoringWeather(req,"org",subject,point.at);assert.match(called,/subjects\/plantation\/plantation-1\/report\?at=/u);assert.doesNotMatch(called,/subjects\/campaign/u);assert.equal(snapshot.status,"available");assert.match(JSON.stringify(snapshot),/Monte/);assert.doesNotMatch(JSON.stringify(snapshot),/must-not-persist|Provider text|pressureHpa/);if(snapshot.status==="available"){assert.equal(snapshot.temporalStatus,"observed");assert.equal(snapshot.valueSource,"estimated");assert.equal(snapshot.values.temperatureC,22);assert.equal(snapshot.provenance.assignment?.id,report.station?.assignment?.id)}}finally{globalThis.fetch=original}});
test("monitoring weather records explicit unavailability without blocking",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({error:{code:"WEATHER_LEVEL_REQUIRED",message:"English detail must stay private"}}),{status:403,headers:{"content-type":"application/json"}});try{const snapshot=await captureMonitoringWeather(req,"org",subject,point.at);assert.deepEqual({status:snapshot.status,reason:snapshot.status==="unavailable"?snapshot.reason:null},{status:"unavailable",reason:"plan_history_unavailable"});assert.doesNotMatch(JSON.stringify(snapshot),/English detail/)}finally{globalThis.fetch=original}});
test("monitoring weather distinguishes missing station and missing subject",async()=>{const noSubject=await captureMonitoringWeather(req,"org",null,point.at);assert.equal(noSubject.status,"unavailable");if(noSubject.status==="unavailable")assert.equal(noSubject.reason,"no_plantation");const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({data:{...report,station:null}}),{status:200,headers:{"content-type":"application/json"}});try{const noStation=await captureMonitoringWeather(req,"org",subject,point.at);assert.equal(noStation.status,"unavailable");if(noStation.status==="unavailable")assert.equal(noStation.reason,"no_station")}finally{globalThis.fetch=original}});
test("monitoring weather does not contact Core when the plan has no history",async()=>{const original=globalThis.fetch;let called=false;globalThis.fetch=async()=>{called=true;throw new Error("must not be called")};try{const snapshot=await captureMonitoringWeather(req,"org",subject,point.at,false);assert.equal(snapshot.status,"unavailable");if(snapshot.status==="unavailable")assert.equal(snapshot.reason,"plan_history_unavailable");assert.equal(called,false)}finally{globalThis.fetch=original}});
