import assert from "node:assert/strict";
import test from "node:test";
import type { Request } from "express";
import type { WeatherBaseSeries } from "@shared/weather";
import type { WeatherStore } from "./weather-store";
import { captureMonitoringWeather } from "./monitoring-weather";

const subject={subjectType:"plantation" as const,subjectId:"plantation-1",plantationId:"plantation-1",cropPeriodId:"campaign-2026"};
const req={headers:{cookie:"gero_session=session"}} as Request;
const station={id:"11111111-1111-4111-8111-111111111111",organizationId:"org",name:"Monte",latitude:38,longitude:-9,elevationM:100,timezone:"Europe/Lisbon",archivedAt:null,createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z"};
const assignment={id:"22222222-2222-4222-8222-222222222222",stationId:station.id,subjectType:"plantation" as const,subjectId:"plantation-1",effectiveFrom:"2026-01-01T00:00:00Z",effectiveTo:null};
const hour={at:"2026-08-24T09:00:00.000Z",temperatureC:22,apparentTemperatureC:23,precipitationProbability:.1,precipitationIntensityMmPerHour:0,precipitationAccumulationMm:0,precipitationType:"none" as const,humidityPercent:65,windSpeedKph:12,windGustKph:18,windBearingDegrees:270,pressureHpa:1015,cloudCoverPercent:20,uvIndex:4,dewPointC:15,solarRadiationWm2:450,elevationM:100,temporalStatus:"observed" as const,valueSource:"estimated" as const};
const series=(periods=true):WeatherBaseSeries=>({contractVersion:"2",subject:{subjectType:"plantation",subjectId:"plantation-1"},interval:{from:"2026-08-24",to:"2026-08-24",maximumDays:366},page:{from:"2026-08-24",to:"2026-08-24",sizeDays:1,nextCursor:null},timezone:"Europe/Lisbon",units:"metric",hourly:[hour],daily:[],stationPeriods:periods?[{from:"2026-08-24",to:"2026-08-24",station,assignment}]:[],coverage:{requestedDays:1,daysWithHourlyData:1,daysWithDailyData:0,requestedHours:24,availableHours:1,complete:false,gaps:[{from:"2026-08-24",to:"2026-08-24",reason:"daily_data_unavailable"}]},meta:{provider:"must-not-persist",fetchedAt:"2026-08-24T09:01:00Z",cached:true,stale:false,cache:{status:"fresh",requests:1,hits:1,misses:0}}});
const store:WeatherStore={assertScope:async()=>{},completeSeries:async()=>null,persistSeries:async()=>{},profile:async()=>null,saveProfile:async()=>{throw new Error("unused")},saveResult:async()=>{}};

test("monitoring reuses the persisted-series pipeline and stores only normalized provenance",async()=>{const original=globalThis.fetch;let called="";globalThis.fetch=async input=>{called=String(input);return new Response(JSON.stringify({data:series()}),{status:200,headers:{"content-type":"application/json"}})};try{const snapshot=await captureMonitoringWeather(req,"org",subject,hour.at,true,store);assert.match(called,/subjects\/plantation\/plantation-1\/series\?/u);assert.doesNotMatch(called,/\/report|agronomic-accumulation/u);assert.equal(snapshot.status,"available");assert.doesNotMatch(JSON.stringify(snapshot),/must-not-persist|pressureHpa/);if(snapshot.status==="available"){assert.equal(snapshot.values.temperatureC,22);assert.equal(snapshot.provenance.assignment?.id,assignment.id)}}finally{globalThis.fetch=original}});
test("monitoring records explicit Core unavailability without forged observations",async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({error:{code:"WEATHER_LEVEL_REQUIRED",message:"private"}}),{status:403,headers:{"content-type":"application/json"}});try{const snapshot=await captureMonitoringWeather(req,"org",subject,hour.at,true,store);assert.equal(snapshot.status,"unavailable");if(snapshot.status==="unavailable")assert.equal(snapshot.reason,"plan_history_unavailable")}finally{globalThis.fetch=original}});
test("monitoring distinguishes missing station and subject",async()=>{const noSubject=await captureMonitoringWeather(req,"org",null,hour.at,true,store);assert.equal(noSubject.status,"unavailable");if(noSubject.status==="unavailable")assert.equal(noSubject.reason,"no_plantation");const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({data:series(false)}),{status:200,headers:{"content-type":"application/json"}});try{const snapshot=await captureMonitoringWeather(req,"org",subject,hour.at,true,store);assert.equal(snapshot.status,"unavailable");if(snapshot.status==="unavailable")assert.equal(snapshot.reason,"no_station")}finally{globalThis.fetch=original}});
test("monitoring does not contact Core when history is unavailable in the plan",async()=>{const original=globalThis.fetch;let called=false;globalThis.fetch=async()=>{called=true;throw new Error("must not be called")};try{const snapshot=await captureMonitoringWeather(req,"org",subject,hour.at,false,store);assert.equal(snapshot.status,"unavailable");assert.equal(called,false)}finally{globalThis.fetch=original}});
