import { randomUUID } from "node:crypto";
import { and, asc, count, eq } from "drizzle-orm";
import { farmAuditEvents, farmFields, farmHoldings, farmOperations, privacyRequests } from "@shared/schema";
import { farmRetentionPolicies, sanitizePrivacyAuditMetadata, type PrivacyRequestDto } from "@shared/privacy";
import type { FarmDatabase } from "./database";
import { withOrganizationTransaction } from "./database";
import type { FarmRequestContext } from "./farm-context";

const dto = (row: typeof privacyRequests.$inferSelect): PrivacyRequestDto => ({ id: row.id, requesterUserId: row.requesterUserId, type: row.type as PrivacyRequestDto["type"], details: row.details, status: row.status as PrivacyRequestDto["status"], response: row.response || undefined, submittedAt: row.submittedAt.toISOString(), deadlineAt: row.deadlineAt.toISOString(), updatedAt: row.updatedAt.toISOString() });
function assertOwner(context: FarmRequestContext) { if (context.membership.role !== "owner") throw Object.assign(new Error("Organization owner access required"), { status: 403, code: "PRIVACY_MANAGER_REQUIRED" }); }
export function createPostgresPrivacyRepository(db: FarmDatabase) {
  async function audit(tx: Parameters<Parameters<FarmDatabase["transaction"]>[0]>[0], context: FarmRequestContext, action: string, entityId: string, metadata?: Record<string, unknown>) { await tx.insert(farmAuditEvents).values({ id: randomUUID(), organizationId: context.organization.id, actorUserId: context.user.id, action, entityType: "privacy", entityId, metadata: sanitizePrivacyAuditMetadata(metadata) }); }
  return {
    async overview(context: FarmRequestContext) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [requests, holdings, fields, operations] = await Promise.all([tx.select().from(privacyRequests).where(eq(privacyRequests.requesterUserId, context.user.id)).orderBy(asc(privacyRequests.submittedAt)), tx.select({ value: count() }).from(farmHoldings), tx.select({ value: count() }).from(farmFields), tx.select({ value: count() }).from(farmOperations)]); await audit(tx, context, "privacy.center.accessed", context.user.id, { count: requests.length }); return { requests: requests.map(dto), policies: farmRetentionPolicies, summary: { holdings: holdings[0].value, fields: fields[0].value, operations: operations[0].value } }; }); },
    async createRequest(context: FarmRequestContext, input: { type: PrivacyRequestDto["type"]; details: string }) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const id = randomUUID(); const submittedAt = new Date(); const deadlineAt = new Date(submittedAt); deadlineAt.setUTCDate(deadlineAt.getUTCDate() + 30); const [created] = await tx.insert(privacyRequests).values({ id, organizationId: context.organization.id, requesterUserId: context.user.id, ...input, submittedAt, deadlineAt, updatedAt: submittedAt }).returning(); await audit(tx, context, "privacy.request.submitted", id, { requestId: id, type: input.type, status: "submitted" }); return dto(created); }); },
    async manage(context: FarmRequestContext) { assertOwner(context); return withOrganizationTransaction(db, context.organization.id, async (tx) => (await tx.select().from(privacyRequests).orderBy(asc(privacyRequests.deadlineAt))).map(dto)); },
    async review(context: FarmRequestContext, id: string, input: { status: "in_review" | "completed" | "rejected" | "archived"; response: string }) { assertOwner(context); return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [existing] = await tx.select().from(privacyRequests).where(eq(privacyRequests.id, id)); if (!existing) return null; if (["completed", "rejected", "archived"].includes(existing.status)) throw Object.assign(new Error("Completed privacy request is immutable"), { status: 409, code: "PRIVACY_REQUEST_IMMUTABLE" }); const [updated] = await tx.update(privacyRequests).set({ ...input, updatedAt: new Date() }).where(and(eq(privacyRequests.id, id), eq(privacyRequests.status, existing.status))).returning(); if (!updated) return null; await audit(tx, context, "privacy.request.reviewed", id, { requestId: id, status: input.status }); return dto(updated); }); },
    async exportPersonalData(context: FarmRequestContext) { return withOrganizationTransaction(db, context.organization.id, async (tx) => { const [requests, auditRows] = await Promise.all([tx.select().from(privacyRequests).where(eq(privacyRequests.requesterUserId, context.user.id)), tx.select({ action: farmAuditEvents.action, entityType: farmAuditEvents.entityType, occurredAt: farmAuditEvents.occurredAt }).from(farmAuditEvents).where(eq(farmAuditEvents.actorUserId, context.user.id))]); await audit(tx, context, "privacy.personal_data.exported", context.user.id, { format: "json", count: requests.length + auditRows.length }); return { generatedAt: new Date().toISOString(), organization: { id: context.organization.id, name: context.organization.name }, user: { id: context.user.id, email: context.user.email, name: context.user.name, preferredLocale: context.user.preferredLocale }, privacyRequests: requests.map(dto), auditActivity: auditRows.map((row) => ({ ...row, occurredAt: row.occurredAt.toISOString() })) }; }); },
  };
}
export type PrivacyRepository = ReturnType<typeof createPostgresPrivacyRepository>;
