import assert from "node:assert/strict";
import test from "node:test";
import type { Request } from "express";
import type { WeatherBaseSeries } from "@shared/weather";
import type { WeatherStore } from "./weather-store";
import { synchronizeWeatherSeries } from "./weather-sync";

const req={headers:{cookie:"gero_session=session"}} as Request,plantationId="44444444-4444-4444-8444-444444444444";
const page=(from:string,to:string,nextCursor:string|null):WeatherBaseSeries=>({contractVersion:"2",subject:{subjectType:"plantation",subjectId:plantationId},interval:{from:"2025-01-01",to:"2025-02-09",maximumDays:366},page:{from,to,sizeDays:31,nextCursor},timezone:"Europe/Lisbon",units:"metric",hourly:[],daily:[],stationPeriods:[],coverage:{requestedDays:from==="2025-01-01"?31:9,daysWithHourlyData:0,daysWithDailyData:0,requestedHours:0,availableHours:0,complete:true,gaps:[]},meta:{provider:"normalized",fetchedAt:"2025-02-10T00:00:00Z",cached:false,stale:false,cache:{status:"miss",requests:1,hits:0,misses:1}}});
test("series synchronization paginates, persists once outside fetches, and reuses complete history",async()=>{let persisted:WeatherBaseSeries|null=null,persistCalls=0,fetchCalls=0;const store:WeatherStore={completeSeries:async()=>persisted,persistSeries:async(_o,_p,_c,value)=>{persistCalls+=1;persisted=value},profile:async()=>null,saveProfile:async()=>{throw new Error("unused")},saveResult:async()=>{}};const original=globalThis.fetch;globalThis.fetch=async input=>{fetchCalls+=1;const url=new URL(String(input)),cursor=url.searchParams.get("cursor");return new Response(JSON.stringify({data:cursor==="2025-01-01"?page("2025-01-01","2025-01-31","2025-02-01"):page("2025-02-01","2025-02-09",null)}),{status:200,headers:{"content-type":"application/json"}})};try{const first=await synchronizeWeatherSeries(req,store,"22222222-2222-4222-8222-222222222222",plantationId,null,"2025-01-01","2025-02-09");assert.equal(first.interval.maximumDays,366);assert.equal(fetchCalls,2);assert.equal(persistCalls,1);await synchronizeWeatherSeries(req,store,"22222222-2222-4222-8222-222222222222",plantationId,null,"2025-01-01","2025-02-09");assert.equal(fetchCalls,2);assert.equal(persistCalls,1)}finally{globalThis.fetch=original}});
test("series synchronization rejects intervals beyond 366 days before network access",async()=>{const store={} as WeatherStore;await assert.rejects(()=>synchronizeWeatherSeries(req,store,"org",plantationId,null,"2024-01-01","2025-01-02"),/between 1 and 366/)});
test("tenant scope is validated before any Core request",async()=>{let called=false;const original=globalThis.fetch;globalThis.fetch=async()=>{called=true;throw new Error("network must not run")};try{const store={assertScope:async()=>{throw Object.assign(new Error("missing"),{status:404,code:"PLANTATION_NOT_FOUND"})}} as unknown as WeatherStore;await assert.rejects(()=>synchronizeWeatherSeries(req,store,"org",plantationId,null,"2025-01-01","2025-01-02"),/missing/);assert.equal(called,false)}finally{globalThis.fetch=original}});
