import type { Request } from "express";
import type { WeatherBaseSeries } from "@shared/weather";
import { CoreApiError, geroCore } from "./gero-core-client";
import type { WeatherStore } from "./weather-store";

const PAGE_DAYS=31,MAX_DAYS=366,MAX_PAGES=12;
const days=(from:string,to:string)=>Math.floor((Date.parse(`${to}T12:00:00Z`)-Date.parse(`${from}T12:00:00Z`))/86400000)+1;
const validSeries=(value:WeatherBaseSeries,plantationId:string)=>{if(value.contractVersion!=="2"||value.subject.subjectType!=="plantation"||value.subject.subjectId!==plantationId||value.units!=="metric")throw new CoreApiError(503,"Gero Core returned an invalid base weather series","CORE_INVALID_WEATHER_SERIES");return value};

export async function synchronizeWeatherSeries(req:Request,store:WeatherStore,organizationId:string,plantationId:string,campaignId:string|null,from:string,to:string):Promise<WeatherBaseSeries>{
  const count=days(from,to);if(count<1||count>MAX_DAYS)throw new CoreApiError(400,`Weather interval must contain between 1 and ${MAX_DAYS} days`,"WEATHER_INTERVAL_INVALID");
  await store.assertScope?.(organizationId,plantationId,campaignId);
  const historical=to<new Date().toISOString().slice(0,10),persisted=await store.completeSeries(organizationId,plantationId,from,to),refreshMs=Math.min(3600000,Math.max(60000,Number(process.env.GEROFARM_WEATHER_REFRESH_MS||900000))),freshEnough=persisted?.meta.fetchedAt&&Date.now()-Date.parse(persisted.meta.fetchedAt)<=refreshMs;if(persisted&&(historical||(!persisted.meta.stale&&freshEnough)))return persisted;
  const pages:WeatherBaseSeries[]=[];let cursor:string|null=from;
  try{while(cursor&&pages.length<MAX_PAGES){const path=`subjects/plantation/${encodeURIComponent(plantationId)}/series?${new URLSearchParams({from,to,pageSizeDays:String(PAGE_DAYS),cursor})}`;let page:WeatherBaseSeries|null=null;for(let attempt=0;attempt<2;attempt+=1){try{page=validSeries(await geroCore.weather.get<WeatherBaseSeries>(req,organizationId,path),plantationId);break}catch(error){if(!(error instanceof CoreApiError)||![429,503].includes(error.status)||attempt===1)throw error}}if(!page)throw new CoreApiError(503,"Gero Core base weather series is unavailable","CORE_UNAVAILABLE");pages.push(page);if(page.page.nextCursor===cursor)throw new CoreApiError(503,"Gero Core weather pagination did not advance","CORE_INVALID_WEATHER_SERIES");cursor=page.page.nextCursor;}}catch(error){await store.recordUnavailable?.(organizationId,plantationId,campaignId,from,to);throw error}
  if(cursor)throw new CoreApiError(503,"Gero Core weather pagination exceeded its safe limit","CORE_INVALID_WEATHER_SERIES");
  const first=pages[0],last=pages.at(-1)!;const merged:WeatherBaseSeries={...first,interval:{from,to,maximumDays:MAX_DAYS},page:{from,to,sizeDays:Math.min(PAGE_DAYS,count),nextCursor:null},hourly:dedupe(pages.flatMap(page=>page.hourly),item=>item.at),daily:dedupe(pages.flatMap(page=>page.daily),item=>item.date),stationPeriods:dedupe(pages.flatMap(page=>page.stationPeriods),item=>`${item.assignment.id}:${item.from}:${item.to}`),coverage:{requestedDays:count,daysWithHourlyData:new Set(pages.flatMap(page=>page.hourly.map(item=>localDate(item.at,page.timezone)))).size,daysWithDailyData:new Set(pages.flatMap(page=>page.daily.map(item=>item.date))).size,requestedHours:pages.reduce((sum,page)=>sum+page.coverage.requestedHours,0),availableHours:new Set(pages.flatMap(page=>page.hourly.map(item=>item.at))).size,complete:pages.every(page=>page.coverage.complete),gaps:pages.flatMap(page=>page.coverage.gaps)},meta:{provider:first.meta.provider,fetchedAt:last.meta.fetchedAt,cached:pages.every(page=>page.meta.cached),stale:pages.some(page=>page.meta.stale),cache:{status:pages.some(page=>page.meta.cache.status==="stale")?"stale":pages.every(page=>page.meta.cache.status==="fresh")?"fresh":"mixed",requests:pages.reduce((sum,page)=>sum+page.meta.cache.requests,0),hits:pages.reduce((sum,page)=>sum+page.meta.cache.hits,0),misses:pages.reduce((sum,page)=>sum+page.meta.cache.misses,0)}}};
  await store.persistSeries(organizationId,plantationId,campaignId,merged);return merged;
}
function dedupe<T>(items:T[],key:(item:T)=>string){return[...new Map(items.map(item=>[key(item),item])).values()]}
function localDate(value:string,timezone:string|null){const parts=Object.fromEntries(new Intl.DateTimeFormat("en",{timeZone:timezone||"UTC",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value)).map(part=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}`}
