import { randomUUID } from "node:crypto";
import { and, asc, eq, gte, lte, sql } from "drizzle-orm";
import type { AgronomicWeatherAccumulation, WeatherAgronomicProfile, WeatherBaseSeries, WeatherSeriesDay, WeatherSeriesHour } from "@shared/weather";
import { cropPeriods, plantations, weatherAgronomicProfiles, weatherAgronomicResults, weatherSamples, weatherSyncs } from "@shared/schema";
import type { FarmDatabase } from "./database";
import { withOrganizationTransaction } from "./database";
import { AGRONOMIC_ENGINE_VERSION } from "./agronomic-weather-engine";

export interface WeatherStore {
  assertScope?(organizationId:string,plantationId:string,campaignId:string|null):Promise<void>;
  completeSeries(organizationId:string,plantationId:string,from:string,to:string):Promise<WeatherBaseSeries|null>;
  persistSeries(organizationId:string,plantationId:string,campaignId:string|null,series:WeatherBaseSeries):Promise<void>;
  recordUnavailable?(organizationId:string,plantationId:string,campaignId:string|null,from:string,to:string):Promise<void>;
  profile(organizationId:string,plantationId:string,campaignId:string|null,from:string,to:string):Promise<WeatherAgronomicProfile[]|WeatherAgronomicProfile|null>;
  saveProfile(organizationId:string,plantationId:string,campaignId:string,input:Omit<WeatherAgronomicProfile,"id"|"organizationId"|"campaignId"|"validTo"|"createdAt">):Promise<WeatherAgronomicProfile>;
  saveResult(organizationId:string,plantationId:string,campaignId:string|null,result:AgronomicWeatherAccumulation):Promise<void>;
}
const dateOnly=(value:Date|string)=>typeof value==="string"?value.slice(0,10):value.toISOString().slice(0,10);
const instant=(value:Date|string|null)=>value?typeof value==="string"?value:value.toISOString():null;

export function createPostgresWeatherStore(db:FarmDatabase):WeatherStore{return{
  async assertScope(organizationId,plantationId,campaignId){await withOrganizationTransaction(db,organizationId,async tx=>{const [plantation]=await tx.select({id:plantations.id}).from(plantations).where(and(eq(plantations.organizationId,organizationId),eq(plantations.id,plantationId))).limit(1);if(!plantation)throw Object.assign(new Error("Plantation not found"),{status:404,code:"PLANTATION_NOT_FOUND"});if(campaignId){const [period]=await tx.select({id:cropPeriods.id}).from(cropPeriods).where(and(eq(cropPeriods.organizationId,organizationId),eq(cropPeriods.id,campaignId),eq(cropPeriods.plantationId,plantationId))).limit(1);if(!period)throw Object.assign(new Error("Cultural period not found for plantation"),{status:404,code:"CROP_PERIOD_NOT_FOUND"})}})},
  async completeSeries(organizationId,plantationId,from,to){return withOrganizationTransaction(db,organizationId,async tx=>{
    const [sync]=await tx.select().from(weatherSyncs).where(and(eq(weatherSyncs.organizationId,organizationId),eq(weatherSyncs.plantationId,plantationId),eq(weatherSyncs.status,"complete"),lte(weatherSyncs.fromDate,from),gte(weatherSyncs.toDate,to))).orderBy(asc(weatherSyncs.createdAt)).limit(1);
    if(!sync)return null;
    const samples=await tx.select().from(weatherSamples).where(and(eq(weatherSamples.organizationId,organizationId),eq(weatherSamples.plantationId,plantationId),gte(weatherSamples.localDate,from),lte(weatherSamples.localDate,to))).orderBy(asc(weatherSamples.sampleAt));
    const hourly=samples.filter(row=>row.resolution==="hourly").map(row=>row.payload as WeatherSeriesHour),daily=samples.filter(row=>row.resolution==="daily").map(row=>row.payload as WeatherSeriesDay),timezone=samples[0]?.timezone||null,gaps=sync.coverage.gaps.filter(gap=>gap.to>=from&&gap.from<=to).map(gap=>({...gap,from:gap.from<from?from:gap.from,to:gap.to>to?to:gap.to})),requestedHours=expectedHours(from,to,timezone);
    return{contractVersion:"2",subject:{subjectType:"plantation",subjectId:plantationId},interval:{from,to,maximumDays:366},page:{from,to,sizeDays:Math.min(31,days(from,to)),nextCursor:null},timezone,units:"metric",hourly,daily,stationPeriods:sync.stationPeriods.filter(period=>period.to>=from&&period.from<=to).map(period=>({...period,from:period.from<from?from:period.from,to:period.to>to?to:period.to})),coverage:{requestedDays:days(from,to),daysWithHourlyData:new Set(hourly.map(item=>localDate(item.at,timezone))).size,daysWithDailyData:new Set(daily.map(item=>item.date)).size,requestedHours,availableHours:new Set(hourly.map(item=>item.at)).size,complete:gaps.length===0,gaps},meta:{provider:"persisted-provider-independent",fetchedAt:instant(sync.fetchedAt),cached:sync.cached,stale:sync.stale,cache:{status:sync.cacheStatus as WeatherBaseSeries["meta"]["cache"]["status"],requests:0,hits:1,misses:0}}};
  })},
  async persistSeries(organizationId,plantationId,campaignId,series){await withOrganizationTransaction(db,organizationId,async tx=>{
    const stationFor=(date:string)=>series.stationPeriods.find(period=>date>=period.from&&date<=period.to);
    const rows=[...series.hourly.map(source=>{const payload=sanitizeWeatherPayload(source);return{resolution:"hourly" as const,date:localDate(source.at,series.timezone),at:new Date(source.at),payload}}),...series.daily.map(source=>{const payload=sanitizeWeatherPayload(source);return{resolution:"daily" as const,date:source.date,at:new Date(`${source.date}T12:00:00Z`),payload}})].flatMap(item=>{const period=stationFor(item.date);return period?[{id:randomUUID(),organizationId,plantationId,campaignId,stationId:period.station.id,assignmentId:period.assignment.id,resolution:item.resolution,sampleAt:item.at,localDate:item.date,timezone:series.timezone,station:period.station,payload:item.payload,temporalStatus:item.payload.temporalStatus,valueSource:item.payload.valueSource,fetchedAt:series.meta.fetchedAt?new Date(series.meta.fetchedAt):null,cached:series.meta.cached,stale:series.meta.stale,updatedAt:new Date()}]:[]});
    for(const row of rows)await tx.insert(weatherSamples).values(row).onConflictDoUpdate({target:[weatherSamples.organizationId,weatherSamples.plantationId,weatherSamples.stationId,weatherSamples.resolution,weatherSamples.sampleAt],set:{campaignId:row.campaignId,assignmentId:row.assignmentId,localDate:row.localDate,timezone:row.timezone,station:row.station,payload:row.payload,temporalStatus:row.temporalStatus,valueSource:row.valueSource,fetchedAt:row.fetchedAt,cached:row.cached,stale:row.stale,updatedAt:new Date()}});
    await tx.insert(weatherSyncs).values({id:randomUUID(),organizationId,plantationId,campaignId,fromDate:series.interval.from,toDate:series.interval.to,status:series.coverage.complete?"complete":"partial",coverage:series.coverage,stationPeriods:series.stationPeriods,fetchedAt:series.meta.fetchedAt?new Date(series.meta.fetchedAt):null,cached:series.meta.cached,stale:series.meta.stale,cacheStatus:series.meta.cache.status});
  })},
  async recordUnavailable(organizationId,plantationId,campaignId,from,to){await withOrganizationTransaction(db,organizationId,async tx=>{await tx.insert(weatherSyncs).values({id:randomUUID(),organizationId,plantationId,campaignId,fromDate:from,toDate:to,status:"unavailable",coverage:{requestedDays:days(from,to),daysWithHourlyData:0,daysWithDailyData:0,requestedHours:days(from,to)*24,availableHours:0,complete:false,gaps:[{from,to,reason:"provider_unavailable"}]},stationPeriods:[],fetchedAt:null,cached:false,stale:false,cacheStatus:"not_requested"})})},
  async profile(organizationId,plantationId,campaignId,from,to){if(!campaignId)return[];return withOrganizationTransaction(db,organizationId,async tx=>{const rows=await tx.select().from(weatherAgronomicProfiles).where(and(eq(weatherAgronomicProfiles.organizationId,organizationId),eq(weatherAgronomicProfiles.plantationId,plantationId),eq(weatherAgronomicProfiles.campaignId,campaignId),lte(weatherAgronomicProfiles.validFrom,new Date(`${to}T23:59:59Z`)),sql`(${weatherAgronomicProfiles.validTo} is null or ${weatherAgronomicProfiles.validTo}>=${new Date(`${from}T00:00:00Z`)})`)).orderBy(asc(weatherAgronomicProfiles.validFrom));return rows.map(row=>({...row,validFrom:row.validFrom.toISOString(),validTo:instant(row.validTo),createdAt:row.createdAt.toISOString()}))})},
  async saveProfile(organizationId,plantationId,campaignId,input){return withOrganizationTransaction(db,organizationId,async tx=>{const validFrom=new Date(input.validFrom),existing=await tx.select().from(weatherAgronomicProfiles).where(and(eq(weatherAgronomicProfiles.organizationId,organizationId),eq(weatherAgronomicProfiles.plantationId,plantationId),eq(weatherAgronomicProfiles.campaignId,campaignId))).orderBy(asc(weatherAgronomicProfiles.validFrom));if(existing.some(item=>item.validFrom.getTime()===validFrom.getTime()))throw Object.assign(new Error("A profile already starts at this instant"),{status:409,code:"WEATHER_PROFILE_VERSION_CONFLICT"});const previous=existing.filter(item=>item.validFrom<validFrom).at(-1),next=existing.find(item=>item.validFrom>validFrom);if(previous)await tx.update(weatherAgronomicProfiles).set({validTo:validFrom}).where(eq(weatherAgronomicProfiles.id,previous.id));const row={id:randomUUID(),organizationId,plantationId,campaignId,cropId:input.cropId,varietyId:input.varietyId,methodVersion:input.methodVersion,parameters:input.parameters,validFrom,validTo:next?.validFrom||null,createdAt:new Date()};await tx.insert(weatherAgronomicProfiles).values(row);return{...row,validFrom:row.validFrom.toISOString(),validTo:instant(row.validTo),createdAt:row.createdAt.toISOString()}})},
  async saveResult(organizationId,plantationId,campaignId,result){const inputHash=result.metrics.et0.inputHash;await withOrganizationTransaction(db,organizationId,async tx=>{await tx.insert(weatherAgronomicResults).values({id:randomUUID(),organizationId,plantationId,campaignId,fromDate:result.interval.from,toDate:result.interval.to,engineVersion:AGRONOMIC_ENGINE_VERSION,inputHash,result}).onConflictDoNothing()})},
}}
function days(from:string,to:string){return Math.floor((Date.parse(`${to}T12:00:00Z`)-Date.parse(`${from}T12:00:00Z`))/86400000)+1}
function localDate(value:string,timezone:string|null){const parts=Object.fromEntries(new Intl.DateTimeFormat("en",{timeZone:timezone||"UTC",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value)).map(part=>[part.type,part.value]));return`${parts.year}-${parts.month}-${parts.day}`}
function expectedHours(from:string,to:string,timezone:string|null){let count=0;for(let instant=Date.parse(`${from}T00:00:00Z`)-2*86400000;instant<=Date.parse(`${to}T00:00:00Z`)+3*86400000;instant+=3600000){const date=localDate(new Date(instant).toISOString(),timezone);if(date>=from&&date<=to)count+=1}return count}
const weatherPayloadKeys=["at","date","temperatureC","apparentTemperatureC","temperatureMinC","temperatureMaxC","precipitationProbability","precipitationIntensityMmPerHour","precipitationAccumulationMm","precipitationType","humidityPercent","windSpeedKph","windGustKph","windBearingDegrees","pressureHpa","cloudCoverPercent","uvIndex","dewPointC","solarRadiationWm2","elevationM","temporalStatus","valueSource"] as const;
function sanitizeWeatherPayload<T extends WeatherSeriesHour|WeatherSeriesDay>(source:T):T{return Object.fromEntries(weatherPayloadKeys.filter(key=>key in source).map(key=>[key,source[key as keyof T]])) as unknown as T}
