import assert from "node:assert/strict";
import test from "node:test";
import { createServer } from "node:http";
import { createApp } from "./app";

const organizationId="11111111-1111-4111-8111-111111111111";
const context={user:{id:"u",email:"u@example.test",name:"User",preferredLocale:"pt-PT",preferences:{},status:"active",emailVerifiedAt:null,platformRoles:[]},organization:{id:organizationId,name:"Farm",slug:"farm",status:"active"},membership:{role:"owner",status:"active"},access:undefined};

test("weather routes proxy station reads and writes without local persistence",async()=>{const nativeFetch=globalThis.fetch;const coreCalls:Array<{url:string;method:string;cookie:string;csrf:string|null}>=[];globalThis.fetch=async(input,init)=>{const url=String(input);if(url.startsWith("http://127.0.0.1:"))return nativeFetch(input,init);coreCalls.push({url,method:init?.method||"GET",cookie:new Headers(init?.headers).get("cookie")||"",csrf:new Headers(init?.headers).get("x-csrf-token")});const station={id:"22222222-2222-4222-8222-222222222222",organizationId,name:"North",latitude:38,longitude:-9,elevationM:null,timezone:"Europe/Lisbon",archivedAt:null,createdAt:"2026-08-24T00:00:00Z",updatedAt:"2026-08-24T00:00:00Z"};return new Response(JSON.stringify({data:init?.method==="POST"?station:[station]}),{status:init?.method==="POST"?201:200,headers:{"content-type":"application/json"}})};
  const server=createServer(createApp({farmContextResolver:async()=>context as never}));await new Promise<void>((resolve)=>server.listen(0,"127.0.0.1",resolve));try{const address=server.address();assert(address&&typeof address==="object");const base=`http://127.0.0.1:${address.port}`;const read=await nativeFetch(`${base}/api/weather/stations`,{headers:{cookie:"gero_session=session; gero_csrf=csrf"}});assert.equal(read.status,200);const write=await nativeFetch(`${base}/api/weather/stations`,{method:"POST",headers:{origin:base,cookie:"gero_session=session; gero_csrf=csrf","content-type":"application/json"},body:JSON.stringify({name:"North",latitude:38,longitude:-9,elevationM:null,timezone:"Europe/Lisbon"})});assert.equal(write.status,201);assert.equal(coreCalls.length,2);assert.match(coreCalls[0].url,/applications\/farm\/weather\/stations$/);assert.equal(coreCalls[0].cookie,"gero_session=session");assert.equal(coreCalls[1].cookie,"gero_session=session; gero_csrf=csrf");assert.equal(coreCalls[1].csrf,"csrf")}finally{globalThis.fetch=nativeFetch;await new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()))}});

test("essential weather level blocks history before contacting Core",async()=>{const server=createServer(createApp({farmContextResolver:async()=>context as never}));await new Promise<void>((resolve)=>server.listen(0,"127.0.0.1",resolve));try{const address=server.address();assert(address&&typeof address==="object");const response=await fetch(`http://127.0.0.1:${address.port}/api/weather/historical?latitude=38&longitude=-9&at=2026-08-24T12%3A00%3A00.000Z`);assert.equal(response.status,403);assert.equal((await response.json() as{code:string}).code,"WEATHER_LEVEL_REQUIRED")}finally{await new Promise<void>((resolve,reject)=>server.close((error)=>error?reject(error):resolve()))}});
