import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import type { CultureCatalogEntry, VarietyDto } from "@shared/crops";
import { formatCount } from "@shared/crops";
import { useAuth } from "../../auth";
import { useI18n } from "../../i18n";
import { cropCopies } from "./crop-locales.generated";
import { lifecycleCopies } from "./lifecycle-locales.generated";
import CropLifecyclePanel from "./CropLifecyclePanel";
import "./crops.css";

export default function CropsModule() {
  const { locale } = useI18n(); const { session } = useAuth(); const t = cropCopies[locale]; const lifecycle = lifecycleCopies[locale];
  const permissions = session?.access.applicationMembership.permissions || []; const canWrite = Boolean(session?.access.access.writeAllowed && (permissions.includes("*") || permissions.includes("farm.manage")));
  const [cultures, setCultures] = useState<readonly CultureCatalogEntry[]>([]); const [varieties, setVarieties] = useState<VarietyDto[]>([]); const [tab, setTab] = useState<"cultures" | "varieties" | "lifecycle">("cultures"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [adding, setAdding] = useState(false);
  const load = useCallback(async () => { setLoading(true); setFailed(false); try { const [catalogueResponse, varietiesResponse] = await Promise.all([fetch("/api/farm/crop-catalog", { credentials: "include" }), fetch("/api/farm/varieties", { credentials: "include" })]); if (!catalogueResponse.ok || !varietiesResponse.ok) throw new Error(); setCultures(((await catalogueResponse.json()) as { data: CultureCatalogEntry[] }).data); setVarieties(((await varietiesResponse.json()) as { data: VarietyDto[] }).data); } catch { setFailed(true); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => { const needle = query.trim().toLocaleLowerCase(locale); return needle ? cultures.filter(({ id, sourceName }) => `${id} ${sourceName}`.toLocaleLowerCase(locale).includes(needle)) : cultures; }, [cultures, locale, query]);
  const names = useMemo(() => new Map<string, string>(cultures.map((culture) => [culture.id, culture.sourceName])), [cultures]);
  let content;
  if (loading) content = <div className="module-state"><span className="spinner" /></div>;
  else if (failed) content = <div className="module-state error-state"><p>{t.loadError}</p><button onClick={() => void load()}>{t.search}</button></div>;
  else if (tab === "lifecycle") content = <CropLifecyclePanel />;
  else if (tab === "cultures") content = <><div className="catalogue-toolbar"><label><span>{t.search}</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.search}/></label><b>{formatCount(t.records, filtered.length, locale)}</b></div><aside className="catalogue-notice"><strong>{t.provenance}</strong><p>{t.sourceNotice} {t.duplicateRemoved}</p></aside>{filtered.length ? <div className="culture-grid">{filtered.map((culture) => <article key={culture.id}><code>{culture.id}</code><h3>{culture.sourceName}</h3><span>{t.sourceDesignation}</span></article>)}</div> : <div className="module-state"><p>{t.emptySearch}</p></div>}</>;
  else content = varieties.length ? <div className="holdings-table variety-table"><div className="holdings-head"><span>{t.varietyName}</span><span>{t.crop}</span></div>{varieties.map((variety) => <div className="holding-row" key={variety.id}><b>{variety.name}</b><span>{names.get(variety.cultureId)}</span></div>)}</div> : <div className="module-state"><p>{t.emptyVarieties}</p>{canWrite && <button className="primary-action" onClick={() => setAdding(true)}>＋ {t.addVariety}</button>}</div>;
  return <><section className="page-heading"><div><p>{t.kicker}</p><h1>{t.title}</h1><span>{t.description}</span></div>{tab === "varieties" && <button className="primary-action" disabled={!canWrite} onClick={() => setAdding(true)}>＋ {t.addVariety}</button>}</section><section className="section-tabs territory-tabs"><button className={tab === "cultures" ? "active" : ""} onClick={() => setTab("cultures")}>{t.cultures}</button><button className={tab === "varieties" ? "active" : ""} onClick={() => setTab("varieties")}>{t.varieties}</button><button className={tab === "lifecycle" ? "active" : ""} onClick={() => setTab("lifecycle")}>{lifecycle.plantations}</button></section><section className="panel crop-panel">{content}</section>{adding && canWrite && <VarietyDialog cultures={cultures} onClose={() => setAdding(false)} onSaved={async () => { setAdding(false); await load(); }} />}</>;
}

function VarietyDialog({ cultures, onClose, onSaved }: { cultures: readonly CultureCatalogEntry[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const { locale } = useI18n(); const t = cropCopies[locale]; const [cultureId, setCultureId] = useState<string>(cultures[0]?.id || ""); const [name, setName] = useState(""); const [saving, setSaving] = useState(false); const [failed, setFailed] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setFailed(false); try { const response = await fetch("/api/farm/varieties", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ cultureId, name }) }); if (!response.ok) throw new Error(); await onSaved(); } catch { setFailed(true); setSaving(false); } }
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section className="holding-dialog"><header><div><p>{t.kicker}</p><h2>{t.addVariety}</h2></div><button onClick={onClose} aria-label={t.cancel}>×</button></header><form className="holding-form" onSubmit={(event) => void submit(event)}><label><span>{t.crop}</span><select required value={cultureId} onChange={(event) => setCultureId(event.target.value)}>{cultures.map((culture) => <option key={culture.id} value={culture.id}>{culture.sourceName}</option>)}</select><small>{t.sourceDesignation}</small></label><label><span>{t.varietyName}</span><input required maxLength={160} value={name} onChange={(event) => setName(event.target.value)}/><small>{t.customValueNotice}</small></label>{failed && <p className="form-error">{t.saveError}</p>}<footer><button type="button" className="subtle-button" onClick={onClose}>{t.cancel}</button><button className="primary-action" disabled={saving}>{t.save}</button></footer></form></section></div>;
}
