import type { SupportedLocale } from "../../home-copy";

export type SettingsCopy = {
  subtitle: string; centralNotice: string; name: string; email: string; status: string; profile: string;
  manageProfile: string; manageSecurity: string; membership: string; manageOrganization: string;
  administration: string; openAdministration: string; accessMode: string; permissions: string;
  permissionCount: string; write: string; export: string; subscription: string; modules: string;
  enabled: string; notEnabled: string; noSubscription: string; none: string; languageDescription: string;
  saveLanguage: string; saving: string; saved: string; saveError: string; opensCore: string;
  temporary: string; permanent: string; expires: string; full: string; readOnly: string; denied: string;
  active: string; inactive: string; limits: string;
};

const c = (...v: string[]): SettingsCopy => {
  const [subtitle, centralNotice, name, email, status, profile, manageProfile, manageSecurity, membership,
    manageOrganization, administration, openAdministration, accessMode, permissions, permissionCount,
    write, exportLabel, subscription, modules, enabled, notEnabled, noSubscription, none, languageDescription,
    saveLanguage, saving, saved, saveError, opensCore, temporary, permanent, expires, full, readOnly, denied,
    active, inactive, limits] = v;
  return { subtitle, centralNotice, name, email, status, profile, manageProfile, manageSecurity, membership,
    manageOrganization, administration, openAdministration, accessMode, permissions, permissionCount,
    write, export: exportLabel, subscription, modules, enabled, notEnabled, noSubscription, none,
    languageDescription, saveLanguage, saving, saved, saveError, opensCore, temporary, permanent, expires,
    full, readOnly, denied, active, inactive, limits };
};

export const settingsCopies: Record<SupportedLocale, SettingsCopy> = {
  "pt-PT": c("Consulte o acesso atual e gira no Gero Core os dados que são centrais.", "Conta, organização, segurança, subscrição e permissões permanecem fontes oficiais no Gero Core.", "Nome", "E-mail", "Estado", "Perfil na aplicação", "Gerir perfil", "Gerir segurança", "Vínculo", "Gerir organização", "Administração central", "Abrir administração", "Modo de acesso", "Permissões", "{count} permissões", "Escrita", "Exportação", "Subscrição", "Módulos", "Ativo", "Não ativo", "Sem subscrição", "Nenhum", "A escolha é guardada no seu perfil central e aplicada a todas as superfícies Gero compatíveis.", "Guardar idioma", "A guardar…", "Idioma guardado.", "Não foi possível guardar o idioma. Tente novamente.", "Abre o Gero Core", "Temporário", "Permanente", "Termina em {date}", "Completo", "Apenas consulta", "Negado", "Ativo", "Inativo", "Limites"),
  "pt-BR": c("Consulte o acesso atual e gerencie no Gero Core os dados que são centrais.", "Conta, organização, segurança, assinatura e permissões continuam sendo fontes oficiais do Gero Core.", "Nome", "E-mail", "Status", "Perfil no aplicativo", "Gerenciar perfil", "Gerenciar segurança", "Vínculo", "Gerenciar organização", "Administração central", "Abrir administração", "Modo de acesso", "Permissões", "{count} permissões", "Gravação", "Exportação", "Assinatura", "Módulos", "Ativo", "Não ativo", "Sem assinatura", "Nenhum", "A escolha é salva no seu perfil central e aplicada a todas as interfaces Gero compatíveis.", "Salvar idioma", "Salvando…", "Idioma salvo.", "Não foi possível salvar o idioma. Tente novamente.", "Abre o Gero Core", "Temporário", "Permanente", "Termina em {date}", "Completo", "Somente leitura", "Negado", "Ativo", "Inativo", "Limites"),
  en: c("Review current access and manage central data in Gero Core.", "Account, organisation, security, subscription and permissions remain authoritative in Gero Core.", "Name", "Email", "Status", "Application profile", "Manage profile", "Manage security", "Membership", "Manage organisation", "Central administration", "Open administration", "Access mode", "Permissions", "{count} permissions", "Write", "Export", "Subscription", "Modules", "Enabled", "Not enabled", "No subscription", "None", "Your choice is saved to your central profile and applied to all compatible Gero surfaces.", "Save language", "Saving…", "Language saved.", "The language could not be saved. Please try again.", "Opens Gero Core", "Temporary", "Permanent", "Ends on {date}", "Full", "Read only", "Denied", "Active", "Inactive", "Limits"),
  fr: c("Consultez l’accès actuel et gérez les données centrales dans Gero Core.", "Le compte, l’organisation, la sécurité, l’abonnement et les autorisations restent gérés par Gero Core.", "Nom", "E-mail", "État", "Profil d’application", "Gérer le profil", "Gérer la sécurité", "Adhésion", "Gérer l’organisation", "Administration centrale", "Ouvrir l’administration", "Mode d’accès", "Autorisations", "{count} autorisations", "Écriture", "Exportation", "Abonnement", "Modules", "Activé", "Non activé", "Aucun abonnement", "Aucun", "Votre choix est enregistré dans votre profil central et appliqué aux interfaces Gero compatibles.", "Enregistrer la langue", "Enregistrement…", "Langue enregistrée.", "Impossible d’enregistrer la langue. Veuillez réessayer.", "Ouvre Gero Core", "Temporaire", "Permanent", "Se termine le {date}", "Complet", "Lecture seule", "Refusé", "Actif", "Inactif", "Limites"),
  es: c("Consulte el acceso actual y gestione en Gero Core los datos centrales.", "La cuenta, la organización, la seguridad, la suscripción y los permisos siguen teniendo su fuente oficial en Gero Core.", "Nombre", "Correo electrónico", "Estado", "Perfil de la aplicación", "Gestionar perfil", "Gestionar seguridad", "Membresía", "Gestionar organización", "Administración central", "Abrir administración", "Modo de acceso", "Permisos", "{count} permisos", "Escritura", "Exportación", "Suscripción", "Módulos", "Activo", "No activo", "Sin suscripción", "Ninguno", "La elección se guarda en su perfil central y se aplica a todas las interfaces Gero compatibles.", "Guardar idioma", "Guardando…", "Idioma guardado.", "No se pudo guardar el idioma. Inténtelo de nuevo.", "Abre Gero Core", "Temporal", "Permanente", "Finaliza el {date}", "Completo", "Solo lectura", "Denegado", "Activo", "Inactivo", "Límites"),
  nl: c("Bekijk de huidige toegang en beheer centrale gegevens in Gero Core.", "Account, organisatie, beveiliging, abonnement en rechten blijven leidend in Gero Core.", "Naam", "E-mailadres", "Status", "Toepassingsprofiel", "Profiel beheren", "Beveiliging beheren", "Lidmaatschap", "Organisatie beheren", "Centraal beheer", "Beheer openen", "Toegangsmodus", "Rechten", "{count} rechten", "Schrijven", "Exporteren", "Abonnement", "Modules", "Actief", "Niet actief", "Geen abonnement", "Geen", "Uw keuze wordt in uw centrale profiel opgeslagen en op alle compatibele Gero-omgevingen toegepast.", "Taal opslaan", "Opslaan…", "Taal opgeslagen.", "De taal kon niet worden opgeslagen. Probeer het opnieuw.", "Opent Gero Core", "Tijdelijk", "Permanent", "Eindigt op {date}", "Volledig", "Alleen-lezen", "Geweigerd", "Actief", "Inactief", "Limieten"),
  de: c("Prüfen Sie den aktuellen Zugriff und verwalten Sie zentrale Daten in Gero Core.", "Konto, Organisation, Sicherheit, Abonnement und Berechtigungen bleiben in Gero Core maßgeblich.", "Name", "E-Mail", "Status", "Anwendungsprofil", "Profil verwalten", "Sicherheit verwalten", "Mitgliedschaft", "Organisation verwalten", "Zentrale Verwaltung", "Verwaltung öffnen", "Zugriffsmodus", "Berechtigungen", "{count} Berechtigungen", "Schreiben", "Export", "Abonnement", "Module", "Aktiv", "Nicht aktiv", "Kein Abonnement", "Keine", "Ihre Auswahl wird im zentralen Profil gespeichert und auf alle kompatiblen Gero-Oberflächen angewendet.", "Sprache speichern", "Wird gespeichert…", "Sprache gespeichert.", "Die Sprache konnte nicht gespeichert werden. Versuchen Sie es erneut.", "Öffnet Gero Core", "Befristet", "Dauerhaft", "Endet am {date}", "Vollständig", "Nur Lesen", "Verweigert", "Aktiv", "Inaktiv", "Grenzwerte"),
  ja: c("現在のアクセスを確認し、中央データは Gero Core で管理します。", "アカウント、組織、セキュリティ、契約、権限の正本は Gero Core にあります。", "名前", "メールアドレス", "状態", "アプリケーションプロファイル", "プロファイルを管理", "セキュリティを管理", "所属", "組織を管理", "中央管理", "管理画面を開く", "アクセスモード", "権限", "権限 {count} 件", "書き込み", "エクスポート", "契約", "モジュール", "有効", "無効", "契約なし", "なし", "選択した言語は中央プロファイルに保存され、対応するすべての Gero 画面に適用されます。", "言語を保存", "保存中…", "言語を保存しました。", "言語を保存できませんでした。もう一度お試しください。", "Gero Core を開きます", "一時的", "恒久的", "{date} に終了", "完全", "読み取り専用", "拒否", "有効", "無効", "上限"),
  he: c("בדיקת הגישה הנוכחית וניהול הנתונים המרכזיים ב-Gero Core.", "החשבון, הארגון, האבטחה, המינוי וההרשאות מנוהלים כמקור מוסמך ב-Gero Core.", "שם", "דוא״ל", "מצב", "פרופיל ביישום", "ניהול פרופיל", "ניהול אבטחה", "חברות", "ניהול ארגון", "ניהול מרכזי", "פתיחת הניהול", "מצב גישה", "הרשאות", "{count} הרשאות", "כתיבה", "ייצוא", "מינוי", "מודולים", "פעיל", "לא פעיל", "ללא מינוי", "ללא", "הבחירה נשמרת בפרופיל המרכזי ומוחלת על כל ממשקי Gero התואמים.", "שמירת שפה", "בשמירה…", "השפה נשמרה.", "לא ניתן לשמור את השפה. נסו שוב.", "פותח את Gero Core", "זמני", "קבוע", "מסתיים ב-{date}", "מלא", "קריאה בלבד", "נדחה", "פעיל", "לא פעיל", "מגבלות"),
  tr: c("Mevcut erişimi inceleyin ve merkezi verileri Gero Core’da yönetin.", "Hesap, kuruluş, güvenlik, abonelik ve izinlerin yetkili kaynağı Gero Core’dur.", "Ad", "E-posta", "Durum", "Uygulama profili", "Profili yönet", "Güvenliği yönet", "Üyelik", "Kuruluşu yönet", "Merkezi yönetim", "Yönetimi aç", "Erişim modu", "İzinler", "{count} izin", "Yazma", "Dışa aktarma", "Abonelik", "Modüller", "Etkin", "Etkin değil", "Abonelik yok", "Yok", "Seçiminiz merkezi profilinize kaydedilir ve uyumlu tüm Gero arayüzlerine uygulanır.", "Dili kaydet", "Kaydediliyor…", "Dil kaydedildi.", "Dil kaydedilemedi. Lütfen tekrar deneyin.", "Gero Core’u açar", "Geçici", "Kalıcı", "{date} tarihinde sona erer", "Tam", "Salt okunur", "Reddedildi", "Etkin", "Etkin değil", "Sınırlar"),
  ar: c("راجع صلاحية الوصول الحالية وأدر البيانات المركزية في Gero Core.", "يبقى الحساب والمنظمة والأمان والاشتراك والأذونات في Gero Core هي المصدر المعتمد.", "الاسم", "البريد الإلكتروني", "الحالة", "ملف التطبيق", "إدارة الملف الشخصي", "إدارة الأمان", "العضوية", "إدارة المنظمة", "الإدارة المركزية", "فتح الإدارة", "وضع الوصول", "الأذونات", "{count} أذونات", "الكتابة", "التصدير", "الاشتراك", "الوحدات", "مفعّل", "غير مفعّل", "لا يوجد اشتراك", "لا يوجد", "يُحفظ اختيارك في ملفك المركزي ويُطبّق على جميع واجهات Gero المتوافقة.", "حفظ اللغة", "جارٍ الحفظ…", "تم حفظ اللغة.", "تعذر حفظ اللغة. يرجى المحاولة مرة أخرى.", "يفتح Gero Core", "مؤقت", "دائم", "ينتهي في {date}", "كامل", "للقراءة فقط", "مرفوض", "نشط", "غير نشط", "الحدود"),
  pl: c("Sprawdź bieżący dostęp i zarządzaj danymi centralnymi w Gero Core.", "Konto, organizacja, bezpieczeństwo, subskrypcja i uprawnienia mają oficjalne źródło w Gero Core.", "Nazwa", "E-mail", "Stan", "Profil aplikacji", "Zarządzaj profilem", "Zarządzaj bezpieczeństwem", "Członkostwo", "Zarządzaj organizacją", "Administracja centralna", "Otwórz administrację", "Tryb dostępu", "Uprawnienia", "Liczba uprawnień: {count}", "Zapis", "Eksport", "Subskrypcja", "Moduły", "Włączony", "Niewłączony", "Brak subskrypcji", "Brak", "Wybór jest zapisywany w profilu centralnym i stosowany we wszystkich zgodnych interfejsach Gero.", "Zapisz język", "Zapisywanie…", "Język zapisany.", "Nie udało się zapisać języka. Spróbuj ponownie.", "Otwiera Gero Core", "Tymczasowy", "Stały", "Wygasa {date}", "Pełny", "Tylko odczyt", "Odmowa", "Aktywny", "Nieaktywny", "Limity"),
  hr: c("Pregledajte trenutačni pristup i upravljajte središnjim podacima u Gero Coreu.", "Račun, organizacija, sigurnost, pretplata i dopuštenja ostaju mjerodavni u Gero Coreu.", "Ime", "E-pošta", "Status", "Profil aplikacije", "Upravljaj profilom", "Upravljaj sigurnošću", "Članstvo", "Upravljaj organizacijom", "Središnja administracija", "Otvori administraciju", "Način pristupa", "Dopuštenja", "Dopuštenja: {count}", "Pisanje", "Izvoz", "Pretplata", "Moduli", "Aktivno", "Nije aktivno", "Nema pretplate", "Nema", "Odabir se sprema u središnji profil i primjenjuje na sva kompatibilna Gero sučelja.", "Spremi jezik", "Spremanje…", "Jezik je spremljen.", "Jezik nije moguće spremiti. Pokušajte ponovno.", "Otvara Gero Core", "Privremeno", "Trajno", "Istječe {date}", "Potpuno", "Samo čitanje", "Odbijeno", "Aktivno", "Neaktivno", "Ograničenja"),
  el: c("Ελέγξτε την τρέχουσα πρόσβαση και διαχειριστείτε τα κεντρικά δεδομένα στο Gero Core.", "Ο λογαριασμός, ο οργανισμός, η ασφάλεια, η συνδρομή και τα δικαιώματα έχουν ως επίσημη πηγή το Gero Core.", "Όνομα", "Ηλεκτρονική διεύθυνση", "Κατάσταση", "Προφίλ εφαρμογής", "Διαχείριση προφίλ", "Διαχείριση ασφάλειας", "Ιδιότητα μέλους", "Διαχείριση οργανισμού", "Κεντρική διαχείριση", "Άνοιγμα διαχείρισης", "Λειτουργία πρόσβασης", "Δικαιώματα", "{count} δικαιώματα", "Εγγραφή", "Εξαγωγή", "Συνδρομή", "Ενότητες", "Ενεργό", "Μη ενεργό", "Χωρίς συνδρομή", "Κανένα", "Η επιλογή αποθηκεύεται στο κεντρικό προφίλ και εφαρμόζεται σε όλες τις συμβατές επιφάνειες Gero.", "Αποθήκευση γλώσσας", "Αποθήκευση…", "Η γλώσσα αποθηκεύτηκε.", "Δεν ήταν δυνατή η αποθήκευση της γλώσσας. Δοκιμάστε ξανά.", "Ανοίγει το Gero Core", "Προσωρινό", "Μόνιμο", "Λήγει στις {date}", "Πλήρης", "Μόνο ανάγνωση", "Απορρίφθηκε", "Ενεργό", "Ανενεργό", "Όρια"),
  sv: c("Granska aktuell åtkomst och hantera centrala uppgifter i Gero Core.", "Konto, organisation, säkerhet, abonnemang och behörigheter förblir styrande i Gero Core.", "Namn", "E-post", "Status", "Programprofil", "Hantera profil", "Hantera säkerhet", "Medlemskap", "Hantera organisation", "Central förvaltning", "Öppna administration", "Åtkomstläge", "Behörigheter", "{count} behörigheter", "Skrivning", "Export", "Abonnemang", "Moduler", "Aktiv", "Inte aktiv", "Inget abonnemang", "Inga", "Valet sparas i din centrala profil och används på alla kompatibla Gero-gränssnitt.", "Spara språk", "Sparar…", "Språket har sparats.", "Språket kunde inte sparas. Försök igen.", "Öppnar Gero Core", "Tillfällig", "Permanent", "Upphör {date}", "Fullständig", "Endast läsning", "Nekad", "Aktiv", "Inaktiv", "Gränser"),
  no: c("Se gjennom gjeldende tilgang og administrer sentrale data i Gero Core.", "Konto, organisasjon, sikkerhet, abonnement og tillatelser har fortsatt Gero Core som offisiell kilde.", "Navn", "E-post", "Status", "Applikasjonsprofil", "Administrer profil", "Administrer sikkerhet", "Medlemskap", "Administrer organisasjon", "Sentral administrasjon", "Åpne administrasjon", "Tilgangsmodus", "Tillatelser", "{count} tillatelser", "Skriving", "Eksport", "Abonnement", "Moduler", "Aktiv", "Ikke aktiv", "Intet abonnement", "Ingen", "Valget lagres i den sentrale profilen og brukes på alle kompatible Gero-grensesnitt.", "Lagre språk", "Lagrer…", "Språket er lagret.", "Språket kunne ikke lagres. Prøv igjen.", "Åpner Gero Core", "Midlertidig", "Permanent", "Utløper {date}", "Full", "Bare lesing", "Avvist", "Aktiv", "Inaktiv", "Grenser"),
  da: c("Gennemgå den aktuelle adgang, og administrer centrale data i Gero Core.", "Konto, organisation, sikkerhed, abonnement og tilladelser har fortsat Gero Core som officiel kilde.", "Navn", "E-mail", "Status", "Applikationsprofil", "Administrer profil", "Administrer sikkerhed", "Medlemskab", "Administrer organisation", "Central forvaltning", "Åbn administration", "Adgangstilstand", "Tilladelser", "{count} tilladelser", "Skrivning", "Eksport", "Abonnement", "Moduler", "Aktiv", "Ikke aktiv", "Intet abonnement", "Ingen", "Dit valg gemmes i den centrale profil og anvendes på alle kompatible Gero-grænseflader.", "Gem sprog", "Gemmer…", "Sproget er gemt.", "Sproget kunne ikke gemmes. Prøv igen.", "Åbner Gero Core", "Midlertidig", "Permanent", "Udløber {date}", "Fuld", "Kun læsning", "Afvist", "Aktiv", "Inaktiv", "Grænser"),
  it: c("Controlla l’accesso attuale e gestisci i dati centrali in Gero Core.", "Account, organizzazione, sicurezza, abbonamento e autorizzazioni hanno in Gero Core la loro fonte ufficiale.", "Nome", "E-mail", "Stato", "Profilo applicazione", "Gestisci profilo", "Gestisci sicurezza", "Appartenenza", "Gestisci organizzazione", "Amministrazione centrale", "Apri amministrazione", "Modalità di accesso", "Autorizzazioni", "{count} autorizzazioni", "Scrittura", "Esportazione", "Abbonamento", "Moduli", "Attivo", "Non attivo", "Nessun abbonamento", "Nessuno", "La scelta viene salvata nel profilo centrale e applicata a tutte le interfacce Gero compatibili.", "Salva lingua", "Salvataggio…", "Lingua salvata.", "Impossibile salvare la lingua. Riprova.", "Apre Gero Core", "Temporaneo", "Permanente", "Termina il {date}", "Completo", "Sola lettura", "Negato", "Attivo", "Inattivo", "Limiti"),
  uk: c("Перегляньте поточний доступ і керуйте центральними даними в Gero Core.", "Обліковий запис, організація, безпека, підписка й дозволи мають офіційне джерело в Gero Core.", "Ім’я", "Електронна пошта", "Стан", "Профіль застосунку", "Керувати профілем", "Керувати безпекою", "Членство", "Керувати організацією", "Центральне адміністрування", "Відкрити адміністрування", "Режим доступу", "Дозволи", "Дозволів: {count}", "Запис", "Експорт", "Підписка", "Модулі", "Увімкнено", "Не ввімкнено", "Без підписки", "Немає", "Вибір зберігається в центральному профілі й застосовується до всіх сумісних інтерфейсів Gero.", "Зберегти мову", "Збереження…", "Мову збережено.", "Не вдалося зберегти мову. Спробуйте ще раз.", "Відкриває Gero Core", "Тимчасовий", "Постійний", "Завершується {date}", "Повний", "Лише читання", "Відмовлено", "Активний", "Неактивний", "Обмеження"),
  ro: c("Verificați accesul curent și gestionați datele centrale în Gero Core.", "Contul, organizația, securitatea, abonamentul și permisiunile sunt sursele oficiale în Gero Core.", "Nume", "E-mail", "Stare", "Profilul aplicației", "Gestionează profilul", "Gestionează securitatea", "Calitate de membru", "Gestionează organizația", "Administrare centrală", "Deschide administrarea", "Mod de acces", "Permisiuni", "{count} permisiuni", "Scriere", "Export", "Abonament", "Module", "Activ", "Inactiv", "Fără abonament", "Niciunul", "Alegerea este salvată în profilul central și aplicată tuturor interfețelor Gero compatibile.", "Salvează limba", "Se salvează…", "Limba a fost salvată.", "Limba nu a putut fi salvată. Încercați din nou.", "Deschide Gero Core", "Temporar", "Permanent", "Se încheie la {date}", "Complet", "Doar citire", "Refuzat", "Activ", "Inactiv", "Limite"),
  fi: c("Tarkista nykyinen käyttöoikeus ja hallitse keskitettyjä tietoja Gero Coressa.", "Tili, organisaatio, tietoturva, tilaus ja käyttöoikeudet pysyvät Gero Coren hallinnassa.", "Nimi", "Sähköposti", "Tila", "Sovellusprofiili", "Hallitse profiilia", "Hallitse tietoturvaa", "Jäsenyys", "Hallitse organisaatiota", "Keskitetty hallinta", "Avaa hallinta", "Käyttötila", "Oikeudet", "{count} oikeutta", "Kirjoitus", "Vienti", "Tilaus", "Moduulit", "Käytössä", "Ei käytössä", "Ei tilausta", "Ei mitään", "Valinta tallennetaan keskitettyyn profiiliin ja otetaan käyttöön kaikissa yhteensopivissa Gero-näkymissä.", "Tallenna kieli", "Tallennetaan…", "Kieli tallennettu.", "Kieltä ei voitu tallentaa. Yritä uudelleen.", "Avaa Gero Core -palvelun", "Väliaikainen", "Pysyvä", "Päättyy {date}", "Täysi", "Vain luku", "Estetty", "Aktiivinen", "Ei aktiivinen", "Rajat"),
  bg: c("Прегледайте текущия достъп и управлявайте централните данни в Gero Core.", "Акаунтът, организацията, сигурността, абонаментът и разрешенията имат официален източник в Gero Core.", "Име", "Имейл", "Състояние", "Профил на приложението", "Управление на профила", "Управление на сигурността", "Членство", "Управление на организацията", "Централна администрация", "Отваряне на администрацията", "Режим на достъп", "Разрешения", "{count} разрешения", "Запис", "Експорт", "Абонамент", "Модули", "Активен", "Неактивен", "Без абонамент", "Няма", "Изборът се запазва в централния профил и се прилага към всички съвместими интерфейси на Gero.", "Запазване на езика", "Запазване…", "Езикът е запазен.", "Езикът не можа да бъде запазен. Опитайте отново.", "Отваря Gero Core", "Временен", "Постоянен", "Приключва на {date}", "Пълен", "Само за четене", "Отказан", "Активен", "Неактивен", "Ограничения"),
  hu: c("Tekintse át a jelenlegi hozzáférést, és kezelje a központi adatokat a Gero Core-ban.", "A fiók, a szervezet, a biztonság, az előfizetés és a jogosultságok hiteles forrása a Gero Core.", "Név", "E-mail", "Állapot", "Alkalmazásprofil", "Profil kezelése", "Biztonság kezelése", "Tagság", "Szervezet kezelése", "Központi adminisztráció", "Adminisztráció megnyitása", "Hozzáférési mód", "Jogosultságok", "{count} jogosultság", "Írás", "Exportálás", "Előfizetés", "Modulok", "Aktív", "Nem aktív", "Nincs előfizetés", "Nincs", "A választást a központi profil menti, és minden kompatibilis Gero-felületen alkalmazza.", "Nyelv mentése", "Mentés…", "Nyelv mentve.", "A nyelv nem menthető. Próbálja újra.", "Megnyitja a Gero Core-t", "Ideiglenes", "Állandó", "Lejár: {date}", "Teljes", "Csak olvasás", "Elutasítva", "Aktív", "Inaktív", "Korlátok"),
  is: c("Farðu yfir núverandi aðgang og stjórnaðu miðlægum gögnum í Gero Core.", "Reikningur, stofnun, öryggi, áskrift og heimildir eiga áfram opinberan gagnagjafa í Gero Core.", "Nafn", "Netfang", "Staða", "Forritssnið", "Stjórna sniði", "Stjórna öryggi", "Aðild", "Stjórna stofnun", "Miðlæg stjórnun", "Opna stjórnun", "Aðgangshamur", "Heimildir", "{count} heimildir", "Skrifun", "Útflutningur", "Áskrift", "Einingar", "Virkt", "Ekki virkt", "Engin áskrift", "Ekkert", "Valið er vistað í miðlæga sniðinu og notað á öllum samhæfum Gero-viðmótum.", "Vista tungumál", "Vistar…", "Tungumál vistað.", "Ekki tókst að vista tungumálið. Reyndu aftur.", "Opnar Gero Core", "Tímabundið", "Varanlegt", "Lýkur {date}", "Fullt", "Aðeins lestur", "Hafnað", "Virkt", "Óvirkt", "Takmörk"),
  sk: c("Skontrolujte aktuálny prístup a spravujte centrálne údaje v Gero Core.", "Účet, organizácia, zabezpečenie, predplatné a oprávnenia majú oficiálny zdroj v Gero Core.", "Meno", "E-mail", "Stav", "Profil aplikácie", "Spravovať profil", "Spravovať zabezpečenie", "Členstvo", "Spravovať organizáciu", "Centrálna administrácia", "Otvoriť administráciu", "Režim prístupu", "Oprávnenia", "Počet oprávnení: {count}", "Zápis", "Export", "Predplatné", "Moduly", "Aktívne", "Neaktívne", "Bez predplatného", "Žiadne", "Výber sa uloží do centrálneho profilu a použije sa vo všetkých kompatibilných rozhraniach Gero.", "Uložiť jazyk", "Ukladá sa…", "Jazyk bol uložený.", "Jazyk sa nepodarilo uložiť. Skúste to znova.", "Otvorí Gero Core", "Dočasné", "Trvalé", "Končí {date}", "Úplný", "Len na čítanie", "Zamietnutý", "Aktívny", "Neaktívny", "Limity"),
  lt: c("Peržiūrėkite dabartinę prieigą ir tvarkykite centrinius duomenis „Gero Core“.", "Paskyra, organizacija, saugumas, prenumerata ir leidimai turi oficialų šaltinį „Gero Core“.", "Vardas", "El. paštas", "Būsena", "Programos profilis", "Tvarkyti profilį", "Tvarkyti saugumą", "Narystė", "Tvarkyti organizaciją", "Centrinis administravimas", "Atverti administravimą", "Prieigos režimas", "Leidimai", "Leidimų: {count}", "Rašymas", "Eksportas", "Prenumerata", "Moduliai", "Įjungta", "Neįjungta", "Nėra prenumeratos", "Nėra", "Pasirinkimas išsaugomas centriniame profilyje ir taikomas visose suderinamose „Gero“ sąsajose.", "Išsaugoti kalbą", "Išsaugoma…", "Kalba išsaugota.", "Kalbos išsaugoti nepavyko. Bandykite dar kartą.", "Atveria „Gero Core“", "Laikina", "Nuolatinė", "Baigiasi {date}", "Visa", "Tik skaityti", "Atmesta", "Aktyvi", "Neaktyvi", "Ribos"),
  sl: c("Preglejte trenutni dostop in upravljajte osrednje podatke v Gero Core.", "Račun, organizacija, varnost, naročnina in dovoljenja ostajajo merodajni v Gero Core.", "Ime", "E-pošta", "Stanje", "Profil aplikacije", "Upravljaj profil", "Upravljaj varnost", "Članstvo", "Upravljaj organizacijo", "Osrednje upravljanje", "Odpri upravljanje", "Način dostopa", "Dovoljenja", "Dovoljenja: {count}", "Pisanje", "Izvoz", "Naročnina", "Moduli", "Omogočeno", "Ni omogočeno", "Brez naročnine", "Nič", "Izbira se shrani v osrednji profil in uporabi v vseh združljivih vmesnikih Gero.", "Shrani jezik", "Shranjevanje…", "Jezik je shranjen.", "Jezika ni bilo mogoče shraniti. Poskusite znova.", "Odpre Gero Core", "Začasno", "Trajno", "Konča se {date}", "Polno", "Samo za branje", "Zavrnjeno", "Aktivno", "Neaktivno", "Omejitve"),
  lv: c("Pārskatiet pašreizējo piekļuvi un pārvaldiet centrālos datus Gero Core.", "Konts, organizācija, drošība, abonements un atļaujas oficiāli glabājas Gero Core kā vienīgajā avotā.", "Vārds", "E-pasts", "Statuss", "Lietotnes profils", "Pārvaldīt profilu", "Pārvaldīt drošību", "Dalība", "Pārvaldīt organizāciju", "Centrālā administrēšana", "Atvērt administrēšanu", "Piekļuves režīms", "Atļaujas", "Atļaujas: {count}", "Rakstīšana", "Eksports", "Abonements", "Moduļi", "Aktīvs", "Nav aktīvs", "Nav abonementa", "Nav", "Izvēle tiek saglabāta centrālajā profilā un piemērota visās saderīgajās Gero saskarnēs.", "Saglabāt valodu", "Saglabā…", "Valoda saglabāta.", "Valodu neizdevās saglabāt. Mēģiniet vēlreiz.", "Atver Gero Core", "Pagaidu", "Pastāvīgs", "Beidzas {date}", "Pilns", "Tikai lasīšana", "Noraidīts", "Aktīvs", "Neaktīvs", "Limiti"),
};

export function settingsMessage(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => String(values[key] ?? `{${key}}`));
}
