import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import area from "@turf/area";
import type { FarmHoldingDto } from "@shared/farm-holdings";
import { normalizeFarmHoldingCode } from "@shared/farm-holdings";
import type { FieldDto, FieldPolygon } from "@shared/fields";
import { normalizeFieldCode } from "@shared/fields";
import { useI18n } from "../../i18n";
import { farmHoldingCopies, type FarmHoldingCopy } from "./farm-holding-locales";
import { fieldCopies, type FieldCopy } from "./field-locales";
import { parseFieldFile, type ImportedFieldPolygon } from "./field-import";
import FieldMapEditor from "./FieldMapEditor";
import "./farm-holdings.css";

const defaultTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone || "Europe/Lisbon";

export default function FarmHoldingsModule() {
  const { locale } = useI18n(); const holdingCopy = farmHoldingCopies[locale]; const fieldCopy = fieldCopies[locale];
  const [holdings, setHoldings] = useState<FarmHoldingDto[]>([]); const [fields, setFields] = useState<FieldDto[]>([]); const [loading, setLoading] = useState(true); const [loadFailed, setLoadFailed] = useState(false); const [tab, setTab] = useState<"holdings" | "fields">("holdings"); const [editingHolding, setEditingHolding] = useState<FarmHoldingDto | null | undefined>(); const [editingField, setEditingField] = useState<FieldDto | null | undefined>();
  const load = useCallback(async () => { setLoading(true); setLoadFailed(false); try { const [holdingResponse, fieldResponse] = await Promise.all([fetch("/api/farm/holdings", { credentials: "include" }), fetch("/api/farm/fields", { credentials: "include" })]); if (!holdingResponse.ok || !fieldResponse.ok) throw new Error(); setHoldings(((await holdingResponse.json()) as { data: FarmHoldingDto[] }).data); setFields(((await fieldResponse.json()) as { data: FieldDto[] }).data); } catch { setLoadFailed(true); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); const activeHoldings = holdings.filter(({ status }) => status === "active");
  return <><section className="page-heading"><div><p>{holdingCopy.kicker}</p><h1>{tab === "holdings" ? holdingCopy.title : fieldCopy.fields}</h1><span>{tab === "holdings" ? holdingCopy.description : fieldCopy.importHint}</span></div><button className="primary-action" disabled={tab === "fields" && !activeHoldings.length} onClick={() => tab === "holdings" ? setEditingHolding(null) : setEditingField(null)}>＋ {tab === "holdings" ? holdingCopy.add : fieldCopy.add}</button></section><section className="section-tabs territory-tabs"><button className={tab === "holdings" ? "active" : ""} onClick={() => setTab("holdings")}>{holdingCopy.title}</button><button className={tab === "fields" ? "active" : ""} onClick={() => setTab("fields")}>{fieldCopy.fields}</button></section><section className="panel holdings-panel">{loading ? <ModuleState /> : loadFailed ? <div className="module-state error-state"><p>{tab === "holdings" ? holdingCopy.loadError : fieldCopy.loadError}</p><button onClick={() => void load()}>{holdingCopy.edit}</button></div> : tab === "holdings" ? <HoldingsList holdings={holdings} copy={holdingCopy} onAdd={() => setEditingHolding(null)} onEdit={setEditingHolding} /> : <FieldsList locale={locale} fields={fields} holdings={holdings} copy={fieldCopy} common={holdingCopy} onAdd={() => activeHoldings.length ? setEditingField(null) : setTab("holdings")} onEdit={setEditingField} />}</section>{editingHolding !== undefined && <HoldingDialog holding={editingHolding} copy={holdingCopy} onClose={() => setEditingHolding(undefined)} onSaved={async () => { setEditingHolding(undefined); await load(); }} />}{editingField !== undefined && <FieldDialog locale={locale} field={editingField} holdings={activeHoldings} copy={fieldCopy} common={holdingCopy} onClose={() => setEditingField(undefined)} onSaved={async () => { setEditingField(undefined); await load(); }} />}</>;
}

function ModuleState() { return <div className="module-state"><span className="spinner" /></div>; }
function HoldingsList({ holdings, copy: t, onAdd, onEdit }: { holdings: FarmHoldingDto[]; copy: FarmHoldingCopy; onAdd: () => void; onEdit: (holding: FarmHoldingDto) => void }) { return holdings.length === 0 ? <div className="module-state"><p>{t.empty}</p><button className="primary-action" onClick={onAdd}>＋ {t.add}</button></div> : <div className="holdings-table"><div className="holdings-head"><span>{t.name}</span><span>{t.code}</span><span>{t.timezone}</span><span>{t.status}</span><span /></div>{holdings.map((holding) => <div className="holding-row" key={holding.id}><span><b>{holding.name}</b></span><code>{holding.code}</code><span>{holding.timezone}</span><em className={holding.status}>{holding.status === "active" ? t.active : t.inactive}</em><button onClick={() => onEdit(holding)}>{t.edit}</button></div>)}</div>; }
function FieldsList({ locale, fields, holdings, copy: t, common, onAdd, onEdit }: { locale: string; fields: FieldDto[]; holdings: FarmHoldingDto[]; copy: FieldCopy; common: FarmHoldingCopy; onAdd: () => void; onEdit: (field: FieldDto) => void }) { const names = new Map(holdings.map((holding) => [holding.id, holding.name])); return fields.length === 0 ? <div className="module-state"><p>{holdings.length ? t.empty : common.empty}</p><button className="primary-action" onClick={onAdd}>＋ {holdings.length ? t.add : common.add}</button></div> : <div className="holdings-table fields-table"><div className="holdings-head"><span>{common.name}</span><span>{common.code}</span><span>{t.holding}</span><span>{t.usableArea}</span><span>{common.status}</span><span /></div>{fields.map((field) => <div className="holding-row" key={field.id}><span><b>{field.name}</b><small>{t.freeArea}: {field.freeAreaHa.toLocaleString(locale, { maximumFractionDigits: 4 })} ha</small></span><code>{field.code}</code><span>{names.get(field.holdingId)}</span><span>{field.usableAreaHa.toLocaleString(locale, { maximumFractionDigits: 4 })} ha</span><em className={field.status}>{field.status === "active" ? common.active : common.inactive}</em><button onClick={() => onEdit(field)}>{common.edit}</button></div>)}</div>; }

function HoldingDialog({ holding, copy: t, onClose, onSaved }: { holding: FarmHoldingDto | null; copy: FarmHoldingCopy; onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(holding?.name || ""); const [code, setCode] = useState(holding?.code || ""); const [timezone, setTimezone] = useState(holding?.timezone || defaultTimezone); const [status, setStatus] = useState(holding?.status || "active"); const [saving, setSaving] = useState(false); const [saveFailed, setSaveFailed] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setSaveFailed(false); try { const response = await fetch(holding ? `/api/farm/holdings/${holding.id}` : "/api/farm/holdings", { method: holding ? "PATCH" : "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, code, timezone, ...(holding ? { status } : {}) }) }); if (!response.ok) throw new Error(); await onSaved(); } catch { setSaveFailed(true); setSaving(false); } }
  return <DialogFrame title={holding ? t.edit : t.add} kicker={t.kicker} cancel={t.cancel} onClose={onClose}><form className="holding-form" onSubmit={(event) => void submit(event)}><TextField label={t.name} value={name} onChange={setName} minLength={2} maxLength={160}/><TextField label={t.code} value={code} onChange={(value) => setCode(normalizeFarmHoldingCode(value))} minLength={2} maxLength={12} hint={t.codeHint}/><TextField label={t.timezone} value={timezone} onChange={setTimezone} maxLength={64}/>{holding && <SelectField label={t.status} value={status} onChange={(value) => setStatus(value as FarmHoldingDto["status"])} options={[["active", t.active], ["inactive", t.inactive]]}/>} {saveFailed && <p className="form-error">{t.saveError}</p>}<FormActions cancel={t.cancel} save={t.save} saving={saving} onClose={onClose}/></form></DialogFrame>;
}

function FieldDialog({ locale, field, holdings, copy: t, common, onClose, onSaved }: { locale: string; field: FieldDto | null; holdings: FarmHoldingDto[]; copy: FieldCopy; common: FarmHoldingCopy; onClose: () => void; onSaved: () => Promise<void> }) {
  const [holdingId, setHoldingId] = useState(field?.holdingId || holdings[0]?.id || ""); const [name, setName] = useState(field?.name || ""); const [code, setCode] = useState(field?.code || ""); const [usableArea, setUsableArea] = useState(field ? String(field.usableAreaHa) : ""); const [manuallyClosed, setManuallyClosed] = useState(field?.manuallyClosed || false); const [status, setStatus] = useState(field?.status || "active"); const [geometry, setGeometry] = useState<FieldPolygon | null>(field?.geometry || null); const [imports, setImports] = useState<ImportedFieldPolygon[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<"geometry" | "overlap" | "file" | "save" | "">(""); const mappedArea = geometry ? area({ type: "Feature", properties: {}, geometry }) / 10_000 : 0;
  async function importFile(file?: File) { if (!file) return; try { const next = await parseFieldFile(file); if (!next.length) throw new Error(); setImports(next); setGeometry(next[0].geometry); setError(""); } catch { setError("file"); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!geometry) { setError("geometry"); return; } setSaving(true); setError(""); try { const response = await fetch(field ? `/api/farm/fields/${field.id}` : "/api/farm/fields", { method: field ? "PATCH" : "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ holdingId, name, code: normalizeFieldCode(code), geometry, ...(usableArea ? { usableAreaHa: Number(usableArea) } : {}), manuallyClosed, ...(field ? { status } : {}) }) }); if (!response.ok) { const body = await response.json().catch(() => null) as { code?: string } | null; setError(body?.code === "FIELD_GEOMETRY_OVERLAP" ? "overlap" : "save"); setSaving(false); return; } await onSaved(); } catch { setError("save"); setSaving(false); } }
  const normalizeInput = (value: string) => value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 4);
  return <DialogFrame wide title={field ? common.edit : t.add} kicker={t.fields} cancel={common.cancel} onClose={onClose}><form className="holding-form field-form" onSubmit={(event) => void submit(event)}><div className="field-form-grid"><div className="field-details"><SelectField label={t.holding} value={holdingId} onChange={setHoldingId} options={holdings.map((holding) => [holding.id, holding.name])}/><TextField label={common.name} value={name} onChange={setName} minLength={2} maxLength={160}/><TextField label={common.code} value={code} onChange={(value) => setCode(normalizeInput(value))} onBlur={() => setCode(normalizeFieldCode(code))} minLength={1} maxLength={4} hint="A1 → 00A1 · 0MIX" disabled={Boolean(field?.codeLocked)}/><TextField label={`${t.usableArea} (ha)`} value={usableArea} onChange={setUsableArea} type="number" step="0.0001" hint={mappedArea ? `${t.totalArea}: ${mappedArea.toLocaleString(locale, { maximumFractionDigits: 4 })} ha` : undefined}/><label className="check-field"><input type="checkbox" checked={manuallyClosed} onChange={(event) => setManuallyClosed(event.target.checked)}/><span>{t.manuallyClosed}</span></label>{field && <SelectField label={common.status} value={status} onChange={(value) => setStatus(value as FieldDto["status"])} options={[["active", common.active], ["inactive", common.inactive]]}/>}<label className="file-field"><span>{t.import}</span><input type="file" accept=".kml,.kmz,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kmz" onChange={(event) => void importFile(event.target.files?.[0])}/><small>{t.importHint}</small></label>{imports.length > 1 && <SelectField label={t.choosePolygon} value={String(imports.findIndex((item) => item.geometry === geometry))} onChange={(value) => setGeometry(imports[Number(value)].geometry)} options={imports.map((item, index) => [String(index), item.name])}/>}</div><FieldMapEditor geometry={geometry} onChange={setGeometry} copy={t}/></div>{error && <p className="form-error">{error === "geometry" ? t.geometryRequired : error === "overlap" ? t.overlapError : error === "file" ? t.invalidFile : t.saveError}</p>}<FormActions cancel={common.cancel} save={t.save} saving={saving} onClose={onClose}/></form></DialogFrame>;
}

function DialogFrame({ title, kicker, cancel, onClose, wide, children }: { title: string; kicker: string; cancel: string; onClose: () => void; wide?: boolean; children: ReactNode }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={`holding-dialog ${wide ? "field-dialog" : ""}`}><header><div><p>{kicker}</p><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label={cancel}>×</button></header>{children}</section></div>; }
function TextField({ label, value, onChange, onBlur, hint, type = "text", disabled, ...props }: { label: string; value: string; onChange: (value: string) => void; onBlur?: () => void; hint?: string; type?: string; disabled?: boolean; minLength?: number; maxLength?: number; step?: string }) { return <label><span>{label}</span><input required type={type} disabled={disabled} value={value} onChange={(event) => onChange(event.target.value)} onBlur={onBlur} {...props}/>{hint && <small>{hint}</small>}</label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <label><span>{label}</span><select required value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([optionValue, label]) => <option value={optionValue} key={optionValue}>{label}</option>)}</select></label>; }
function FormActions({ cancel, save, saving, onClose }: { cancel: string; save: string; saving: boolean; onClose: () => void }) { return <footer><button type="button" className="subtle-button" onClick={onClose}>{cancel}</button><button className="primary-action" disabled={saving}>{save}</button></footer>; }
