import { writeFile } from "node:fs/promises";
import { operationCopies } from "../client/src/app/operations/operation-locales.generated";
import { supportedLocales, type SupportedLocale } from "../client/src/home-copy";

const en = { soilActions: "Soil preparation actions", customAction: "Other action", addAction: "Add action", depthCm: "Working depth (cm)", passes: "Number of passes", soilCondition: "Soil condition", residueDestination: "Crop residue destination", dry: "Dry", moist: "Moist", wet: "Wet", left: "Left on the soil", shredded: "Shredded", incorporated: "Incorporated", removed: "Removed", burned: "Burned", actionSubsoiling: "Subsoiling", actionPloughing: "Ploughing", actionScarifying: "Soil scarification", actionHarrowing: "Harrowing", actionRotaryTilling: "Rotary cultivation", actionLevelling: "Land levelling", actionBedForming: "Raised-bed forming", actionFurrowOpening: "Furrow opening", actionStoneRemoval: "Stone clearing", actionResidueShredding: "Crop residue shredding", actionResidueIncorporation: "Crop residue incorporation", actionSolarisation: "Soil solarisation" };
const pt = { soilActions: "Ações de preparação do solo", customAction: "Outra ação", addAction: "Adicionar ação", depthCm: "Profundidade de trabalho (cm)", passes: "Número de passagens", soilCondition: "Condição do solo", residueDestination: "Destino dos resíduos da cultura", dry: "Seco", moist: "Húmido", wet: "Encharcado", left: "Deixados no solo", shredded: "Triturados", incorporated: "Incorporados", removed: "Retirados", burned: "Queimados", actionSubsoiling: "Subsolagem", actionPloughing: "Lavoura", actionScarifying: "Escarificação", actionHarrowing: "Gradagem", actionRotaryTilling: "Fresagem", actionLevelling: "Nivelamento", actionBedForming: "Formação de camalhões", actionFurrowOpening: "Abertura de regos", actionStoneRemoval: "Despedrega", actionResidueShredding: "Trituração de resíduos", actionResidueIncorporation: "Incorporação de resíduos", actionSolarisation: "Solarização do solo" } satisfies typeof en;
const targets: Record<Exclude<SupportedLocale, "en" | "pt-PT">, string> = { "pt-BR": "pt", fr: "fr", es: "es", nl: "nl", de: "de", ja: "ja", he: "iw", tr: "tr", ar: "ar", pl: "pl", hr: "hr", el: "el", sv: "sv", no: "no", da: "da", it: "it", uk: "uk", ro: "ro", fi: "fi", bg: "bg", hu: "hu", is: "is", sk: "sk", lt: "lt", sl: "sl", lv: "lv" };
async function translate(locale: Exclude<SupportedLocale, "en" | "pt-PT">) { const keys = Object.keys(en) as Array<keyof typeof en>; const payload = keys.map((key, index) => `ZXQSEG${index}QXZ\n${en[key]}`).join("\n"); const body = new URLSearchParams({ client: "gtx", sl: "en", tl: targets[locale], dt: "t", q: payload }); for (let attempt = 1; attempt <= 5; attempt++) { const response = await fetch("https://translate.googleapis.com/translate_a/single", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded;charset=UTF-8" }, body, signal: AbortSignal.timeout(40000) }); if (response.ok) { const data = await response.json() as Array<Array<Array<string>>>; const text = data[0].map((segment) => segment[0]).join(""); const markers = [...text.matchAll(/ZXQSEG(\d+)QXZ\s*/g)]; if (markers.length !== keys.length) throw new Error(`${locale}:segments:${markers.length}`); return Object.fromEntries(keys.map((key, index) => [key, text.slice(markers[index].index! + markers[index][0].length, markers[index + 1]?.index ?? text.length).trim()])) as typeof en; } if (response.status !== 429 || attempt === 5) throw new Error(`${locale}:${response.status}`); await new Promise((resolve) => setTimeout(resolve, attempt * 1500)); } throw new Error(`${locale}:unreachable`); }
const result: Record<string, Record<string, string>> = structuredClone(operationCopies);
for (const locale of supportedLocales) { const extra = locale === "en" ? en : locale === "pt-PT" ? pt : await translate(locale); Object.assign(result[locale], extra); await new Promise((resolve) => setTimeout(resolve, 500)); }
Object.assign(result["pt-BR"], { soilActions: "Ações de preparo do solo", actionPloughing: "Aração", actionHarrowing: "Gradagem", actionRotaryTilling: "Fresagem", actionBedForming: "Formação de canteiros", actionFurrowOpening: "Abertura de sulcos", actionStoneRemoval: "Retirada de pedras", wet: "Encharcado" });
Object.assign(result.es, { actionPloughing: "Arado", actionHarrowing: "Rastreo", actionRotaryTilling: "Fresado", actionBedForming: "Formación de caballones", actionFurrowOpening: "Apertura de surcos", actionStoneRemoval: "Despedregado" });
Object.assign(result.fr, { actionPloughing: "Labour", actionHarrowing: "Hersage", actionRotaryTilling: "Fraisage", actionBedForming: "Formation de billons", actionFurrowOpening: "Ouverture de sillons", actionStoneRemoval: "Épierrage" });
const union = Object.keys(result.en).map((key) => JSON.stringify(key)).join(" | ");
await writeFile(new URL("../client/src/app/operations/operation-locales.generated.ts", import.meta.url), `import type { SupportedLocale } from "../../home-copy";export type OperationCopy=Record<${union},string>;export const operationCopies=${JSON.stringify(result, null, 2)} as const satisfies Record<SupportedLocale,OperationCopy>;\n`, "utf8");
