import { writeFile } from "node:fs/promises";
import { operationCopies } from "../client/src/app/operations/operation-locales.generated";
import { supportedLocales, type SupportedLocale } from "../client/src/home-copy";

const en = { installCrop: "Install crop", plantationName: "Plantation name", culture: "Crop", varieties: "Varieties", cropKind: "Crop duration", permanent: "Permanent crop", temporary: "Temporary crop", installationMethod: "Installation method", sowing: "Sowing", transplanting: "Transplanting", planting: "Planting", customMethod: "Other method", densityPlantsHa: "Plant density (plants/ha)", rowSpacingCm: "Row spacing (cm)", plantSpacingCm: "Plant spacing (cm)", installationEndDate: "Installation end date", materialLots: "Seed or plant material lots", addLot: "Add lot", lotNumber: "Lot number", quantity: "Quantity used", unit: "Unit", origin: "Origin", supplier: "Supplier", predecessor: "Previous crop", preparatoryOperations: "Applicable soil-preparation operations", createPlantationNotice: "Saving creates the plantation and records this installation as one physical operation." };
const pt = { installCrop: "Instalar cultura", plantationName: "Nome da plantação", culture: "Cultura", varieties: "Variedades", cropKind: "Duração da cultura", permanent: "Cultura permanente", temporary: "Cultura temporária", installationMethod: "Método de instalação", sowing: "Sementeira", transplanting: "Transplantação", planting: "Plantação", customMethod: "Outro método", densityPlantsHa: "Densidade de plantação (plantas/ha)", rowSpacingCm: "Distância entre linhas (cm)", plantSpacingCm: "Distância entre plantas (cm)", installationEndDate: "Data final da instalação", materialLots: "Lotes de sementes ou plantas", addLot: "Adicionar lote", lotNumber: "Número do lote", quantity: "Quantidade utilizada", unit: "Unidade", origin: "Origem", supplier: "Fornecedor", predecessor: "Cultura antecessora", preparatoryOperations: "Operações de preparação do solo aplicáveis", createPlantationNotice: "Ao guardar, é criada a plantação e esta instalação fica registada como uma única operação física." } satisfies typeof en;
const targets: Record<Exclude<SupportedLocale, "en" | "pt-PT">, string> = { "pt-BR": "pt", fr: "fr", es: "es", nl: "nl", de: "de", ja: "ja", he: "iw", tr: "tr", ar: "ar", pl: "pl", hr: "hr", el: "el", sv: "sv", no: "no", da: "da", it: "it", uk: "uk", ro: "ro", fi: "fi", bg: "bg", hu: "hu", is: "is", sk: "sk", lt: "lt", sl: "sl", lv: "lv" };
async function translate(locale: Exclude<SupportedLocale, "en" | "pt-PT">) { const keys = Object.keys(en) as Array<keyof typeof en>; const payload = keys.map((key, index) => `ZXQSEG${index}QXZ\n${en[key]}`).join("\n"); const body = new URLSearchParams({ client: "gtx", sl: "en", tl: targets[locale], dt: "t", q: payload }); for (let attempt = 1; attempt <= 5; attempt++) { const response = await fetch("https://translate.googleapis.com/translate_a/single", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded;charset=UTF-8" }, body, signal: AbortSignal.timeout(40000) }); if (response.ok) { const data = await response.json() as Array<Array<Array<string>>>; const text = data[0].map((segment) => segment[0]).join(""); const markers = [...text.matchAll(/ZXQSEG(\d+)QXZ\s*/g)]; if (markers.length !== keys.length) throw new Error(`${locale}:segments:${markers.length}`); return Object.fromEntries(keys.map((key, index) => [key, text.slice(markers[index].index! + markers[index][0].length, markers[index + 1]?.index ?? text.length).trim()])) as typeof en; } if (response.status !== 429 || attempt === 5) throw new Error(`${locale}:${response.status}`); await new Promise((resolve) => setTimeout(resolve, attempt * 1500)); } throw new Error(`${locale}:unreachable`); }
const result: Record<string, Record<string, string>> = structuredClone(operationCopies);
for (const locale of supportedLocales) { const extra = locale === "en" ? en : locale === "pt-PT" ? pt : await translate(locale); Object.assign(result[locale], extra); await new Promise((resolve) => setTimeout(resolve, 500)); }
const reviewed: Partial<Record<SupportedLocale, Partial<typeof en>>> = {
  "pt-BR": { installCrop: "Implantar cultura", plantationName: "Nome do plantio", cropKind: "Duração da cultura", sowing: "Semeadura", transplanting: "Transplantio", planting: "Plantio", densityPlantsHa: "Densidade de plantio (plantas/ha)", rowSpacingCm: "Espaçamento entre linhas (cm)", plantSpacingCm: "Espaçamento entre plantas (cm)", predecessor: "Cultura antecessora" },
  fr: { sowing: "Semis", transplanting: "Repiquage", planting: "Plantation", densityPlantsHa: "Densité de plantation (plants/ha)" }, es: { sowing: "Siembra", transplanting: "Trasplante", planting: "Plantación", densityPlantsHa: "Densidad de plantación (plantas/ha)" },
  nl: { sowing: "Zaaien", transplanting: "Verspenen", planting: "Planten" }, de: { sowing: "Aussaat", transplanting: "Umpflanzen", planting: "Pflanzung" }, it: { sowing: "Semina", transplanting: "Trapianto", planting: "Impianto" },
  pl: { sowing: "Siew", transplanting: "Przesadzanie", planting: "Sadzenie" }, uk: { sowing: "Сівба", transplanting: "Пересаджування", planting: "Садіння" }, ro: { sowing: "Semănat", transplanting: "Transplantare", planting: "Plantare" },
  sv: { sowing: "Sådd", transplanting: "Omplantering", planting: "Plantering" }, no: { sowing: "Såing", transplanting: "Omplanting", planting: "Planting" }, da: { sowing: "Såning", transplanting: "Omplantning", planting: "Plantning" }, fi: { sowing: "Kylvö", transplanting: "Uudelleenistutus", planting: "Istutus" },
  ja: { sowing: "播種", transplanting: "移植", planting: "植付け" }, tr: { sowing: "Ekim", transplanting: "Şaşırtma", planting: "Dikim" }, ar: { sowing: "بذر", transplanting: "شتل", planting: "غرس" }, el: { sowing: "Σπορά", transplanting: "Μεταφύτευση", planting: "Φύτευση" },
};
for (const [locale, values] of Object.entries(reviewed)) Object.assign(result[locale], values);
const union = Object.keys(result.en).map((key) => JSON.stringify(key)).join(" | ");
await writeFile(new URL("../client/src/app/operations/operation-locales.generated.ts", import.meta.url), `import type { SupportedLocale } from "../../home-copy";export type OperationCopy=Record<${union},string>;export const operationCopies=${JSON.stringify(result, null, 2)} as const satisfies Record<SupportedLocale,OperationCopy>;\n`, "utf8");
