import { writeFile } from "node:fs/promises";
import { operationCopies } from "../client/src/app/operations/operation-locales.generated";
import { supportedLocales } from "../client/src/home-copy";
import { fertilizationTranslationKeys as keys, fertilizationTranslationRows as rows } from "./fertilization-translations";

const fixed: Record<string, readonly string[]> = {
  en: ["Fertilization details","Application mode","Base fertilization","Top dressing","Foliar application","Soil amendment","Organic matter application","Cover crop incorporation","Other","Linked soil preparation","Products","Product name","Product category","Fertilizer","Soil amendment","Organic material","Dose per hectare","Total quantity","Density (kg/L)","Known composition","Dry matter (%)","Total nitrogen","P₂O₅","K₂O","CaO","MgO","SO₃","Unknown composition: the product quantity is counted, but nutrients are not treated as zero."],
  "pt-PT": ["Dados da fertilização","Modalidade de aplicação","Adubação de fundo","Adubação de cobertura","Aplicação foliar","Aplicação de corretivo","Aplicação de matéria orgânica","Incorporação de cultura de cobertura","Outra","Preparação do solo associada","Produtos","Nome do produto","Categoria do produto","Fertilizante","Corretivo do solo","Matéria orgânica","Dose por hectare","Quantidade total","Densidade (kg/L)","Composição conhecida","Matéria seca (%)","Azoto total","P₂O₅","K₂O","CaO","MgO","SO₃","Composição desconhecida: a quantidade do produto é contabilizada, mas os nutrientes não são considerados zero."],
  "pt-BR": ["Dados da adubação","Modalidade de aplicação","Adubação de base","Adubação de cobertura","Aplicação foliar","Aplicação de corretivo","Aplicação de matéria orgânica","Incorporação de cultura de cobertura","Outra","Preparo do solo associado","Produtos","Nome do produto","Categoria do produto","Fertilizante","Corretivo do solo","Matéria orgânica","Dose por hectare","Quantidade total","Densidade (kg/L)","Composição conhecida","Matéria seca (%)","Nitrogênio total","P₂O₅","K₂O","CaO","MgO","SO₃","Composição desconhecida: a quantidade do produto é contabilizada, mas os nutrientes não são considerados zero."],
};
const result: Record<string, Record<string, string>> = structuredClone(operationCopies);
for (const locale of supportedLocales) { const row = fixed[locale] || rows[locale]; if (!row || row.length !== keys.length) throw new Error(`${locale}: expected ${keys.length} fertilization translations, got ${row?.length ?? 0}`); Object.assign(result[locale], Object.fromEntries(keys.map((key,index)=>[key,row[index]]))); }
const union=Object.keys(result.en).map((key)=>JSON.stringify(key)).join(" | ");
await writeFile(new URL("../client/src/app/operations/operation-locales.generated.ts",import.meta.url),`import type { SupportedLocale } from "../../home-copy";export type OperationCopy=Record<${union},string>;export const operationCopies=${JSON.stringify(result,null,2)} as const satisfies Record<SupportedLocale,OperationCopy>;\n`,"utf8");
