import { writeFile } from "node:fs/promises";
import { operationCopies } from "../client/src/app/operations/operation-locales.generated";
import { supportedLocales } from "../client/src/home-copy";
import { culturalWorkTranslationKeys as keys, culturalWorkTranslationRows as rows } from "./cultural-work-translations";

const en = { culturalActions: "Cultural work carried out", executionMethod: "Execution method", manual: "Manual", mechanical: "Mechanical", thermal: "Thermal", intensity: "Intensity", light: "Light", medium: "Medium", severe: "Severe", intensityPercentage: "Intensity (%)", biomassDestination: "Biomass destination", plantPercentage: "Plants worked (%)", plantCount: "Number of plants worked", materials: "Materials used", materialName: "Material", replantingDetails: "Replanting details", originalDensity: "Original density (plants/ha)", plantsReplaced: "Plants replaced", plantsPlaced: "Plants placed", estimatedCurrentDensity: "Estimated current density (plants/ha)", actionTrainingPruning: "Training pruning", actionProductionPruning: "Production pruning", actionRenewalPruning: "Renewal pruning", actionSanitaryPruning: "Sanitary pruning", actionGreenPruning: "Green pruning", actionTopping: "Topping", actionDefoliation: "Defoliation", actionSuckerRemoval: "Sucker removal", actionManualWeeding: "Manual weeding", actionMechanicalWeeding: "Mechanical weeding", actionThermalWeeding: "Thermal weeding", actionPlantThinning: "Plant thinning", actionFlowerThinning: "Flower thinning", actionFruitThinning: "Fruit thinning", actionMowing: "Mowing", actionCoverCropCutting: "Cover crop cutting", actionStaking: "Staking", actionTying: "Tying", actionTrellisMaintenance: "Trellis maintenance", actionManualPollination: "Manual pollination", actionCleaning: "Cleaning", actionResidueRemoval: "Residue removal", actionMulching: "Mulch placement or maintenance", actionReplanting: "Replacement planting" };
const pt = { culturalActions: "Trabalhos culturais realizados", executionMethod: "Método de execução", manual: "Manual", mechanical: "Mecânico", thermal: "Térmico", intensity: "Intensidade", light: "Ligeira", medium: "Média", severe: "Severa", intensityPercentage: "Intensidade (%)", biomassDestination: "Destino da biomassa", plantPercentage: "Plantas intervencionadas (%)", plantCount: "Número de plantas intervencionadas", materials: "Materiais utilizados", materialName: "Material", replantingDetails: "Dados da retancha", originalDensity: "Densidade original (plantas/ha)", plantsReplaced: "Plantas substituídas", plantsPlaced: "Plantas colocadas", estimatedCurrentDensity: "Densidade atual estimada (plantas/ha)", actionTrainingPruning: "Poda de formação", actionProductionPruning: "Poda de produção", actionRenewalPruning: "Poda de renovação", actionSanitaryPruning: "Poda sanitária", actionGreenPruning: "Poda em verde", actionTopping: "Desponta", actionDefoliation: "Desfolha", actionSuckerRemoval: "Desladroamento", actionManualWeeding: "Monda manual", actionMechanicalWeeding: "Monda mecânica", actionThermalWeeding: "Monda térmica", actionPlantThinning: "Desbaste de plantas", actionFlowerThinning: "Desbaste de flores", actionFruitThinning: "Desbaste de frutos", actionMowing: "Roçagem", actionCoverCropCutting: "Corte de culturas de cobertura", actionStaking: "Tutoragem", actionTying: "Atamento", actionTrellisMaintenance: "Manutenção da condução", actionManualPollination: "Polinização manual", actionCleaning: "Limpeza", actionResidueRemoval: "Remoção de resíduos", actionMulching: "Colocação ou manutenção da cobertura do solo", actionReplanting: "Retancha" } satisfies typeof en;
const ptBr = { ...pt, culturalActions: "Tratos culturais realizados", light: "Leve", actionGreenPruning: "Poda verde", actionTopping: "Desponte", actionSuckerRemoval: "Desbrota", actionManualWeeding: "Capina manual", actionMechanicalWeeding: "Capina mecânica", actionThermalWeeding: "Capina térmica", actionFlowerThinning: "Raleio de flores", actionFruitThinning: "Raleio de frutos", actionMowing: "Roçada", actionStaking: "Tutoramento", actionTying: "Amarração", actionReplanting: "Replantio" } satisfies typeof en;
const es = { culturalActions: "Trabajos culturales realizados", executionMethod: "Método de ejecución", manual: "Manual", mechanical: "Mecánico", thermal: "Térmico", intensity: "Intensidad", light: "Ligera", medium: "Media", severe: "Severa", intensityPercentage: "Intensidad (%)", biomassDestination: "Destino de la biomasa", plantPercentage: "Plantas intervenidas (%)", plantCount: "Número de plantas intervenidas", materials: "Materiales utilizados", materialName: "Material", replantingDetails: "Datos de reposición de marras", originalDensity: "Densidad original (plantas/ha)", plantsReplaced: "Plantas sustituidas", plantsPlaced: "Plantas colocadas", estimatedCurrentDensity: "Densidad actual estimada (plantas/ha)", actionTrainingPruning: "Poda de formación", actionProductionPruning: "Poda de producción", actionRenewalPruning: "Poda de renovación", actionSanitaryPruning: "Poda sanitaria", actionGreenPruning: "Poda en verde", actionTopping: "Despunte", actionDefoliation: "Deshojado", actionSuckerRemoval: "Deschuponado", actionManualWeeding: "Escarda manual", actionMechanicalWeeding: "Escarda mecánica", actionThermalWeeding: "Escarda térmica", actionPlantThinning: "Aclareo de plantas", actionFlowerThinning: "Aclareo de flores", actionFruitThinning: "Aclareo de frutos", actionMowing: "Desbroce", actionCoverCropCutting: "Siega de la cubierta vegetal", actionStaking: "Tutorado", actionTying: "Atado", actionTrellisMaintenance: "Mantenimiento del emparrado", actionManualPollination: "Polinización manual", actionCleaning: "Limpieza", actionResidueRemoval: "Retirada de restos vegetales", actionMulching: "Colocación o mantenimiento del acolchado", actionReplanting: "Reposición de marras" } satisfies typeof en;

function fromRow(locale: string) {
  const row = rows[locale];
  if (!row || row.length !== keys.length) throw new Error(`${locale}: expected ${keys.length} cultural-work translations, got ${row?.length ?? 0}`);
  return Object.fromEntries(keys.map((key, index) => [key, row[index]])) as typeof en;
}

const result: Record<string, Record<string, string>> = structuredClone(operationCopies);
for (const locale of supportedLocales) Object.assign(result[locale], locale === "en" ? en : locale === "pt-PT" ? pt : locale === "pt-BR" ? ptBr : locale === "es" ? es : fromRow(locale));
const union = Object.keys(result.en).map((key) => JSON.stringify(key)).join(" | ");
await writeFile(new URL("../client/src/app/operations/operation-locales.generated.ts", import.meta.url), `import type { SupportedLocale } from "../../home-copy";export type OperationCopy=Record<${union},string>;export const operationCopies=${JSON.stringify(result, null, 2)} as const satisfies Record<SupportedLocale,OperationCopy>;\n`, "utf8");
