import type { HomepageCopy, SupportedLocale } from "../client/src/home-copy";

type CommercialReview = {
  heroTitle: string; heroAccent: string; heroDescription: string;
  logbookDescription: string;
  modulesKicker: string; modulesTitle: string; modulesDescription: string;
};

const reviews: Record<Exclude<SupportedLocale, "en" | "pt-PT">, CommercialReview> = {
  "pt-BR": { heroTitle: "Toda a fazenda,", heroAccent: "sob controle.", heroDescription: "Planeje, registre e acompanhe todo o trabalho agrícola em uma aplicação simples de usar, com visão completa da fazenda e planos acessíveis que crescem com você.", logbookDescription: "Estruture registros e evidências rastreáveis para apoiar a Produção Integrada e o Manejo Integrado de Pragas (MIP), a produção orgânica, GLOBALG.A.P. IFA, GRASP, SPRING e outros referenciais aplicáveis. A certificação permanece dependente do organismo competente.", modulesKicker: "Estoque e custos sob controle", modulesTitle: "Saiba o que tem, o que utiliza e quanto custa", modulesDescription: "Acompanhe estoques e lotes, conecte cada consumo ao trabalho realizado e transforme mão de obra, equipamentos e insumos em custos claros por plantio e colheita." },
  fr: { heroTitle: "Toute l’exploitation,", heroAccent: "sous contrôle.", heroDescription: "Planifiez, enregistrez et suivez tous les travaux agricoles dans une application simple à utiliser, avec une vue complète de l’exploitation et des offres accessibles qui évoluent avec vous.", logbookDescription: "Structurez des registres et des preuves traçables pour soutenir la production intégrée et la protection intégrée (IPM), l’agriculture biologique, GLOBALG.A.P. IFA, GRASP, SPRING et d’autres référentiels applicables. La certification reste soumise à l’organisme compétent.", modulesKicker: "Stocks et coûts sous contrôle", modulesTitle: "Sachez ce que vous avez, ce que vous utilisez et ce que cela coûte", modulesDescription: "Suivez les stocks et les lots, reliez chaque consommation au travail réalisé et transformez la main-d’œuvre, les équipements et les intrants en coûts clairs par culture et récolte." },
  es: { heroTitle: "Toda la explotación,", heroAccent: "bajo control.", heroDescription: "Planifique, registre y siga todo el trabajo agrícola en una aplicación fácil de usar, con una visión completa de la explotación y planes accesibles que crecen con usted.", logbookDescription: "Estructure registros y evidencias trazables para apoyar la producción integrada y la gestión integrada de plagas (GIP), la producción ecológica, GLOBALG.A.P. IFA, GRASP, SPRING y otros referenciales aplicables. La certificación sigue dependiendo del organismo competente.", modulesKicker: "Inventario y costes bajo control", modulesTitle: "Sepa qué tiene, qué utiliza y cuánto cuesta", modulesDescription: "Controle existencias y lotes, vincule cada consumo al trabajo realizado y convierta mano de obra, equipos e insumos en costes claros por cultivo y cosecha." },
  nl: { heroTitle: "Het hele landbouwbedrijf,", heroAccent: "onder controle.", heroDescription: "Plan, registreer en volg al het werk in één gebruiksvriendelijke toepassing, met volledig zicht op het bedrijf en betaalbare plannen die met u meegroeien.", logbookDescription: "Structureer traceerbare registraties en bewijs voor geïntegreerde productie en geïntegreerde gewasbescherming (IPM), biologische productie, GLOBALG.A.P. IFA, GRASP, SPRING en andere toepasselijke schema’s. Certificering blijft afhankelijk van de bevoegde certificeringsinstantie.", modulesKicker: "Voorraad en kosten onder controle", modulesTitle: "Weet wat u heeft, wat u gebruikt en wat het kost", modulesDescription: "Volg voorraad en partijen, koppel elk verbruik aan het uitgevoerde werk en vertaal arbeid, machines en productiemiddelen naar duidelijke kosten per teelt en oogst." },
  de: { heroTitle: "Der ganze Betrieb,", heroAccent: "unter Kontrolle.", heroDescription: "Planen, dokumentieren und verfolgen Sie alle landwirtschaftlichen Arbeiten in einer einfach bedienbaren Anwendung – mit vollständigem Überblick und bezahlbaren Tarifen, die mit Ihrem Betrieb wachsen.", logbookDescription: "Strukturieren Sie rückverfolgbare Aufzeichnungen und Nachweise zur Unterstützung der integrierten Produktion und des integrierten Pflanzenschutzes (IPM), des ökologischen Landbaus, von GLOBALG.A.P. IFA, GRASP, SPRING und weiteren anwendbaren Standards. Die Zertifizierung bleibt der zuständigen Zertifizierungsstelle vorbehalten.", modulesKicker: "Bestände und Kosten im Griff", modulesTitle: "Wissen, was vorhanden ist, was eingesetzt wird und was es kostet", modulesDescription: "Verfolgen Sie Bestände und Chargen, ordnen Sie jeden Verbrauch der ausgeführten Arbeit zu und erhalten Sie klare Kosten je Kultur und Ernte aus Arbeit, Maschinen und Betriebsmitteln." },
  ja: { heroTitle: "農場全体を、", heroAccent: "シンプルに管理。", heroDescription: "使いやすい一つのアプリで農作業を計画・記録・確認。農場全体を把握でき、成長に合わせて選べる手頃なプランを用意しています。", logbookDescription: "統合生産・総合的病害虫管理（IPM）、有機生産、GLOBALG.A.P. IFA、GRASP、SPRING、その他の適用基準を支える、追跡可能な記録と証拠を整備します。認証は所管する認証機関の審査によります。", modulesKicker: "在庫とコストを一元管理", modulesTitle: "在庫、使用量、コストを正確に把握", modulesDescription: "在庫とロットを追跡し、使用量を作業に結び付け、人件費・機械・資材を栽培と収穫ごとの明確なコストにまとめます。" },
  he: { heroTitle: "כל המשק,", heroAccent: "תחת שליטה.", heroDescription: "תכננו, תעדו ועקבו אחר כל העבודה החקלאית ביישום אחד וקל לשימוש, עם תמונה מלאה של המשק ומסלולים נגישים שצומחים איתכם.", logbookDescription: "ארגנו רישומים וראיות ניתנים למעקב לתמיכה בייצור משולב ובהדברה משולבת (IPM), בייצור אורגני, ב-GLOBALG.A.P. IFA, ב-GRASP, ב-SPRING ובתקנים רלוונטיים נוספים. ההסמכה נשארת באחריות גוף ההסמכה המוסמך.", modulesKicker: "מלאי ועלויות תחת שליטה", modulesTitle: "דעו מה יש, במה משתמשים וכמה זה עולה", modulesDescription: "עקבו אחר מלאי ואצוות, קשרו כל צריכה לעבודה שבוצעה והפכו עבודה, ציוד ותשומות לעלויות ברורות לכל גידול וקטיף." },
  tr: { heroTitle: "Tüm işletme,", heroAccent: "kontrol altında.", heroDescription: "Tüm tarımsal işleri kullanımı kolay tek bir uygulamada planlayın, kaydedin ve izleyin; işletmenin tamamını görün ve sizinle büyüyen erişilebilir planlardan yararlanın.", logbookDescription: "Entegre üretim ve entegre zararlı yönetimi (IPM), organik üretim, GLOBALG.A.P. IFA, GRASP, SPRING ve diğer geçerli standartları destekleyen izlenebilir kayıt ve kanıtları yapılandırın. Belgelendirme yetkili belgelendirme kuruluşunun değerlendirmesine tabidir.", modulesKicker: "Stok ve maliyetler kontrol altında", modulesTitle: "Neye sahip olduğunuzu, ne kullandığınızı ve maliyetini bilin", modulesDescription: "Stokları ve partileri izleyin, her tüketimi yapılan işle ilişkilendirin; işçilik, ekipman ve girdileri ürün ve hasat bazında net maliyetlere dönüştürün." },
  ar: { heroTitle: "المزرعة بأكملها،", heroAccent: "تحت السيطرة.", heroDescription: "خطط لكل الأعمال الزراعية وسجّلها وتابعها في تطبيق واحد سهل الاستخدام، مع رؤية كاملة للمزرعة وخطط ميسّرة تنمو معك.", logbookDescription: "نظّم سجلات وأدلة قابلة للتتبع لدعم الإنتاج المتكامل والإدارة المتكاملة للآفات (IPM)، والإنتاج العضوي، وGLOBALG.A.P. IFA، وGRASP، وSPRING، وغيرها من المعايير المعمول بها. ويظل الاعتماد خاضعًا لجهة التصديق المختصة.", modulesKicker: "المخزون والتكاليف تحت السيطرة", modulesTitle: "اعرف ما لديك وما تستخدمه وتكلفته", modulesDescription: "تابع المخزون والدفعات، واربط كل استهلاك بالعمل المنفذ، وحوّل العمالة والمعدات والمدخلات إلى تكاليف واضحة لكل زراعة وحصاد." },
  pl: { heroTitle: "Całe gospodarstwo,", heroAccent: "pod kontrolą.", heroDescription: "Planuj, zapisuj i monitoruj wszystkie prace rolnicze w jednej prostej aplikacji, z pełnym obrazem gospodarstwa i przystępnymi planami, które rosną razem z nim.", logbookDescription: "Twórz identyfikowalne rejestry i dowody wspierające produkcję integrowaną i integrowaną ochronę roślin (IPM), produkcję ekologiczną, GLOBALG.A.P. IFA, GRASP, SPRING oraz inne właściwe standardy. Certyfikacja pozostaje w gestii właściwej jednostki certyfikującej.", modulesKicker: "Zapasy i koszty pod kontrolą", modulesTitle: "Wiedz, co masz, czego używasz i ile to kosztuje", modulesDescription: "Śledź zapasy i partie, łącz każde zużycie z wykonaną pracą i przeliczaj robociznę, sprzęt oraz środki produkcji na czytelne koszty uprawy i zbioru." },
  hr: { heroTitle: "Cijelo gospodarstvo,", heroAccent: "pod kontrolom.", heroDescription: "Planirajte, bilježite i pratite sve poljoprivredne radove u jednoj jednostavnoj aplikaciji, uz potpuni pregled gospodarstva i pristupačne pakete koji rastu s vama.", logbookDescription: "Uredite sljedive zapise i dokaze za potporu integriranoj proizvodnji i integriranoj zaštiti bilja (IPM), ekološkoj proizvodnji, GLOBALG.A.P. IFA, GRASP, SPRING i drugim primjenjivim standardima. Certifikacija ostaje u nadležnosti ovlaštenog certifikacijskog tijela.", modulesKicker: "Zalihe i troškovi pod kontrolom", modulesTitle: "Znajte što imate, što koristite i koliko to košta", modulesDescription: "Pratite zalihe i serije, povežite svaku potrošnju s obavljenim radom te pretvorite rad, opremu i inpute u jasne troškove po uzgoju i berbi." },
  el: { heroTitle: "Ολόκληρη η εκμετάλλευση,", heroAccent: "υπό έλεγχο.", heroDescription: "Σχεδιάστε, καταγράψτε και παρακολουθήστε όλες τις γεωργικές εργασίες σε μία εύχρηστη εφαρμογή, με πλήρη εικόνα της εκμετάλλευσης και προσιτά προγράμματα που εξελίσσονται μαζί σας.", logbookDescription: "Οργανώστε ιχνηλάσιμα αρχεία και τεκμήρια για την υποστήριξη της ολοκληρωμένης παραγωγής και της ολοκληρωμένης φυτοπροστασίας (IPM), της βιολογικής παραγωγής, των GLOBALG.A.P. IFA, GRASP, SPRING και άλλων εφαρμοστέων προτύπων. Η πιστοποίηση παραμένει αρμοδιότητα του εξουσιοδοτημένου φορέα.", modulesKicker: "Απόθεμα και κόστος υπό έλεγχο", modulesTitle: "Γνωρίζετε τι έχετε, τι χρησιμοποιείτε και πόσο κοστίζει", modulesDescription: "Παρακολουθήστε αποθέματα και παρτίδες, συνδέστε κάθε κατανάλωση με την εργασία και μετατρέψτε εργασία, εξοπλισμό και εισροές σε σαφές κόστος ανά καλλιέργεια και συγκομιδή." },
  sv: { heroTitle: "Hela gården,", heroAccent: "under kontroll.", heroDescription: "Planera, registrera och följ allt arbete i en lättanvänd applikation, med full överblick över gården och prisvärda planer som växer med dig.", logbookDescription: "Strukturera spårbara journaler och underlag som stöd för integrerad produktion och integrerat växtskydd (IPM), ekologisk produktion, GLOBALG.A.P. IFA, GRASP, SPRING och andra tillämpliga standarder. Certifiering avgörs alltid av behörigt certifieringsorgan.", modulesKicker: "Lager och kostnader under kontroll", modulesTitle: "Se vad du har, vad du använder och vad det kostar", modulesDescription: "Följ lager och partier, koppla varje förbrukning till utfört arbete och omvandla arbete, utrustning och insatsvaror till tydliga kostnader per odling och skörd." },
  no: { heroTitle: "Hele gården,", heroAccent: "under kontroll.", heroDescription: "Planlegg, registrer og følg alt arbeid i én brukervennlig applikasjon, med full oversikt over gården og rimelige planer som vokser med deg.", logbookDescription: "Strukturer sporbare journaler og dokumentasjon som støtter integrert produksjon og integrert plantevern (IPM), økologisk produksjon, GLOBALG.A.P. IFA, GRASP, SPRING og andre relevante standarder. Sertifisering avgjøres alltid av et kompetent sertifiseringsorgan.", modulesKicker: "Lager og kostnader under kontroll", modulesTitle: "Vit hva du har, hva du bruker og hva det koster", modulesDescription: "Følg lager og partier, knytt hvert forbruk til utført arbeid og gjør arbeid, utstyr og innsatsmidler om til tydelige kostnader per dyrking og innhøsting." },
  da: { heroTitle: "Hele bedriften,", heroAccent: "under kontrol.", heroDescription: "Planlæg, registrér og følg alt landbrugsarbejde i én brugervenlig applikation med fuldt overblik og prisvenlige planer, der vokser med dig.", logbookDescription: "Strukturér sporbare journaler og dokumentation til støtte for integreret produktion og integreret plantebeskyttelse (IPM), økologisk produktion, GLOBALG.A.P. IFA, GRASP, SPRING og andre relevante standarder. Certificering afgøres fortsat af det kompetente certificeringsorgan.", modulesKicker: "Lager og omkostninger under kontrol", modulesTitle: "Vid, hvad du har, hvad du bruger, og hvad det koster", modulesDescription: "Følg lager og partier, knyt hvert forbrug til det udførte arbejde, og omsæt arbejdskraft, udstyr og input til klare omkostninger pr. dyrkning og høst." },
  it: { heroTitle: "Tutta l’azienda,", heroAccent: "sotto controllo.", heroDescription: "Pianifica, registra e segui ogni attività agricola in un’applicazione facile da usare, con una visione completa dell’azienda e piani accessibili che crescono con te.", logbookDescription: "Organizza registri e prove tracciabili a supporto della produzione integrata e della difesa integrata (IPM), della produzione biologica, di GLOBALG.A.P. IFA, GRASP, SPRING e di altri standard applicabili. La certificazione resta soggetta all’organismo competente.", modulesKicker: "Scorte e costi sotto controllo", modulesTitle: "Sapere cosa hai, cosa utilizzi e quanto costa", modulesDescription: "Monitora scorte e lotti, collega ogni consumo al lavoro svolto e trasforma manodopera, attrezzature e mezzi tecnici in costi chiari per coltura e raccolto." },
  uk: { heroTitle: "Усе господарство,", heroAccent: "під контролем.", heroDescription: "Плануйте, записуйте й відстежуйте всі сільськогосподарські роботи в одному простому застосунку, з повним оглядом господарства та доступними планами, що зростають разом із вами.", logbookDescription: "Створюйте простежувані записи й докази на підтримку інтегрованого виробництва та інтегрованого захисту рослин (IPM), органічного виробництва, GLOBALG.A.P. IFA, GRASP, SPRING та інших застосовних стандартів. Сертифікація залишається компетенцією уповноваженого органу.", modulesKicker: "Запаси й витрати під контролем", modulesTitle: "Знайте, що маєте, що використовуєте і скільки це коштує", modulesDescription: "Відстежуйте запаси й партії, пов’язуйте кожне використання з виконаною роботою та отримуйте чіткі витрати за культурою і врожаєм з праці, техніки й ресурсів." },
  ro: { heroTitle: "Întreaga exploatație,", heroAccent: "sub control.", heroDescription: "Planificați, înregistrați și urmăriți toate lucrările agricole într-o aplicație ușor de folosit, cu o imagine completă a exploatației și planuri accesibile care cresc odată cu dumneavoastră.", logbookDescription: "Structurați registre și dovezi trasabile pentru a sprijini producția integrată și gestionarea integrată a dăunătorilor (IPM), producția ecologică, GLOBALG.A.P. IFA, GRASP, SPRING și alte standarde aplicabile. Certificarea rămâne în responsabilitatea organismului competent.", modulesKicker: "Stocuri și costuri sub control", modulesTitle: "Știți ce aveți, ce utilizați și cât costă", modulesDescription: "Urmăriți stocurile și loturile, legați fiecare consum de lucrarea realizată și transformați munca, echipamentele și inputurile în costuri clare pe cultură și recoltă." },
  fi: { heroTitle: "Koko maatila,", heroAccent: "hallinnassa.", heroDescription: "Suunnittele, kirjaa ja seuraa kaikki maataloustyöt yhdessä helppokäyttöisessä sovelluksessa, josta saat kokonaiskuvan tilasta ja edulliset, mukanasi kasvavat paketit.", logbookDescription: "Rakenna jäljitettävät kirjaukset ja todisteet integroidun tuotannon ja integroidun kasvinsuojelun (IPM), luonnonmukaisen tuotannon, GLOBALG.A.P. IFA:n, GRASP:n, SPRINGin ja muiden sovellettavien standardien tueksi. Sertifioinnista päättää aina toimivaltainen sertifiointielin.", modulesKicker: "Varasto ja kustannukset hallinnassa", modulesTitle: "Tiedä, mitä sinulla on, mitä käytät ja mitä se maksaa", modulesDescription: "Seuraa varastoja ja eriä, yhdistä kulutus tehtyyn työhön ja muodosta työstä, kalustosta ja tuotantopanoksista selkeät kustannukset viljelylle ja sadolle." },
  bg: { heroTitle: "Цялото стопанство,", heroAccent: "под контрол.", heroDescription: "Планирайте, записвайте и проследявайте всички земеделски дейности в едно лесно за използване приложение, с пълен поглед върху стопанството и достъпни планове, които растат с вас.", logbookDescription: "Структурирайте проследими записи и доказателства в подкрепа на интегрираното производство и интегрираното управление на вредителите (IPM), биологичното производство, GLOBALG.A.P. IFA, GRASP, SPRING и други приложими стандарти. Сертифицирането остава в компетентността на упълномощения орган.", modulesKicker: "Наличности и разходи под контрол", modulesTitle: "Знайте какво имате, какво използвате и колко струва", modulesDescription: "Следете наличности и партиди, свързвайте всяко потребление с извършената работа и превръщайте труда, техниката и вложенията в ясни разходи по култура и реколта." },
  hu: { heroTitle: "Az egész gazdaság,", heroAccent: "kézben tartva.", heroDescription: "Tervezze, rögzítse és kövesse az összes mezőgazdasági munkát egy könnyen használható alkalmazásban, teljes rálátással a gazdaságra és megfizethető, együtt növekvő csomagokkal.", logbookDescription: "Hozzon létre nyomon követhető nyilvántartásokat és bizonyítékokat az integrált termelés és integrált növényvédelem (IPM), az ökológiai termelés, a GLOBALG.A.P. IFA, a GRASP, a SPRING és más alkalmazandó szabványok támogatására. A tanúsítás az illetékes tanúsító szervezet hatáskörébe tartozik.", modulesKicker: "Készletek és költségek kézben tartva", modulesTitle: "Tudja, mije van, mit használ és mennyibe kerül", modulesDescription: "Kövesse a készleteket és tételeket, kapcsoljon minden felhasználást az elvégzett munkához, és alakítsa a munkaerőt, gépeket és inputokat egyértelmű költségekké kultúránként és betakarításonként." },
  is: { heroTitle: "Allur búreksturinn,", heroAccent: "undir stjórn.", heroDescription: "Skipuleggðu, skráðu og fylgstu með öllum landbúnaðarstörfum í einu einföldu kerfi, með heildarsýn yfir reksturinn og hagkvæmum áskriftum sem vaxa með þér.", logbookDescription: "Byggðu upp rekjanlegar skrár og gögn til stuðnings samþættri framleiðslu og samþættum plöntuverndaraðferðum (IPM), lífrænni framleiðslu, GLOBALG.A.P. IFA, GRASP, SPRING og öðrum viðeigandi stöðlum. Vottun er ávallt háð mati viðurkennds vottunaraðila.", modulesKicker: "Birgðir og kostnaður undir stjórn", modulesTitle: "Veistu hvað er til, hvað er notað og hvað það kostar", modulesDescription: "Fylgstu með birgðum og lotum, tengdu hverja notkun við unnið verk og breyttu vinnu, búnaði og aðföngum í skýran kostnað eftir ræktun og uppskeru." },
  sk: { heroTitle: "Celé hospodárstvo,", heroAccent: "pod kontrolou.", heroDescription: "Plánujte, zaznamenávajte a sledujte všetky poľnohospodárske práce v jednej jednoduchej aplikácii s úplným prehľadom a dostupnými plánmi, ktoré rastú spolu s vami.", logbookDescription: "Vytvárajte vysledovateľné záznamy a dôkazy na podporu integrovanej produkcie a integrovanej ochrany rastlín (IPM), ekologickej produkcie, GLOBALG.A.P. IFA, GRASP, SPRING a ďalších platných štandardov. Certifikácia zostáva v právomoci príslušného certifikačného orgánu.", modulesKicker: "Zásoby a náklady pod kontrolou", modulesTitle: "Vedzte, čo máte, čo používate a koľko to stojí", modulesDescription: "Sledujte zásoby a šarže, prepájajte každú spotrebu s vykonanou prácou a premeňte prácu, stroje a vstupy na jasné náklady podľa pestovania a zberu." },
  lt: { heroTitle: "Visas ūkis,", heroAccent: "jūsų kontrolėje.", heroDescription: "Planuokite, registruokite ir stebėkite visus žemės ūkio darbus vienoje lengvai naudojamoje programoje, matydami visą ūkį ir rinkdamiesi prieinamus, kartu augančius planus.", logbookDescription: "Kurkite atsekamus įrašus ir įrodymus, padedančius laikytis integruotos gamybos ir integruotos kenkėjų kontrolės (IPM), ekologinės gamybos, GLOBALG.A.P. IFA, GRASP, SPRING ir kitų taikomų standartų. Sertifikavimą visada atlieka kompetentinga sertifikavimo įstaiga.", modulesKicker: "Atsargos ir sąnaudos kontroliuojamos", modulesTitle: "Žinokite, ką turite, ką naudojate ir kiek tai kainuoja", modulesDescription: "Stebėkite atsargas ir partijas, susiekite kiekvieną sunaudojimą su atliktu darbu ir paverskite darbą, techniką bei išteklius aiškiomis auginimo ir derliaus sąnaudomis." },
  sl: { heroTitle: "Celotno gospodarstvo,", heroAccent: "pod nadzorom.", heroDescription: "Načrtujte, beležite in spremljajte vsa kmetijska dela v eni preprosti aplikaciji, s popolnim pregledom gospodarstva in dostopnimi paketi, ki rastejo z vami.", logbookDescription: "Uredite sledljive evidence in dokazila v podporo integrirani pridelavi in integriranemu varstvu rastlin (IPM), ekološki pridelavi, GLOBALG.A.P. IFA, GRASP, SPRING ter drugim veljavnim standardom. Certificiranje ostaja v pristojnosti pooblaščenega certifikacijskega organa.", modulesKicker: "Zaloge in stroški pod nadzorom", modulesTitle: "Vedite, kaj imate, kaj uporabljate in koliko stane", modulesDescription: "Spremljajte zaloge in serije, povežite vsako porabo z opravljenim delom ter pretvorite delo, opremo in vložke v jasne stroške po gojenju in spravilu." },
  lv: { heroTitle: "Visa saimniecība,", heroAccent: "jūsu kontrolē.", heroDescription: "Plānojiet, reģistrējiet un pārraugiet visus lauksaimniecības darbus vienā viegli lietojamā programmā, ar pilnu saimniecības pārskatu un pieejamiem plāniem, kas aug kopā ar jums.", logbookDescription: "Veidojiet izsekojamus ierakstus un pierādījumus integrētās ražošanas un integrētās augu aizsardzības (IPM), bioloģiskās ražošanas, GLOBALG.A.P. IFA, GRASP, SPRING un citu piemērojamo standartu atbalstam. Sertifikāciju vienmēr veic kompetentā sertifikācijas iestāde.", modulesKicker: "Krājumi un izmaksas kontrolē", modulesTitle: "Ziniet, kas jums ir, ko izmantojat un cik tas maksā", modulesDescription: "Sekojiet krājumiem un partijām, sasaistiet katru patēriņu ar paveikto darbu un pārvērtiet darbu, tehniku un resursus skaidrās izmaksās pa audzējumiem un ražām." },
};

export function applyHomepageCommercialReview(copies: Record<SupportedLocale, HomepageCopy>) {
  for (const [locale, review] of Object.entries(reviews) as Array<[Exclude<SupportedLocale, "en" | "pt-PT">, CommercialReview]>) {
    const copy = copies[locale];
    Object.assign(copy.hero, { title: review.heroTitle, accent: review.heroAccent, description: review.heroDescription });
    const schemeEnd = review.logbookDescription.indexOf("SPRING") + "SPRING".length;
    const sentenceEnd = review.logbookDescription.slice(schemeEnd).search(/[.!?。]/u);
    copy.platform.cards[7].description = sentenceEnd < 0 ? review.logbookDescription : review.logbookDescription.slice(0, schemeEnd + sentenceEnd + 1);
    Object.assign(copy.modules, { kicker: review.modulesKicker, title: review.modulesTitle, description: review.modulesDescription });
  }
}
