import type { HomepageCopy, SupportedLocale } from "../client/src/home-copy";

type PlanWeatherReview = {
  weather: string;
  pricingKicker: string;
  pricingTitle: string;
  pricingDescription: string;
};

const reviews: Record<Exclude<SupportedLocale, "en" | "pt-PT">, PlanWeatherReview> = {
  "pt-BR": { weather: "As estações virtuais calculam remotamente evapotranspiração de referência, radiação solar, DLI estimada, graus-dia, necessidades de frio e molhamento foliar estimado, sem exigir a compra ou instalação de sensores. Para a maioria das fazendas, fornecem a informação agronômica necessária para planejar e acompanhar o campo, evitando custos desnecessários com hardware.", pricingKicker: "Planos simples e previsíveis", pricingTitle: "Pague pela escala de que precisa, não pelo trabalho que registra.", pricingDescription: "Os planos variam por usuários, área, talhões e profundidade meteorológica. Operações, colheitas e cadernos de campo continuam sem limites artificiais." },
  fr: { weather: "Les stations virtuelles calculent à distance l’évapotranspiration de référence, le rayonnement solaire, le DLI estimé, les degrés-jours, les besoins en froid et l’humectation foliaire estimée, sans achat ni installation de capteurs. Pour la plupart des exploitations, elles fournissent les informations agronomiques nécessaires à la planification et au suivi des cultures, sans coûts matériels inutiles.", pricingKicker: "Des offres simples et prévisibles", pricingTitle: "Payez pour l’échelle dont vous avez besoin, pas pour le travail que vous enregistrez.", pricingDescription: "Les offres varient selon les utilisateurs, la surface, les parcelles et le niveau de détail météorologique. Les opérations, récoltes et cahiers de culture restent sans limites artificielles." },
  es: { weather: "Las estaciones virtuales calculan a distancia la evapotranspiración de referencia, la radiación solar, el DLI estimado, los grados-día, las necesidades de frío y la humectación foliar estimada, sin comprar ni instalar sensores. Para la mayoría de las explotaciones, aportan la información agronómica necesaria para planificar y seguir el campo, evitando costes innecesarios de hardware.", pricingKicker: "Planes sencillos y previsibles", pricingTitle: "Pague por la escala que necesita, no por el trabajo que registra.", pricingDescription: "Los planes varían por usuarios, superficie, parcelas y profundidad meteorológica. Las operaciones, cosechas y cuadernos de campo siguen sin límites artificiales." },
  nl: { weather: "Virtuele stations berekenen op afstand referentie-evapotranspiratie, zonnestraling, geschatte DLI, groeigraaddagen, koudebehoefte en geschatte bladnatheid, zonder dat u sensoren hoeft te kopen of installeren. Voor de meeste landbouwbedrijven leveren ze de agronomische informatie om het veldwerk te plannen en volgen, zonder onnodige hardwarekosten.", pricingKicker: "Eenvoudige, voorspelbare plannen", pricingTitle: "Betaal voor de schaal die u nodig hebt, niet voor het werk dat u registreert.", pricingDescription: "Plannen verschillen naar gebruikers, oppervlakte, percelen en meteorologische diepgang. Bewerkingen, oogsten en teeltregistraties blijven vrij van kunstmatige limieten." },
  de: { weather: "Virtuelle Stationen berechnen Referenzverdunstung, Sonneneinstrahlung, geschätzte DLI, Wachstumsgradtage, Kältebedarf und geschätzte Blattnässe aus der Ferne – ohne Kauf oder Installation von Sensoren. Für die meisten Betriebe liefern sie die agronomischen Informationen zur Planung und Überwachung der Feldarbeit, ohne unnötige Hardwarekosten.", pricingKicker: "Einfache, planbare Tarife", pricingTitle: "Zahlen Sie für die benötigte Betriebsgröße, nicht für die dokumentierte Arbeit.", pricingDescription: "Die Tarife unterscheiden sich nach Nutzern, Fläche, Schlägen und meteorologischer Tiefe. Maßnahmen, Ernten und Schlagkarteien bleiben ohne künstliche Begrenzungen." },
  ja: { weather: "仮想観測点が基準蒸発散量、日射量、推定DLI、積算温度、低温要求量、推定葉面湿潤を遠隔で算出するため、センサーを購入・設置する必要がありません。多くの農場では、不要な機器費用をかけずに、作業の計画と確認に必要な農業気象情報を得られます。", pricingKicker: "シンプルで分かりやすいプラン", pricingTitle: "記録する作業量ではなく、必要な規模に応じてお支払いください。", pricingDescription: "プランは利用者数、面積、圃場数、気象情報の深さによって異なります。作業、収穫、圃場記録に不自然な上限はありません。" },
  he: { weather: "תחנות וירטואליות מחשבות מרחוק התאדות־דיות ייחוס, קרינת שמש, DLI משוער, ימי מעלה, דרישות קור ורטיבות עלים משוערת, ללא צורך ברכישה או בהתקנה של חיישנים. עבור רוב המשקים הן מספקות את המידע האגרונומי הדרוש לתכנון ולמעקב, בלי עלויות חומרה מיותרות.", pricingKicker: "מסלולים פשוטים וצפויים", pricingTitle: "שלמו לפי ההיקף שאתם צריכים, לא לפי העבודה שאתם מתעדים.", pricingDescription: "המסלולים משתנים לפי מספר משתמשים, שטח, חלקות ועומק המידע המטאורולוגי. לפעולות, לקטיפים וליומני השדה אין מגבלות מלאכותיות." },
  tr: { weather: "Sanal istasyonlar referans evapotranspirasyonu, güneş radyasyonunu, tahmini DLI’yi, büyüme derece-günlerini, soğuklanma ihtiyacını ve tahmini yaprak ıslaklığını uzaktan hesaplar; sensör satın almanız veya kurmanız gerekmez. Çoğu işletme için gereksiz donanım maliyetleri olmadan planlama ve izleme için gereken tarımsal bilgiyi sağlar.", pricingKicker: "Basit ve öngörülebilir planlar", pricingTitle: "Kaydettiğiniz iş için değil, ihtiyacınız olan ölçek için ödeme yapın.", pricingDescription: "Planlar kullanıcı, alan, parsel ve meteorolojik ayrıntı düzeyine göre değişir. İşlemler, hasatlar ve tarla kayıtları yapay sınırlara tabi değildir." },
  ar: { weather: "تحسب المحطات الافتراضية عن بُعد التبخر والنتح المرجعي والإشعاع الشمسي وDLI التقديري وأيام الدرجة والاحتياجات الباردة وبلل الأوراق التقديري، من دون شراء أجهزة استشعار أو تركيبها. وتوفر لمعظم المزارع المعلومات الزراعية اللازمة للتخطيط والمتابعة مع تجنب تكاليف أجهزة غير ضرورية.", pricingKicker: "خطط بسيطة ويمكن توقع تكلفتها", pricingTitle: "ادفع مقابل الحجم الذي تحتاج إليه، لا مقابل العمل الذي تسجله.", pricingDescription: "تختلف الخطط حسب المستخدمين والمساحة والقطع وعمق بيانات الطقس. وتبقى العمليات والحصاد وسجلات الحقل من دون حدود مصطنعة." },
  pl: { weather: "Wirtualne stacje zdalnie obliczają ewapotranspirację referencyjną, promieniowanie słoneczne, szacowane DLI, stopniodni wzrostu, zapotrzebowanie na chłód i szacowaną wilgotność liści, bez zakupu ani instalacji czujników. Większości gospodarstw zapewniają informacje agronomiczne potrzebne do planowania i monitorowania pola, bez zbędnych kosztów sprzętu.", pricingKicker: "Proste i przewidywalne plany", pricingTitle: "Płać za potrzebną skalę, a nie za rejestrowaną pracę.", pricingDescription: "Plany różnią się liczbą użytkowników, powierzchnią, działkami i zakresem danych pogodowych. Zabiegi, zbiory i ewidencja polowa pozostają bez sztucznych limitów." },
  hr: { weather: "Virtualne stanice daljinski izračunavaju referentnu evapotranspiraciju, sunčevo zračenje, procijenjeni DLI, stupanj-dane, potrebe za hladnoćom i procijenjenu vlažnost lista, bez kupnje ili ugradnje senzora. Većini gospodarstava pružaju agronomske informacije potrebne za planiranje i praćenje rada bez nepotrebnih troškova opreme.", pricingKicker: "Jednostavni i predvidljivi paketi", pricingTitle: "Plaćajte prema potrebnom opsegu, a ne prema radu koji bilježite.", pricingDescription: "Paketi se razlikuju prema korisnicima, površini, parcelama i razini meteoroloških podataka. Zahvati, berbe i evidencije polja ostaju bez umjetnih ograničenja." },
  el: { weather: "Οι εικονικοί σταθμοί υπολογίζουν εξ αποστάσεως την εξατμισοδιαπνοή αναφοράς, την ηλιακή ακτινοβολία, το εκτιμώμενο DLI, τις βαθμοημέρες, τις ανάγκες ψύχους και την εκτιμώμενη διαβροχή φύλλων, χωρίς αγορά ή εγκατάσταση αισθητήρων. Για τις περισσότερες εκμεταλλεύσεις παρέχουν τις αναγκαίες γεωπονικές πληροφορίες χωρίς περιττό κόστος εξοπλισμού.", pricingKicker: "Απλά και προβλέψιμα προγράμματα", pricingTitle: "Πληρώστε για την κλίμακα που χρειάζεστε, όχι για την εργασία που καταγράφετε.", pricingDescription: "Τα προγράμματα διαφέρουν ανά χρήστες, έκταση, αγροτεμάχια και βάθος μετεωρολογικών δεδομένων. Οι εργασίες, οι συγκομιδές και τα ημερολόγια αγρού παραμένουν χωρίς τεχνητά όρια." },
  sv: { weather: "Virtuella stationer beräknar referensevapotranspiration, solstrålning, uppskattad DLI, växtgraddagar, kylbehov och uppskattad bladväta på distans, utan att du behöver köpa eller installera sensorer. För de flesta gårdar ger de den agronomiska information som behövs för planering och uppföljning utan onödiga hårdvarukostnader.", pricingKicker: "Enkla och förutsägbara planer", pricingTitle: "Betala för den skala du behöver, inte för arbetet du registrerar.", pricingDescription: "Planerna varierar med användare, areal, skiften och meteorologisk detaljnivå. Åtgärder, skördar och fältjournaler förblir fria från konstgjorda gränser." },
  no: { weather: "Virtuelle stasjoner beregner referanse-evapotranspirasjon, solstråling, estimert DLI, vekstgraddager, kuldebehov og estimert bladfuktighet eksternt, uten at du må kjøpe eller installere sensorer. For de fleste gårder gir de den agronomiske informasjonen som trengs for planlegging og oppfølging, uten unødvendige maskinvarekostnader.", pricingKicker: "Enkle og forutsigbare planer", pricingTitle: "Betal for skalaen du trenger, ikke for arbeidet du registrerer.", pricingDescription: "Planene varierer etter brukere, areal, skifter og meteorologisk detaljnivå. Tiltak, innhøstinger og skifteloggbøker har ingen kunstige grenser." },
  da: { weather: "Virtuelle stationer beregner referencefordampning, solstråling, estimeret DLI, vækstgraddage, kuldebehov og estimeret bladvådhed på afstand, uden at du skal købe eller installere sensorer. For de fleste bedrifter giver de den agronomiske information, der er nødvendig for planlægning og opfølgning, uden unødige hardwareomkostninger.", pricingKicker: "Enkle og forudsigelige planer", pricingTitle: "Betal for den skala, du har brug for, ikke for det arbejde, du registrerer.", pricingDescription: "Planerne varierer efter brugere, areal, marker og meteorologisk detaljeniveau. Arbejdsgange, høst og markjournaler forbliver uden kunstige grænser." },
  it: { weather: "Le stazioni virtuali calcolano da remoto evapotraspirazione di riferimento, radiazione solare, DLI stimato, gradi giorno, fabbisogno in freddo e bagnatura fogliare stimata, senza acquistare o installare sensori. Per la maggior parte delle aziende forniscono le informazioni agronomiche necessarie alla pianificazione e al monitoraggio, evitando costi hardware inutili.", pricingKicker: "Piani semplici e prevedibili", pricingTitle: "Paga per la scala che ti serve, non per il lavoro che registri.", pricingDescription: "I piani variano per utenti, superficie, appezzamenti e profondità meteorologica. Operazioni, raccolti e quaderni di campagna restano senza limiti artificiali." },
  uk: { weather: "Віртуальні станції дистанційно розраховують еталонну евапотранспірацію, сонячну радіацію, орієнтовний DLI, градусо-дні, потребу в холоді та орієнтовну вологість листя без придбання чи встановлення датчиків. Для більшості господарств вони дають потрібну агрономічну інформацію без зайвих витрат на обладнання.", pricingKicker: "Прості й передбачувані плани", pricingTitle: "Сплачуйте за потрібний масштаб, а не за роботу, яку реєструєте.", pricingDescription: "Плани відрізняються кількістю користувачів, площею, ділянками та глибиною метеоданих. Операції, врожаї та польові журнали не мають штучних обмежень." },
  ro: { weather: "Stațiile virtuale calculează de la distanță evapotranspirația de referință, radiația solară, DLI estimat, gradele-zile, necesarul de frig și umectarea foliară estimată, fără cumpărarea sau instalarea senzorilor. Pentru majoritatea exploatațiilor oferă informațiile agronomice necesare planificării și monitorizării, evitând costuri hardware inutile.", pricingKicker: "Planuri simple și previzibile", pricingTitle: "Plătiți pentru dimensiunea de care aveți nevoie, nu pentru munca pe care o înregistrați.", pricingDescription: "Planurile variază după utilizatori, suprafață, parcele și profunzimea datelor meteo. Operațiunile, recoltările și registrele de câmp rămân fără limite artificiale." },
  fi: { weather: "Virtuaaliasemat laskevat etänä viite-evapotranspiraation, auringonsäteilyn, arvioidun DLI:n, kasvukauden astepäivät, kylmäntarpeen ja arvioidun lehtikosteuden ilman anturien hankintaa tai asennusta. Useimmille tiloille ne tarjoavat suunnitteluun ja seurantaan tarvittavat agronomiset tiedot ilman tarpeettomia laitekuluja.", pricingKicker: "Selkeät ja ennakoitavat paketit", pricingTitle: "Maksa tarvitsemastasi mittakaavasta, älä kirjaamasi työn määrästä.", pricingDescription: "Paketit vaihtelevat käyttäjien, pinta-alan, lohkojen ja säätietojen syvyyden mukaan. Toimenpiteille, sadonkorjuille ja lohkokirjanpidolle ei aseteta keinotekoisia rajoja." },
  bg: { weather: "Виртуалните станции изчисляват дистанционно референтната евапотранспирация, слънчевата радиация, прогнозния DLI, градусо-дните, нуждите от студ и прогнозното овлажняване на листата, без покупка или монтаж на сензори. За повечето стопанства те осигуряват нужната агрономическа информация без ненужни разходи за оборудване.", pricingKicker: "Прости и предвидими планове", pricingTitle: "Плащайте за необходимия мащаб, а не за работата, която регистрирате.", pricingDescription: "Плановете се различават по потребители, площ, парцели и дълбочина на метеорологичните данни. Операциите, реколтите и дневниците нямат изкуствени ограничения." },
  hu: { weather: "A virtuális állomások távolról számítják a referencia-evapotranszspirációt, a napsugárzást, a becsült DLI-t, a növekedési foknapokat, a hidegigényt és a becsült levélnedvességet, érzékelők megvásárlása vagy telepítése nélkül. A legtöbb gazdaság számára biztosítják a tervezéshez és követéshez szükséges agronómiai információt, felesleges eszközköltség nélkül.", pricingKicker: "Egyszerű és kiszámítható csomagok", pricingTitle: "A szükséges méretért fizessen, ne a rögzített munka mennyiségéért.", pricingDescription: "A csomagok felhasználók, terület, táblák és meteorológiai részletesség szerint változnak. A műveletekre, betakarításokra és táblatörzskönyvekre nem vonatkoznak mesterséges korlátok." },
  is: { weather: "Sýndarveðurstöðvar reikna fjarstýrt viðmiðunargufun, sólgeislun, áætlað DLI, vaxtargráðudaga, kuldaþörf og áætlaðan laufblauta án þess að kaupa eða setja upp skynjara. Fyrir flest bú veita þær nauðsynlegar upplýsingar til skipulagningar og eftirfylgni án óþarfa tækjakostnaðar.", pricingKicker: "Einfaldar og fyrirsjáanlegar áskriftir", pricingTitle: "Greiddu fyrir þá stærð sem þú þarft, ekki fyrir vinnuna sem þú skráir.", pricingDescription: "Áskriftir miðast við notendur, flatarmál, reiti og dýpt veðurupplýsinga. Aðgerðir, uppskera og akraskrár eru áfram án gervilegra takmarkana." },
  sk: { weather: "Virtuálne stanice na diaľku počítajú referenčnú evapotranspiráciu, slnečné žiarenie, odhadované DLI, rastové stupňodní, potrebu chladu a odhadovanú vlhkosť listov bez nákupu či inštalácie senzorov. Väčšine hospodárstiev poskytujú agronomické informácie potrebné na plánovanie a sledovanie bez zbytočných nákladov na hardvér.", pricingKicker: "Jednoduché a predvídateľné plány", pricingTitle: "Plaťte za rozsah, ktorý potrebujete, nie za prácu, ktorú evidujete.", pricingDescription: "Plány sa líšia počtom používateľov, výmerou, parcelami a hĺbkou meteorologických údajov. Zásahy, zbery a poľné denníky zostávajú bez umelých obmedzení." },
  lt: { weather: "Virtualios stotys nuotoliniu būdu apskaičiuoja etaloninę evapotranspiraciją, saulės spinduliuotę, numatomą DLI, augimo laipsniadienius, šalčio poreikį ir numatomą lapų drėgnumą, todėl nereikia pirkti ar montuoti jutiklių. Daugumai ūkių jos suteikia planavimui ir stebėjimui reikalingą agronominę informaciją be nereikalingų įrangos išlaidų.", pricingKicker: "Paprasti ir nuspėjami planai", pricingTitle: "Mokėkite už reikalingą mastą, o ne už registruojamą darbą.", pricingDescription: "Planai skiriasi pagal naudotojus, plotą, laukus ir meteorologinių duomenų išsamumą. Operacijoms, derliui ir lauko žurnalams netaikomi dirbtiniai limitai." },
  sl: { weather: "Virtualne postaje na daljavo izračunavajo referenčno evapotranspiracijo, sončno sevanje, ocenjeno DLI, rastne stopinjske dni, potrebe po hladu in ocenjeno omočenost listov, brez nakupa ali namestitve senzorjev. Večini gospodarstev zagotavljajo agronomske informacije za načrtovanje in spremljanje brez nepotrebnih stroškov opreme.", pricingKicker: "Preprosti in predvidljivi paketi", pricingTitle: "Plačajte za obseg, ki ga potrebujete, ne za delo, ki ga beležite.", pricingDescription: "Paketi se razlikujejo po uporabnikih, površini, parcelah in globini meteoroloških podatkov. Opravila, spravila in poljski dnevniki ostajajo brez umetnih omejitev." },
  lv: { weather: "Virtuālās stacijas attālināti aprēķina references evapotranspirāciju, saules starojumu, aplēsto DLI, augšanas grādu dienas, aukstuma vajadzību un aplēsto lapu mitrumu, neprasot iegādāties vai uzstādīt sensorus. Vairumam saimniecību tās nodrošina plānošanai un uzraudzībai vajadzīgo agronomisko informāciju bez liekām aparatūras izmaksām.", pricingKicker: "Vienkārši un paredzami plāni", pricingTitle: "Maksājiet par vajadzīgo mērogu, nevis par reģistrēto darbu.", pricingDescription: "Plāni atšķiras pēc lietotāju skaita, platības, laukiem un meteoroloģisko datu dziļuma. Darbībām, ražām un lauku žurnāliem nav mākslīgu ierobežojumu." },
};

export function applyHomepagePlanWeatherReview(copies: Record<SupportedLocale, HomepageCopy>) {
  for (const [locale, review] of Object.entries(reviews) as Array<[Exclude<SupportedLocale, "en" | "pt-PT">, PlanWeatherReview]>) {
    const copy = copies[locale];
    copy.weather.description = review.weather;
    Object.assign(copy.pricing, { kicker: review.pricingKicker, title: review.pricingTitle, description: review.pricingDescription });
  }
}
