import { writeFile } from "node:fs/promises";
import { supportedLocales, type SupportedLocale } from "../client/src/home-copy";
import { planCopies } from "../client/src/app/plans/plan-locales.generated";
import { planEnglishCopy, type PlanCopy } from "../client/src/app/plans/plan-copy-source";

type Forms={one:string;other:string;zero?:string;two?:string;few?:string;many?:string};
const forms:Record<SupportedLocale,Forms>={
  "pt-PT":{one:"{count} plano de talhão",other:"{count} planos de talhão"},"pt-BR":{one:"{count} plano de talhão",other:"{count} planos de talhão"},
  en:{one:"{count} field plan",other:"{count} field plans"},fr:{one:"{count} plan de parcelle",other:"{count} plans de parcelle"},es:{one:"{count} plan de parcela",other:"{count} planes de parcela"},nl:{one:"{count} perceelsplan",other:"{count} perceelsplannen"},de:{one:"{count} Schlagplan",other:"{count} Schlagpläne"},ja:{one:"{count}件の圃場計画",other:"{count}件の圃場計画"},he:{one:"תוכנית חלקה אחת ({count})",two:"שתי תוכניות חלקה ({count})",other:"{count} תוכניות חלקה"},tr:{one:"{count} tarla planı",other:"{count} tarla planı"},
  ar:{zero:"{count} من خطط الحقول",one:"{count} خطة حقل",two:"{count} خطتا حقل",few:"{count} خطط حقول",many:"{count} خطة حقل",other:"{count} خطة حقل"},
  pl:{one:"{count} plan pola",few:"{count} plany pól",many:"{count} planów pól",other:"{count} planu pola"},hr:{one:"{count} plan polja",few:"{count} plana polja",many:"{count} planova polja",other:"{count} plana polja"},el:{one:"{count} σχέδιο αγροτεμαχίου",other:"{count} σχέδια αγροτεμαχίων"},sv:{one:"{count} fältplan",other:"{count} fältplaner"},no:{one:"{count} skifteplan",other:"{count} skifteplaner"},da:{one:"{count} markplan",other:"{count} markplaner"},it:{one:"{count} piano di appezzamento",other:"{count} piani di appezzamento"},
  uk:{one:"{count} план поля",few:"{count} плани полів",many:"{count} планів полів",other:"{count} плану поля"},ro:{one:"{count} plan de parcelă",few:"{count} planuri de parcelă",other:"{count} de planuri de parcelă"},fi:{one:"{count} lohkosuunnitelma",other:"{count} lohkosuunnitelmaa"},bg:{one:"{count} план на парцел",other:"{count} плана на парцели"},hu:{one:"{count} táblaterv",other:"{count} táblaterv"},is:{one:"{count} reitáætlun",other:"{count} reitáætlanir"},sk:{one:"{count} plán parcely",few:"{count} plány parciel",many:"{count} plánov parciel",other:"{count} plánu parcely"},lt:{one:"{count} lauko planas",few:"{count} lauko planai",many:"{count} lauko planų",other:"{count} lauko plano"},sl:{one:"{count} načrt polja",two:"{count} načrta polja",few:"{count} načrti polj",other:"{count} načrtov polj"},lv:{zero:"{count} lauku plānu",one:"{count} lauka plāns",other:"{count} lauku plāni"},
};
const result={}as Record<SupportedLocale,PlanCopy>;
for(const locale of supportedLocales){const current=planCopies[locale]as Record<string,string>;const f=forms[locale];result[locale]=Object.fromEntries(Object.keys(planEnglishCopy).map(key=>[key,({fieldOne:f.one,fieldTwo:f.two||f.other,fieldFew:f.few||f.other,fieldMany:f.many||f.other,fieldZero:f.zero||f.other,fieldOther:f.other}as Record<string,string>)[key]||current[key]||planEnglishCopy[key as keyof PlanCopy]]))as PlanCopy;}
result.is.remaining="Vantar upp á markmiðið";
await writeFile(new URL("../client/src/app/plans/plan-locales.generated.ts",import.meta.url),`import type { SupportedLocale } from "../../home-copy";import type { PlanCopy } from "./plan-copy-source";export type { PlanCopy } from "./plan-copy-source";export const planCopies=${JSON.stringify(result,null,2)} as const satisfies Record<SupportedLocale,PlanCopy>;\n`,"utf8");
