import { writeFile } from "node:fs/promises";
import { cropCopies, type CropCopy } from "../client/src/app/crops/crop-locales.generated";
import type { SupportedLocale } from "../client/src/home-copy";

const reviewed = structuredClone(cropCopies) as Record<SupportedLocale, CropCopy>;
const terms: Partial<Record<SupportedLocale, Pick<CropCopy, "crop" | "save" | "emptySearch">>> = {
  "pt-BR": { crop: "Cultura", save: "Salvar variedade", emptySearch: "Nenhuma cultura corresponde a esta pesquisa." },
  fr: { crop: "Culture", save: "Enregistrer la variété", emptySearch: "Aucune culture ne correspond à cette recherche." },
  es: { crop: "Cultivo", save: "Guardar variedad", emptySearch: "Ningún cultivo coincide con esta búsqueda." },
  nl: { crop: "Gewas", save: "Ras opslaan", emptySearch: "Geen gewas komt overeen met deze zoekopdracht." },
  de: { crop: "Kulturpflanze", save: "Sorte speichern", emptySearch: "Keine Kulturpflanze entspricht dieser Suche." },
  ja: { crop: "作物", save: "品種を保存", emptySearch: "この検索に一致する作物はありません。" },
  he: { crop: "גידול", save: "שמירת זן", emptySearch: "אין גידול התואם לחיפוש זה." },
  tr: { crop: "Mahsul", save: "Çeşidi kaydet", emptySearch: "Bu aramayla eşleşen mahsul yok." },
  ar: { crop: "محصول", save: "حفظ الصنف", emptySearch: "لا يوجد محصول يطابق هذا البحث." },
  pl: { crop: "Uprawa", save: "Zapisz odmianę", emptySearch: "Żadna uprawa nie pasuje do tego wyszukiwania." },
  hr: { crop: "Usjev", save: "Spremi sortu", emptySearch: "Nijedan usjev ne odgovara ovoj pretrazi." },
  el: { crop: "Καλλιέργεια", save: "Αποθήκευση ποικιλίας", emptySearch: "Καμία καλλιέργεια δεν αντιστοιχεί σε αυτήν την αναζήτηση." },
  sv: { crop: "Gröda", save: "Spara sort", emptySearch: "Ingen gröda matchar sökningen." },
  no: { crop: "Avling", save: "Lagre sort", emptySearch: "Ingen avling samsvarer med søket." },
  da: { crop: "Afgrøde", save: "Gem sort", emptySearch: "Ingen afgrøde matcher søgningen." },
  it: { crop: "Coltura", save: "Salva varietà", emptySearch: "Nessuna coltura corrisponde alla ricerca." },
  uk: { crop: "Культура", save: "Зберегти сорт", emptySearch: "Жодна культура не відповідає цьому пошуку." },
  ro: { crop: "Cultură", save: "Salvează soiul", emptySearch: "Nicio cultură nu corespunde acestei căutări." },
  fi: { crop: "Viljelykasvi", save: "Tallenna lajike", emptySearch: "Mikään viljelykasvi ei vastaa hakua." },
  bg: { crop: "Култура", save: "Запазване на сорта", emptySearch: "Никоя култура не съответства на търсенето." },
  hu: { crop: "Termény", save: "Fajta mentése", emptySearch: "Egyetlen termény sem felel meg a keresésnek." },
  sk: { crop: "Plodina", save: "Uložiť odrodu", emptySearch: "Tomuto vyhľadávaniu nezodpovedá žiadna plodina." },
  lt: { crop: "Pasėlis", save: "Išsaugoti veislę", emptySearch: "Joks pasėlis neatitinka šios paieškos." },
  sl: { crop: "Pridelek", save: "Shrani sorto", emptySearch: "Noben pridelek ne ustreza temu iskanju." },
  lv: { crop: "Kultūraugs", save: "Saglabāt šķirni", emptySearch: "Neviens kultūraugs neatbilst šim meklējumam." },
};
for (const [locale, copy] of Object.entries(terms)) Object.assign(reviewed[locale as SupportedLocale], copy);
reviewed.is = { kicker: "Landbúnaðarskrá", title: "Ræktunartegundir og yrki", description: "Notaðu stöðuga skrá yfir ræktunartegundir og haltu utan um yrki stofnunarinnar.", cultures: "Ræktunartegundir", varieties: "Yrki", search: "Leita að ræktunartegundum", sourceDesignation: "Portúgölsk upprunaheiti", sourceNotice: "Sögulega skráin inniheldur 106 aðgreind portúgölsk upprunaheiti. Þau eru sýnd sem upprunagögn og eru ekki rangþýdd í kyrrþey.", records: "{count} ræktunartegundir", emptySearch: "Engin ræktunartegund samsvarar leitinni.", addVariety: "Nýtt yrki", varietyName: "Heiti yrkis", crop: "Ræktunartegund", save: "Vista yrki", cancel: "Hætta við", emptyVarieties: "Engin yrki hafa verið skráð enn.", loadError: "Ekki tókst að hlaða ræktunarskránni.", saveError: "Ekki tókst að vista yrkið.", customValueNotice: "Heiti sem stofnunin skráir varðveitast á upprunalegu tungumáli.", provenance: "Uppruni eldri skrár", duplicateRemoved: "Ein tvítekin upprunalína var fjarlægð." };

const keys = Object.keys(reviewed.en);
const keyUnion = keys.map((key) => JSON.stringify(key)).join(" | ");
const output = `// Generated by script/generate-crop-locales.ts and agronomically reviewed by script/review-crop-locales.ts.\nimport type { SupportedLocale } from "../../home-copy";\nexport type CropCopy = Record<${keyUnion}, string>;\nexport const cropCopies = ${JSON.stringify(reviewed, null, 2)} as const satisfies Record<SupportedLocale, CropCopy>;\n`;
await writeFile(new URL("../client/src/app/crops/crop-locales.generated.ts", import.meta.url), output, "utf8");
