import { writeFile } from "node:fs/promises";
import { operationCopies } from "../client/src/app/operations/operation-locales.generated";
import type { SupportedLocale } from "../client/src/home-copy";

const concepts = { actionSubsoiling: "subsoiling", actionPloughing: "ploughing", actionScarifying: "soil scarification", actionHarrowing: "harrowing", actionRotaryTilling: "rotary cultivation", actionLevelling: "land levelling", actionBedForming: "raised bed cultivation", actionFurrowOpening: "furrow opening", actionStoneRemoval: "stone clearing", actionResidueShredding: "crop residue shredding", actionResidueIncorporation: "crop residue incorporation", actionSolarisation: "soil solarisation" } as const;
const language: Record<SupportedLocale, string> = { "pt-PT": "pt", "pt-BR": "pt-BR", en: "en", fr: "fr", es: "es", nl: "nl", de: "de", ja: "ja", he: "he", tr: "tr", ar: "ar", pl: "pl", hr: "hr", el: "el", sv: "sv", no: "nb", da: "da", it: "it", uk: "uk", ro: "ro", fi: "fi", bg: "bg", hu: "hu", is: "is", sk: "sk", lt: "lt", sl: "sl", lv: "lv" };
async function json(url: string) { const response = await fetch(url, { headers: { accept: "application/json" }, signal: AbortSignal.timeout(40000) }); if (!response.ok) throw new Error(`${response.status}:${url}`); return response.json() as Promise<Record<string, unknown>>; }
const reviewed: Record<string, Record<string, string>> = structuredClone(operationCopies);
await Promise.all(Object.entries(concepts).map(async ([key, query]) => { const search = await json(`https://agrovoc.fao.org/browse/rest/v1/search/?query=${encodeURIComponent(query)}&lang=en`) as { results?: Array<{ uri: string; prefLabel: string }> }; const match = search.results?.find((item) => item.prefLabel.toLowerCase() === query); if (!match) return; const data = await json(`https://agrovoc.fao.org/browse/rest/v1/data/?uri=${encodeURIComponent(match.uri)}`) as { graph?: Array<{ uri: string; prefLabel?: Array<{ lang: string; value: string }> }> }; const labels = data.graph?.find((item) => item.uri === match.uri)?.prefLabel || []; for (const [locale, code] of Object.entries(language)) { const label = labels.find((item) => item.lang === code) || (locale === "pt-BR" ? labels.find((item) => item.lang === "pt") : undefined); if (label) reviewed[locale][key] = label.value; } }));
Object.assign(reviewed.de, { actionSubsoiling: "Untergrundlockerung" }); Object.assign(reviewed.ja, { actionSubsoiling: "心土破砕" }); Object.assign(reviewed.it, { actionSubsoiling: "Ripuntatura" }); Object.assign(reviewed.hu, { actionSubsoiling: "Altalajlazítás" }); Object.assign(reviewed.pl, { actionSubsoiling: "Głęboszowanie" }); Object.assign(reviewed.ro, { actionSubsoiling: "Subsolaj" }); Object.assign(reviewed.sk, { actionSubsoiling: "Podrývanie" }); Object.assign(reviewed.tr, { actionSubsoiling: "Dipkazanla toprak işleme" }); Object.assign(reviewed.ar, { actionSubsoiling: "حراثة تحت التربة" });
const corrections: Partial<Record<SupportedLocale, Record<string, string>>> = {
  en:{actionBedForming:"Raised-bed forming",actionFurrowOpening:"Furrow opening",actionSolarisation:"Soil solarisation"},
  "pt-PT":{actionPloughing:"Lavoura",actionScarifying:"Escarificação",actionHarrowing:"Gradagem",actionRotaryTilling:"Fresagem",actionBedForming:"Formação de camalhões",actionFurrowOpening:"Abertura de regos",actionStoneRemoval:"Despedrega"},
  "pt-BR":{passes:"Número de passadas",actionPloughing:"Aração",actionScarifying:"Escarificação",actionHarrowing:"Gradagem",actionRotaryTilling:"Fresagem",actionBedForming:"Formação de canteiros",actionFurrowOpening:"Abertura de sulcos",actionStoneRemoval:"Retirada de pedras"},
  fr:{actionScarifying:"Scarification du sol",actionRotaryTilling:"Fraisage",actionBedForming:"Formation de billons",actionFurrowOpening:"Ouverture de sillons",actionStoneRemoval:"Épierrage"},
  es:{actionPloughing:"Arado",actionHarrowing:"Rastreo",actionRotaryTilling:"Fresado",actionBedForming:"Formación de caballones",actionFurrowOpening:"Apertura de surcos",actionStoneRemoval:"Despedregado"},
  nl:{actionSubsoiling:"Diepwoelen",actionScarifying:"Bodemwoeling",actionHarrowing:"Eggen",actionRotaryTilling:"Frezen",actionBedForming:"Bedden vormen",actionFurrowOpening:"Voren trekken",actionStoneRemoval:"Stenen verwijderen",incorporated:"Ingewerkt"},
  de:{actionScarifying:"Bodenlockerung",actionBedForming:"Dammformung",actionFurrowOpening:"Furchenziehen",actionStoneRemoval:"Steinräumung",incorporated:"Eingearbeitet"},
  ja:{soilActions:"土壌準備作業",residueDestination:"作物残さの処理",dry:"乾燥",moist:"適湿",wet:"過湿",left:"土壌表面に残置",shredded:"粉砕",incorporated:"すき込み",removed:"搬出",burned:"焼却",actionScarifying:"土壌の掻き起こし",actionHarrowing:"砕土",actionBedForming:"畝立て",actionFurrowOpening:"溝切り",actionStoneRemoval:"除礫"},
  he:{actionSubsoiling:"עיבוד תת־קרקעי",actionScarifying:"תחיחת קרקע",actionHarrowing:"שידוד",actionRotaryTilling:"תיחוח סיבובי",actionBedForming:"יצירת ערוגות מוגבהות",actionFurrowOpening:"פתיחת תלמים",actionStoneRemoval:"סיקול אבנים",shredded:"קצוץ",incorporated:"הוצנע בקרקע"},
  tr:{residueDestination:"Bitki artıklarının akıbeti",shredded:"Parçalandı",incorporated:"Toprağa karıştırıldı",actionHarrowing:"Tırmıklama",actionBedForming:"Sırt oluşturma",actionFurrowOpening:"Karık açma"},
  ar:{residueDestination:"مصير بقايا المحاصيل",shredded:"مفرومة",incorporated:"مدمجة في التربة",removed:"مُزالة",burned:"محروقة",actionScarifying:"تفكيك التربة",actionHarrowing:"تمشيط التربة",actionRotaryTilling:"حراثة دورانية",actionBedForming:"تشكيل المصاطب",actionFurrowOpening:"فتح الأخاديد"},
  pl:{residueDestination:"Przeznaczenie resztek pożniwnych",incorporated:"Wymieszane z glebą",actionRotaryTilling:"Glebogryzowanie",actionBedForming:"Formowanie zagonów",actionFurrowOpening:"Otwieranie bruzd"},
  hr:{soilActions:"Radovi pripreme tla",actionSubsoiling:"Podrivanje",actionScarifying:"Rahljenje tla",actionHarrowing:"Drljanje",actionRotaryTilling:"Frezanje",actionBedForming:"Formiranje gredica",actionFurrowOpening:"Otvaranje brazdi",actionStoneRemoval:"Uklanjanje kamenja",incorporated:"Uneseni u tlo"},
  el:{moist:"Νωπό",wet:"Υδατοκορεσμένο",incorporated:"Ενσωματωμένα",removed:"Απομακρυσμένα",actionSubsoiling:"Βαθιά κατεργασία εδάφους",actionScarifying:"Σκαριφάρισμα εδάφους",actionHarrowing:"Σβάρνισμα",actionRotaryTilling:"Φρεζάρισμα",actionBedForming:"Διαμόρφωση αναχωμάτων",actionFurrowOpening:"Διάνοιξη αυλακιών",actionStoneRemoval:"Απομάκρυνση λίθων"},
  sv:{actionSubsoiling:"Alvluckring",actionScarifying:"Markrivning",actionHarrowing:"Harvning",actionRotaryTilling:"Jordfräsning",actionBedForming:"Bäddformning",actionStoneRemoval:"Stenröjning"},
  no:{actionSubsoiling:"Dypjordløsning",actionScarifying:"Jordløsning",actionHarrowing:"Harving",actionRotaryTilling:"Jordfresing",actionBedForming:"Bedforming",actionStoneRemoval:"Steinrydding"},
  da:{passes:"Antal overkørsler",actionSubsoiling:"Grubning",actionScarifying:"Jordløsning",actionHarrowing:"Harvning",actionRotaryTilling:"Jordfræsning",actionBedForming:"Bedformning",actionStoneRemoval:"Stenrydning"},
  it:{actionBedForming:"Formazione di baulature",actionFurrowOpening:"Apertura dei solchi"},
  uk:{incorporated:"Зароблені в ґрунт",actionSubsoiling:"Глибоке розпушування ґрунту",actionScarifying:"Скарифікація ґрунту",actionHarrowing:"Боронування",actionRotaryTilling:"Фрезерування ґрунту",actionBedForming:"Формування гряд",actionFurrowOpening:"Нарізання борозен",actionStoneRemoval:"Видалення каміння"},
  ro:{moist:"Reavăn",wet:"Umed",actionPloughing:"Arat",actionScarifying:"Scarificarea solului",actionHarrowing:"Grăpat",actionRotaryTilling:"Frezarea solului",actionBedForming:"Formarea biloanelor",actionFurrowOpening:"Deschiderea brazdelor",actionStoneRemoval:"Îndepărtarea pietrelor"},
  fi:{incorporated:"Maahan sekoitettu",actionSubsoiling:"Jankkurointi",actionScarifying:"Maan kuohkeutus",actionHarrowing:"Äestys",actionRotaryTilling:"Jyrsintä",actionBedForming:"Penkkien muodostus",actionFurrowOpening:"Vakojen avaus",actionStoneRemoval:"Kivien poisto"},
  bg:{passes:"Брой преминавания",actionSubsoiling:"Продълбочаване",actionScarifying:"Разрохкване на почвата",actionHarrowing:"Брануване",actionRotaryTilling:"Фрезоване",actionBedForming:"Оформяне на лехи",actionFurrowOpening:"Отваряне на бразди",actionStoneRemoval:"Почистване на камъни"},
  hu:{passes:"Menetszám",moist:"Nyirkos",wet:"Nedves",actionScarifying:"Talajlazítás",actionHarrowing:"Boronálás",actionRotaryTilling:"Talajmarás",actionBedForming:"Ágyáskészítés",actionFurrowOpening:"Barázdanyitás",actionStoneRemoval:"Kőeltávolítás"},
  is:{passes:"Fjöldi yfirferða",moist:"Rakt",actionSubsoiling:"Djúplosun jarðvegs",actionScarifying:"Jarðvegslosun",actionHarrowing:"Herfing",actionRotaryTilling:"Jarðvegsfræsing",actionBedForming:"Beðamótun",actionFurrowOpening:"Rásagerð",actionStoneRemoval:"Grjóthreinsun"},
  sk:{passes:"Počet prejazdov",incorporated:"Zapracované do pôdy",actionScarifying:"Kyprenie pôdy",actionHarrowing:"Bránenie",actionRotaryTilling:"Frézovanie pôdy",actionBedForming:"Tvarovanie záhonov",actionFurrowOpening:"Otváranie brázd",actionStoneRemoval:"Odstraňovanie kameňov"},
  lt:{incorporated:"Įterpta į dirvą",actionSubsoiling:"Podirvio purenimas",actionScarifying:"Dirvos purenimas",actionHarrowing:"Akėjimas",actionRotaryTilling:"Dirvos frezavimas",actionBedForming:"Lysvių formavimas",actionFurrowOpening:"Vagų atvėrimas",actionStoneRemoval:"Akmenų šalinimas"},
  sl:{moist:"Vlažna",incorporated:"Vdelani v tla",actionSubsoiling:"Podrahljavanje",actionScarifying:"Rahljanje tal",actionHarrowing:"Brananje",actionRotaryTilling:"Frezanje tal",actionBedForming:"Oblikovanje gred",actionFurrowOpening:"Odpiranje brazd",actionStoneRemoval:"Odstranjevanje kamenja"},
  lv:{passes:"Braucienu skaits",incorporated:"Iestrādātas augsnē",actionSubsoiling:"Dziļirdināšana",actionScarifying:"Augsnes irdināšana",actionHarrowing:"Ecēšana",actionRotaryTilling:"Augsnes frēzēšana",actionBedForming:"Dobju veidošana",actionFurrowOpening:"Vagu atvēršana",actionStoneRemoval:"Akmeņu novākšana"}
};
for(const [locale,values] of Object.entries(corrections))Object.assign(reviewed[locale],values);
const union = Object.keys(reviewed.en).map((key) => JSON.stringify(key)).join(" | "); await writeFile(new URL("../client/src/app/operations/operation-locales.generated.ts", import.meta.url), `import type { SupportedLocale } from "../../home-copy";export type OperationCopy=Record<${union},string>;export const operationCopies=${JSON.stringify(reviewed, null, 2)} as const satisfies Record<SupportedLocale,OperationCopy>;\n`, "utf8");
