import { writeFile } from "node:fs/promises";
import { resourceCopies, type ResourceCopy } from "../client/src/app/resources/resource-locales.generated";
import type { SupportedLocale } from "../client/src/home-copy";

const reviewed = structuredClone(resourceCopies) as Record<SupportedLocale, ResourceCopy>;
const overrides: Partial<Record<SupportedLocale, Partial<ResourceCopy>>> = {
  fr: { contractors: "Prestataires de services" }, es: { contractors: "Prestadores de servicios" },
  nl: { contractors: "Loonwerkers", equipment: "Materieel", applicator: "Toepasser van gewasbeschermingsmiddelen" },
  de: { workers: "Mitarbeitende", contractors: "Dienstleister", equipment: "Maschinen und Geräte", applicator: "Sachkundiger Anwender von Pflanzenschutzmitteln", implement: "Anbaugerät", sprayer: "Pflanzenschutzspritze" },
  ja: { applicator: "農薬散布者" }, he: { applicator: "מפעיל תכשירי הגנת הצומח" }, tr: { contractors: "Hizmet sağlayıcılar", applicator: "Bitki koruma ürünü uygulayıcısı" }, ar: { implement: "معدّة زراعية" },
  pl: { applicator: "Operator środków ochrony roślin", implement: "Maszyna rolnicza" }, hr: { sprayer: "Prskalica", implement: "Poljoprivredni priključak" }, el: { applicator: "Χειριστής φυτοπροστατευτικών προϊόντων" },
  sv: { sprayer: "Växtskyddsspruta" }, no: { sprayer: "Åkersprøyte" }, da: { applicator: "Sprøjtefører", sprayer: "Marksprøjte" },
  it: { contractors: "Fornitori di servizi", implement: "Attrezzo agricolo", sprayer: "Irroratrice" }, uk: { applicator: "Оператор засобів захисту рослин", sprayer: "Обприскувач" }, ro: { contractors: "Prestatori de servicii", implement: "Utilaj agricol" },
  fi: { contractors: "Urakoitsijat", applicator: "Kasvinsuojeluaineiden käyttäjä", implement: "Maatalouskone", sprayer: "Kasvinsuojeluruisku" }, bg: { applicator: "Оператор на продукти за растителна защита" }, hu: { applicator: "Növényvédőszer-kijuttató" },
  is: { workers: "Starfsfólk", contractors: "Þjónustuaðilar", applicator: "Notandi plöntuverndarvara" }, sk: { workers: "Pracovníci" }, sl: { contractors: "Izvajalci storitev", sprayer: "Škropilnica" }, lv: { contractors: "Pakalpojumu sniedzēji", applicator: "Augu aizsardzības līdzekļu lietotājs" },
};
for (const [locale, copy] of Object.entries(overrides)) Object.assign(reviewed[locale as SupportedLocale], copy);
const union = Object.keys(reviewed.en).map((key) => JSON.stringify(key)).join(" | ");
await writeFile(new URL("../client/src/app/resources/resource-locales.generated.ts", import.meta.url), `// Generated by script/generate-resource-locales.ts and agronomically reviewed by script/review-resource-locales.ts.\nimport type { SupportedLocale } from "../../home-copy";\nexport type ResourceCopy=Record<${union},string>;\nexport const resourceCopies=${JSON.stringify(reviewed, null, 2)} as const satisfies Record<SupportedLocale,ResourceCopy>;\n`, "utf8");
