import type { SupportedLocale } from "../../home-copy";
import { homepageCopies } from "../../home-locales.generated";
import { workspaceCopies } from "../workspace-locales";
import { planCopies } from "../plans/plan-locales.generated";
import { resourceCopies } from "../resources/resource-locales.generated";
import { operationCopies } from "./operation-locales.generated";

const en = { kicker:"Water management",title:"Irrigation, meters and fertigation",description:"Record one physical operation and project it without duplicating water, products, nutrients, resources or costs.",physicalNotice:"A single physical operation feeds operations, performed fertilization, plan balances and the field notebook.",irrigations:"Irrigation",sectors:"Sectors",meters:"Meters",analyses:"Water analyses",readings:"Readings",undistributed:"Undistributed consumption",addIrrigation:"Record irrigation",addSector:"Create sector",addMeter:"Create meter",addAnalysis:"Add analysis",weekly:"Weekly schedule",performed:"Performed",performedBySchedule:"Performed by schedule",reversed:"Reversed",reverse:"Reverse",volume:"Volume",dose:"Dose",depth:"Depth",flow:"Flow",duration:"Duration",fertigation:"Fertigation",product:"Product",totalQuantity:"Total quantity",holding:"Holding",code:"Code",name:"Name",system:"Irrigation system",serial:"Serial number",drip:"Drip",sprinkler:"Sprinkler",gravity:"Gravity",date:"Date",weekEnd:"Farm week end",source:"Input source",status:"Status",save:"Save",cancel:"Cancel",noData:"No records yet.",loadError:"Irrigation data could not be loaded." } as const;
export type IrrigationCopy = { [K in keyof typeof en]: string };
const core: Record<SupportedLocale, [string,string,string,string,string,string,string,string,string,string]> = {
  "pt-PT":["Gestão da água","Rega, contadores e fertirrega","Rega","Setores","Contadores","Análises de água","Leituras","Consumo não distribuído","Programação semanal","Realizada por programação"],
  "pt-BR":["Gestão da água","Irrigação, medidores e fertirrigação","Irrigação","Setores","Medidores","Análises de água","Leituras","Consumo não distribuído","Programação semanal","Realizada por programação"],
  en:[en.kicker,en.title,en.irrigations,en.sectors,en.meters,en.analyses,en.readings,en.undistributed,en.weekly,en.performedBySchedule],
  fr:["Gestion de l’eau","Irrigation, compteurs et fertigation","Irrigation","Secteurs","Compteurs","Analyses de l’eau","Relevés","Consommation non répartie","Programmation hebdomadaire","Réalisée selon la programmation"],
  es:["Gestión del agua","Riego, contadores y fertirrigación","Riego","Sectores","Contadores","Análisis de agua","Lecturas","Consumo no distribuido","Programación semanal","Realizada por programación"],
  nl:["Waterbeheer","Irrigatie, meters en fertigatie","Irrigatie","Sectoren","Meters","Wateranalyses","Meterstanden","Niet-toegewezen verbruik","Weekplanning","Uitgevoerd volgens planning"],
  de:["Wassermanagement","Bewässerung, Zähler und Fertigation","Bewässerung","Sektoren","Zähler","Wasseranalysen","Ablesungen","Nicht verteilter Verbrauch","Wochenplanung","Nach Planung durchgeführt"],
  ja:["水管理","灌水・メーター・液肥灌水","灌水","セクター","メーター","水質分析","検針値","未配分使用量","週間予定","予定により実施"],
  he:["ניהול מים","השקיה, מונים ודישון בהשקיה","השקיה","מגזרים","מונים","בדיקות מים","קריאות","צריכה לא מחולקת","תכנית שבועית","בוצע לפי תכנית"],
  tr:["Su yönetimi","Sulama, sayaçlar ve fertigasyon","Sulama","Sektörler","Sayaçlar","Su analizleri","Okumalar","Dağıtılmamış tüketim","Haftalık program","Programa göre gerçekleştirildi"],
  ar:["إدارة المياه","الري والعدادات والتسميد بالري","الري","القطاعات","العدادات","تحاليل المياه","القراءات","استهلاك غير موزع","البرنامج الأسبوعي","نُفّذت حسب البرنامج"],
  pl:["Gospodarka wodna","Nawadnianie, liczniki i fertygacja","Nawadnianie","Sekcje","Liczniki","Analizy wody","Odczyty","Zużycie nierozdzielone","Plan tygodniowy","Wykonano według planu"],
  hr:["Upravljanje vodom","Navodnjavanje, brojila i fertirigacija","Navodnjavanje","Sektori","Brojila","Analize vode","Očitanja","Neraspoređena potrošnja","Tjedni raspored","Izvršeno prema rasporedu"],
  el:["Διαχείριση νερού","Άρδευση, μετρητές και υδρολίπανση","Άρδευση","Τομείς","Μετρητές","Αναλύσεις νερού","Μετρήσεις","Μη κατανεμημένη κατανάλωση","Εβδομαδιαίο πρόγραμμα","Εκτελέστηκε βάσει προγράμματος"],
  sv:["Vattenhantering","Bevattning, mätare och fertigering","Bevattning","Sektioner","Mätare","Vattenanalyser","Avläsningar","Ofördelad förbrukning","Veckoplan","Utförd enligt plan"],
  no:["Vannstyring","Vanning, målere og gjødselvanning","Vanning","Sektorer","Målere","Vannanalyser","Avlesninger","Ufordelt forbruk","Ukeplan","Utført etter plan"],
  da:["Vandstyring","Vanding, målere og gødevanding","Vanding","Sektorer","Målere","Vandanalyser","Aflæsninger","Ikke-fordelt forbrug","Ugeplan","Udført efter plan"],
  it:["Gestione dell’acqua","Irrigazione, contatori e fertirrigazione","Irrigazione","Settori","Contatori","Analisi dell’acqua","Letture","Consumo non distribuito","Programma settimanale","Eseguita da programma"],
  uk:["Управління водою","Зрошення, лічильники та фертигація","Зрошення","Сектори","Лічильники","Аналізи води","Показники","Нерозподілене споживання","Тижневий графік","Виконано за графіком"],
  ro:["Gestionarea apei","Irigare, contoare și fertirigare","Irigare","Sectoare","Contoare","Analize de apă","Citiri","Consum nedistribuit","Program săptămânal","Realizată conform programării"],
  fi:["Vesien hallinta","Kastelu, mittarit ja lannoitekastelu","Kastelu","Sektorit","Mittarit","Vesianalyysit","Lukemat","Kohdistamaton kulutus","Viikko-ohjelma","Toteutettu ohjelman mukaan"],
  bg:["Управление на водата","Напояване, водомери и фертигация","Напояване","Сектори","Водомери","Анализи на вода","Показания","Неразпределено потребление","Седмична програма","Извършено по програма"],
  hu:["Vízgazdálkodás","Öntözés, mérők és tápoldatozás","Öntözés","Szektorok","Mérők","Vízelemzések","Leolvasások","Fel nem osztott fogyasztás","Heti program","Program szerint elvégezve"],
  is:["Vatnsstjórnun","Vökvun, mælar og áburðargjöf með vökvun","Vökvun","Svæði","Mælar","Vatnsgreiningar","Álestrar","Óúthlutuð notkun","Vikuáætlun","Framkvæmt samkvæmt áætlun"],
  sk:["Vodné hospodárstvo","Zavlažovanie, merače a fertigácia","Zavlažovanie","Sektory","Merače","Analýzy vody","Odpočty","Nerozdelená spotreba","Týždenný plán","Vykonané podľa plánu"],
  lt:["Vandens valdymas","Drėkinimas, skaitikliai ir fertigacija","Drėkinimas","Sektoriai","Skaitikliai","Vandens tyrimai","Rodmenys","Nepaskirstytas suvartojimas","Savaitės programa","Atlikta pagal programą"],
  sl:["Upravljanje vode","Namakanje, števci in fertigacija","Namakanje","Sektorji","Števci","Analize vode","Odčitki","Nerazporejena poraba","Tedenski program","Izvedeno po programu"],
  lv:["Ūdens pārvaldība","Apūdeņošana, skaitītāji un fertigācija","Apūdeņošana","Sektori","Skaitītāji","Ūdens analīzes","Rādījumi","Nesadalītais patēriņš","Nedēļas programma","Izpildīts pēc programmas"],
};
const systems:Record<SupportedLocale,[string,string,string]>={"pt-PT":["Gota-a-gota","Aspersão","Gravidade"],"pt-BR":["Gotejamento","Aspersão","Gravidade"],en:["Drip","Sprinkler","Gravity"],fr:["Goutte-à-goutte","Aspersion","Gravité"],es:["Goteo","Aspersión","Gravedad"],nl:["Druppel","Beregening","Zwaartekracht"],de:["Tropf","Beregnung","Schwerkraft"],ja:["点滴","散水","重力"],he:["טפטוף","המטרה","כבידה"],tr:["Damla","Yağmurlama","Cazibe"],ar:["تنقيط","رش","جاذبية"],pl:["Kroplowe","Zraszanie","Grawitacyjne"],hr:["Kap po kap","Raspršivanje","Gravitacijsko"],el:["Στάγδην","Καταιονισμός","Βαρύτητα"],sv:["Dropp","Sprinkler","Självfall"],no:["Drypp","Spreder","Tyngdekraft"],da:["Dryp","Sprinkler","Tyngdekraft"],it:["Goccia","Aspersione","Gravità"],uk:["Крапельне","Дощування","Самоплив"],ro:["Picurare","Aspersiune","Gravitațional"],fi:["Tippu","Sadetus","Painovoima"],bg:["Капково","Дъждуване","Гравитачно"],hu:["Csepegtető","Esőztető","Gravitációs"],is:["Dreypi","Úðari","Þyngdarafl"],sk:["Kvapkové","Postrekovanie","Gravitačné"],lt:["Lašelinis","Purkštuvai","Savitakis"],sl:["Kapljično","Razprševanje","Gravitacijsko"],lv:["Pilienveida","Smidzināšana","Pašteces"]};
export const irrigationCopies = Object.fromEntries(Object.entries(core).map(([localeCode, values]) => {const locale=localeCode as SupportedLocale;const operation=operationCopies[locale],resource=resourceCopies[locale],plan=planCopies[locale],home=homepageCopies[locale],workspace=workspaceCopies[locale],[drip,sprinkler,gravity]=systems[locale];return[locale,{...en,kicker:values[0],title:values[1],description:home.flow.description,physicalNotice:operation.sharedNotice,irrigations:values[2],sectors:values[3],meters:values[4],analyses:values[5],readings:values[6],undistributed:values[7],addIrrigation:operation.add,addSector:values[3],addMeter:values[4],addAnalysis:values[5],weekly:values[8],performed:operation.performed,performedBySchedule:values[9],reversed:operation.cancel,reverse:operation.cancel,volume:"m³",dose:operation.dosePerHa,depth:operation.depthCm,flow:"m³/h",duration:operation.duration,fertigation:operation.fertigation,product:operation.productName,totalQuantity:operation.totalQuantity,holding:workspace.organization,code:operation.code,name:resource.name,system:resource.irrigation,serial:resource.number,drip,sprinkler,gravity,date:operation.performedAt,weekEnd:values[8],source:operation.origin,status:operation.type,save:operation.save,cancel:operation.cancel,noData:operation.empty,loadError:operation.loadError}]})) as Record<SupportedLocale, IrrigationCopy>;
