import { useCallback, useEffect, useId, useMemo, useState, type FormEvent } from "react";
import type { FieldDto } from "@shared/fields";
import type { FarmHoldingDto } from "@shared/farm-holdings";
import type { IrrigationOverviewDto } from "@shared/irrigation";
import { useI18n } from "../../i18n";
import { useAuth } from "../../auth";
import { AccessibleDialog, DialogError } from "../../components/AccessibleDialog";
import { Alert, Button, EmptyState, Skeleton } from "../../design-system";
import { irrigationCopies } from "./irrigation-locales";
import "./irrigation.css";
import { formatLocalDate } from "../locale-format";

type Props = { fields: FieldDto[]; onPhysicalOperationChanged: () => Promise<void> };
type Tab = "irrigations" | "sectors" | "meters" | "analyses";
const empty: IrrigationOverviewDto = { sectors: [], meters: [], readings: [], analyses: [], irrigations: [], reconciliations: [], undistributedConsumptionM3: 0 };

async function request(url: string, method = "GET", body?: unknown) {
  const response = await fetch(url, { method, credentials: "include", headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.code || "REQUEST_FAILED");
  return response.json();
}

export default function IrrigationPanel({ fields, onPhysicalOperationChanged }: Props) {
  const { locale } = useI18n(); const t = irrigationCopies[locale];
  const {session}=useAuth();const permissions=session?.access.applicationMembership.permissions||[];const canWrite=Boolean(session?.access.access.writeAllowed&&(permissions.includes("*")||permissions.includes("irrigation.manage")||permissions.includes("operations.manage")||permissions.includes("operations.create")));
  const [data, setData] = useState(empty); const [holdings, setHoldings] = useState<FarmHoldingDto[]>([]); const [tab, setTab] = useState<Tab>("irrigations"); const [dialog, setDialog] = useState<Tab | "reading" | null>(null); const [failed, setFailed] = useState(false);const[loading,setLoading]=useState(true);
  const load = useCallback(async () => { setLoading(true);try { const [irrigation, farms] = await Promise.all([request("/api/farm/irrigation"), request("/api/farm/holdings")]); setData(irrigation.data); setHoldings(farms.data); setFailed(false); } catch { setFailed(true); }finally{setLoading(false)} }, []);
  useEffect(() => { void load(); }, [load]);
  const sectorById = useMemo(() => new Map(data.sectors.map((row) => [row.id, row])), [data.sectors]);
  const actionDisabled = !canWrite || (tab === "sectors" ? !holdings.length || !fields.length : !data.sectors.length);
  const actionLabel = tab === "irrigations" ? t.addIrrigation : tab === "sectors" ? t.addSector : tab === "meters" ? t.addMeter : t.addAnalysis;
  async function reverse(id: string) { if(!window.confirm(t.reverse))return;try{await request(`/api/farm/irrigation/records/${id}/reverse`, "POST"); await Promise.all([load(), onPhysicalOperationChanged()]);}catch{setFailed(true)} }
  return <section className="panel irrigation-panel">
    <header><div><p>{t.kicker}</p><h2>{t.title}</h2><span>{t.description}</span></div><div className="irrigation-heading-actions"><strong>{data.undistributedConsumptionM3.toLocaleString(locale)} m³<small>{t.undistributed}</small></strong><Button onClick={() => setDialog(tab)} disabled={actionDisabled}>＋ {actionLabel}</Button></div></header>
    <Alert tone="info">{t.physicalNotice}</Alert>
    <nav>{(["irrigations", "sectors", "meters", "analyses"] as Tab[]).map((id) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{t[id]}</button>)}</nav>
    {loading?<div className="module-state"><Skeleton label={t.title}/></div>:failed ? <Alert tone="danger">{t.loadError}</Alert> : tab === "irrigations" ? <div className="irrigation-list">{data.irrigations.map((row) => <article key={row.id}><div><code>{row.operationCode || t.weekly}</code><b>{row.status === "performed_by_schedule" ? t.performedBySchedule : row.status === "scheduled" ? t.weekly : row.status === "reversed" ? t.reversed : t.performed}</b><span>{row.applications.map((item) => sectorById.get(item.sectorId)?.name).filter(Boolean).join(" · ")}</span></div><dl><div><dt>{t.volume}</dt><dd>{row.volumeM3.toLocaleString(locale)} m³</dd></div><div><dt>{t.dose}</dt><dd>{row.doseM3Ha.toLocaleString(locale)} m³/ha</dd></div><div><dt>{t.depth}</dt><dd>{row.depthMm.toLocaleString(locale)} mm</dd></div></dl><em>{row.projectionKinds.join(" · ")}</em>{["performed", "performed_by_schedule"].includes(row.status) && <button disabled={!canWrite} onClick={() => void reverse(row.id)}>{t.reverse}</button>}</article>)}{!data.irrigations.length && <EmptyState title={t.noData}/>}</div>
      : tab === "sectors" ? <div className="irrigation-cards">{data.sectors.map((row) => <article key={row.id}><code>{row.code}</code><h3>{row.name}</h3><p>{row.fieldIds.length} · {row.areaHa.toLocaleString(locale)} ha</p><span>{row.system}</span></article>)}{!data.sectors.length && <EmptyState className="irrigation-empty" title={t.noData} action={<Button onClick={() => setDialog("sectors")} disabled={actionDisabled}>＋ {t.addSector}</Button>}/>}</div>
      : tab === "meters" ? <><div className="irrigation-cards">{data.meters.map((row) => { const reconciliation = data.reconciliations.find((item) => item.meterId === row.id); return <article key={row.id}><code>{row.code}</code><h3>{row.name}</h3><p>{t.readings}: {data.readings.filter((item) => item.meterId === row.id).length}</p><span>{t.undistributed}: {reconciliation?.undistributedM3.toLocaleString(locale) || 0} m³</span></article>; })}</div><button className="subtle-button" disabled={!data.meters.length} onClick={() => setDialog("reading")}>＋ {t.readings}</button></>
      : <div className="irrigation-cards">{data.analyses.map((row) => <article key={row.id}><code>{formatLocalDate(row.sampledOn, locale)}</code><h3>{row.nitrateMgL.toLocaleString(locale)} mg/L NO₃</h3><p>{row.source || "—"}</p><span>{row.sectorIds.length} {t.sectors.toLocaleLowerCase()}</span></article>)}</div>}
    {dialog && <IrrigationDialog kind={dialog} t={t} fields={fields} holdings={holdings} data={data} onClose={() => setDialog(null)} onSaved={async (physical) => { setDialog(null); await load(); if (physical) await onPhysicalOperationChanged(); }} />}
  </section>;
}

function IrrigationDialog({ kind, t, fields, holdings, data, onClose, onSaved }: { kind: Tab | "reading"; t: (typeof irrigationCopies)["en"]; fields: FieldDto[]; holdings: FarmHoldingDto[]; data: IrrigationOverviewDto; onClose: () => void; onSaved: (physical: boolean) => Promise<void> }) {
  const titleId = useId(); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [values, setValues] = useState<Record<string, string | boolean | string[]>>({ holdingId: holdings[0]?.id || "", code: "", name: "", system: "drip", fieldIds: [], sectorIds: [], meterId: data.meters[0]?.id || "", serialNumber: "", sampledOn: new Date().toISOString().slice(0, 10), nitrateMgL: "", source: "", readAt: new Date().toISOString().slice(0, 16), valueM3: "", event: "normal", irrigationKind: "performed", performedAt: new Date().toISOString().slice(0, 16), scheduledWeekEnd: "", inputMode: "volume_total", volumeM3: "", doseM3Ha: "", depthMm: "", flowM3H: "", durationMinutes: "", fertigation: false, productName: "", productDose: "", productTotal: "" });
  const set = (key: string, value: string | boolean | string[]) => setValues((current) => ({ ...current, [key]: value })); const toggle = (key: "fieldIds" | "sectorIds", id: string) => set(key, (values[key] as string[]).includes(id) ? (values[key] as string[]).filter((item) => item !== id) : [...values[key] as string[], id]);
  async function submit(event: FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setError(""); try {
    if (kind === "sectors") await request("/api/farm/irrigation/sectors", "POST", { holdingId: values.holdingId, code: values.code, name: values.name, system: values.system, fieldIds: values.fieldIds });
    else if (kind === "meters") await request("/api/farm/irrigation/meters", "POST", { holdingId: values.holdingId, code: values.code, name: values.name, serialNumber: values.serialNumber, unit: "m3", sectorIds: values.sectorIds });
    else if (kind === "reading") await request(`/api/farm/irrigation/meters/${values.meterId}/readings`, "POST", { readAt: new Date(values.readAt as string).toISOString(), valueM3: Number(values.valueM3), origin: "manual", event: values.event });
    else if (kind === "analyses") await request("/api/farm/irrigation/water-analyses", "POST", { sampledOn: values.sampledOn, nitrateMgL: Number(values.nitrateMgL), source: values.source || undefined, sectorIds: values.sectorIds });
    else { const selected = data.sectors.filter((row) => (values.sectorIds as string[]).includes(row.id)); const area = selected.reduce((sum, row) => sum + row.areaHa, 0); const total = Number(values.productTotal || 0); const dose = Number(values.productDose || 0) || (area ? total / area : 0); const product = values.fertigation ? { mode: "other", customMode: "fertigation", products: [{ name: values.productName, category: "fertilizer", quantitySource: values.productDose ? "dose_per_ha" : "total", dosePerHa: dose, totalQuantity: total || dose * area, unit: "kg", compositionKnown: false, composition: { micronutrients: {} }, destinationApplications: [], nutrientTotalsKg: {} }] } : undefined; await request("/api/farm/irrigation/records", "POST", { kind: values.irrigationKind, ...(values.irrigationKind === "performed" ? { performedAt: new Date(values.performedAt as string).toISOString() } : { scheduledWeekEnd: values.scheduledWeekEnd }), inputMode: values.inputMode, ...(values.volumeM3 ? { volumeM3: Number(values.volumeM3) } : {}), ...(values.doseM3Ha ? { doseM3Ha: Number(values.doseM3Ha) } : {}), ...(values.depthMm ? { depthMm: Number(values.depthMm) } : {}), ...(values.flowM3H ? { flowM3H: Number(values.flowM3H) } : {}), ...(values.durationMinutes ? { durationMinutes: Number(values.durationMinutes) } : {}), applications: selected.map((row) => ({ sectorId: row.id, fieldIds: row.fieldIds, plantationIds: [] })), meterAllocations: [], fertigation: product, workerIds: [], equipmentIds: [], contractorIds: [] }); }
    await onSaved(kind === "irrigations");
  } catch (caught) { setError(caught instanceof Error ? caught.message : "REQUEST_FAILED"); } finally { setSaving(false); } }
  const checks = (key: "fieldIds" | "sectorIds", rows: Array<{ id: string; name: string }>) => <div className="irrigation-checks">{rows.map((row) => <label key={row.id}><input type="checkbox" checked={(values[key] as string[]).includes(row.id)} onChange={() => toggle(key, row.id)} />{row.name}</label>)}</div>;
  return <AccessibleDialog labelledBy={titleId} onClose={onClose} busy={saving} backdropClassName="dialog-backdrop" className="dialog-card irrigation-dialog"><form onSubmit={submit}><header><h2 id={titleId}>{kind === "irrigations" ? t.addIrrigation : kind === "sectors" ? t.addSector : kind === "meters" ? t.addMeter : kind === "reading" ? t.readings : t.addAnalysis}</h2><button type="button" data-dialog-close onClick={onClose} disabled={saving} aria-label={t.cancel}>×</button></header>
    {(kind === "sectors" || kind === "meters") && <><label><span>{t.holding}</span><select value={values.holdingId as string} onChange={(event) => set("holdingId", event.target.value)}>{holdings.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>{t.code}</span><input required value={values.code as string} onChange={(event) => set("code", event.target.value)} /></label><label><span>{t.name}</span><input required value={values.name as string} onChange={(event) => set("name", event.target.value)} /></label></>}
    {kind === "sectors" && <><label><span>{t.system}</span><select value={values.system as string} onChange={(event) => set("system", event.target.value)}><option value="drip">{t.drip}</option><option value="sprinkler">{t.sprinkler}</option><option value="gravity">{t.gravity}</option></select></label>{checks("fieldIds", fields)}</>}
    {kind === "meters" && <><label><span>{t.serial}</span><input required value={values.serialNumber as string} onChange={(event) => set("serialNumber", event.target.value)} /></label>{checks("sectorIds", data.sectors)}</>}
    {kind === "reading" && <><label><span>{t.meters}</span><select value={values.meterId as string} onChange={(event) => set("meterId", event.target.value)}>{data.meters.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>{t.readings}</span><input type="datetime-local" required value={values.readAt as string} onChange={(event) => set("readAt", event.target.value)} /></label><label><span>{t.volume}</span><input type="number" step="0.001" required value={values.valueM3 as string} onChange={(event) => set("valueM3", event.target.value)} /></label></>}
    {kind === "analyses" && <><label><span>{t.date}</span><input type="date" required value={values.sampledOn as string} onChange={(event) => set("sampledOn", event.target.value)} /></label><label><span>NO₃ mg/L</span><input type="number" step="0.001" required value={values.nitrateMgL as string} onChange={(event) => set("nitrateMgL", event.target.value)} /></label>{checks("sectorIds", data.sectors)}</>}
    {kind === "irrigations" && <><label><span>{t.status}</span><select value={values.irrigationKind as string} onChange={(event) => set("irrigationKind", event.target.value)}><option value="performed">{t.performed}</option><option value="weekly_schedule">{t.weekly}</option></select></label>{values.irrigationKind === "performed" ? <label><span>{t.date}</span><input type="datetime-local" required value={values.performedAt as string} onChange={(event) => set("performedAt", event.target.value)} /></label> : <label><span>{t.weekEnd}</span><input type="date" required value={values.scheduledWeekEnd as string} onChange={(event) => set("scheduledWeekEnd", event.target.value)} /></label>}{checks("sectorIds", data.sectors)}<label><span>{t.source}</span><select value={values.inputMode as string} onChange={(event) => set("inputMode", event.target.value)}><option value="volume_total">{t.volume}</option><option value="dose_m3_ha">{t.dose}</option><option value="depth_mm">{t.depth}</option><option value="flow_duration">{t.flow}</option></select></label>{values.inputMode === "volume_total" ? <NumberField label={t.volume} value={values.volumeM3 as string} set={(value) => set("volumeM3", value)} /> : values.inputMode === "dose_m3_ha" ? <NumberField label={t.dose} value={values.doseM3Ha as string} set={(value) => set("doseM3Ha", value)} /> : values.inputMode === "depth_mm" ? <NumberField label={t.depth} value={values.depthMm as string} set={(value) => set("depthMm", value)} /> : <><NumberField label={t.flow} value={values.flowM3H as string} set={(value) => set("flowM3H", value)} /><NumberField label={t.duration} value={values.durationMinutes as string} set={(value) => set("durationMinutes", value)} /></>}<label className="check-line"><input type="checkbox" checked={Boolean(values.fertigation)} onChange={(event) => set("fertigation", event.target.checked)} />{t.fertigation}</label>{values.fertigation && <><label><span>{t.product}</span><input required value={values.productName as string} onChange={(event) => set("productName", event.target.value)} /></label><NumberField label={t.totalQuantity} value={values.productTotal as string} set={(value) => set("productTotal", value)} /></>}</>}
    {error && <DialogError>{error}</DialogError>}<footer><button type="button" onClick={onClose} disabled={saving}>{t.cancel}</button><button className="primary-action" disabled={saving}>{t.save}</button></footer></form></AccessibleDialog>;
}

function NumberField({ label, value, set }: { label: string; value: string; set: (value: string) => void }) { return <label><span>{label}</span><input type="number" step="0.001" required value={value} onChange={(event) => set(event.target.value)} /></label>; }
