import type { SupportedLocale } from "../../home-copy";

export type OperationExtensionCopy = {
  catalog: string; details: string; voided: string; soilAnalyses: string; automatic: string;
  noValidAnalysis: string; totalHours: string; manualAllocation: string; operationCatalog: string;
  designation: string; createOption: string; deactivate: string; reactivate: string;
  noCustomOptions: string; voidNotice: string; reason: string; confirmVoid: string;
  close: string; voidOperation: string; active: string; inactive: string;
};

const c = (v: string[]): OperationExtensionCopy => {
  const keys = ["catalog","details","voided","soilAnalyses","automatic","noValidAnalysis","totalHours","manualAllocation","operationCatalog","designation","createOption","deactivate","reactivate","noCustomOptions","voidNotice","reason","confirmVoid","close","voidOperation","active","inactive"] as const;
  return Object.fromEntries(keys.map((key, index) => [key, v[index]])) as OperationExtensionCopy;
};

export const operationExtensionCopies: Record<SupportedLocale, OperationExtensionCopy> = {
  "pt-PT": c(["Catálogo","Detalhes","Anulada","Análises do solo","Automática","Sem análise válida","Horas totais","Distribuição manual integral","Catálogo de operações","Designação","Criar opção","Desativar","Reativar","Nenhuma opção personalizada.","Esta ação preserva a operação no histórico e reverte as projeções associadas.","Motivo","Confirmar anulação","Fechar","Anular {code}","Ativa","Inativa"]),
  "pt-BR": c(["Catálogo","Detalhes","Anulada","Análises de solo","Automática","Sem análise válida","Horas totais","Distribuição manual integral","Catálogo de operações","Designação","Criar opção","Desativar","Reativar","Nenhuma opção personalizada.","Esta ação preserva a operação no histórico e reverte as projeções associadas.","Motivo","Confirmar anulação","Fechar","Anular {code}","Ativa","Inativa"]),
  en: c(["Catalog","Details","Voided","Soil analyses","Automatic","No valid analysis","Total hours","Full manual allocation","Operation catalog","Designation","Create option","Deactivate","Reactivate","No custom options.","This action preserves the operation in the audit trail and reverses its associated projections.","Reason","Confirm voiding","Close","Void {code}","Active","Inactive"]),
  es: c(["Catálogo","Detalles","Anulada","Análisis de suelo","Automática","Sin análisis válido","Horas totales","Distribución manual completa","Catálogo de operaciones","Denominación","Crear opción","Desactivar","Reactivar","No hay opciones personalizadas.","Esta acción conserva la operación en el historial y revierte sus proyecciones asociadas.","Motivo","Confirmar anulación","Cerrar","Anular {code}","Activa","Inactiva"]),
  fr: c(["Catalogue","Détails","Annulée","Analyses de sol","Automatique","Aucune analyse valide","Heures totales","Répartition manuelle intégrale","Catalogue des opérations","Désignation","Créer une option","Désactiver","Réactiver","Aucune option personnalisée.","Cette action conserve l’opération dans l’historique et annule ses projections associées.","Motif","Confirmer l’annulation","Fermer","Annuler {code}","Active","Inactive"]),
  de: c(["Katalog","Details","Storniert","Bodenanalysen","Automatisch","Keine gültige Analyse","Gesamtstunden","Vollständige manuelle Verteilung","Arbeitskatalog","Bezeichnung","Option erstellen","Deaktivieren","Reaktivieren","Keine benutzerdefinierten Optionen.","Diese Aktion erhält den Arbeitsgang im Prüfpfad und macht die zugehörigen Projektionen rückgängig.","Grund","Stornierung bestätigen","Schließen","{code} stornieren","Aktiv","Inaktiv"]),
  it: c(["Catalogo","Dettagli","Annullata","Analisi del suolo","Automatica","Nessuna analisi valida","Ore totali","Ripartizione manuale completa","Catalogo delle operazioni","Denominazione","Crea opzione","Disattiva","Riattiva","Nessuna opzione personalizzata.","Questa azione conserva l’operazione nello storico e annulla le proiezioni associate.","Motivo","Conferma annullamento","Chiudi","Annulla {code}","Attiva","Inattiva"]),
  nl: c(["Catalogus","Details","Geannuleerd","Bodemanalyses","Automatisch","Geen geldige analyse","Totaal aantal uren","Volledige handmatige verdeling","Bewerkingscatalogus","Benaming","Optie maken","Deactiveren","Opnieuw activeren","Geen aangepaste opties.","Deze actie bewaart de bewerking in het controlespoor en draait de bijbehorende projecties terug.","Reden","Annulering bevestigen","Sluiten","{code} annuleren","Actief","Inactief"]),
  da: c(["Katalog","Detaljer","Annulleret","Jordbundsanalyser","Automatisk","Ingen gyldig analyse","Timer i alt","Fuld manuel fordeling","Arbejdsgangskatalog","Betegnelse","Opret valgmulighed","Deaktivér","Genaktivér","Ingen brugerdefinerede valgmuligheder.","Denne handling bevarer arbejdsgangen i revisionssporet og tilbagefører de tilknyttede projektioner.","Årsag","Bekræft annullering","Luk","Annuller {code}","Aktiv","Inaktiv"]),
  no: c(["Katalog","Detaljer","Annullert","Jordanalyser","Automatisk","Ingen gyldig analyse","Timer totalt","Full manuell fordeling","Arbeidsoperasjonskatalog","Betegnelse","Opprett alternativ","Deaktiver","Aktiver på nytt","Ingen egendefinerte alternativer.","Denne handlingen beholder arbeidsoperasjonen i revisjonssporet og reverserer tilknyttede projeksjoner.","Årsak","Bekreft annullering","Lukk","Annuller {code}","Aktiv","Inaktiv"]),
  sv: c(["Katalog","Detaljer","Annullerad","Jordanalyser","Automatisk","Ingen giltig analys","Totalt antal timmar","Fullständig manuell fördelning","Arbetsmomentskatalog","Benämning","Skapa alternativ","Inaktivera","Återaktivera","Inga anpassade alternativ.","Åtgärden bevarar arbetsmomentet i revisionsspåret och återställer tillhörande projektioner.","Orsak","Bekräfta annullering","Stäng","Annullera {code}","Aktiv","Inaktiv"]),
  fi: c(["Luettelo","Tiedot","Mitätöity","Maa-analyysit","Automaattinen","Ei voimassa olevaa analyysia","Tunnit yhteensä","Täysi manuaalinen kohdistus","Työvaiheluettelo","Nimike","Luo vaihtoehto","Poista käytöstä","Ota uudelleen käyttöön","Ei mukautettuja vaihtoehtoja.","Toiminto säilyttää työvaiheen kirjausketjussa ja peruu siihen liittyvät kohdistukset.","Syy","Vahvista mitätöinti","Sulje","Mitätöi {code}","Aktiivinen","Ei aktiivinen"]),
  is: c(["Skrá","Upplýsingar","Ógild","Jarðvegsgreiningar","Sjálfvirkt","Engin gild greining","Heildartímar","Full handvirk úthlutun","Aðgerðaskrá","Heiti","Búa til valkost","Óvirkja","Virkja aftur","Engir sérsniðnir valkostir.","Þessi aðgerð varðveitir aðgerðina í rekjanlegri sögu og afturkallar tengdar varpanir.","Ástæða","Staðfesta ógildingu","Loka","Ógilda {code}","Virk","Óvirk"]),
  pl: c(["Katalog","Szczegóły","Unieważniony","Analizy gleby","Automatyczna","Brak ważnej analizy","Łączna liczba godzin","Pełny podział ręczny","Katalog zabiegów","Nazwa","Utwórz opcję","Wyłącz","Włącz ponownie","Brak opcji niestandardowych.","Ta czynność zachowuje zabieg w historii audytowej i cofa powiązane projekcje.","Powód","Potwierdź unieważnienie","Zamknij","Unieważnij {code}","Aktywna","Nieaktywna"]),
  bg: c(["Каталог","Подробности","Анулирана","Почвени анализи","Автоматично","Няма валиден анализ","Общо часове","Пълно ръчно разпределение","Каталог на операциите","Наименование","Създаване на опция","Деактивиране","Повторно активиране","Няма персонализирани опции.","Това действие запазва операцията в одитната история и отменя свързаните проекции.","Причина","Потвърждаване на анулирането","Затваряне","Анулиране на {code}","Активна","Неактивна"]),
  ro: c(["Catalog","Detalii","Anulată","Analize de sol","Automată","Nicio analiză valabilă","Total ore","Alocare manuală integrală","Catalog de operațiuni","Denumire","Creează opțiune","Dezactivează","Reactivează","Nicio opțiune personalizată.","Această acțiune păstrează operațiunea în istoricul de audit și inversează proiecțiile asociate.","Motiv","Confirmă anularea","Închide","Anulează {code}","Activă","Inactivă"]),
  hu: c(["Katalógus","Részletek","Érvénytelenítve","Talajvizsgálatok","Automatikus","Nincs érvényes vizsgálat","Összes munkaóra","Teljes kézi felosztás","Műveleti katalógus","Megnevezés","Opció létrehozása","Inaktiválás","Újraaktiválás","Nincsenek egyéni opciók.","Ez a művelet megőrzi a bejegyzést az ellenőrzési nyomvonalban, és visszafordítja a kapcsolódó vetületeket.","Indok","Érvénytelenítés megerősítése","Bezárás","{code} érvénytelenítése","Aktív","Inaktív"]),
  hr: c(["Katalog","Pojedinosti","Poništena","Analize tla","Automatski","Nema valjane analize","Ukupno sati","Potpuna ručna raspodjela","Katalog postupaka","Naziv","Izradi opciju","Deaktiviraj","Ponovno aktiviraj","Nema prilagođenih opcija.","Ova radnja čuva postupak u revizijskom tragu i poništava povezane projekcije.","Razlog","Potvrdi poništavanje","Zatvori","Poništi {code}","Aktivna","Neaktivna"]),
  sl: c(["Katalog","Podrobnosti","Razveljavljena","Analize tal","Samodejno","Ni veljavne analize","Skupno število ur","Popolna ročna razporeditev","Katalog postopkov","Poimenovanje","Ustvari možnost","Deaktiviraj","Ponovno aktiviraj","Ni možnosti po meri.","To dejanje ohrani postopek v revizijski sledi in razveljavi povezane projekcije.","Razlog","Potrdi razveljavitev","Zapri","Razveljavi {code}","Aktivna","Neaktivna"]),
  sk: c(["Katalóg","Podrobnosti","Anulovaná","Pôdne analýzy","Automaticky","Žiadna platná analýza","Celkový počet hodín","Úplné ručné rozdelenie","Katalóg operácií","Názov","Vytvoriť možnosť","Deaktivovať","Znova aktivovať","Žiadne vlastné možnosti.","Táto akcia zachová operáciu v auditnej stope a zvráti súvisiace projekcie.","Dôvod","Potvrdiť anulovanie","Zavrieť","Anulovať {code}","Aktívna","Neaktívna"]),
  uk: c(["Каталог","Подробиці","Анульована","Аналізи ґрунту","Автоматично","Немає чинного аналізу","Усього годин","Повний ручний розподіл","Каталог операцій","Назва","Створити варіант","Деактивувати","Активувати знову","Немає власних варіантів.","Ця дія зберігає операцію в журналі аудиту та скасовує пов’язані проєкції.","Причина","Підтвердити анулювання","Закрити","Анулювати {code}","Активна","Неактивна"]),
  tr: c(["Katalog","Ayrıntılar","İptal edildi","Toprak analizleri","Otomatik","Geçerli analiz yok","Toplam saat","Tam manuel dağıtım","İşlem kataloğu","Tanım","Seçenek oluştur","Devre dışı bırak","Yeniden etkinleştir","Özel seçenek yok.","Bu işlem kaydı denetim geçmişinde korur ve ilişkili yansıtmaları geri alır.","Gerekçe","İptali onayla","Kapat","{code} kaydını iptal et","Etkin","Etkin değil"]),
  el: c(["Κατάλογος","Λεπτομέρειες","Ακυρωμένη","Αναλύσεις εδάφους","Αυτόματη","Δεν υπάρχει έγκυρη ανάλυση","Συνολικές ώρες","Πλήρης χειροκίνητη κατανομή","Κατάλογος εργασιών","Ονομασία","Δημιουργία επιλογής","Απενεργοποίηση","Επανενεργοποίηση","Δεν υπάρχουν προσαρμοσμένες επιλογές.","Η ενέργεια διατηρεί την εργασία στο ιστορικό ελέγχου και αντιστρέφει τις σχετικές προβολές.","Αιτιολογία","Επιβεβαίωση ακύρωσης","Κλείσιμο","Ακύρωση {code}","Ενεργή","Ανενεργή"]),
  lt: c(["Katalogas","Išsami informacija","Anuliuota","Dirvožemio tyrimai","Automatinė","Nėra galiojančio tyrimo","Iš viso valandų","Visas rankinis paskirstymas","Operacijų katalogas","Pavadinimas","Sukurti parinktį","Išjungti","Vėl įjungti","Nėra pasirinktinių parinkčių.","Šis veiksmas išsaugo operaciją audito istorijoje ir atšaukia susijusias projekcijas.","Priežastis","Patvirtinti anuliavimą","Uždaryti","Anuliuoti {code}","Aktyvi","Neaktyvi"]),
  lv: c(["Katalogs","Informācija","Anulēta","Augsnes analīzes","Automātiska","Nav derīgas analīzes","Kopējais stundu skaits","Pilnīga manuāla sadale","Darbību katalogs","Nosaukums","Izveidot opciju","Deaktivizēt","Aktivizēt atkārtoti","Nav pielāgotu opciju.","Šī darbība saglabā operāciju audita vēsturē un atsauc saistītās projekcijas.","Iemesls","Apstiprināt anulēšanu","Aizvērt","Anulēt {code}","Aktīva","Neaktīva"]),
  ar: c(["الكتالوج","التفاصيل","ملغاة","تحاليل التربة","تلقائي","لا يوجد تحليل صالح","إجمالي الساعات","توزيع يدوي كامل","كتالوج العمليات","التسمية","إنشاء خيار","تعطيل","إعادة تفعيل","لا توجد خيارات مخصصة.","يحفظ هذا الإجراء العملية في سجل التدقيق ويعكس الإسقاطات المرتبطة بها.","السبب","تأكيد الإلغاء","إغلاق","إلغاء {code}","نشطة","غير نشطة"]),
  he: c(["קטלוג","פרטים","בוטלה","בדיקות קרקע","אוטומטי","אין בדיקה תקפה","סך השעות","הקצאה ידנית מלאה","קטלוג פעולות","כינוי","יצירת אפשרות","השבתה","הפעלה מחדש","אין אפשרויות מותאמות.","פעולה זו שומרת את הפעולה בנתיב הביקורת ומבטלת את ההשלכות המשויכות לה.","סיבה","אישור ביטול","סגירה","ביטול {code}","פעילה","לא פעילה"]),
  ja: c(["カタログ","詳細","取消済み","土壌分析","自動","有効な分析なし","合計時間","完全手動配分","作業カタログ","名称","選択肢を作成","無効化","再有効化","独自の選択肢はありません。","この操作は作業を監査履歴に保持し、関連する投影を取り消します。","理由","取消を確定","閉じる","{code}を取り消す","有効","無効"]),
};

export function operationExtensionMessage(template: string, values: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => values[key] ?? `{${key}}`);
}
