import { z } from "zod";

const uuid = z.string().uuid();
const positive = z.number().positive();
const attachmentSchema = z.object({ id: uuid.optional(), name: z.string().trim().min(1).max(180), url: z.string().url().max(1000), kind: z.enum(["photo", "document", "bulletin"]) });
export const findingKinds = ["pest", "disease", "weed", "nutrient_deficiency", "physiological_disorder", "phenology", "beneficial_insects", "weather_damage", "animal_damage", "irrigation_problem", "development_vigor", "other"] as const;
export const findingSchema = z.object({
  id: uuid.optional(), kind: z.enum(findingKinds), customKind: z.string().trim().min(1).max(120).optional(),
  cultureId: z.string().max(32).optional(), cropPeriodId: uuid.optional(), organism: z.string().trim().max(180).optional(), symptom: z.string().trim().max(500).optional(),
  presence: z.enum(["present", "absent"]), plantsObserved: z.number().int().nonnegative().optional(), plantsAffected: z.number().int().nonnegative().optional(),
  incidencePercent: z.number().min(0).max(100).optional(), severity: z.number().min(0).max(100).optional(), count: z.number().nonnegative().optional(), countUnit: z.string().trim().max(60).optional(), notes: z.string().trim().max(2000).optional(),
}).superRefine((value, ctx) => { if (value.kind === "other" && !value.customKind) ctx.addIssue({ code: "custom", path: ["customKind"], message: "required" }); if (value.plantsAffected !== undefined && value.plantsObserved !== undefined && value.plantsAffected > value.plantsObserved) ctx.addIssue({ code: "custom", path: ["plantsAffected"], message: "cannot exceed observed plants" }); });
export const createMonitoringSchema = z.object({
  observedAt: z.string().datetime({ offset: true }), technicianWorkerId: uuid.optional(), fieldIds: z.array(uuid).min(1), plantationIds: z.array(uuid).default([]), cropPeriodIds: z.array(uuid).default([]),
  geometry: z.record(z.unknown()).optional(), automaticWeather: z.record(z.unknown()).default({}), correctedWeather: z.record(z.unknown()).optional(), correctionReason: z.string().trim().max(500).optional(),
  findings: z.array(findingSchema).min(1), linkedOperationIds: z.array(uuid).default([]), attachments: z.array(attachmentSchema).default([]), notes: z.string().trim().max(2000).optional(),
}).superRefine((value, ctx) => { if (value.correctedWeather && !value.correctionReason) ctx.addIssue({ code: "custom", path: ["correctionReason"], message: "required when weather is corrected" }); });
export type CreateMonitoringInput = z.infer<typeof createMonitoringSchema>;

export const createLaboratorySampleSchema = z.object({ sampledOn: z.string().date(), responsibleWorkerId: uuid.optional(), type: z.enum(["soil", "water", "leaf", "other"]), method: z.string().trim().min(1).max(180), fieldIds: z.array(uuid).default([]), irrigationSectorIds: z.array(uuid).default([]), plantationIds: z.array(uuid).default([]), cropPeriodIds: z.array(uuid).default([]), notes: z.string().trim().max(2000).optional() }).superRefine((v,ctx)=>{ const count=v.fieldIds.length+v.irrigationSectorIds.length+v.plantationIds.length; if(!count)ctx.addIssue({code:"custom",path:["fieldIds"],message:"at least one target is required"}); if(v.type==="soil"&&!v.fieldIds.length)ctx.addIssue({code:"custom",path:["fieldIds"],message:"soil analysis requires fields"}); if(v.type==="water"&&!v.irrigationSectorIds.length)ctx.addIssue({code:"custom",path:["irrigationSectorIds"],message:"water analysis requires irrigation sectors"}); if(v.type==="leaf"&&(!v.plantationIds.length||!v.cropPeriodIds.length))ctx.addIssue({code:"custom",path:["cropPeriodIds"],message:"leaf analysis requires selected plantations and periods"}); });
export const createLaboratoryResultSchema = z.object({ sampleId: uuid, resultedOn: z.string().date(), laboratory: z.string().trim().min(1).max(180), bulletinNumber: z.string().trim().min(1).max(120), bulletinUrl: z.string().url().max(1000).optional(), validUntil: z.string().date().optional(), results: z.array(z.object({ parameter: z.string().trim().min(1).max(120), value: z.number(), unit: z.string().trim().min(1).max(40), reference: z.string().trim().max(160).optional() })).min(1) });
export type CreateLaboratorySampleInput=z.infer<typeof createLaboratorySampleSchema>; export type CreateLaboratoryResultInput=z.infer<typeof createLaboratoryResultSchema>;

export const harvestDestinationSchema=z.object({name:z.string().trim().min(1).max(180),type:z.enum(["customer","storage","processing","field","destruction","compost","animal_feed","other"]),quantityKg:positive,notes:z.string().trim().max(500).optional()});
export const createHarvestSchema=z.object({
  startedAt:z.string().datetime({offset:true}),endedAt:z.string().datetime({offset:true}).optional(),cultureId:z.string().min(1).max(32),
  origins:z.array(z.object({fieldId:uuid,plantationId:uuid,cropPeriodId:uuid,fieldCode:z.string().regex(/^(?!0MIX$)[A-Z0-9]{4}$/),varietyCode:z.string().regex(/^(?!0MIX$)[A-Z0-9]{4}$/),areaHa:positive,quantityKg:positive.optional(),finishPlantation:z.boolean().default(false),areaFreed:z.boolean().default(false)})).min(1),
  totalNetKg:positive,categories:z.array(z.object({name:z.string().trim().min(1).max(120),quantityKg:z.number().nonnegative(),commercial:z.boolean(),separateLot:z.boolean().default(false),refuseDestination:z.enum(["field","destruction","compost","animal_feed","processing","other"]).optional()})).min(1),
  destinations:z.array(harvestDestinationSchema).default([]),quality:z.array(z.object({parameter:z.string().trim().min(1).max(120),value:z.number(),unit:z.string().trim().min(1).max(40)})).default([]),
  revenue:z.object({amount:z.number().nonnegative(),quantity:z.number().positive(),unit:z.string().max(20),commercialBasis:z.string().trim().max(300).optional()}).optional(),lossReason:z.string().trim().max(1000).optional(),safetyWarnings:z.array(z.string().max(500)).default([]),acceptSafetyWarnings:z.boolean().default(false),notes:z.string().trim().max(2000).optional(),
  workerIds:z.array(uuid).max(50).default([]),equipmentIds:z.array(uuid).max(50).default([]),contractorIds:z.array(uuid).max(20).default([]),
}).superRefine((v,ctx)=>{const categoryTotal=v.categories.reduce((s,x)=>s+x.quantityKg,0);if(Math.abs(categoryTotal-v.totalNetKg)>.001)ctx.addIssue({code:"custom",path:["categories"],message:"category quantities must equal total net weight"});const explicit=v.origins.filter(x=>x.quantityKg!==undefined);if(explicit.length&&explicit.length!==v.origins.length)ctx.addIssue({code:"custom",path:["origins"],message:"origin quantities must be all automatic or all explicit"});if(explicit.length&&Math.abs(explicit.reduce((s,x)=>s+(x.quantityKg||0),0)-v.totalNetKg)>.001)ctx.addIssue({code:"custom",path:["origins"],message:"origin quantities must equal total net weight"});const destinationTotal=v.destinations.reduce((s,x)=>s+x.quantityKg,0);if(destinationTotal-v.totalNetKg>.001)ctx.addIssue({code:"custom",path:["destinations"],message:"destinations cannot exceed total net weight"});if(v.safetyWarnings.length&&!v.acceptSafetyWarnings)ctx.addIssue({code:"custom",path:["acceptSafetyWarnings"],message:"warnings must be accepted"});});
export type CreateHarvestInput=z.infer<typeof createHarvestSchema>;
export function allocateHarvest(input:CreateHarvestInput){const area=input.origins.reduce((s,x)=>s+x.areaHa,0);return input.origins.map(origin=>({...origin,quantityKg:origin.quantityKg??input.totalNetKg*origin.areaHa/area,productivityKgHa:(origin.quantityKg??input.totalNetKg*origin.areaHa/area)/origin.areaHa}));}
export function harvestLotSegments(input:CreateHarvestInput){const varieties=new Set(input.origins.map(x=>x.varietyCode)),fields=new Set(input.origins.map(x=>x.fieldCode));return{variety:varieties.size===1?[...varieties][0]:"0MIX",field:fields.size===1?[...fields][0]:"0MIX"};}

export const notebookScopeSchema=z.object({holdingId:uuid,previousNotebookId:uuid.optional(),from:z.string().date(),to:z.string().date(),plantationIds:z.array(uuid).default([]),fieldIds:z.array(uuid).default([]),cropPeriodIds:z.array(uuid).default([]),wholeHolding:z.boolean().default(false),language:z.string().min(2).max(16),attachmentIds:z.array(uuid).default([]),includeVoidedAudit:z.boolean().default(false),acceptedWarnings:z.array(z.string().max(500)).default([])}).refine(v=>v.to>=v.from,{path:["to"],message:"end must be after start"}).refine(v=>v.wholeHolding||v.plantationIds.length>0||v.fieldIds.length>0,{path:["wholeHolding"],message:"scope is required"});
export type NotebookScope=z.infer<typeof notebookScopeSchema>;
export function canonicalJson(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonicalJson).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonicalJson(v)}`).join(",")}}`;return JSON.stringify(value);}
