import { z } from "zod";
const date=z.string().date();
export const createWorkerSchema=z.object({name:z.string().trim().min(2).max(160),role:z.string().trim().min(2).max(120),email:z.string().email().max(200).optional(),phone:z.string().trim().min(5).max(40).optional()});
export const createCertificateSchema=z.object({workerId:z.string().uuid(),type:z.enum(["phytopharmaceutical_applicator","machinery_operator","other"]),number:z.string().trim().min(2).max(80),validFrom:date,validUntil:date}).refine((value)=>value.validUntil>=value.validFrom,{path:["validUntil"],message:"Expiry precedes validity start"});
export const createContractorSchema=z.object({name:z.string().trim().min(2).max(180),taxIdentifier:z.string().trim().min(2).max(40).optional(),contactName:z.string().trim().min(2).max(160).optional(),email:z.string().email().max(200).optional(),phone:z.string().trim().min(5).max(40).optional()});
export const createEquipmentSchema=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9-]{2,20}$/),name:z.string().trim().min(2).max(160),category:z.enum(["tractor","implement","sprayer","irrigation","vehicle","other"])});
export type CreateWorkerInput=z.infer<typeof createWorkerSchema>;export type CreateCertificateInput=z.infer<typeof createCertificateSchema>;export type CreateContractorInput=z.infer<typeof createContractorSchema>;export type CreateEquipmentInput=z.infer<typeof createEquipmentSchema>;
export type WorkerDto=CreateWorkerInput&{id:string;status:"active"|"inactive";createdAt:string};export type CertificateDto=CreateCertificateInput&{id:string;createdAt:string};export type ContractorDto=CreateContractorInput&{id:string;status:"active"|"inactive";createdAt:string};export type EquipmentDto=CreateEquipmentInput&{id:string;status:"active"|"maintenance"|"inactive";createdAt:string};
export function isValidApplicator(workerId:string,onDate:string,workers:WorkerDto[],certificates:CertificateDto[]){return workers.some((worker)=>worker.id===workerId&&worker.status==="active")&&certificates.some((certificate)=>certificate.workerId===workerId&&certificate.type==="phytopharmaceutical_applicator"&&certificate.validFrom<=onDate&&certificate.validUntil>=onDate)}
