import { sql } from "drizzle-orm";
import { boolean, check, date, foreignKey, index, jsonb, numeric, pgPolicy, pgSchema, text, timestamp, unique, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";
import type { FieldPolygon } from "./fields";
import type { NutrientAmounts } from "./fertilization-plans";
import type { AutomaticMonitoringWeather, MonitoringWeatherMetrics } from "./agronomy";
import type { AgronomicWeatherAccumulation, WeatherBaseSeries, WeatherSeriesDay, WeatherSeriesHour, WeatherVirtualStation } from "./weather";

export const farmSchema = pgSchema("farm");

/**
 * Privacy-minimised local projection of a Gero Core organization.
 *
 * Gero Core remains the source of truth for identity, membership and access.
 * Future product tables reference this key and inherit the same tenant boundary.
 */
export const farmOrganizations = farmSchema.table("organizations", {
  organizationId: uuid("organization_id").primaryKey(),
  name: varchar("name", { length: 200 }).notNull(),
  slug: varchar("slug", { length: 120 }).notNull(),
  defaultLocale: varchar("default_locale", { length: 16 }).notNull().default("pt-PT"),
  timezone: varchar("timezone", { length: 64 }).notNull().default("Europe/Lisbon"),
  coreSyncedAt: timestamp("core_synced_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  pgPolicy("organizations_tenant_isolation", {
    as: "restrictive",
    for: "all",
    to: "public",
    using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,
    withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,
  }),
]).enableRLS();

export type FarmOrganization = typeof farmOrganizations.$inferSelect;
export type NewFarmOrganization = typeof farmOrganizations.$inferInsert;

export const farmHoldings = farmSchema.table("farm_holdings", {
  id: uuid("id").primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId),
  code: varchar("code", { length: 12 }).notNull(),
  name: varchar("name", { length: 160 }).notNull(),
  timezone: varchar("timezone", { length: 64 }).notNull(),
  status: varchar("status", { length: 16 }).notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("farm_holdings_organization_unique").on(table.organizationId),
  uniqueIndex("farm_holdings_organization_code_unique").on(table.organizationId, table.code),
  index("farm_holdings_organization_status_idx").on(table.organizationId, table.status),
  check("farm_holdings_code_format", sql`${table.code} ~ '^[A-Z0-9]{2,12}$'`),
  check("farm_holdings_status_valid", sql`${table.status} in ('active', 'inactive')`),
  pgPolicy("farm_holdings_tenant_isolation", {
    as: "restrictive", for: "all", to: "public",
    using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,
    withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,
  }),
]).enableRLS();

export const farmAuditEvents = farmSchema.table("audit_events", {
  id: uuid("id").primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId),
  actorUserId: uuid("actor_user_id").notNull(),
  action: varchar("action", { length: 80 }).notNull(),
  entityType: varchar("entity_type", { length: 80 }).notNull(),
  entityId: uuid("entity_id").notNull(),
  metadata: jsonb("metadata").$type<Record<string, string | number | boolean | null>>().notNull().default({}),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("audit_events_organization_entity_idx").on(table.organizationId, table.entityType, table.entityId),
  pgPolicy("audit_events_tenant_isolation", {
    as: "restrictive", for: "all", to: "public",
    using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,
    withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,
  }),
]).enableRLS();

export const idempotencyRequests=farmSchema.table("idempotency_requests",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),key:varchar("key",{length:128}).notNull(),method:varchar("method",{length:8}).notNull(),path:varchar("path",{length:300}).notNull(),requestHash:varchar("request_hash",{length:64}).notNull(),status:varchar("status",{length:16}).notNull(),responseStatus:numeric("response_status",{precision:3,scale:0}),responseHeaders:jsonb("response_headers").$type<Record<string,string>>(),responseBody:jsonb("response_body").$type<unknown>(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull()},table=>[uniqueIndex("idempotency_requests_org_key_unique").on(table.organizationId,table.key),index("idempotency_requests_expiry_idx").on(table.expiresAt),check("idempotency_requests_status_valid",sql`${table.status} in ('pending','completed')`),pgPolicy("idempotency_requests_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export type FarmHolding = typeof farmHoldings.$inferSelect;
export type NewFarmHolding = typeof farmHoldings.$inferInsert;

export const farmFields = farmSchema.table("fields", {
  id: uuid("id").primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId),
  holdingId: uuid("holding_id").notNull().references(() => farmHoldings.id),
  code: varchar("code", { length: 4 }).notNull(),
  name: varchar("name", { length: 160 }).notNull(),
  geometry: jsonb("geometry").$type<FieldPolygon>().notNull(),
  totalAreaHa: numeric("total_area_ha", { precision: 12, scale: 4 }).notNull(),
  usableAreaHa: numeric("usable_area_ha", { precision: 12, scale: 4 }).notNull(),
  manuallyClosed: boolean("manually_closed").notNull().default(false),
  status: varchar("status", { length: 16 }).notNull().default("active"),
  codeLockedAt: timestamp("code_locked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("fields_organization_code_unique").on(table.organizationId, table.code),
  index("fields_holding_status_idx").on(table.organizationId, table.holdingId, table.status),
  check("fields_code_format", sql`${table.code} ~ '^[A-Z0-9]{4}$' and ${table.code} <> '0MIX'`),
  check("fields_area_valid", sql`${table.totalAreaHa} > 0 and ${table.usableAreaHa} > 0 and ${table.usableAreaHa} <= ${table.totalAreaHa}`),
  check("fields_status_valid", sql`${table.status} in ('active', 'inactive')`),
  pgPolicy("fields_tenant_isolation", { as: "restrictive", for: "all", to: "public", using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`, withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid` }),
]).enableRLS();

export type FarmField = typeof farmFields.$inferSelect;

export const cropVarieties = farmSchema.table("crop_varieties", {
  id: uuid("id").primaryKey(),
  organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId),
  cultureId: varchar("culture_id", { length: 32 }).notNull(),
  name: varchar("name", { length: 160 }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("crop_varieties_organization_culture_name_unique").on(table.organizationId, table.cultureId, table.name),
  index("crop_varieties_organization_culture_idx").on(table.organizationId, table.cultureId),
  check("crop_varieties_culture_id_format", sql`${table.cultureId} ~ '^pt-drap-[0-9]{3}$'`),
  pgPolicy("crop_varieties_tenant_isolation", { as: "restrictive", for: "all", to: "public", using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`, withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid` }),
]).enableRLS();

export type CropVariety = typeof cropVarieties.$inferSelect;

export const plantations = farmSchema.table("plantations", {
  id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId), fieldId: uuid("field_id").notNull().references(() => farmFields.id), cultureId: varchar("culture_id", { length: 32 }).notNull(), varietyId: uuid("variety_id").references(() => cropVarieties.id),
  name: varchar("name", { length: 160 }).notNull(), kind: varchar("kind", { length: 16 }).notNull(), areaHa: numeric("area_ha", { precision: 12, scale: 4 }).notNull(), startedOn: date("started_on").notNull(), endedOn: date("ended_on"), status: varchar("status", { length: 16 }).notNull().default("active"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("plantations_field_status_idx").on(table.organizationId, table.fieldId, table.status), check("plantations_kind_valid", sql`${table.kind} in ('permanent','temporary')`), check("plantations_status_valid", sql`${table.status} in ('active','ended','uprooted','voided')`), check("plantations_area_valid", sql`${table.areaHa} > 0`), check("plantations_dates_valid", sql`${table.endedOn} is null or ${table.endedOn} >= ${table.startedOn}`), pgPolicy("plantations_tenant_isolation", { as: "restrictive", for: "all", to: "public", using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`, withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid` })]).enableRLS();
export type Plantation = typeof plantations.$inferSelect;

export const cropPeriods = farmSchema.table("crop_periods", {
  id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId), plantationId: uuid("plantation_id").notNull().references(() => plantations.id), kind: varchar("kind", { length: 16 }).notNull(), name: varchar("name", { length: 160 }).notNull(), startedOn: date("started_on").notNull(), endedOn: date("ended_on"), status: varchar("status", { length: 16 }).notNull().default("active"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("crop_periods_plantation_status_idx").on(table.organizationId, table.plantationId, table.status), uniqueIndex("crop_periods_one_active_per_plantation").on(table.organizationId,table.plantationId).where(sql`${table.status}='active'`), check("crop_periods_kind_valid", sql`${table.kind} in ('campaign','cycle')`), check("crop_periods_status_valid", sql`${table.status} in ('active','closed')`), check("crop_periods_dates_valid", sql`${table.endedOn} is null or ${table.endedOn} >= ${table.startedOn}`), pgPolicy("crop_periods_tenant_isolation", { as: "restrictive", for: "all", to: "public", using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`, withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid` })]).enableRLS();
export type CropPeriod = typeof cropPeriods.$inferSelect;

export const weatherSyncs=farmSchema.table("weather_syncs",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),plantationId:uuid("plantation_id").notNull().references(()=>plantations.id),campaignId:uuid("campaign_id").references(()=>cropPeriods.id),fromDate:date("from_date").notNull(),toDate:date("to_date").notNull(),status:varchar("status",{length:24}).notNull(),coverage:jsonb("coverage").$type<WeatherBaseSeries["coverage"]>().notNull(),stationPeriods:jsonb("station_periods").$type<WeatherBaseSeries["stationPeriods"]>().notNull(),fetchedAt:timestamp("fetched_at",{withTimezone:true}),cached:boolean("cached").notNull(),stale:boolean("stale").notNull(),cacheStatus:varchar("cache_status",{length:24}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[index("weather_syncs_org_plantation_interval_idx").on(table.organizationId,table.plantationId,table.fromDate,table.toDate),check("weather_syncs_dates_valid",sql`${table.toDate}>=${table.fromDate}`),check("weather_syncs_status_valid",sql`${table.status} in ('complete','partial','unavailable')`),pgPolicy("weather_syncs_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const weatherSamples=farmSchema.table("weather_samples",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),plantationId:uuid("plantation_id").notNull().references(()=>plantations.id),campaignId:uuid("campaign_id").references(()=>cropPeriods.id),stationId:uuid("station_id").notNull(),assignmentId:uuid("assignment_id").notNull(),resolution:varchar("resolution",{length:8}).notNull(),sampleAt:timestamp("sample_at",{withTimezone:true}).notNull(),localDate:date("local_date").notNull(),timezone:varchar("timezone",{length:100}),station:jsonb("station").$type<WeatherVirtualStation>().notNull(),payload:jsonb("payload").$type<WeatherSeriesHour|WeatherSeriesDay>().notNull(),temporalStatus:varchar("temporal_status",{length:16}).notNull(),valueSource:varchar("value_source",{length:16}).notNull(),fetchedAt:timestamp("fetched_at",{withTimezone:true}),cached:boolean("cached").notNull(),stale:boolean("stale").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("weather_samples_idempotent_unique").on(table.organizationId,table.plantationId,table.stationId,table.resolution,table.sampleAt),index("weather_samples_org_plantation_date_idx").on(table.organizationId,table.plantationId,table.localDate,table.resolution),pgPolicy("weather_samples_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const weatherAgronomicProfiles=farmSchema.table("weather_agronomic_profiles",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),plantationId:uuid("plantation_id").notNull().references(()=>plantations.id),campaignId:uuid("campaign_id").notNull().references(()=>cropPeriods.id),cropId:varchar("crop_id",{length:150}).notNull(),varietyId:varchar("variety_id",{length:150}).notNull(),methodVersion:varchar("method_version",{length:50}).notNull(),parameters:jsonb("parameters").$type<Record<string,unknown>>().notNull(),validFrom:timestamp("valid_from",{withTimezone:true}).notNull(),validTo:timestamp("valid_to",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("weather_profiles_campaign_from_unique").on(table.organizationId,table.campaignId,table.validFrom),uniqueIndex("weather_profiles_one_open_per_campaign").on(table.organizationId,table.campaignId).where(sql`${table.validTo} is null`),pgPolicy("weather_profiles_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const weatherAgronomicResults=farmSchema.table("weather_agronomic_results",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),plantationId:uuid("plantation_id").notNull().references(()=>plantations.id),campaignId:uuid("campaign_id").references(()=>cropPeriods.id),fromDate:date("from_date").notNull(),toDate:date("to_date").notNull(),engineVersion:varchar("engine_version",{length:50}).notNull(),inputHash:varchar("input_hash",{length:64}).notNull(),result:jsonb("result").$type<AgronomicWeatherAccumulation>().notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[unique("weather_results_reproducible_unique").on(table.organizationId,table.plantationId,table.campaignId,table.fromDate,table.toDate,table.engineVersion,table.inputHash).nullsNotDistinct(),pgPolicy("weather_results_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const plantationUprootings = farmSchema.table("plantation_uprootings", {
  id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId), plantationId: uuid("plantation_id").notNull().references(() => plantations.id), uprootedOn: date("uprooted_on").notNull(), reason: varchar("reason", { length: 500 }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("plantation_uprootings_plantation_unique").on(table.plantationId), pgPolicy("plantation_uprootings_tenant_isolation", { as: "restrictive", for: "all", to: "public", using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`, withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid` })]).enableRLS();

export const fieldFallows = farmSchema.table("field_fallows", {
  id: uuid("id").primaryKey(), organizationId: uuid("organization_id").notNull().references(() => farmOrganizations.organizationId), fieldId: uuid("field_id").notNull().references(() => farmFields.id), name: varchar("name", { length: 160 }).notNull(), areaHa: numeric("area_ha", { precision: 12, scale: 4 }).notNull(), startedOn: date("started_on").notNull(), endedOn: date("ended_on"), status: varchar("status", { length: 16 }).notNull().default("active"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("field_fallows_field_status_idx").on(table.organizationId, table.fieldId, table.status), check("field_fallows_area_valid", sql`${table.areaHa} > 0`), check("field_fallows_status_valid", sql`${table.status} in ('active','closed')`), check("field_fallows_dates_valid", sql`${table.endedOn} is null or ${table.endedOn} >= ${table.startedOn}`), pgPolicy("field_fallows_tenant_isolation", { as: "restrictive", for: "all", to: "public", using: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`, withCheck: sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid` })]).enableRLS();
export type FieldFallow = typeof fieldFallows.$inferSelect;

export const farmWorkers=farmSchema.table("workers",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),name:varchar("name",{length:160}).notNull(),role:varchar("role",{length:120}).notNull(),email:varchar("email",{length:200}),phone:varchar("phone",{length:40}),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("workers_org_id_unique").on(table.organizationId,table.id),index("workers_organization_status_idx").on(table.organizationId,table.status),check("workers_status_valid",sql`${table.status} in ('active','inactive')`),pgPolicy("workers_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,withCheck:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`})]).enableRLS();export type FarmWorker=typeof farmWorkers.$inferSelect;
export const workerCertificates=farmSchema.table("worker_certificates",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),workerId:uuid("worker_id").notNull().references(()=>farmWorkers.id),type:varchar("type",{length:48}).notNull(),number:varchar("number",{length:80}).notNull(),validFrom:date("valid_from").notNull(),validUntil:date("valid_until").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[index("worker_certificates_worker_validity_idx").on(table.organizationId,table.workerId,table.validUntil),check("worker_certificates_type_valid",sql`${table.type} in ('phytopharmaceutical_applicator','machinery_operator','other')`),check("worker_certificates_dates_valid",sql`${table.validUntil} >= ${table.validFrom}`),pgPolicy("worker_certificates_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,withCheck:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`})]).enableRLS();export type WorkerCertificate=typeof workerCertificates.$inferSelect;
export const farmContractors=farmSchema.table("contractors",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),name:varchar("name",{length:180}).notNull(),taxIdentifier:varchar("tax_identifier",{length:40}),contactName:varchar("contact_name",{length:160}),email:varchar("email",{length:200}),phone:varchar("phone",{length:40}),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("contractors_org_id_unique").on(table.organizationId,table.id),index("contractors_organization_status_idx").on(table.organizationId,table.status),check("contractors_status_valid",sql`${table.status} in ('active','inactive')`),pgPolicy("contractors_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,withCheck:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`})]).enableRLS();export type FarmContractor=typeof farmContractors.$inferSelect;
export const farmEquipment=farmSchema.table("equipment",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),code:varchar("code",{length:20}).notNull(),name:varchar("name",{length:160}).notNull(),category:varchar("category",{length:24}).notNull(),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("equipment_org_id_unique").on(table.organizationId,table.id),uniqueIndex("equipment_organization_code_unique").on(table.organizationId,table.code),index("equipment_organization_status_idx").on(table.organizationId,table.status),check("equipment_category_valid",sql`${table.category} in ('tractor','implement','sprayer','irrigation','vehicle','other')`),check("equipment_status_valid",sql`${table.status} in ('active','maintenance','inactive')`),pgPolicy("equipment_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`,withCheck:sql`${table.organizationId} = nullif(current_setting('app.organization_id', true), '')::uuid`})]).enableRLS();export type FarmEquipment=typeof farmEquipment.$inferSelect;

export const operationSequences=farmSchema.table("operation_sequences",{organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),year:numeric("year",{precision:4,scale:0}).notNull(),nextValue:numeric("next_value",{precision:12,scale:0}).notNull().default("1")},(table)=>[uniqueIndex("operation_sequences_organization_year_unique").on(table.organizationId,table.year),pgPolicy("operation_sequences_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const farmOperations=farmSchema.table("operations",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),code:varchar("code",{length:24}).notNull(),type:varchar("type",{length:32}).notNull(),performedAt:timestamp("performed_at",{withTimezone:true}).notNull(),durationMinutes:numeric("duration_minutes",{precision:8,scale:0}),notes:varchar("notes",{length:2000}),status:varchar("status",{length:16}).notNull().default("performed"),voidReason:varchar("void_reason",{length:500}),voidedAt:timestamp("voided_at",{withTimezone:true}),voidedBy:uuid("voided_by"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("operations_organization_code_unique").on(table.organizationId,table.code),index("operations_organization_date_idx").on(table.organizationId,table.performedAt),check("operations_status_valid",sql`${table.status} in ('performed','voided')`),check("operations_void_state_valid",sql`(${table.status}='performed' and ${table.voidReason} is null and ${table.voidedAt} is null and ${table.voidedBy} is null) or (${table.status}='voided' and ${table.voidReason} is not null and ${table.voidedAt} is not null and ${table.voidedBy} is not null)`),pgPolicy("operations_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();export type FarmOperation=typeof farmOperations.$inferSelect;
export const operationCatalogItems=farmSchema.table("operation_catalog_items",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),kind:varchar("kind",{length:40}).notNull(),label:varchar("label",{length:120}).notNull(),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("operation_catalog_items_org_kind_label_unique").on(table.organizationId,table.kind,table.label),pgPolicy("operation_catalog_items_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationDestinations=farmSchema.table("operation_destinations",{id:uuid("id").primaryKey(),operationId:uuid("operation_id").notNull().references(()=>farmOperations.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),fieldId:uuid("field_id").notNull().references(()=>farmFields.id),plantationId:uuid("plantation_id").references(()=>plantations.id),areaHa:numeric("area_ha",{precision:12,scale:4}).notNull(),percentage:numeric("percentage",{precision:7,scale:4}).notNull()},(table)=>[index("operation_destinations_operation_idx").on(table.organizationId,table.operationId),check("operation_destinations_area_valid",sql`${table.areaHa} > 0`),check("operation_destinations_percentage_valid",sql`${table.percentage} > 0 and ${table.percentage} <= 100`),pgPolicy("operation_destinations_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationSoilPreparations=farmSchema.table("operation_soil_preparations",{operationId:uuid("operation_id").primaryKey().references(()=>farmOperations.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),actions:jsonb("actions").$type<string[]>().notNull(),soilAnalysisResultId:uuid("soil_analysis_result_id"),soilAnalysisSnapshot:jsonb("soil_analysis_snapshot").$type<Record<string,unknown>>(),analysisWarnings:jsonb("analysis_warnings").$type<string[]>().notNull().default([]),depthCm:numeric("depth_cm",{precision:7,scale:2}),passes:numeric("passes",{precision:4,scale:0}),soilCondition:varchar("soil_condition",{length:16}),residueDestination:varchar("residue_destination",{length:24})},(table)=>[check("operation_soil_preparations_actions_valid",sql`jsonb_array_length(${table.actions}) > 0`),check("operation_soil_preparations_depth_valid",sql`${table.depthCm} is null or ${table.depthCm} > 0`),check("operation_soil_preparations_passes_valid",sql`${table.passes} is null or ${table.passes} > 0`),check("operation_soil_preparations_condition_valid",sql`${table.soilCondition} is null or ${table.soilCondition} in ('dry','moist','wet')`),check("operation_soil_preparations_residue_valid",sql`${table.residueDestination} is null or ${table.residueDestination} in ('left','shredded','incorporated','removed','burned','other')`),pgPolicy("operation_soil_preparations_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationCropInstallations=farmSchema.table("operation_crop_installations",{operationId:uuid("operation_id").primaryKey().references(()=>farmOperations.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),plantationId:uuid("plantation_id").notNull().references(()=>plantations.id),cultureId:varchar("culture_id",{length:32}).notNull(),varietyIds:jsonb("variety_ids").$type<string[]>().notNull().default([]),varietyDensities:jsonb("variety_densities").$type<Array<{varietyId:string;densityPlantsHa:number}>>().notNull().default([]),method:varchar("method",{length:24}).notNull(),customMethod:varchar("custom_method",{length:120}),endedOn:date("ended_on"),densityPlantsHa:numeric("density_plants_ha",{precision:14,scale:2}).notNull(),rowSpacingCm:numeric("row_spacing_cm",{precision:10,scale:2}),plantSpacingCm:numeric("plant_spacing_cm",{precision:10,scale:2}),materialLots:jsonb("material_lots").$type<Array<{varietyId?:string;lotNumber:string;quantity:number;unit:string;origin?:string;supplier?:string}>>().notNull().default([]),predecessor:varchar("predecessor",{length:160}),preparatoryOperationIds:jsonb("preparatory_operation_ids").$type<string[]>().notNull().default([])},(table)=>[check("operation_crop_installations_method_valid",sql`${table.method} in ('sowing','transplanting','planting','other')`),check("operation_crop_installations_custom_method_valid",sql`(${table.method}='other' and ${table.customMethod} is not null) or (${table.method}<>'other' and ${table.customMethod} is null)`),check("operation_crop_installations_density_valid",sql`${table.densityPlantsHa} > 0`),pgPolicy("operation_crop_installations_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationCulturalWorks=farmSchema.table("operation_cultural_works",{operationId:uuid("operation_id").primaryKey().references(()=>farmOperations.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),actions:jsonb("actions").$type<string[]>().notNull(),method:varchar("method",{length:24}).notNull(),customMethod:varchar("custom_method",{length:120}),intensity:varchar("intensity",{length:16}),intensityPercentage:numeric("intensity_percentage",{precision:7,scale:2}),biomassDestination:varchar("biomass_destination",{length:24}),plantPercentage:numeric("plant_percentage",{precision:7,scale:2}),plantCount:numeric("plant_count",{precision:12,scale:0}),materials:jsonb("materials").$type<Array<{name:string;quantity:number;unit:string;lotNumber?:string}>>().notNull().default([]),replanting:jsonb("replanting").$type<{originalDensityPlantsHa:number;plantsReplaced:number;plantsPlaced:number;estimatedCurrentDensityPlantsHa?:number}>()},(table)=>[check("operation_cultural_works_actions_valid",sql`jsonb_array_length(${table.actions}) > 0`),check("operation_cultural_works_method_valid",sql`${table.method} in ('manual','mechanical','thermal','other')`),check("operation_cultural_works_intensity_valid",sql`${table.intensity} is null or ${table.intensity} in ('light','medium','severe')`),check("operation_cultural_works_biomass_valid",sql`${table.biomassDestination} is null or ${table.biomassDestination} in ('left','shredded','incorporated','removed','burned','other')`),pgPolicy("operation_cultural_works_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationFertilizations=farmSchema.table("operation_fertilizations",{operationId:uuid("operation_id").primaryKey().references(()=>farmOperations.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),mode:varchar("mode",{length:40}).notNull(),customMode:varchar("custom_mode",{length:120}),products:jsonb("products").$type<Array<Record<string,unknown>>>().notNull()},(table)=>[check("operation_fertilizations_products_valid",sql`jsonb_array_length(${table.products}) > 0`),pgPolicy("operation_fertilizations_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationSprayings=farmSchema.table("operation_sprayings",{operationId:uuid("operation_id").primaryKey().references(()=>farmOperations.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),method:varchar("method",{length:32}).notNull(),customMethod:varchar("custom_method",{length:120}),sprayVolumeLHa:numeric("spray_volume_l_ha",{precision:14,scale:4}),legalApplicatorWorkerId:uuid("legal_applicator_worker_id").references(()=>farmWorkers.id),products:jsonb("products").$type<Array<Record<string,unknown>>>().notNull(),weather:jsonb("weather").$type<Record<string,unknown>>().notNull(),equipmentInspectionValid:boolean("equipment_inspection_valid"),equipmentCalibrationValid:boolean("equipment_calibration_valid"),warnings:jsonb("warnings").$type<Array<Record<string,unknown>>>().notNull().default([]),warningsAccepted:boolean("warnings_accepted").notNull().default(false)},(table)=>[check("operation_sprayings_products_valid",sql`jsonb_array_length(${table.products}) > 0`),check("operation_sprayings_method_valid",sql`${table.method} in ('spray','granules','bait','injection','other')`),check("operation_sprayings_volume_valid",sql`(${table.method} = 'spray' and ${table.sprayVolumeLHa} > 0) or (${table.method} <> 'spray' and ${table.sprayVolumeLHa} is null)`),pgPolicy("operation_sprayings_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const fertilizationPlans=farmSchema.table("fertilization_plans",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),name:varchar("name",{length:180}).notNull(),cultureId:varchar("culture_id",{length:32}).notNull(),startsOn:date("starts_on").notNull(),endsOn:date("ends_on").notNull(),version:numeric("version",{precision:6,scale:0}).notNull(),status:varchar("status",{length:16}).notNull().default("draft"),notes:varchar("notes",{length:2000}),activatedAt:timestamp("activated_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("fertilization_plans_org_culture_version_unique").on(table.organizationId,table.cultureId,table.version),uniqueIndex("fertilization_plans_one_in_force").on(table.organizationId,table.cultureId).where(sql`${table.status} = 'in_force'`),index("fertilization_plans_org_status_idx").on(table.organizationId,table.status),check("fertilization_plans_dates_valid",sql`${table.endsOn} >= ${table.startsOn}`),check("fertilization_plans_version_valid",sql`${table.version} > 0`),check("fertilization_plans_status_valid",sql`${table.status} in ('draft','in_force','superseded')`),pgPolicy("fertilization_plans_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export type FertilizationPlan=typeof fertilizationPlans.$inferSelect;
export const fertilizationPlanFields=farmSchema.table("fertilization_plan_fields",{id:uuid("id").primaryKey(),planId:uuid("plan_id").notNull().references(()=>fertilizationPlans.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),fieldId:uuid("field_id").notNull().references(()=>farmFields.id),plantationId:uuid("plantation_id").references(()=>plantations.id),targetType:varchar("target_type",{length:24}).notNull(),targetLabel:varchar("target_label",{length:180}).notNull(),areaHa:numeric("area_ha",{precision:12,scale:4}).notNull(),objectivesKgHa:jsonb("objectives_kg_ha").$type<NutrientAmounts>().notNull(),plannedSources:jsonb("planned_sources").$type<Array<{name:string;nutrientsKgHa:NutrientAmounts}>>().notNull().default([]),irrigationSectorSnapshot:varchar("irrigation_sector_snapshot",{length:180}),nitrateAnalysisSnapshot:jsonb("nitrate_analysis_snapshot").$type<{sampledOn:string;nitrateMgL:number;source?:string}>(),irrigationForecastM3Ha:numeric("irrigation_forecast_m3_ha",{precision:14,scale:3}),includeCoverCrop:boolean("include_cover_crop").notNull().default(false),coverCropContributionKgHa:jsonb("cover_crop_contribution_kg_ha").$type<NutrientAmounts>(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("fertilization_plan_fields_plan_field_unique").on(table.planId,table.fieldId),index("fertilization_plan_fields_org_plan_idx").on(table.organizationId,table.planId),check("fertilization_plan_fields_target_valid",sql`${table.targetType} in ('current_plantation','next_planting','current_campaign','next_campaign')`),check("fertilization_plan_fields_area_valid",sql`${table.areaHa} > 0`),check("fertilization_plan_fields_irrigation_valid",sql`${table.irrigationForecastM3Ha} is null or ${table.irrigationForecastM3Ha} >= 0`),pgPolicy("fertilization_plan_fields_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationWorkers=farmSchema.table("operation_workers",{operationId:uuid("operation_id").notNull().references(()=>farmOperations.id),workerId:uuid("worker_id").notNull().references(()=>farmWorkers.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),totalHours:numeric("total_hours",{precision:10,scale:4}),allocationSnapshot:jsonb("allocation_snapshot").$type<Array<Record<string,unknown>>>().notNull().default([])},(table)=>[uniqueIndex("operation_workers_unique").on(table.operationId,table.workerId),foreignKey({name:"operation_workers_same_tenant_fk",columns:[table.organizationId,table.workerId],foreignColumns:[farmWorkers.organizationId,farmWorkers.id]}),pgPolicy("operation_workers_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationEquipment=farmSchema.table("operation_equipment",{operationId:uuid("operation_id").notNull().references(()=>farmOperations.id),equipmentId:uuid("equipment_id").notNull().references(()=>farmEquipment.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),totalHours:numeric("total_hours",{precision:10,scale:4}),allocationSnapshot:jsonb("allocation_snapshot").$type<Array<Record<string,unknown>>>().notNull().default([])},(table)=>[uniqueIndex("operation_equipment_unique").on(table.operationId,table.equipmentId),foreignKey({name:"operation_equipment_same_tenant_fk",columns:[table.organizationId,table.equipmentId],foreignColumns:[farmEquipment.organizationId,farmEquipment.id]}),pgPolicy("operation_equipment_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationContractors=farmSchema.table("operation_contractors",{operationId:uuid("operation_id").notNull().references(()=>farmOperations.id),contractorId:uuid("contractor_id").notNull().references(()=>farmContractors.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),totalHours:numeric("total_hours",{precision:10,scale:4}),allocationSnapshot:jsonb("allocation_snapshot").$type<Array<Record<string,unknown>>>().notNull().default([])},(table)=>[uniqueIndex("operation_contractors_unique").on(table.operationId,table.contractorId),foreignKey({name:"operation_contractors_same_tenant_fk",columns:[table.organizationId,table.contractorId],foreignColumns:[farmContractors.organizationId,farmContractors.id]}),pgPolicy("operation_contractors_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const privacyRequests=farmSchema.table("privacy_requests",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),requesterUserId:uuid("requester_user_id").notNull(),type:varchar("type",{length:24}).notNull(),details:varchar("details",{length:4000}).notNull(),status:varchar("status",{length:20}).notNull().default("submitted"),response:varchar("response",{length:4000}),submittedAt:timestamp("submitted_at",{withTimezone:true}).notNull().defaultNow(),deadlineAt:timestamp("deadline_at",{withTimezone:true}).notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[index("privacy_requests_organization_status_idx").on(table.organizationId,table.status,table.deadlineAt),index("privacy_requests_requester_idx").on(table.organizationId,table.requesterUserId,table.submittedAt),check("privacy_requests_type_valid",sql`${table.type} in ('access','rectification','erasure','restriction','portability','objection')`),check("privacy_requests_status_valid",sql`${table.status} in ('submitted','in_review','completed','rejected','archived')`),pgPolicy("privacy_requests_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const irrigationSectors=farmSchema.table("irrigation_sectors",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),holdingId:uuid("holding_id").notNull().references(()=>farmHoldings.id),code:varchar("code",{length:20}).notNull(),name:varchar("name",{length:160}).notNull(),system:varchar("system",{length:24}).notNull(),customSystem:varchar("custom_system",{length:120}),efficiencyPercent:numeric("efficiency_percent",{precision:6,scale:2}),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("irrigation_sectors_org_code_unique").on(table.organizationId,table.code),index("irrigation_sectors_holding_status_idx").on(table.organizationId,table.holdingId,table.status),check("irrigation_sectors_system_valid",sql`${table.system} in ('drip','sprinkler','gravity','flood','other')`),check("irrigation_sectors_custom_system_valid",sql`(${table.system}='other' and ${table.customSystem} is not null) or (${table.system}<>'other' and ${table.customSystem} is null)`),check("irrigation_sectors_efficiency_valid",sql`${table.efficiencyPercent} is null or (${table.efficiencyPercent}>0 and ${table.efficiencyPercent}<=100)`),check("irrigation_sectors_status_valid",sql`${table.status} in ('active','inactive')`),pgPolicy("irrigation_sectors_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const irrigationSectorFields=farmSchema.table("irrigation_sector_fields",{sectorId:uuid("sector_id").notNull().references(()=>irrigationSectors.id),fieldId:uuid("field_id").notNull().references(()=>farmFields.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),assignedAt:timestamp("assigned_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("irrigation_sector_fields_sector_field_unique").on(table.sectorId,table.fieldId),uniqueIndex("irrigation_sector_fields_active_field_unique").on(table.organizationId,table.fieldId),pgPolicy("irrigation_sector_fields_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const waterMeters=farmSchema.table("water_meters",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),holdingId:uuid("holding_id").notNull().references(()=>farmHoldings.id),code:varchar("code",{length:20}).notNull(),name:varchar("name",{length:160}).notNull(),serialNumber:varchar("serial_number",{length:120}).notNull(),unit:varchar("unit",{length:8}).notNull().default("m3"),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("water_meters_org_code_unique").on(table.organizationId,table.code),index("water_meters_holding_status_idx").on(table.organizationId,table.holdingId,table.status),check("water_meters_unit_valid",sql`${table.unit}='m3'`),check("water_meters_status_valid",sql`${table.status} in ('active','inactive','replaced')`),pgPolicy("water_meters_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const waterMeterSectors=farmSchema.table("water_meter_sectors",{meterId:uuid("meter_id").notNull().references(()=>waterMeters.id),sectorId:uuid("sector_id").notNull().references(()=>irrigationSectors.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId)},(table)=>[uniqueIndex("water_meter_sectors_unique").on(table.meterId,table.sectorId),pgPolicy("water_meter_sectors_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const waterMeterReadings=farmSchema.table("water_meter_readings",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),meterId:uuid("meter_id").notNull().references(()=>waterMeters.id),readAt:timestamp("read_at",{withTimezone:true}).notNull(),valueM3:numeric("value_m3",{precision:18,scale:3}).notNull(),origin:varchar("origin",{length:16}).notNull(),event:varchar("event",{length:16}).notNull().default("normal"),photoUrl:varchar("photo_url",{length:1000}),notes:varchar("notes",{length:1000}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[index("water_meter_readings_meter_date_idx").on(table.organizationId,table.meterId,table.readAt),check("water_meter_readings_value_valid",sql`${table.valueM3}>=0`),check("water_meter_readings_origin_valid",sql`${table.origin} in ('manual','integrated')`),check("water_meter_readings_event_valid",sql`${table.event} in ('normal','replacement','reset','rollover')`),pgPolicy("water_meter_readings_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const irrigationWaterAnalyses=farmSchema.table("irrigation_water_analyses",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),sampledOn:date("sampled_on").notNull(),nitrateMgL:numeric("nitrate_mg_l",{precision:12,scale:4}).notNull(),source:varchar("source",{length:180}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[index("irrigation_water_analyses_org_date_idx").on(table.organizationId,table.sampledOn),check("irrigation_water_analyses_nitrate_valid",sql`${table.nitrateMgL}>=0`),pgPolicy("irrigation_water_analyses_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const irrigationWaterAnalysisSectors=farmSchema.table("irrigation_water_analysis_sectors",{analysisId:uuid("analysis_id").notNull().references(()=>irrigationWaterAnalyses.id),sectorId:uuid("sector_id").notNull().references(()=>irrigationSectors.id),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId)},(table)=>[uniqueIndex("irrigation_water_analysis_sectors_unique").on(table.analysisId,table.sectorId),pgPolicy("irrigation_water_analysis_sectors_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const irrigationRecords=farmSchema.table("irrigation_records",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),operationId:uuid("operation_id").references(()=>farmOperations.id),status:varchar("status",{length:32}).notNull(),inputMode:varchar("input_mode",{length:24}).notNull(),scheduledWeekEnd:date("scheduled_week_end"),performedAt:timestamp("performed_at",{withTimezone:true}),areaHa:numeric("area_ha",{precision:14,scale:4}).notNull(),volumeM3:numeric("volume_m3",{precision:16,scale:3}).notNull(),doseM3Ha:numeric("dose_m3_ha",{precision:16,scale:3}).notNull(),depthMm:numeric("depth_mm",{precision:16,scale:3}).notNull(),flowM3H:numeric("flow_m3_h",{precision:16,scale:3}),durationMinutes:numeric("duration_minutes",{precision:12,scale:2}),applications:jsonb("applications").$type<Array<{sectorId:string;fieldIds:string[];plantationIds:string[]}>>().notNull(),meterAllocations:jsonb("meter_allocations").$type<Array<{meterId:string;startReadingId?:string;endReadingId?:string;volumeM3?:number}>>().notNull().default([]),waterAnalysisId:uuid("water_analysis_id").references(()=>irrigationWaterAnalyses.id),nitrateAnalysisSnapshot:jsonb("nitrate_analysis_snapshot").$type<{sampledOn:string;nitrateMgL:number;source?:string;stale:boolean}>(),fertigationSnapshot:jsonb("fertigation_snapshot").$type<Record<string,unknown>>(),resourceSnapshot:jsonb("resource_snapshot").$type<{workerIds:string[];equipmentIds:string[];contractorIds:string[];timezone?:string}>().notNull(),notes:varchar("notes",{length:2000}),reversedAt:timestamp("reversed_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},(table)=>[uniqueIndex("irrigation_records_operation_unique").on(table.operationId),index("irrigation_records_org_status_week_idx").on(table.organizationId,table.status,table.scheduledWeekEnd),check("irrigation_records_status_valid",sql`${table.status} in ('scheduled','performed','performed_by_schedule','reversed')`),check("irrigation_records_input_valid",sql`${table.inputMode} in ('volume_total','dose_m3_ha','depth_mm','flow_duration','meter_difference')`),check("irrigation_records_values_valid",sql`${table.areaHa}>0 and ${table.volumeM3}>0 and ${table.doseM3Ha}>0 and ${table.depthMm}>0`),check("irrigation_records_state_consistent",sql`(${table.status}='scheduled' and ${table.operationId} is null and ${table.performedAt} is null and ${table.scheduledWeekEnd} is not null) or (${table.status} in ('performed','performed_by_schedule','reversed') and ${table.operationId} is not null and ${table.performedAt} is not null)`),pgPolicy("irrigation_records_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const agronomicMonitorings=farmSchema.table("agronomic_monitorings",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),observedAt:timestamp("observed_at",{withTimezone:true}).notNull(),technicianWorkerId:uuid("technician_worker_id").references(()=>farmWorkers.id),fieldIds:jsonb("field_ids").$type<string[]>().notNull(),plantationIds:jsonb("plantation_ids").$type<string[]>().notNull().default([]),cropPeriodIds:jsonb("crop_period_ids").$type<string[]>().notNull().default([]),geometry:jsonb("geometry").$type<Record<string,unknown>>(),automaticWeather:jsonb("automatic_weather").$type<AutomaticMonitoringWeather>().notNull(),correctedWeather:jsonb("corrected_weather").$type<Partial<MonitoringWeatherMetrics>>(),correctionReason:varchar("correction_reason",{length:500}),findings:jsonb("findings").$type<Array<Record<string,unknown>>>().notNull(),linkedOperationIds:jsonb("linked_operation_ids").$type<string[]>().notNull().default([]),attachments:jsonb("attachments").$type<Array<Record<string,unknown>>>().notNull().default([]),notes:varchar("notes",{length:2000}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[index("agronomic_monitorings_org_date_idx").on(table.organizationId,table.observedAt),check("agronomic_monitorings_findings_valid",sql`jsonb_array_length(${table.findings})>0`),pgPolicy("agronomic_monitorings_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const laboratorySamples=farmSchema.table("laboratory_samples",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),sampledOn:date("sampled_on").notNull(),responsibleWorkerId:uuid("responsible_worker_id").references(()=>farmWorkers.id),type:varchar("type",{length:16}).notNull(),method:varchar("method",{length:180}).notNull(),fieldIds:jsonb("field_ids").$type<string[]>().notNull().default([]),irrigationSectorIds:jsonb("irrigation_sector_ids").$type<string[]>().notNull().default([]),plantationIds:jsonb("plantation_ids").$type<string[]>().notNull().default([]),cropPeriodIds:jsonb("crop_period_ids").$type<string[]>().notNull().default([]),notes:varchar("notes",{length:2000}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[index("laboratory_samples_org_date_idx").on(table.organizationId,table.sampledOn),check("laboratory_samples_type_valid",sql`${table.type} in ('soil','water','leaf','other')`),pgPolicy("laboratory_samples_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const laboratoryResults=farmSchema.table("laboratory_results",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),sampleId:uuid("sample_id").notNull().references(()=>laboratorySamples.id),resultedOn:date("resulted_on").notNull(),laboratory:varchar("laboratory",{length:180}).notNull(),bulletinNumber:varchar("bulletin_number",{length:120}).notNull(),bulletinUrl:varchar("bulletin_url",{length:1000}),validUntil:date("valid_until"),results:jsonb("results").$type<Array<Record<string,unknown>>>().notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("laboratory_results_sample_unique").on(table.sampleId),index("laboratory_results_org_validity_idx").on(table.organizationId,table.validUntil),pgPolicy("laboratory_results_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const harvestSequences=farmSchema.table("harvest_sequences",{organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),year:numeric("year",{precision:4,scale:0}).notNull(),nextValue:numeric("next_value",{precision:12,scale:0}).notNull().default("1")},table=>[uniqueIndex("harvest_sequences_org_year_unique").on(table.organizationId,table.year),pgPolicy("harvest_sequences_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const harvestLotSequences=farmSchema.table("harvest_lot_sequences",{organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),prefix:varchar("prefix",{length:32}).notNull(),nextValue:numeric("next_value",{precision:12,scale:0}).notNull().default("1")},table=>[uniqueIndex("harvest_lot_sequences_org_prefix_unique").on(table.organizationId,table.prefix),pgPolicy("harvest_lot_sequences_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const harvests=farmSchema.table("harvests",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),operationId:uuid("operation_id").notNull().references(()=>farmOperations.id),lotCode:varchar("lot_code",{length:40}).notNull(),cultureId:varchar("culture_id",{length:32}).notNull(),startedAt:timestamp("started_at",{withTimezone:true}).notNull(),endedAt:timestamp("ended_at",{withTimezone:true}),totalNetKg:numeric("total_net_kg",{precision:18,scale:3}).notNull(),origins:jsonb("origins").$type<Array<Record<string,unknown>>>().notNull(),categories:jsonb("categories").$type<Array<Record<string,unknown>>>().notNull(),lots:jsonb("lots").$type<Array<Record<string,unknown>>>().notNull(),destinations:jsonb("destinations").$type<Array<Record<string,unknown>>>().notNull(),quality:jsonb("quality").$type<Array<Record<string,unknown>>>().notNull(),commercialSnapshot:jsonb("commercial_snapshot").$type<Record<string,unknown>>(),lossReason:varchar("loss_reason",{length:1000}),safetyWarnings:jsonb("safety_warnings").$type<string[]>().notNull().default([]),notes:varchar("notes",{length:2000}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("harvests_operation_unique").on(table.operationId),uniqueIndex("harvests_org_lot_unique").on(table.organizationId,table.lotCode),index("harvests_org_date_idx").on(table.organizationId,table.startedAt),check("harvests_weight_valid",sql`${table.totalNetKg}>0`),pgPolicy("harvests_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const notebookSequences=farmSchema.table("notebook_sequences",{organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),holdingId:uuid("holding_id").notNull().references(()=>farmHoldings.id),year:numeric("year",{precision:4,scale:0}).notNull(),nextValue:numeric("next_value",{precision:12,scale:0}).notNull().default("1")},table=>[uniqueIndex("notebook_sequences_holding_year_unique").on(table.holdingId,table.year),pgPolicy("notebook_sequences_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const fieldNotebooks=farmSchema.table("field_notebooks",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),holdingId:uuid("holding_id").notNull().references(()=>farmHoldings.id),number:varchar("number",{length:40}).notNull(),version:numeric("version",{precision:6,scale:0}).notNull(),scope:jsonb("scope").$type<Record<string,unknown>>().notNull(),snapshot:jsonb("snapshot").$type<Record<string,unknown>>().notNull(),language:varchar("language",{length:16}).notNull(),timezone:varchar("timezone",{length:64}).notNull(),issuerUserId:uuid("issuer_user_id").notNull(),integrityId:varchar("integrity_id",{length:64}).notNull(),pdfBase64:text("pdf_base64"),issuedAt:timestamp("issued_at",{withTimezone:true}).notNull().defaultNow(),deletedAt:timestamp("deleted_at",{withTimezone:true}),deletedBy:uuid("deleted_by"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("field_notebooks_org_number_version_unique").on(table.organizationId,table.number,table.version),uniqueIndex("field_notebooks_integrity_unique").on(table.integrityId),index("field_notebooks_org_issued_idx").on(table.organizationId,table.issuedAt),check("field_notebooks_version_valid",sql`${table.version}>0`),check("field_notebooks_number_valid",sql`${table.number} ~ '^EXP-[0-9]{4}-[0-9]{4,}$'`),pgPolicy("field_notebooks_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();

export const inventoryProducts=farmSchema.table("inventory_products",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),code:varchar("code",{length:24}).notNull(),name:varchar("name",{length:180}).notNull(),unit:varchar("unit",{length:24}).notNull(),lotTracking:boolean("lot_tracking").notNull().default(false),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("inventory_products_org_code_unique").on(table.organizationId,table.code),index("inventory_products_org_status_idx").on(table.organizationId,table.status),check("inventory_products_status_valid",sql`${table.status} in ('active','inactive')`),pgPolicy("inventory_products_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const inventoryLots=farmSchema.table("inventory_lots",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),productId:uuid("product_id").notNull().references(()=>inventoryProducts.id),lotNumber:varchar("lot_number",{length:100}).notNull(),supplier:varchar("supplier",{length:180}),originDocument:varchar("origin_document",{length:120}),receivedOn:date("received_on").notNull(),receivedQuantity:numeric("received_quantity",{precision:18,scale:4}).notNull(),availableQuantity:numeric("available_quantity",{precision:18,scale:4}).notNull(),unitCost:numeric("unit_cost",{precision:18,scale:6}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[uniqueIndex("inventory_lots_org_product_lot_unique").on(table.organizationId,table.productId,table.lotNumber),index("inventory_lots_org_product_idx").on(table.organizationId,table.productId),pgPolicy("inventory_lots_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const operationConsumptions=farmSchema.table("operation_consumptions",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),operationId:uuid("operation_id").notNull().references(()=>farmOperations.id),productId:uuid("product_id").notNull().references(()=>inventoryProducts.id),requestedQuantity:numeric("requested_quantity",{precision:18,scale:4}).notNull(),allocatedQuantity:numeric("allocated_quantity",{precision:18,scale:4}).notNull().default("0"),unit:varchar("unit",{length:24}).notNull(),status:varchar("status",{length:24}).notNull().default("pending"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),regularizedAt:timestamp("regularized_at",{withTimezone:true})},table=>[uniqueIndex("operation_consumptions_org_operation_product_unique").on(table.organizationId,table.operationId,table.productId),index("operation_consumptions_org_status_idx").on(table.organizationId,table.status),pgPolicy("operation_consumptions_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const inventoryMovements=farmSchema.table("inventory_movements",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),productId:uuid("product_id").notNull().references(()=>inventoryProducts.id),lotId:uuid("lot_id").references(()=>inventoryLots.id),consumptionId:uuid("consumption_id").references(()=>operationConsumptions.id),kind:varchar("kind",{length:20}).notNull(),quantity:numeric("quantity",{precision:18,scale:4}).notNull(),unitCostSnapshot:numeric("unit_cost_snapshot",{precision:18,scale:6}),occurredAt:timestamp("occurred_at",{withTimezone:true}).notNull(),reason:varchar("reason",{length:500}),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[index("inventory_movements_org_date_idx").on(table.organizationId,table.occurredAt),pgPolicy("inventory_movements_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
export const farmCosts=farmSchema.table("farm_costs",{id:uuid("id").primaryKey(),organizationId:uuid("organization_id").notNull().references(()=>farmOrganizations.organizationId),operationId:uuid("operation_id").references(()=>farmOperations.id),category:varchar("category",{length:24}).notNull(),description:varchar("description",{length:240}).notNull(),netAmount:numeric("net_amount",{precision:18,scale:2}).notNull(),taxAmount:numeric("tax_amount",{precision:18,scale:2}).notNull().default("0"),currency:varchar("currency",{length:3}).notNull().default("EUR"),occurredOn:date("occurred_on").notNull(),allocationSnapshot:jsonb("allocation_snapshot").$type<Array<{destinationId:string;percentage:number;amount:number}>>().notNull().default([]),sourceSnapshot:jsonb("source_snapshot").$type<Record<string,unknown>>().notNull().default({}),status:varchar("status",{length:16}).notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},table=>[index("farm_costs_org_date_idx").on(table.organizationId,table.occurredOn),index("farm_costs_org_operation_idx").on(table.organizationId,table.operationId),pgPolicy("farm_costs_tenant_isolation",{as:"restrictive",for:"all",to:"public",using:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`,withCheck:sql`${table.organizationId}=nullif(current_setting('app.organization_id',true),'')::uuid`})]).enableRLS();
