import assert from "node:assert/strict";
import test from "node:test";
import { accumulationStart, accumulationWindowStart, activeStationCount, aggregateWeatherIndicators, dateRange, fieldCentroid, indicatorInputFromReport, weatherCapabilities, weatherContractVersion, type WeatherIndicatorResponse, type WeatherReport, type WeatherVirtualStation } from "./weather";

test("consumer is pinned to the canonical additive weather contract",()=>{assert.equal(weatherContractVersion,"2")});
test("commercial weather depth follows the Core feature level",()=>{assert.deepEqual(weatherCapabilities("essential"),{level:"essential",history:false,campaignProfiles:false,crossCampaignComparison:false,export:false});assert.equal(weatherCapabilities("campaign").history,true);assert.equal(weatherCapabilities("professional").crossCampaignComparison,true);assert.equal(weatherCapabilities("custom").export,true)});
test("virtual station capacity counts active records only",()=>{const base={id:"1",organizationId:"o",name:"A",latitude:1,longitude:2,elevationM:null,timezone:"Europe/Lisbon",createdAt:"2026-01-01",updatedAt:"2026-01-01"};assert.equal(activeStationCount([{...base,archivedAt:null},{...base,id:"2",archivedAt:"2026-02-01"}] as WeatherVirtualStation[]),1)});
test("field centroid uses stable field geometry and ignores closing duplicate",()=>{assert.deepEqual(fieldCentroid([[-9,38],[-8,38],[-8,39],[-9,39],[-9,38]]),{longitude:-8.5,latitude:38.5})});
test("accumulation starts obey crop lifecycle without inferring operation dates",()=>{
  assert.deepEqual(accumulationStart({plantationKind:"temporary",establishment:"sown",hasDormancy:false,sowingDate:"2026-03-01"}),{date:"2026-03-01",basis:"sowing_fallback"});
  assert.deepEqual(accumulationStart({plantationKind:"temporary",establishment:"sown",hasDormancy:false,sowingDate:"2026-03-01",emergenceDate:"2026-03-10"}),{date:"2026-03-10",basis:"emergence"});
  assert.deepEqual(accumulationStart({plantationKind:"temporary",establishment:"transplanted",hasDormancy:false,transplantDate:"2026-04-01"}),{date:"2026-04-01",basis:"transplant"});
  assert.deepEqual(accumulationStart({plantationKind:"permanent",establishment:"not_applicable",hasDormancy:true,campaignStartDate:"2026-01-01"}),{date:null,basis:"missing_vegetative_start"});
  assert.deepEqual(accumulationStart({plantationKind:"permanent",establishment:"not_applicable",hasDormancy:false,campaignStartDate:"2026-01-01"}),{date:"2026-01-01",basis:"campaign_start"});
});
test("rolling and custom windows are explicit",()=>{assert.equal(accumulationWindowStart("2026-08-24","7"),"2026-08-18");assert.equal(accumulationWindowStart("2026-08-24","custom","2026-04-02"),"2026-04-02")});
test("daily Core derivations aggregate without mixing observed and forecast values",()=>{assert.deepEqual(dateRange("2026-08-23","2026-08-24"),["2026-08-23","2026-08-24"]);const derivation=(value:number,status:"observed"|"forecast")=>({value,unit:"unit",method:"core",version:"1",valueSource:"estimated" as const,temporalStatus:status,inputs:{}});const indicators=Object.fromEntries(["et0","degreeDays","chillHoursBelow7_2C","modifiedChillHours","utahChillUnits","dynamicModelChillPortions","estimatedLeafWetnessHours","solarEnergy","estimatedPar","estimatedDli"].map((key)=>[key,derivation(2,"observed")])) as WeatherIndicatorResponse["indicators"];const report={station:null} as WeatherReport;const result=aggregateWeatherIndicators("2026-08-23","2026-08-24",[{response:{profile:null,indicators},report},{response:{profile:null,indicators:{...indicators,et0:derivation(3,"forecast")}},report}]);assert.deepEqual(result.values.et0,{unit:"unit",observed:2,forecast:3,total:5,dailyAverage:2.5});assert.equal(result.values.degreeDays.total,4)});
test("Core report normalization does not derive agronomic results locally",()=>{const point={at:"2026-08-24T12:00:00Z",summary:null,icon:null,temperatureC:20,apparentTemperatureC:20,precipitationProbability:0,precipitationIntensityMmPerHour:0,humidityPercent:70,windSpeedKph:7.2,windGustKph:null,windBearingDegrees:null,pressureHpa:1013,cloudCoverPercent:10,uvIndex:5,dewPointC:14,elevationM:100,solarRadiationWm2:500,precipitationAccumulationMm:0,precipitationType:"none" as const,temporalStatus:"observed" as const,valueSource:"estimated" as const};const report={latitude:38,longitude:-9,timezone:"Europe/Lisbon",units:"metric",current:point,hourly:{summary:null,data:[point]},daily:{summary:null,data:[{...point,sunriseAt:null,sunsetAt:null,temperatureMinC:12,temperatureMaxC:25}]},station:null,meta:{provider:"core-provider",fetchedAt:point.at,cached:false,stale:false,cache:{status:"miss",freshUntil:point.at,staleUntil:point.at},contractVersion:"2"}} satisfies WeatherReport;const input=indicatorInputFromReport(report,"campaign-id");assert(input);assert.equal(input.windSpeed2mMps,2);assert.equal(input.solarRadiationMjM2Day,1.8);assert.equal("et0" in input,false)});
