import type{SupportedLocale}from"../../home-copy";
export type EconomicCopy={inventory:string;costs:string;products:string;lots:string;pending:string;newProduct:string;receive:string;consume:string;newCost:string;code:string;name:string;unit:string;lot:string;quantity:string;unitCost:string;supplier:string;document:string;operation:string;description:string;amount:string;tax:string;date:string;category:string;general:string;save:string;empty:string;error:string;allocated:string;regularize:string;stockValue:string;totalCosts:string;material:string;labour:string;equipment:string;contractor:string;fuel:string;fixed:string;other:string};
const c=(v:string[]):EconomicCopy=>{const k=["inventory","costs","products","lots","pending","newProduct","receive","consume","newCost","code","name","unit","lot","quantity","unitCost","supplier","document","operation","description","amount","tax","date","category","general","save","empty","error","allocated","regularize","stockValue","totalCosts","material","labour","equipment","contractor","fuel","fixed","other"]as const;return Object.fromEntries(k.map((key,i)=>[key,v[i]]))as EconomicCopy};
export const economicCopies:Record<SupportedLocale,EconomicCopy>={
"pt-PT":c(["Inventário","Custos","Produtos","Lotes","Por regularizar","Novo produto","Registar entrada","Registar consumo","Novo custo","Código","Nome","Unidade","Lote","Quantidade","Custo unitário","Fornecedor","Documento de origem","Operação","Descrição","Valor líquido","Imposto","Data","Categoria","Custo geral","Guardar","Ainda não existem registos.","Não foi possível guardar.","Imputado","Regularizar","Valor em stock","Custos registados","Material","Mão de obra","Equipamento","Prestador","Combustível","Fixo","Outro"]),
"pt-BR":c(["Inventário","Custos","Produtos","Lotes","A regularizar","Novo produto","Registrar entrada","Registrar consumo","Novo custo","Código","Nome","Unidade","Lote","Quantidade","Custo unitário","Fornecedor","Documento de origem","Operação","Descrição","Valor líquido","Imposto","Data","Categoria","Custo geral","Salvar","Ainda não há registros.","Não foi possível salvar.","Alocado","Regularizar","Valor em estoque","Custos registrados","Material","Mão de obra","Equipamento","Prestador","Combustível","Fixo","Outro"]),
en:c(["Inventory","Costs","Products","Lots","Pending allocation","New product","Record receipt","Record consumption","New cost","Code","Name","Unit","Lot","Quantity","Unit cost","Supplier","Source document","Operation","Description","Net amount","Tax","Date","Category","General cost","Save","No records yet.","Could not save.","Allocated","Regularise","Stock value","Recorded costs","Material","Labour","Equipment","Contractor","Fuel","Fixed","Other"]),
fr:c(["Stock","Coûts","Produits","Lots","À régulariser","Nouveau produit","Enregistrer une entrée","Enregistrer une consommation","Nouveau coût","Code","Nom","Unité","Lot","Quantité","Coût unitaire","Fournisseur","Document d’origine","Opération","Description","Montant net","Taxe","Date","Catégorie","Coût général","Enregistrer","Aucun enregistrement.","Enregistrement impossible.","Affecté","Régulariser","Valeur du stock","Coûts enregistrés","Matière","Main-d’œuvre","Équipement","Prestataire","Carburant","Fixe","Autre"]),
es:c(["Inventario","Costes","Productos","Lotes","Por regularizar","Nuevo producto","Registrar entrada","Registrar consumo","Nuevo coste","Código","Nombre","Unidad","Lote","Cantidad","Coste unitario","Proveedor","Documento de origen","Operación","Descripción","Importe neto","Impuesto","Fecha","Categoría","Coste general","Guardar","Aún no hay registros.","No se pudo guardar.","Imputado","Regularizar","Valor del stock","Costes registrados","Material","Mano de obra","Equipo","Contratista","Combustible","Fijo","Otro"]),
nl:c(["Voorraad","Kosten","Producten","Partijen","Nog toe te wijzen","Nieuw product","Ontvangst registreren","Verbruik registreren","Nieuwe kosten","Code","Naam","Eenheid","Partij","Hoeveelheid","Eenheidskosten","Leverancier","Brondocument","Bewerking","Beschrijving","Nettobedrag","Belasting","Datum","Categorie","Algemene kosten","Opslaan","Nog geen registraties.","Opslaan mislukt.","Toegewezen","Toewijzen","Voorraadwaarde","Geregistreerde kosten","Materiaal","Arbeid","Apparatuur","Aannemer","Brandstof","Vast","Overig"]),
de:c(["Bestand","Kosten","Produkte","Chargen","Noch zuzuordnen","Neues Produkt","Eingang erfassen","Verbrauch erfassen","Neue Kosten","Code","Name","Einheit","Charge","Menge","Stückkosten","Lieferant","Quelldokument","Arbeitsgang","Beschreibung","Nettobetrag","Steuer","Datum","Kategorie","Allgemeine Kosten","Speichern","Noch keine Einträge.","Speichern fehlgeschlagen.","Zugeordnet","Zuordnen","Bestandswert","Erfasste Kosten","Material","Arbeit","Gerät","Auftragnehmer","Kraftstoff","Fest","Sonstige"]),
ja:c(["在庫","費用","資材","ロット","未引当","資材を追加","入庫を記録","使用を記録","費用を追加","コード","名称","単位","ロット","数量","単価","仕入先","元伝票","作業","説明","税抜額","税","日付","区分","一般費用","保存","記録はありません。","保存できませんでした。","引当済み","引き当てる","在庫金額","記録済み費用","資材","労務","機械","請負","燃料","固定","その他"]),
he:c(["מלאי","עלויות","מוצרים","אצוות","ממתין להסדרה","מוצר חדש","רישום קבלה","רישום צריכה","עלות חדשה","קוד","שם","יחידה","אצווה","כמות","עלות ליחידה","ספק","מסמך מקור","פעולה","תיאור","סכום נטו","מס","תאריך","קטגוריה","עלות כללית","שמירה","אין עדיין רשומות.","השמירה נכשלה.","הוקצה","הסדרה","שווי מלאי","עלויות שנרשמו","חומר","עבודה","ציוד","קבלן","דלק","קבוע","אחר"]),
tr:c(["Stok","Maliyetler","Ürünler","Partiler","Düzenlenecek","Yeni ürün","Giriş kaydet","Tüketim kaydet","Yeni maliyet","Kod","Ad","Birim","Parti","Miktar","Birim maliyet","Tedarikçi","Kaynak belge","İşlem","Açıklama","Net tutar","Vergi","Tarih","Kategori","Genel maliyet","Kaydet","Henüz kayıt yok.","Kaydedilemedi.","Tahsis edildi","Düzenle","Stok değeri","Kaydedilen maliyetler","Malzeme","İşçilik","Ekipman","Yüklenici","Yakıt","Sabit","Diğer"]),
ar:c(["المخزون","التكاليف","المنتجات","الدُفعات","بانتظار التسوية","منتج جديد","تسجيل استلام","تسجيل استهلاك","تكلفة جديدة","الرمز","الاسم","الوحدة","الدُفعة","الكمية","تكلفة الوحدة","المورّد","مستند المصدر","العملية","الوصف","المبلغ الصافي","الضريبة","التاريخ","الفئة","تكلفة عامة","حفظ","لا توجد سجلات بعد.","تعذّر الحفظ.","مخصّص","تسوية","قيمة المخزون","التكاليف المسجلة","مواد","عمالة","معدات","متعهد","وقود","ثابت","أخرى"]),
pl:c(["Zapasy","Koszty","Produkty","Partie","Do rozliczenia","Nowy produkt","Zarejestruj przyjęcie","Zarejestruj zużycie","Nowy koszt","Kod","Nazwa","Jednostka","Partia","Ilość","Koszt jednostkowy","Dostawca","Dokument źródłowy","Zabieg","Opis","Kwota netto","Podatek","Data","Kategoria","Koszt ogólny","Zapisz","Brak zapisów.","Nie udało się zapisać.","Rozliczone","Rozlicz","Wartość zapasów","Zarejestrowane koszty","Materiał","Praca","Sprzęt","Wykonawca","Paliwo","Stały","Inny"]),
hr:c(["Zalihe","Troškovi","Proizvodi","Serije","Za usklađivanje","Novi proizvod","Evidentiraj ulaz","Evidentiraj potrošnju","Novi trošak","Šifra","Naziv","Jedinica","Serija","Količina","Jedinični trošak","Dobavljač","Izvorni dokument","Postupak","Opis","Neto iznos","Porez","Datum","Kategorija","Opći trošak","Spremi","Još nema zapisa.","Spremanje nije uspjelo.","Raspoređeno","Uskladi","Vrijednost zaliha","Evidentirani troškovi","Materijal","Rad","Oprema","Izvođač","Gorivo","Fiksni","Ostalo"]),
el:c(["Απόθεμα","Κόστη","Προϊόντα","Παρτίδες","Προς τακτοποίηση","Νέο προϊόν","Καταχώριση παραλαβής","Καταχώριση κατανάλωσης","Νέο κόστος","Κωδικός","Όνομα","Μονάδα","Παρτίδα","Ποσότητα","Μοναδιαίο κόστος","Προμηθευτής","Παραστατικό","Εργασία","Περιγραφή","Καθαρό ποσό","Φόρος","Ημερομηνία","Κατηγορία","Γενικό κόστος","Αποθήκευση","Δεν υπάρχουν εγγραφές.","Η αποθήκευση απέτυχε.","Κατανεμημένο","Τακτοποίηση","Αξία αποθέματος","Καταχωρισμένα κόστη","Υλικό","Εργασία","Εξοπλισμός","Εργολάβος","Καύσιμο","Σταθερό","Άλλο"]),
sv:c(["Lager","Kostnader","Produkter","Partier","Att reglera","Ny produkt","Registrera inleverans","Registrera förbrukning","Ny kostnad","Kod","Namn","Enhet","Parti","Mängd","Enhetskostnad","Leverantör","Källdokument","Arbetsmoment","Beskrivning","Nettobelopp","Skatt","Datum","Kategori","Allmän kostnad","Spara","Inga poster ännu.","Kunde inte spara.","Tilldelad","Reglera","Lagervärde","Registrerade kostnader","Material","Arbete","Utrustning","Entreprenör","Bränsle","Fast","Övrigt"]),
no:c(["Lager","Kostnader","Produkter","Partier","Til avstemming","Nytt produkt","Registrer mottak","Registrer forbruk","Ny kostnad","Kode","Navn","Enhet","Parti","Mengde","Enhetskostnad","Leverandør","Kildedokument","Arbeidsoperasjon","Beskrivelse","Nettobeløp","Avgift","Dato","Kategori","Generell kostnad","Lagre","Ingen registreringer ennå.","Kunne ikke lagre.","Fordelt","Avstem","Lagerverdi","Registrerte kostnader","Materiale","Arbeid","Utstyr","Entreprenør","Drivstoff","Fast","Annet"]),
da:c(["Lager","Omkostninger","Produkter","Partier","Til afstemning","Nyt produkt","Registrer modtagelse","Registrer forbrug","Ny omkostning","Kode","Navn","Enhed","Parti","Mængde","Enhedsomkostning","Leverandør","Kildedokument","Arbejdsgang","Beskrivelse","Nettobeløb","Afgift","Dato","Kategori","Generel omkostning","Gem","Ingen registreringer endnu.","Kunne ikke gemme.","Fordelt","Afstem","Lagerværdi","Registrerede omkostninger","Materiale","Arbejde","Udstyr","Entreprenør","Brændstof","Fast","Andet"]),
it:c(["Magazzino","Costi","Prodotti","Lotti","Da regolarizzare","Nuovo prodotto","Registra entrata","Registra consumo","Nuovo costo","Codice","Nome","Unità","Lotto","Quantità","Costo unitario","Fornitore","Documento origine","Operazione","Descrizione","Importo netto","Imposta","Data","Categoria","Costo generale","Salva","Nessun dato.","Salvataggio non riuscito.","Imputato","Regolarizza","Valore di magazzino","Costi registrati","Materiale","Manodopera","Attrezzatura","Contoterzista","Carburante","Fisso","Altro"]),
uk:c(["Запаси","Витрати","Продукти","Партії","До врегулювання","Новий продукт","Зареєструвати надходження","Зареєструвати споживання","Нова витрата","Код","Назва","Одиниця","Партія","Кількість","Вартість одиниці","Постачальник","Первинний документ","Операція","Опис","Сума без податку","Податок","Дата","Категорія","Загальна витрата","Зберегти","Записів ще немає.","Не вдалося зберегти.","Розподілено","Врегулювати","Вартість запасів","Зареєстровані витрати","Матеріал","Праця","Обладнання","Підрядник","Паливо","Постійні","Інше"]),
ro:c(["Stoc","Costuri","Produse","Loturi","De regularizat","Produs nou","Înregistrează intrarea","Înregistrează consumul","Cost nou","Cod","Nume","Unitate","Lot","Cantitate","Cost unitar","Furnizor","Document sursă","Operațiune","Descriere","Sumă netă","Taxă","Data","Categorie","Cost general","Salvează","Nu există înregistrări.","Salvarea a eșuat.","Alocat","Regularizează","Valoarea stocului","Costuri înregistrate","Material","Muncă","Echipament","Prestator","Combustibil","Fix","Altul"]),
fi:c(["Varasto","Kustannukset","Tuotteet","Erät","Kohdistamatta","Uusi tuote","Kirjaa vastaanotto","Kirjaa kulutus","Uusi kustannus","Koodi","Nimi","Yksikkö","Erä","Määrä","Yksikkökustannus","Toimittaja","Lähdeasiakirja","Työvaihe","Kuvaus","Nettoarvo","Vero","Päivä","Luokka","Yleiskustannus","Tallenna","Ei vielä tietoja.","Tallennus epäonnistui.","Kohdistettu","Kohdista","Varaston arvo","Kirjatut kustannukset","Materiaali","Työ","Laitteisto","Urakoitsija","Polttoaine","Kiinteä","Muu"]),
bg:c(["Наличности","Разходи","Продукти","Партиди","За уреждане","Нов продукт","Регистриране на доставка","Регистриране на потребление","Нов разход","Код","Име","Единица","Партида","Количество","Единична цена","Доставчик","Изходен документ","Операция","Описание","Нетна сума","Данък","Дата","Категория","Общ разход","Запазване","Все още няма записи.","Неуспешно запазване.","Разпределено","Уреждане","Стойност на наличностите","Регистрирани разходи","Материал","Труд","Оборудване","Изпълнител","Гориво","Постоянен","Друг"]),
hu:c(["Készlet","Költségek","Termékek","Tételek","Rendezendő","Új termék","Bevételezés","Felhasználás rögzítése","Új költség","Kód","Név","Egység","Tétel","Mennyiség","Egységköltség","Szállító","Forrásbizonylat","Művelet","Leírás","Nettó összeg","Adó","Dátum","Kategória","Általános költség","Mentés","Még nincs bejegyzés.","A mentés sikertelen.","Felosztva","Rendezés","Készletérték","Rögzített költségek","Anyag","Munka","Berendezés","Vállalkozó","Üzemanyag","Állandó","Egyéb"]),
is:c(["Birgðir","Kostnaður","Vörur","Lotur","Óráðstafað","Ný vara","Skrá móttöku","Skrá notkun","Nýr kostnaður","Kóði","Heiti","Eining","Lota","Magn","Einingarkostnaður","Birgir","Upprunaskjal","Aðgerð","Lýsing","Nettófjárhæð","Skattur","Dagsetning","Flokkur","Almennur kostnaður","Vista","Engar færslur enn.","Ekki tókst að vista.","Úthlutað","Ráðstafa","Birgðavirði","Skráður kostnaður","Efni","Vinna","Búnaður","Verktaki","Eldsneyti","Fastur","Annað"]),
sk:c(["Zásoby","Náklady","Produkty","Šarže","Na vyrovnanie","Nový produkt","Zaznamenať príjem","Zaznamenať spotrebu","Nový náklad","Kód","Názov","Jednotka","Šarža","Množstvo","Jednotkový náklad","Dodávateľ","Zdrojový doklad","Operácia","Opis","Suma bez dane","Daň","Dátum","Kategória","Všeobecný náklad","Uložiť","Zatiaľ žiadne záznamy.","Uloženie zlyhalo.","Priradené","Vyrovnať","Hodnota zásob","Zaznamenané náklady","Materiál","Práca","Zariadenie","Dodávateľ","Palivo","Fixný","Iný"]),
lt:c(["Atsargos","Sąnaudos","Produktai","Partijos","Nesuderinta","Naujas produktas","Registruoti gavimą","Registruoti sunaudojimą","Naujos sąnaudos","Kodas","Pavadinimas","Vienetas","Partija","Kiekis","Vieneto kaina","Tiekėjas","Pirminis dokumentas","Operacija","Aprašas","Grynoji suma","Mokestis","Data","Kategorija","Bendrosios sąnaudos","Išsaugoti","Įrašų dar nėra.","Nepavyko išsaugoti.","Paskirstyta","Suderinti","Atsargų vertė","Registruotos sąnaudos","Medžiaga","Darbas","Įranga","Rangovas","Kuras","Pastovios","Kita"]),
sl:c(["Zaloga","Stroški","Proizvodi","Serije","Za uskladitev","Nov proizvod","Evidentiraj prejem","Evidentiraj porabo","Nov strošek","Koda","Ime","Enota","Serija","Količina","Strošek na enoto","Dobavitelj","Izvorni dokument","Postopek","Opis","Neto znesek","Davek","Datum","Kategorija","Splošni strošek","Shrani","Zapisov še ni.","Shranjevanje ni uspelo.","Razporejeno","Uskladi","Vrednost zaloge","Evidentirani stroški","Material","Delo","Oprema","Izvajalec","Gorivo","Fiksni","Drugo"]),
lv:c(["Krājumi","Izmaksas","Produkti","Partijas","Jāsaskaņo","Jauns produkts","Reģistrēt saņemšanu","Reģistrēt patēriņu","Jaunas izmaksas","Kods","Nosaukums","Vienība","Partija","Daudzums","Vienības izmaksas","Piegādātājs","Avota dokuments","Darbība","Apraksts","Neto summa","Nodoklis","Datums","Kategorija","Vispārējās izmaksas","Saglabāt","Ierakstu vēl nav.","Neizdevās saglabāt.","Sadalīts","Saskaņot","Krājumu vērtība","Reģistrētās izmaksas","Materiāls","Darbs","Aprīkojums","Darbuzņēmējs","Degviela","Fiksēts","Cits"])
};
